### ISSUE TITLE
Fallback for Websockets

### ISSUE THREAD

**Issue by joymon** [microsoft/cognitive-services-speech-sdk-js#101]
Are there any plans to include a fallback mechanism for browsers that don't support Websockets?
Bing Speech SDK had and migrating to cognitive services speech is getting trouble because it lacks the fallback option.

**Comment by chrisbasoglu** [comment]
Fallback to REST is not currently in our plans.  We will consider it as we make future plans.  You can achieve this now, by testing support and then calling the REST API directly from js when needed.
