### ISSUE TITLE
PropertyId.Conversation_From_Id does not seem to be supported

### ISSUE THREAD

**Issue by alopix** [microsoft/cognitive-services-speech-sdk-js#103]
There does not seem to be support for `PropertyId.Conversation_From_Id` yet – at least setting it does not do anything and it's even necessary to cast to `any` in order to set  the property.
```
this.dialogServiceConfig.setProperty(
  PropertyId.Conversation_From_Id as any,
  'my value'
);
```

Am I using it wrong or was it not implemented yet?

**Comment by modnarb** [comment]
@alopix not using it wrong, I've just published a PR ([110](https://github.com/microsoft/cognitive-services-speech-sdk-js/pull/110)) that contains the fix to address this.

**Comment by modnarb** [comment]
I've merged the change, closing issue.
