### ISSUE TITLE
Unable to set an endpoint ID when using SpeechTranslationConfig

### ISSUE THREAD

**Issue by jkgh2018** [microsoft/cognitive-services-speech-sdk-js#114]
The speechTranslationConfig is setting the EndpointID to the Endpoint property.
This results in an incorrect URL being constructed and a status code of 500.

cognitive-services-speech-sdk-js/src/sdk/SpeechTranslationConfig.ts
 public set endpointId(value: string) {
        this.privSpeechProperties.setProperty(PropertyId.**SpeechServiceConnection_Endpoint**, value);
    }

privErrorDetails: "Unable to contact server. StatusCode: 500, Reason: SyntaxError: Failed to construct 'WebSocket':

**Comment by rhurey** [comment]
PR #139 will have the fix.
