### ISSUE TITLE
Outputresult simple now returns numerals?

### ISSUE THREAD

**Issue by geoff-mathspathway** [microsoft/cognitive-services-speech-sdk-js#119]
Recognizing outputresult simple now returns numerals and text?

When was this changed and how do I just get text output?

It joins numbers together in a string, which you cant tell if its 3 4 or 34?

Recognizing detailed does not provide the needed lexical text

**Comment by rhurey** [comment]
That would have been a service side change and I'm not sure when the change would have happened.

What are you getting for the lexical in the detailed response? The JSON returned for a quick test I did was:

```
{
    "Id": "c1cf31185668425492704780fe2494d3",
    "RecognitionStatus": "Success",
    "Offset": 13500000,
    "Duration": 21500000,
    "DisplayText": "Text 1234.",
    "NBest": [
        {
            "Confidence": 0.964762,
            "Lexical": "text one two three four",
            "ITN": "text 1234",
            "MaskedITN": "Text 1234",
            "Display": "Text 1234."
        },
        {
            "Confidence": 0.8515551,
            "Lexical": "text one two three fourth",
            "ITN": "text 123 fourth",
            "MaskedITN": "Text 123 fourth",
            "Display": "Text 123 fourth."
        },
        {
            "Confidence": 0.8719205,
            "Lexical": "text one two three four oh",
            "ITN": "text 12340",
            "MaskedITN": "Text 12340",
            "Display": "Text 12340."
        },
        {
            "Confidence": 0.8483326,
            "Lexical": "text one two three four i",
            "ITN": "text 1234 i",
            "MaskedITN": "Text 1234 I",
            "Display": "Text 1234 I"
        },
        {
            "Confidence": 0.83176607,
            "Lexical": "text one two three forty",
            "ITN": "text 1 two 340",
            "MaskedITN": "Text 1 two 340",
            "Display": "Text 1, two 340."
        }
    ]
}
```
The JSON can be retrieved from:
result.properties.getProperty(sdk.PropertyId.SpeechServiceResponse_JsonResult)

**Comment by geoff-mathspathway** [comment]
Thanks for the prompt reply.

I can see that the correct lexical form is coming through on the recognized event.

The problem is the 'recognizing' event does not show detailed return information. This is what we are using to show customers their speech as they are talking before finishing a recognized block of text.

Is there any way I can get the lexical information in recognizing? (as it was before)

**Comment by rhurey** [comment]
I'm looking into this with our service team.

**Comment by geoff-mathspathway** [comment]
Hi, any update on how I can get lexical text when recognizing and not just recognized

**Comment by oscholz** [comment]
@geoff-mathspathway closing this issue since there are no more open issues. :)
Thank you for using the JS Speech SDK.
