### ISSUE TITLE
v1.9.0 incompatible with Typescript <3.5.0

### ISSUE THREAD

**Issue by rozele** [microsoft/cognitive-services-speech-sdk-js#129]
The latest release of this SDK is incompatible with earlier versions of the TypeScript compiler. Some common web frameworks (e.g., Angular 8.1.2) still depend on earlier versions of the TypeScript compiler.

E.g., using TypeScript 3.4.5 returns many TS1086 errors:
```
ERROR in node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.browser/FileAudioSource.d.ts:14:9 - error TS1086: An accessor cannot be declared in an ambient context.

14     get format(): AudioStreamFormatImpl;
           ~~~~~~
```

**Comment by rhurey** [comment]
It looks like we were overly aggressive on a TypeScript version.

**Comment by rhurey** [comment]
PR #133 will revert back to 3.5.3

**Comment by rhurey** [comment]
https://github.com/microsoft/cognitive-services-speech-sdk-js/releases/tag/v1.9.1 is pushed and goes back to 3.5.3
