### ISSUE TITLE
Plans to include SpeechSynthesizer implementation for JS SDK?

### ISSUE THREAD

**Issue by rozele** [microsoft/cognitive-services-speech-sdk-js#130]
We are working on an Android Ionic app that uses this SDK for ASR, but we need to use the REST endpoint and the Ionic Native media plugin to play the response. Any plans to add a `SpeechSynthesizer` class, as found in the Java, .NET, and Obj-C SDKs?

**Comment by rhurey** [comment]
I can say the work is in our backlog, but we don't have a timeline for when it will bubble to the top.

We do take customer demand into account when setting priorities.

**Comment by rozele** [comment]
Thanks! Will close for now.
