### ISSUE TITLE
v1.9.0 no longer working on Cordova Android 

### ISSUE THREAD

**Issue by rozele** [microsoft/cognitive-services-speech-sdk-js#131]
I was able to get v1.8.1 mostly working on a Cordova Android app (modulo a small bug: #128).

When trying to get v1.9.0 working, I get the following error:
<img width="811" alt="Screen Shot 2020-01-27 at 2 41 25 PM" src="https://user-images.githubusercontent.com/1106239/73207939-99476b00-4113-11ea-84cc-ff9099fe0f95.png">

Looks like this was recently introduced here: https://github.com/microsoft/cognitive-services-speech-sdk-js/commit/b3a7ca8789fe5cf221ba9126f1bb97599a910e6c

It seems like this env variable check should be isolated to Node.js usage of the Speech SDK.

**Comment by rhurey** [comment]
PR #151 should resolve.

**Comment by rhurey** [comment]
V1.10.0 released that has the fix. Closing.
