### ISSUE TITLE
missing conversation api

### ISSUE THREAD

**Issue by grahamehorner** [microsoft/cognitive-services-speech-sdk-js#136]
I'm looking for the cognitive service speech conversation api for a project; however this seems to be missing; is this part of another package?

**Comment by rhurey** [comment]
Unfortunately, it's not. 

Adding the Conversation API's to the JavaScript API is work that's in our backlog, but hasn't been done, yet. Hearing from developers where we're missing features that they want does help us with our prioritization exercise, so thanks for the feedback.

I'll update this thread when there's more firm information on when the work will be done.
