### ISSUE TITLE
Speech-to-Text: disable audio logging 

### ISSUE THREAD

**Issue by ivpdev** [microsoft/cognitive-services-speech-sdk-js#141]
according to the docs (https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/faq-stt) Speech-To-Text logs audio requests by default ("You have a choice when you create a deployment to switch off tracing. At that point, no audio or transcriptions will be logged. Otherwise, requests are typically logged in Azure in secure storage.").

However in docs of SDK I only see option to enable audio logging SpeechConfig.enableAudioLogging()

How can I ensure, that audio is not logged?

**Comment by eldakms** [comment]
The audio logging can be enabled/disabled on two levels:
1) if you have a custom endpoint, during its creation you can specify that audio logging is on:
![image](https://user-images.githubusercontent.com/12430061/74050114-bb739f80-49d5-11ea-98ef-78a425367a13.png)
if it is "on" - no matter how the client is configured, the service will log all audio to this endpoint.

2) if you use a default endpoint (just specifying the language), or your endpoint has content logging as "off", whether to log audio or not depends on the "&storeAudio=true" query parameter. SpeechConfig internally handles  exactly this query parameter. By default it is false, so nothing is logged.

So, to make sure your audio is not logged: 
   1) make sure your custom endpoint does not have audio logging enabled (if you use a custom endpoint), and 
   2) do not send "&storeAudio=true" in your request. by default storeAudio is false.

**Comment by PanosPeriorellis** [comment]
hi there, thanks for pointing out the discrepancy in the doc. I am updating it. In Speech services and for Cognitive Services in general we do not log unless explicitly turning log on.

**Comment by oscholz** [comment]
Closing this issue, as the question has been answered, and we updated the docs.
