### ISSUE TITLE
[Azure Gov] Cognitive Speech API always points to commercial

### ISSUE THREAD

**Issue by p-nagpal** [microsoft/cognitive-services-speech-sdk-js#154]
This comes from a customer issue: https://github.com/microsoft/BotFramework-WebChat/issues/2969

Webchat consumes the cognitive-services-speech-sdk-js and we found that the endpoints for STT API always point to commercial cloud. From customer issue report: 

_Cognitive Speech API in webchat always points to the commercial endpoint. wss://virginia.stt.speech.microsoft.com instead of wss://virginia.stt.speech.azure.us as stated in [this link](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/sovereign-clouds#azure-government-united-states). This is regardless of using "virginia" or "usgovvirginia" as the region parameter when constructing webSpeechPonyfillFactory._

We noticed that [SpeechConnectionFactory](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/c33ee853a4d221f98951963066474bc540c6a0bb/src/common.speech/SpeechConnectionFactory.ts#L46) uses .stt.speech.microsoft.com regardless of the region and perhaps this is the cause of the issue. 

Could you advise us on how to use Speech API in Azure Gov clouds?

**Comment by rhurey** [comment]
From the link:
SR in SpeechSDK: config.**fromHost**("wss://virginia.stt.speech.azure.us", "<your-key>");

For the Soverign Clouds you need to use the fromHost method to get the right endpoint. 

We're investigating more streamlined solutions in the long run, but for now...

**Comment by compulim** [comment]
Thanks @rhurey for the tips.

This is done on Web Chat side, in this PR, https://github.com/microsoft/BotFramework-WebChat/pull/3040.

The work is only for traditional STT/TTS but not Direct Line Speech.

**Comment by rhurey** [comment]
Closing then
