### ISSUE TITLE
SpeechConfig.fromHost not resolving websocker URI

### ISSUE THREAD

**Issue by marksy-91** [microsoft/cognitive-services-speech-sdk-js#169]
Initialising the speech config using the fromHost doesn't resolve the websocket URI correctly.

I'm attempting to use the speech service installed in an on-prem container instance that I was granted access to as part of the gated preview. Following the documentation, I initialised my speech configuration as follows.

```javascript
const speechConfig = SpeechSDK.SpeechConfig.fromHost("ws://localhost:5000");
```

When attempting to start a recognition, I see the following error in the console:

```bash
(cancel) Reason: Error: Unable to contact server. StatusCode: 500, undefined Reason: SyntaxError: Failed to construct 'WebSocket': The URL 'undefined//undefined:undefined/speech/recognition/conversation/cognitiveservices/v1?language=en-US&format=simple&X-ConnectionId=B295D9AB43584BC9A3DF11251421AC21' is invalid.
```

I have confirmed my container instance is up and running by navigating to localhost:5000 in my browser, where I can see the Swagger URL.

![image](https://user-images.githubusercontent.com/35209732/78001990-3c219d00-7382-11ea-9445-c24fd79613cd.png)

**Comment by lisaweixu** [comment]
You would need to put an URL, https://developer.mozilla.org/en-US/docs/Web/API/URL/URL, to FromHost,  not a string.

**Comment by oscholz** [comment]
Closing issue per @lisaweixu 's comment
