### ISSUE TITLE
Offer package managers like NPM

### ISSUE THREAD

**Issue by robinmanuelthiel** [Microsoft/cognitive-services-speech-sdk-js#17]
From a modern and state of the art JavaScript SDK, I would highly expect a way to integrate it into my project using a package manager like NPM instead of downloading zip files from the docs.microsoft.com website, as it is the current state.

Please provide official npm support to make it easier to install, version and update the SDK as a nice dependency in your customer's projects.

**Comment by rhurey** [comment]
https://www.npmjs.com/package/microsoft-cognitiveservices-speech-sdk

**Comment by robinmanuelthiel** [comment]
We should add this information to the README page and the offical docs.

**Comment by wolfma61** [comment]
already happened ...
>>>The JavaScript versions of the Cognitive Services Speech SDK supports browser scenarios as well as the use in a Node.js environment. For the browser support you find the QuickStart here. For the Node.js environment you find the QuickStart here, in addition a package is available from npmjs.
