### ISSUE TITLE
is it support React Native?

### ISSUE THREAD

**Issue by lkbansal1993** [microsoft/cognitive-services-speech-sdk-js#177]
Hello,
This node module is support or not for react native app? can you please suggest right way for configure microsoft text to speech task?

npm install microsoft-cognitiveservices-speech-sdk

**Comment by oscholz** [comment]
@lkbansal1993  we haven't tested the JavaScript Speech SDK with React Native yet, but we don't know of anything that should stand in the way of using the two together. We encourage you to give it a try. There is a chance that you will encounter some issues. We had a customer that used the JavaScript Speech SDK with Angular, and ran into a tools issue. This was technically a bug in the tool, but we were able to make a change in our code to work around the issue.
So if you try this, and find an issue, please reactivate this issue, and let us know what you found. We'll be happy to try to help.

Thank you for using the JS Speech SDK!

**Comment by cleandevcode** [comment]
Hi, @oscholz 
I am trying to use this SDK for React Native Android by following this sample [project](https://github.com/microsoft/cognitive-services-sdk-react-native-example).

Of course I`ve used JS SDK and could install successfully without any errors.
But `recognizer `object does not have `recognized `and `recognizing `functions.

Can you please let me know if this SDK works for React Native?
Regards.
