### ISSUE TITLE
Reduce speech started event latency

### ISSUE THREAD

**Issue by antoninklopp** [microsoft/cognitive-services-speech-sdk-js#185]
Hello, 

After looking carefully at the SDK it seems to me that the entire processing is done on the server side, and thus it will create a small latency between the moment the user starts to speak and first recognized words. 

After some tests it seems that [speechStartDetected](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/0413695664b8daa71f01f07f52c18b43fb2f4091/src/sdk/Recognizer.ts#L74) and [recognizing](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/0413695664b8daa71f01f07f52c18b43fb2f4091/src/sdk/SpeechRecognizer.ts#L61) first event are very close in time and happen some time after I started to speak (1 or 2 seconds maybe). 

I wanted to know if it was possible to be able to detect client side if a user started to speak, maybe with some pre-processing before sending the audio. Does such an API exist?

**Comment by chrisbasoglu** [comment]
Not currently.  There is some planning for future releases with client side processing, but not in the near term.

**Comment by paolopiaggesi** [comment]
hello @chrisbasoglu! has any improvement around this topic been introduced?
we noticed this very same behaviour and we were wondering if there's anything that can be done to reduce the latency between `speechStartDetected` and `recognizing`
