### ISSUE TITLE
Redirect connection to custom service via websockets

### ISSUE THREAD

**Issue by karrocon** [microsoft/cognitive-services-speech-sdk-js#189]
As a developer, I would like to use the parts of this library related to audio capture and conversion to send recognition-ready chunks to a web socket. Then, it should be easy to add a custom secure middleware to forward those chunks to the desired region and subscription.

In my case scenario, I want to provide a speech recognition service to a group of clients that should not know the grammar specification beforehand.

**Comment by rhurey** [comment]
Today we don't have a sample proxy for this, but have been looking at developing something in that space.

For your application, would you still be looking to get the events raised back at the originating client?

**Comment by oscholz** [comment]
@karrocon We've added this work to our backlog. When we resolve the backlog issue, we will update this GH issue with information about the release that will contain support for this. Until then, I'm closing this issue. If you have additional information for us about the question @rhurey asked, please reactivate the issue with that info.
Thank you for using the JS Speech SDK!
