### ISSUE TITLE
Support PropertyId.SpeechServiceConnection_SynthOutputFormat

### ISSUE THREAD

**Issue by alopix** [microsoft/cognitive-services-speech-sdk-js#193]
The `AudioAgent` does not seem to support the property `PropertyId.SpeechServiceConnection_SynthOutputFormat` yet, in order to set the `ttlAudioFormat` in the initial context messages for DLS.

**Comment by modnarb** [comment]
Hi @alopix, I have an active work item for this and will get you an update within the next week. I'm closing the issue here on github until then, but I'll use it to reactivate/reply with progress.

**Comment by modnarb** [comment]
Hi @alopix, this change has been included in the 1.13 release which should be available over the next few days.
