### ISSUE TITLE
SDK for Javascript vs Rest API

### ISSUE THREAD

**Issue by ozgurgul** [microsoft/cognitive-services-speech-sdk-js#197]
Hi MSFT team, we have tested (y)our REST API for short file and microsoft-cognitiveservices-speech-sdk for JavaScript and realised that transcript results are different with V1 Endpoint -https://uksouth.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?cid=******-  and SDK for JavaScript . It seems boiler plate code is still not slicing the audio correctly and short utterances are coming back differently. 

PS: It feels like it is related to sending FileStream across to the server - Regarding #73 - Continuous recognition doesn't work well

**Comment by trrwilson** [comment]
Thanks for getting back in touch and tying it back to the previous issue, too.

Some degree of difference between the two is expected but it sounds like you're seeing noticeable problems with the audio segmentation in the JS SDK sample. Is that a fair assessment? If so, could you share an example of an utterance (either audio or just the typed words that are spoken!) for us to reproduce? We'll evaluate on our side, as well, and get this tracked in our backlog.

**Comment by ozgurgul** [comment]
Hi Travis, 

Thanks for picking it up. 

We are transcribing the WAV file whose recording is "Constant push, <silence for 4-5 sec> yes we can."

Base Model | Constant food, yes we can.
Custom Model REST API | Constant push, yes we can.
Custom Model Speech SDK C# | Constant push. Yes we can.
Custom Model Speech SDK JS | Constant food.

Hope it helps.

**Comment by ozgurgul** [comment]
@trrwilson, If you drop me a line from ozgur DOT gul AT hpe DOT com, I can send you the audio file for you to test. Thanks,

**Comment by rhurey** [comment]
Thanks for the audio. Turns out that file has a 78 byte header. Which is longer than than 44 bytes the samples skip.

We're going to look at adding a fromWavFileInput(path:string) to solve the need to parse the header and split the bytes in the samples / your code.

**Comment by philenius** [comment]
We're experiencing the same problem where the second sentence of audio recordings is always missing, if we're using Speech SDK to transcribe an audio file and the recording contains a break. Are there any updates on this issue?

**Example:**
WAV file in 16 kHz, mono, 11 seconds: `Ich habe Luftverlust auf der zweiten Lok. <break 1.2s> Ich muss da mal nachschauen gehen.`

* Custom Model with Speech SDK v1.15.1 in Node.js:
  `Ich habe Luftverlust auf der zweiten Lok.`
* Custom Model with REST API v1 in Node.js:
  ` Ich habe Luftverlust auf der zweiten Lok, ich muss da mal
nachschauen gehen.`

**Comment by glharper** [comment]
@philenius Thanks for commenting...would you mind sharing the wav file that reproduces this issue?

**Comment by philenius** [comment]
@glharper here's the audio sample as a zip file. Don't be surprised, the speaker is a non-native speaker and we have added artificial background sounds. The baseline STT model might not be able to transcribe it correctly:

[audio-sample-DE-16kHz.zip](https://github.com/microsoft/cognitive-services-speech-sdk-js/files/6421804/audio-sample-DE-16kHz.zip)

**Comment by glharper** [comment]
@philenius using recognizeOnceAsync(), I do only get the first sentence because of the pause, but startContinuousRecognitionAsync() gives results for the whole file. Are you seeing this with startContinuousRecognitionAsync()?

**Comment by philenius** [comment]
Sorry for my late reply, @glharper . You were right. I was using `recognizeOnceAsync()` instead of `startContinuousRecognitionAsync()`. My bad, I didn't read the documentation of `recognizeOnceAsnyc()` which says:
> Starts speech recognition, and stops after the first utterance is recognized. [...]

That explains why the second utterance / the second sentence wasn't transcribed.

I changed the code to use `startContinuousRecognitionAsync()` according to the explanation in issue [#931](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/931). Now, it works. Thank you!

For others who want to use Speech SDK with continuous recognition, too, here's my code sample:

```javascript
'use strict';

const fs = require('fs');
const sdk = require('microsoft-cognitiveservices-speech-sdk');

(function () {
    const subscriptionKey = 'YOUR-SUBSCRIPTION-KEY';
    const serviceRegion = 'YOUR-REGION'; // e.g. westeurope

    const filename = 'YOUR-AUDIO-FILE.wav';

    const pushStream = sdk.AudioInputStream.createPushStream();

    fs.createReadStream(filename)
        .on('data', (arrayBuffer) => {
            pushStream.write(arrayBuffer.slice());
        })
        .on('end', () => {
            pushStream.close();
        });

    const audioConfig = sdk.AudioConfig.fromStreamInput(pushStream);
    const speechConfig = sdk.SpeechConfig.fromSubscription(subscriptionKey, serviceRegion);

    speechConfig.speechRecognitionLanguage = 'YOUR-LANGUAGE-CODE'; // e.g. de-DE

    const recognizer = new sdk.SpeechRecognizer(speechConfig, audioConfig);

    recognizer.recognized = (sender, event) => {
        try {
            console.log(`recognized text: ${event.result.text}`);
        } catch (error) {
            console.error(`Failed to extract recognized text with error: ${JSON.stringify(error)}`);
        }
    };

    recognizer.canceled = (sender, event) => {
        console.log(`Recognition canceled with event ${JSON.stringify(event)}`);

        recognizer.stopContinuousRecognitionAsync((_) => {
            console.log(`Stopped continuous recognition`);
            recognizer.close();
        }, (error) => {
            console.error(`Failed to stop continuous recognition with error: ${error}`);
        });
    };

    recognizer.startContinuousRecognitionAsync((_) => {
        console.log(`Started continuous recognition`);
    }, (error) => {
        console.error(`Failed to start continuous recognition with error: ${error}`);
        recognizer.close();
    });
})();

```

**Comment by glharper** [comment]
@philenius Glad that worked for you, and thanks for using Speech SDK! By the way, the following code: 
```    const pushStream = sdk.AudioInputStream.createPushStream();

    fs.createReadStream(filename)
        .on('data', (arrayBuffer) => {
            pushStream.write(arrayBuffer.slice());
        })
        .on('end', () => {
            pushStream.close();
        });

    const audioConfig = sdk.AudioConfig.fromStreamInput(pushStream);
```
can now be simplified to:
```
   const audioConfig = sdk.AudioConfig.fromWavFileInput(fs.readFileSync(filename), filename);
```
This simplified code also gives the benefit of wav header checking. :-)
