### ISSUE TITLE
Host is cached and not changed if new instance of SpeechRecognizer with different region

### ISSUE THREAD

**Issue by andreyjamer** [Microsoft/cognitive-services-speech-sdk-js#20]
Hello! 
I've got very strange behavior of SpeechRecognizer  instance.
I've started from the quickstart example - https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstart-js-browser
The example allows to switch regions to try different setting. By if once we created one instance of SpeechRecognizer then all others will be created with first region settings, no matter what region is selected.
It is because inside the SpeechConnectionFactory host variable is taken from Storage.local that is InMemoryStorage. So parameter is set once and not changed during the run-time.
And it is not very obvious. Also other parameters use the same approach. 
So it is impossible to change region or debug mode in run-time.

It is not a very big problem, but it cost me an hour to understand what happened. :)

**Comment by wolfma61** [comment]
sorry for the late response, we are looking into this ....

**Comment by fmegen** [comment]
Hi @andreyjamer,
we are currently fixing the underlying issue.
In case you are interested, please have a look at this pullrequest
https://github.com/Microsoft/cognitive-services-speech-sdk-js/pull/25

kind regards,
 friedel

**Comment by andreyjamer** [comment]
Hi @fmegen,
I checked and it's looking very good.
Thank you!

**Comment by fmegen** [comment]
glad to hear that this is working now!
thanks again for your investigation!

**Comment by andreyjamer** [comment]
Hi!
Could you rebuild npm package?

**Comment by wolfma61** [comment]
there will be an update later this week
