### ISSUE TITLE
Conversation Transcription Support

### ISSUE THREAD

**Issue by hraz-msft** [microsoft/cognitive-services-speech-sdk-js#209]
Do you support the Conversation Transcription APIs in the JS version?
I don't see any docs related to this, and I don't succeed to convert the C# demo to JS (the objects are different).

**Comment by rhurey** [comment]
Sadly the SDK doesn't have Conversation Transcription API's today.

We do have the work to add it planned into the next iteration.

**Comment by rhurey** [comment]
I'm going to close this, let me know if there's more questions.
