### ISSUE TITLE
reference error: window is not defined

### ISSUE THREAD

**Issue by pietersap** [Microsoft/cognitive-services-speech-sdk-js#21]
I am running the following code snippet in node.js while testing the SDK.

```

const speech = require("microsoft-cognitiveservices-speech-sdk");
const rp = require("request-promise");

const region = "westeurope";
const {speechKey, speechTokenEndpoint} = require("./config.json");

async function transcribe(audioconfig) {    
    try {
        const token = await rp.post({uri: speechTokenEndpoint,headers: {"Ocp-Apim-Subscription-Key":speechKey}});
        const speechconfig = speech.SpeechConfig.fromAuthorizationToken(token, region);
        const recognizer = new speech.SpeechRecognizer(speechconfig, audioconfig);
        recognizer.startContinuousRecognitionAsync(recognitionStartedCallback, recognitionFailedCallback);

    } catch (err) {
        console.log(err);
    }
}
function recognitionFailedCallback(err) {
    console.log("[ERROR] starting speech-to-text recognition failed: ", err);
}
function recognitionStartedCallback() {
    console.log("[INFO] speech-to-text recognition started")
}

const audioconfig = speech.AudioConfig.fromDefaultMicrophoneInput();
transcribe(audioconfig);

```

This raises an error in startContinuousRecognitionAsync:
**[ERROR] starting speech-to-text recognition failed:  ReferenceError: window is not defined**

I cannot find the cause in the source code. I suspect it might be related to the following snippet in Recognizer.ts:

```
let osPlatform = (typeof window !== "undefined") ? "Browser" : "Node";
```

However, running this directly in node works perfectly fine.

Windows 10
node v10.15.0

**Comment by rhurey** [comment]
The default microphone support uses the Web Audio API to conjure a microphone stream. The node environment doesn't support this, and the defensive code to return an nicer error message handles a browser that doesn't support audio, but not the entire window global being undefined.

Sorry about that. For pure node code you can use a file, push or pull stream to get audio into the speech recognition engine.

**Comment by wolfma61** [comment]
closing this one ... 
for more issues, please open a new request.
thx
