### ISSUE TITLE
listenOnce only works one time

### ISSUE THREAD

**Issue by encorona-ms** [microsoft/cognitive-services-speech-sdk-js#211]
Consider the following scenario

1. Start a connection
2. listen for audio
3. Custom Commands responds and listens again using listenOnce
4. the user never responds so after 5 seconds the sdk stops listening
5. when we try to listen for audio again (i.e. click the mic button again) with listenOnce it doesn't work anymore

**Comment by rhurey** [comment]
Thanks for getting in touch with us.

Looking at the behavior when there's only silence sent to the service for listenOnceAsync, it looks like the correct events aren't being raised. 

I've opened a workitem in our internal tracking system and will follow up tomorrow once I know if the engineers who own the dialog connector are in agreement.

**Comment by rhurey** [comment]
We've got an internal bug tracking this, and will update this issue when it's fixed.

**Comment by collegewap** [comment]
Any update on this?

**Comment by brandom-msft** [comment]
A fix addressing this has been merged and will also be available in the next release.
#244

**Comment by brandom-msft** [comment]
@compulim for awareness on the related, blocking issue for WebChat
