### ISSUE TITLE
How to use SpeechServiceConnection_EndSilenceTimeoutMs?

### ISSUE THREAD

**Issue by siddiqaa** [microsoft/cognitive-services-speech-sdk-js#214]
Hello, 

I can't find documentation on how to use SpeechServiceConnection_EndSilenceTimeoutMs added in 1.7.0. Is line below acceptable to reduce the default silence detection for the end to 2 seconds from the default larger timeout value?

speechConfig.setProperty(SpeechSDK.SpeechServiceConnection_EndSilenceTimeoutMs, 2000)

Thanks

**Comment by rhurey** [comment]
The best explanation I have is here:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/502#issuecomment-585987283

The one line version is: "End Silence Timeout controls how long after speech is stopped before the speechEndDetected event is raised when doing continuous recognition."

**Comment by siddiqaa** [comment]
Thanks - helpful to read the linked explanation
