### ISSUE TITLE
recognizeOnceAsync throwing Runtime error

### ISSUE THREAD

**Issue by rajdhandus** [microsoft/cognitive-services-speech-sdk-js#220]
I am using JS SDK from AngularJS app. I see the below error when I trigger the recognizeOnceAsync method.

![image](https://user-images.githubusercontent.com/6888014/88934518-b853c080-d24e-11ea-8c72-fecc442a67dd.png)

**Comment by glharper** [comment]
Hi,
Thanks for writing this up. Some of your code there is hidden by the runtime error message. Could you copy/paste S.speechToText?

**Comment by glharper** [comment]
@rajdhandus Were you able to figure the issue out? If not, could I see the code mentioned above?
