### ISSUE TITLE
WebSocket connection immediately closed on macOS

### ISSUE THREAD

**Issue by brandom-msft** [microsoft/cognitive-services-speech-sdk-js#221]
<Opening to track an issue raised by @compulim, his details pasted below> 

We are testing Web Chat on macOS and we found the Web Socket connection closed immediately after it is connected.
 
We tried older versions of Web Chat and same. We are sure it was working on older versions before.
 
Do you know if there is any service interruption on your side related to macOS Safari WS connection to westus2.convai.speech.microsoft.com?

It seems only repro on macOS but not iOS, PC, and Android.

You can test Web Chat with a few clicks.
https://compulim.github.io/webchat-loader/

**Comment by compulim** [comment]
<img width="1440" alt="Screen Shot 2020-07-30 at 11 58 57 AM" src="https://user-images.githubusercontent.com/1622400/88963153-4edaae80-d25c-11ea-87e6-ba2ea720e4a6.png">

This is what we are seeing. If you look at the timestamp on the right-hand side, the Web Socket connection get closed immediately on connect.

To try it out, click these 3 things on https://compulim.github.io/webchat-loader/

![image](https://user-images.githubusercontent.com/1622400/88963415-a842dd80-d25c-11ea-818d-8117a862f531.png)

**Comment by brandom-msft** [comment]
@compulim What version of the SDK is this using? There have been fixes addressing Safari issues published with the 1.13 update

**Comment by compulim** [comment]
I just bumped to 1.13.1 with some hacks before #213 go live. 😛

And I am still seeing the connection get quickly terminated.

<img width="1263" alt="Screen Shot 2020-08-07 at 4 28 39 PM" src="https://user-images.githubusercontent.com/1622400/89696152-6e607f80-d8cb-11ea-9c58-a3559d374564.png">

**Comment by glharper** [comment]
@compulim I'm actually getting a connection close with Edge/Win10 with 4.9.2 using westus and an internal key. The response I'm seeing is: 
WebSocket connection to 'wss://westus.convai.speech.microsoft.com/api/v3?language=en-US&format=simple&Authorization=[...]&X-ConnectionId=DBBF6632F9B048C49C6C1D727CC6D26D' failed: Error during WebSocket handshake: Unexpected response code: 200
Could you email a good key for westus to glharper(at)microsoft or grab me on teams?

**Comment by collegewap** [comment]
Reproducible in Windows 10 + Chrome if I try the following:

![image](https://user-images.githubusercontent.com/9767383/90091698-a7be4280-dd44-11ea-8cde-f2d55fb9ca73.png)

Unable to replicate if I try the steps given in https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/221#issuecomment-666606199 

The difference I could see is in the token generation endpoint:

Not working: https://webchat-mockbot.azurewebsites.net/speechservices/token

Working: https://webchat-mockbot-streaming.azurewebsites.net/speechservices/token

**Comment by collegewap** [comment]
Also, I am facing same issue with my subscription key

https://github.com/microsoft/BotFramework-WebChat/issues/3407

Tried in https://compulim.github.io/webchat-loader/ and same error

**Comment by steps371** [comment]
Also facing the same issue, which I logged on this ticket on the WebChat repo (99% sure it's a duplicate)

https://github.com/microsoft/BotFramework-WebChat/issues/3307

**Comment by steps371** [comment]
I was able to fix our instance of the issue with the following:

I created a new Cognitive Service Speech resource in the same region as my Bot (I discovered bot was in western Europe, while cognitive resource was in west US). 

I don't recall any documentation stating this constraint, so should likely be added as a disclaimer to relevant docs

**Comment by compulim** [comment]
AFAIK, although Cognitive Services is region-based, Azure Bot Service is not. So mix-and-match them should be fine.

And I am only able to repro it on macOS Safari. But not other browsers, including Chrome on Windows, iOS Safari, or macOS Chrome.

**Comment by steps371** [comment]
@compulim that is strange, because we were experiencing the issue across multiple browsers on Mac, and creating a new cognitive speech resource appeared to have fixed the issue across browsers. 

Maybe something changed in the cognitive services deployments?

**Comment by joeyreinders** [comment]
I've tried creating a new Cognitive Speech Resource, yet for me this didn't change a thing.
The WebSocket still closes immediately.

I have an other application which uses an old version of this library (version 1.2.1) and this one works fine.

**Comment by compulim** [comment]
Any updates?

**Comment by glharper** [comment]
@compulim I'm tracking this through [https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/235](https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/235), as that issue includes SDK facing code I can help debug.

**Comment by compulim** [comment]
FYI, we are also seeing very similar issue on iOS 13.6.1. Connection get closed immediately after connect. And it works normally on other browsers connecting to the same bot and using same SDK.

![image](https://user-images.githubusercontent.com/1622400/92686942-80c94100-f2ef-11ea-8b37-52e65e249164.png)

In a few weeks ahead, we will bump to latest version of Speech SDK and see if anything will improve.

**Comment by compulim** [comment]
FYI, we are still seeing the issue on 1.13.1.

**Comment by brandom-msft** [comment]
@compulim 1.14 has gone live, can you update and let me know what you see with that?

**Comment by compulim** [comment]
Do you know anything changed for the connection code in 1.14.0?

We have been testing multiple versions of Speech SDK for the last few months and still seeing the same issue. Maybe it's a good indication that your team should jump into repro-ing it. FYI, it only repro with the DLSpeech, but not other connection types.

**Comment by brandom-msft** [comment]
@compulim 1.14 did have a large set of changes as it was one of our longer releases.

From the behavior seen here, it doesn't appear to be a BF SDK issue nor a JS SDK client issue. There have been similar issues reported like #235 above, I'm inclined to think this is a service issue. Can you try with a different cognitive services subscription to test that hypothesis? Then we can involve the service team for some support.

**Comment by compulim** [comment]
I no longer see this issue when I test it on macOS Safari 14.0.3 today. Probably patched on the service side?

**Comment by Fradulentus** [comment]
Отправлено из приложения "Почта<https://go.microsoft.com/fwlink/?LinkId=550986>" для Windows 10

От: William ***@***.***>
Отправлено: 3 апреля 2021 г. в 2:21
Кому: ***@***.***>
Копия: ***@***.***>
Тема: Re: [microsoft/cognitive-services-speech-sdk-js] WebSocket connection immediately closed on macOS (#221)


I no longer see this issue when I test it on macOS Safari 14.0.3 today. Probably patched on the service side?
