### ISSUE TITLE
JS SDK is misfunctional in inactive webpages

### ISSUE THREAD

**Issue by Dumeng** [microsoft/cognitive-services-speech-sdk-js#225]
When using the startContinuousRecognitionAsync() to activate the transcription in the web browser, the SDK will create a WebSocket connection and keep upload audio data per 100ms. However, if the webpage becomes inactive, such as users switch to other tabs, the uploading period will become 1 second. This issue makes the SDK cannot provide the transcriptions. Please refer to the below screenshots.

Active pages
![image](https://user-images.githubusercontent.com/5249513/89527309-b32cdd80-d81b-11ea-8847-2a357f3332b8.png)

Inactive pages
![image](https://user-images.githubusercontent.com/5249513/89527318-b627ce00-d81b-11ea-81e8-9b65cf444615.png)

I have located the root cause, which is the setInterval() function. Please refer to below link:
https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout#Timeouts_in_inactive_tabs_throttled_to_%E2%89%A5_1000ms

I'm using a tricky way to work around this issue. Hope the team can provide an official fix.

**Comment by rhurey** [comment]
Are you using 1.13.x? This should have been fixed in that release...

**Comment by Dumeng** [comment]
Yes, I see it was fixed in the new release 8 hours ago.
