### ISSUE TITLE
startContinuousRecognitionAsync function doesn't support intention recognition 

### ISSUE THREAD

**Issue by Narcissist1** [microsoft/cognitive-services-speech-sdk-js#228]
Hi, I'm using the IntentRecognizer of the SDK on the browser side. I found the intention recognition only works in the recognizeOnceAsync function but not in the startContinuousRecognitionAsync function. By looking at the code, I noticed there's one key difference in an if statement as below.

In recognizeOnceAsync 

https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/8cbd7057ee084bc3a53643a17c6a8c5687d9f027/src/sdk/IntentRecognizer.ts#L151

In startContinuousRecognitionAsync 

https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/8cbd7057ee084bc3a53643a17c6a8c5687d9f027/src/sdk/IntentRecognizer.ts#L174

The `this.privUmbrellaIntent` variable did use in startContinuousRecognitionAsync function but not been checked.

I just want to know is it intentionally designed like this or there are some other reasons. Thank you very much

### Version of the Cognitive Services Speech SDK:
Latest(1.31.1)

### Platform, Operating System, and Programming Language:
OS: macOS Catalina, Windows 10
Programming language: JavaScript(browser side)

**Comment by glharper** [comment]
@Narcissist1 A fix for this was added to 1.14, could you update and recheck? Latest version zip [here](https://csspeechstorage.blob.core.windows.net/drop/1.14.1/SpeechSDK-JavaScript-1.14.1.zip)

**Comment by Narcissist1** [comment]
> @Narcissist1 A fix for this was added to 1.14, could you update and recheck? Latest version zip [here](https://csspeechstorage.blob.core.windows.net/drop/1.14.1/SpeechSDK-JavaScript-1.14.1.zip)

Looks working, thanks!
