### ISSUE TITLE
Continuous recognition example?

### ISSUE THREAD

**Issue by peey** [microsoft/cognitive-services-speech-sdk-js#230]
I'm unable to find an example using browser-side JavaScript for continuous recognition (live transcription / dictation) 

Where can I find these?

**Comment by rhurey** [comment]
IT's not that it records it and then calls recognizeOnceAsync.

The sample code setups event callbacks and then calls recognize. The callback are invoked when messages are sent to the speech service.

Here's a simple(ish) web page that has a button to download the last audio recognized.

[index.zip](https://github.com/microsoft/cognitive-services-speech-sdk-js/files/5126846/index.zip)

**Comment by peey** [comment]
Thanks a lot for taking the time to prepare this. I'll have to take my time to go through this in more detail. 

Also, now that I've learnt that there are SO tags for this, I'll direct any future questions to there (so issues don't get cluttered).
