### ISSUE TITLE
Brazilian Portuguese transcription returns "undefined"

### ISSUE THREAD

**Issue by 4lp** [microsoft/cognitive-services-speech-sdk-js#233]
When attempting to translate from English (United States) to Portuguese (Brazil) all transcriptions return `undefined`. I think this is on Microsoft's end since I can reproduce the issue on the demo site [here](https://azure.microsoft.com/en-us/services/cognitive-services/speech-translation/#features)

**Comment by rhurey** [comment]
We've found a discrepancy with the languages returned in the translation JSON for both Portuguese languages where the returned language code and the requested language differ.

"pt-br" is coming back as "pt" and "pt-pt" as "pt-PT"

We're investigating with the service team why this is.

**Comment by rhurey** [comment]
I have an answer...

As the translation service has added new languages, some backward compatibility meets documentation confusion happened. The translation will return pt-br as "pt" to maintain compatibility with the past before "pt-pt" was supported. Our documentation was updated for supported languages, but didn't take the service backward compatibility into account. Sorry about that.

I'm going to update the documentation and open a service task to preserve the client requested local definition in the response when it differs.
