### ISSUE TITLE
Error compiling with Typescript v4

### ISSUE THREAD

**Issue by orgads** [microsoft/cognitive-services-speech-sdk-js#234]
```
node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/sdk/CustomCommandsConfig.d.ts(45,9): error TS2611: 'applicationId' is defined as a property in class 'DialogServiceConfigImpl', but is overridden here in 'CustomCommandsConfig' as an accessor.
```

**Comment by mekacharan** [comment]
Hi any update on this issue. I am also getting the same issue and any tentative date that the fix will be released

**Comment by mekacharan** [comment]
![image](https://user-images.githubusercontent.com/45178062/94812426-56f9ca80-0414-11eb-98c4-1c4c997623e6.png)

When I have added "  public set applicationId(value: string) { }" I am getting empty block while building the solution
