### ISSUE TITLE
Unable to contact server. StatusCode: 1006, undefined Reason:  Unexpected server response: 200

### ISSUE THREAD

**Issue by bivas6** [microsoft/cognitive-services-speech-sdk-js#235]
Hi,

I'm trying to use the sdk as described [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/voice-assistants?pivots=programming-language-java&tabs=jre), but I'm getting this weird error: `Unable to contact server. StatusCode: 1006, undefined Reason:  Unexpected server response: 200`

I followed [this](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-directlinespeech?view=azure-bot-service-4.0) guide to connect existing Bot with existing Cognitive Service.

code:

```
const sdk = require('microsoft-cognitiveservices-speech-sdk');
const fs = require('fs');
const Throttle = require('throttle');

async function main() {
  console.log('start')
  const fileName = 'test-message-16k.wav'
  const audioStream = fs.createReadStream(fileName);
  const pushStream = sdk.AudioInputStream.createPushStream();
  const handleData = (buf) => {
    pushStream.write(buf.slice());
    console.log('data')
  };

  audioStream.pipe(new Throttle(16384))
    .on('data', handleData)
    .once('close', () => {
      console.log('close')
      pushStream.close();
      audioStream.removeListener('data', handleData);
    });
  const audioConfig = sdk.AudioConfig.fromStreamInput(pushStream)
  const botConfig = sdk.BotFrameworkConfig.fromSubscription('subscription-key', 'region')
  const reco = new sdk.DialogServiceConnector(botConfig, audioConfig)
  reco.recognizing = (_s, event) => {
    console.log('hypothesis', {
      text: event.result.text
    });
  };

  reco.recognized = (_s, event) => {
    ... <some code here>
    }
  };

  reco.canceled = (_s, event) => {
    ... <some code here>
  };

  // Signals that a new session has started with the speech service
  reco.sessionStarted = (_s, event) => {
    ... <some code here>
  };

  // Signals the end of a session with the speech service.
  reco.sessionStopped = (_s, event) => {
    ... <some code here>
  };

  // Signals that the speech service has started to detect speech.
  reco.speechStartDetected = (_s, event) => {
    ... <some code here>
  };

  // Signals that the speech service has detected that speech has stopped.
  reco.speechEndDetected = (_s, event) => {
    ... <some code here>
  };
  console.log('connect')
  reco.connect()
  reco.listenOnceAsync(undefined,
    (e) => {
      console.error('error')
      console.error(e)
    }
  );
  console.log('end')
}
main().catch((r) => console.error(r))
```

output is somthing like:

```start
data
data
...
reco
connect
end
data
data
....
error
Unable to contact server. StatusCode: 1006, undefined Reason:  Unexpected server response: 200
data
data
```

This `'subscription-key', 'region'` are in used in other parts of our code to connect azure speech sdk and direct line and it works as expected.

Please advise.

Thanks

cc: @orgads

**Comment by nisheetjain** [comment]
Thanks orgads for the sharing the issue with us.

To make sure the setup is right, can you confirm if you have enabled the channel correctly in Azure bot service following this [page](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-directlinespeech?view=azure-bot-service-4.0#:~:text=Add%20the%20Direct%20Line%20Speech%20channel,-To%20add%20the&text=Click%20on%20Channels%20in%20the,shown%20in%20the%20picture%20below.)?

**Comment by orgads** [comment]
We did.

**Comment by compulim** [comment]
FYI, this could be similar to #221, we are also seeing HTTP 200 immediately after Web Socket connection established. Only on Mac though.

**Comment by glharper** [comment]
Hi @bivas6,
One thing that comes to mind, connect() is async. Try this block at the end.

```
  reco.connect(
    function () {
      reco.listenOnceAsync(
        function (result) {
          // Handled by recognizing/recognized callback
        },
        function (err) {
            console.log(err);
        });
    },
    function (err) {
        console.log("Connect error:");
        console.log(err);
    });
```
Also, I'm setting the language for the botConfig and using sdk pushStreams for the audio input:

```
  // create the push stream we need for the speech sdk.
  var pushStream = sdk.AudioInputStream.createPushStream();
  
  // open the file and push it to the push stream.
  fs.createReadStream(filename).on('data', function(arrayBuffer) {
    pushStream.write(arrayBuffer.slice());
  }).on('end', function() {
    pushStream.close();
  })
  
  var audioConfig = sdk.AudioConfig.fromStreamInput(pushStream);
  
  var botConfig = sdk.BotFrameworkConfig.fromSubscription(subscriptionKey, serviceRegion);
  
  botConfig.speechRecognitionLanguage = "en-US";
```

Could you try that in your code?

Thanks,
Glenn

**Comment by bivas6** [comment]
Thanks @glharper, but it didn't works.

There is no `Unable to contact server` error, but no any other response as well. 

BTW, If this is the way to connect the server, `DialogServiceConnector.d.ts` needs update:
```
    /**
     * Starts a connection to the service.
     * Users can optionally call connect() to manually set up a connection in advance, before starting interactions.
     *
     * Note: On return, the connection might not be ready yet. Please subscribe to the Connected event to
     * be notified when the connection is established.
     * @member DialogServiceConnector.prototype.connect
     * @function
     * @public
     */
    connect(): void;
```

Thanks!

**Comment by glharper** [comment]
@bivas6 Giving it some though, why are you calling connect() at all? listenOnceAsync() handles all the connection setup already, and double connecting could introduce issues like this one. Try: 
```
  reco.listenOnceAsync(
    function (result) {
      reco.close();
      reco = undefined;
    },
    function (err) {
      console.log(err);
      reco.close();
      reco = undefined;
    });
```
without any call to connect() in the code.

Thanks. :-)

**Comment by bivas6** [comment]
@glharper It gives `Unable to contact server. StatusCode: 1006, undefined Reason:  Unexpected server response: 200`. 

Thanks for trying.

**Comment by glharper** [comment]
@bivas6 I'm attaching a simple html page that triggers listenOnceAsync() on a given wav file. Using my creds for westus2, I've been unable to repro this issue, but if I could, I can look at fiddler and at least see where in the process this issue is happening. If you can modify this code to repro the issue, or have a key/region pair that reliably causes this, please update this or ping me on teams. 

Thanks,
Glenn
[bot_test_github.zip](https://github.com/microsoft/cognitive-services-speech-sdk-js/files/5226536/bot_test_github.zip)

**Comment by bivas6** [comment]
Hi @glharper, 
we have changed the cognitive service account in the direct line speech channel, and now it works.

Thanks for the help!
