### ISSUE TITLE
Problem with speech recognition in Safari iOS

### ISSUE THREAD

**Issue by MeloJR** [microsoft/cognitive-services-speech-sdk-js#238]
Hi,

I am making an app that uses this library to detect what the user is saying and in Chrome all works fine but in Safari iOS it fails because the app asks for permission too late, not when I call the `startContinuousRecognitionAsync` method. I have debugged a little and done some experiments and I have found that if I comment the next condition
https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/e60968063e3e695c971b6e3accbd03fd191f2123/src/common.browser/MicAudioSource.ts#L147-L155
and always call the `next` method it works perfectly. What am I missing here?

It worths saying that I use other audio processing libraries that also use the `AudioContext API`

**Comment by brandom-msft** [comment]
hi @MeloJR - can you share some more details about this issue? When it fails, what is the behavior you see and/or error message you are getting?

**Comment by Fradulentus** [comment]
Если вы являетесь разработчиками чего либо, задумайтесь и не пытайтесь использую инструменты, освоить ремесло. 
Вольные каменщики существуют прежде всего, из того, что у них есть намерения чтобы просто раскрыть секрет запечатлев момент. Однажды мне пришлось видеть воочию, как один предприимчивый человек бил без устали с плеча по скале, строя ступеньки.
И так, перейдем к вашему вопросу.
Объясните здесь и сейчас, в режиме реальной словесности, зачем вам именно нужно научить машину слышать?
Модернизация — это степень ответственности живых пользователей, или все же результат действительно оправдывает присвоения любых значений, любым неизвестным?

**Comment by Fradulentus** [comment]
Если вы являетесь разработчиками чего либо, задумайтесь и не пытайтесь использую инструменты, освоить ремесло. 
Вольные каменщики существуют прежде всего, из того, что у них есть намерения чтобы просто раскрыть секрет запечатлев момент. Однажды мне пришлось видеть воочию, как один предприимчивый человек бил без устали с плеча по скале, строя ступеньки.
И так, перейдем к вашему вопросу.
Объясните здесь и сейчас, в режиме реальной словесности, зачем вам именно нужно научить машину слышать?
Модернизация — это степень ответственности живых пользователей, или все же результат действительно оправдывает присвоения любых значений, любым неизвестным?

Sorry
@Microsoft

**Comment by Fradulentus** [comment]
Если вы являетесь разработчиками чего либо, задумайтесь и не пытайтесь использую инструменты, освоить ремесло. 
Вольные каменщики существуют прежде всего, из того, что у них есть намерения чтобы просто раскрыть секрет запечатлев момент. Однажды мне пришлось видеть воочию, как один предприимчивый человек бил без устали с плеча по скале, строя ступеньки.
И так, перейдем к вашему вопросу.
Объясните здесь и сейчас, в режиме реальной словесности, зачем вам именно нужно научить машину слышать?
Модернизация — это степень ответственности живых пользователей, или все же результат действительно оправдывает присвоения любых значений, любым неизвестным?

Sorry
@Microsoft
