### ISSUE TITLE
Support for proactive messaging (within 5 minutes of last communication)

### ISSUE THREAD

**Issue by cwhitten** [microsoft/cognitive-services-speech-sdk-js#239]

**Comment by trrwilson** [comment]
Thanks for filing this item to track based on our off-GitHub conversation.

For extra detail: the question here is whether or not a JS SDK client that's already connected (a service interaction has happened in the last ~300 seconds and the WebSocket connection hasn't idled out) can receive an activity from the bot at any point. Cursory validation suggests "yes," but a slightly less cursory confirmation would still be good.

In contrast, #240 is the question of how we could make it so a JS SDK client that *isn't* currently connected (last interaction could be 6 minutes or 6 days ago) would be able to receive a bot-initiated activity. Many of the means of achieving this come with significant overhead or security concerns, so some careful evaluation needs to happen (and this ends up being a much further-reaching and longer-term question).
