### ISSUE TITLE
CPU is exploding on load

### ISSUE THREAD

**Issue by bivas6** [microsoft/cognitive-services-speech-sdk-js#242]
Hi,

We are trying to run multiple simultaneously `startContinuousRecognitionAsync` requests, but CPU is exploding.

We ran about 7 requests/second and in about ~3 minutes, the machine is crashed. 
Note that we are able to make 20 requests/second with [this package](https://github.com/orgads/ms-bing-speech-service#readme), and CPU is about 40-50% usage.

chrome inspector cpuprofile file is attached. 
[azure-ms-cpu.zip](https://github.com/microsoft/cognitive-services-speech-sdk-js/files/5195385/azure-ms-cpu.zip)

cc: @orgads 

Thanks!

**Comment by trrwilson** [comment]
Thanks for getting in touch!

We'll take a look at this apparent leak behavior ASAP and report back. How are you managing audio input for the 7 requests per second? If there's a sample usage you could share, that'd for sure be very helpful.

**Comment by bivas6** [comment]
```
import * as sdk from 'microsoft-cognitiveservices-speech-sdk';
import { Readable } from 'stream';
import getToken from './getToken';
import * as fs from 'fs'
import * as Throttle from 'throttle'
import * as path from 'path';

async function sendStream(stream: Readable) {
  const pushStream = sdk.AudioInputStream.createPushStream();
  const handleData = (buf: Buffer) => pushStream.write(buf.slice().buffer);

  stream
    .on('data', handleData)
    .once('close', () => {
      pushStream.close();
      stream.removeListener('data', handleData);
    });

  const audioConfig = sdk.AudioConfig.fromStreamInput(pushStream);
  const authToken = await getToken(); //getToken create and update valid authrization tokens
  const url = new URL('wss://westus2.stt.speech.microsoft.com/speech/recognition/dictation/cognitiveservices/v1');
  const speechConfig = sdk.SpeechConfig.fromEndpoint(url, '');
  speechConfig.authorizationToken = authToken;
  const recognizer = new sdk.SpeechRecognizer(speechConfig, audioConfig);
  _registerEvents(recognizer);
  recognizer.startContinuousRecognitionAsync(
    undefined,
    (err) => {
      console.error('err - ' + err);
      recognizer.close();
    }
  );
}

function _registerEvents(reco: sdk.SpeechRecognizer) {
  reco.recognizing = (_s: sdk.Recognizer, event: sdk.SpeechRecognitionEventArgs) => {
  };

  reco.recognized = (_s: sdk.Recognizer, event: sdk.SpeechRecognitionEventArgs) => {
  };

  reco.canceled = (_s: sdk.Recognizer, event: sdk.SpeechRecognitionCanceledEventArgs) => {
  };

  // Signals the end of a session with the speech service.
  reco.sessionStopped = (_s: sdk.Recognizer, event: sdk.SessionEventArgs) => {
  }
}


const load = (fileName: string, rate = 20) => {
  let seq = 0;
  setInterval(() => {
    const mySeq = seq++;
    const start = Date.now();
    try {
      const onEnd = () => console.log(`${mySeq}: done [${Date.now() - start}]`);
      const audioStream = fs.createReadStream(fileName).pipe(new Throttle(32000), { end: false });
      sendStream(audioStream);
      setTimeout(() => {
        onEnd();
      }, 5000);
    } catch (err) {
      console.error(`${mySeq}: ${err}`);
    }
  }, 1000 / rate);
};

const filename = path.resolve(__dirname, '../test-message-16k.wav');
load(filename, 7);
```

**Comment by glharper** [comment]
@bivas6 The issue seems to be that you are creating many recognizers, putting a lot of audio data into each, then putting them out of scope without giving them a chance to dispose properly.  (Recognizers must hang onto X seconds of audio data because of response lag from the service and retry logic in case of network instability.) The following code works for me without memory or CPU issues:

```
  // pull in the required packages.
  var sdk = require("microsoft-cognitiveservices-speech-sdk");
  var fs = require("fs");
  var Throttle = require("throttle");
  
  // replace with your own subscription key,
  // service region (e.g., "westus"), and
  // the name of the file you want to run
  // through the speech recognizer.
  var subscriptionKey = "<<KEY_HERE>>";
  var serviceRegion = "<<REGION>>"; // e.g., "westus"
  var filename = "<<FILENAME>>.wav"; // 16000 Hz, Mono
  
  // now create the audio-config pointing to our stream and
  // the speech config specifying the language.
  var speechConfig = sdk.SpeechConfig.fromSubscription(subscriptionKey, serviceRegion);
  
  // setting the recognition language to English.
  speechConfig.speechRecognitionLanguage = "en-US";
  
  async function startReco(recognizer) {
    recognizer.recognizing = (_s, event) => {
      console.log('recognizing');
    };

    recognizer.recognized = (_s, event) => {
      console.log('recognized');
    };

    recognizer.canceled = (_s, event) => {
      console.log('canceled');
    };

    // Signals the end of a session with the speech service.
    recognizer.sessionStopped = (_s, event) => {
      console.log('sessionStopped');
      recognizer.close();
      recognizer = undefined;
    }
    recognizer.startContinuousRecognitionAsync(
        undefined,
        (err) => {
          console.error('err - ' + err);
          recognizer.close();
          recognizer = undefined;
        });
  }

  const load = (fileName, rate) => {
    let seq = 0;
    setInterval(() => {
      const mySeq = seq++;
      const start = Date.now();
      try {
        const audioStream = fs.createReadStream(fileName).pipe(new Throttle(32000), { end: false });
        const pushStream = sdk.AudioInputStream.createPushStream();
        const handleData = (buf) => pushStream.write(buf.slice().buffer);

        audioStream
          .on('data', handleData)
          .once('close', () => {
            pushStream.close();
            stream.removeListener('data', handleData);
          });

        const audioConfig = sdk.AudioConfig.fromStreamInput(pushStream);
        const reco = new sdk.SpeechRecognizer(speechConfig, audioConfig);
        const onEnd = (reco) => {
          reco.close();
          console.log(`${mySeq}: done [${Date.now() - start}]`)
        };
        startReco(reco);
        setTimeout(() => {
          onEnd(reco);
        }, 5000);
      } catch (err) {
        console.error(`${mySeq}: ${err}`);
      }
    }, 1000 / rate);
  };

  load(filename, 7);
```

**Comment by bivas6** [comment]
Hi @glharper , thanks. it is better now, but CPU is still high.

compare the above code with 20 requests per second to this code:
```
// pull in the required packages.
const speechService = require('ac-ms-bing-speech-service');
var fs = require("fs");
var Throttle = require("throttle");
const { default: getToken } = require('./getToken');
const stream = require("stream");

var filename = "<<filename>>.wav"; // 16000 Hz, Mono

function stop(reco) {
  reco.stop();
  delete reco;
}

function startReco(recognizer) {
  return new Promise((res, rej) =>
    recognizer.start().then(() => {
      recognizer.on('speech.phrase', (obj) => {
        switch (obj.RecognitionStatus) {
          case 'Success': {
            const [mainResult] = obj.NBest;
            if (mainResult.Confidence > 0) {
              console.log('recognized')
              break;
            }
          }
          case 'InitialSilenceTimeout':
            break;
          case 'EndOfDictation':
            break;
          default:
            console.log(`STT speech.phrase: RecognitionStatus=${obj.RecognitionStatus}`);
        }
      }); recognizer.on('speech.hypothesis', (obj) => {
        console.log('recognizing')
      });
      recognizer.on('turn.end', (err) => {
        if (err && err.Error)
          console.log(`turn.end: ${err.Error}`);
      });
      recognizer.once('close', stop.bind(recognizer));

      res();
    }
    ).catch((e) => { console.log(JSON.stringify(e)); rej(e) }))
}

const load = (fileName, rate) => {
  let seq = 0;
  setInterval(async () => {
    const mySeq = seq++;
    const start = Date.now();
    try {
      const request = {
        language: 'en-US',
        serviceUrl: 'wss://<<REGION>>.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?format=detailed&language=en-US',
        accessToken: await getToken() // returns valid access token
      }
      console.log(JSON.stringify(request));
      const recognizer = new speechService(request);
      await startReco(recognizer);
      const audioStream = fs.createReadStream(fileName).pipe(new Throttle(32000));
      const passThrough = new stream.PassThrough();
      audioStream.pipe(passThrough);
      recognizer.sendStream(passThrough)
        .catch((err) => console.log('terminated', err.toString()));
    } catch (err) {
      console.error(`${mySeq}: error ${err.message}`);
    }
  }, 1000 / rate);
};

load(filename, 20);
```

**Comment by glharper** [comment]
@bivas6 After profiling, it appears the performance issues are with the Stream library you're using. I'm attaching the profiler log I got using Stream, and recommending you use the code below, and not the Stream library, if possible. (To profile in node, see [https://nodejs.org/en/docs/guides/simple-profiling/](https://nodejs.org/en/docs/guides/simple-profiling/).
[processed.txt](https://github.com/microsoft/cognitive-services-speech-sdk-js/files/5234131/processed.txt)

Code for better performance without Stream:

```
  var sdk = require("microsoft-cognitiveservices-speech-sdk");
  var fs = require("fs");
  
  var subscriptionKey = "<<KEY>>";
  var serviceRegion = "<<REGION>>"; // e.g., "westus"
  var filename = "<<FILE>>.wav"; // 16000 Hz, Mono
  
  var speechConfig = sdk.SpeechConfig.fromSubscription(subscriptionKey, serviceRegion);
  speechConfig.speechRecognitionLanguage = "en-US";
  
  async function startReco(recognizer) {
    recognizer.recognizing = (_s, event) => {
      console.log('recognizing');
    };

    recognizer.recognized = (_s, event) => {
      console.log('recognized');
    };

    recognizer.canceled = (_s, event) => {
      console.log('canceled');
    };

    // Signals the end of a session with the speech service.
    recognizer.sessionStopped = (_s, event) => {
      console.log('sessionStopped');
      recognizer.close();
      recognizer = undefined;
    }
    recognizer.startContinuousRecognitionAsync(
        undefined,
        (err) => {
          console.error('err - ' + err);
          recognizer.close();
          recognizer = undefined;
        });
  }

  const load = (fileName, rate) => {
    let seq = 0;
    setInterval(() => {
      const mySeq = seq++;
      const start = Date.now();
      try {
    
        // create the push stream we need for the speech sdk.
        const pushStream = sdk.AudioInputStream.createPushStream();
        
        // open the file and push it to the push stream.
        fs.createReadStream(filename).on('data', function(arrayBuffer) {
          pushStream.write(arrayBuffer.slice());
        }).on('end', function() {
          pushStream.close();
        });
        const audioConfig = sdk.AudioConfig.fromStreamInput(pushStream);
        const reco = new sdk.SpeechRecognizer(speechConfig, audioConfig);
        const onEnd = (reco) => {
          reco.close();
          console.log(`${mySeq}: done [${Date.now() - start}]`)
        };
        startReco(reco);
        setTimeout(() => {
          onEnd(reco);
        }, 5000);
      } catch (err) {
        console.error(`${mySeq}: ${err}`);
      }
    }, 1000 / rate);
  };

  load(filename, 20);
```

Thanks,
Glenn

**Comment by orgads** [comment]
@glharper Thanks for your response.

The last example @bivas6 posted demonstrates the package that we currently use, and it has good performance (~30% for 20 sessions per second). The high CPU we observe is with the official cognitive services package, which is demonstrated on [this comment](https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/242#issuecomment-691635169), and it doesn't use the stream package, only Throttle. Actually, the coffee looks very similar to yours, except that the stream handling is wrapped in a function.

**Comment by glharper** [comment]
@orgads The code you link to forces a big memory leak by not disposing of the recognizer object properly. If there's any way your team could follow the steps in [https://nodejs.org/en/docs/guides/simple-profiling/](https://nodejs.org/en/docs/guides/simple-profiling/) and send me a processed.txt file for code that allows the recognizer to close on timeout, and doesn't use the Stream library, I'll have a very good idea of which part of our sdk needs to be addressed.

Thanks,
Glenn

**Comment by bivas6** [comment]
Hi @glharper,
All of the stream functions is on the built in node js readable strean objects, the import is just for typescript notation.

Attaced 2 profile file. [processed-azure-ms.txt](https://github.com/microsoft/cognitive-services-speech-sdk-js/files/5298844/processed-azure-ms.txt) is profile using cognitive-services-speech-sdk, and [processed-azure.txt](https://github.com/microsoft/cognitive-services-speech-sdk-js/files/5298848/processed-azure.txt)
 is the same tests using [this package](https://github.com/orgads/ms-bing-speech-service#readme)

**Comment by glharper** [comment]
@bivas6 Thank you for writing code samples and sending the performance analysis for this. The next release should have a couple of mitigations for this issue, with the switch to native promises, and the performance fix in the pull request above. 

One issue I'm still seeing is that this code:
```
        const audioStream = fs.createReadStream(fileName).pipe(new Throttle(32000), { end: false });
        const pushStream = sdk.AudioInputStream.createPushStream();
        const handleData = (buf) => pushStream.write(buf.slice().buffer);

        audioStream
          .on('data', handleData)
          .once('close', () => {
            pushStream.close();
            stream.removeListener('data', handleData);
          })
```
is spiking calls to the windows dll. Using the code below instead seems to half cpu usage in my profiling:

```
  // create the push stream we need for the speech sdk.
  var pushStream = sdk.AudioInputStream.createPushStream();
  
  // open the file and push it to the push stream.
  fs.createReadStream(filename).on('data', function(arrayBuffer) {
    pushStream.write(arrayBuffer.slice());
  }).on('end', function() {
    pushStream.close();
  });
```

Thanks,
Glenn

**Comment by orgads** [comment]
Thank you very much.

The only difference I see between your code and ours is that you don't use Throttle. Can you check our code without Throttle?

**Comment by glharper** [comment]
@orgads Removing Throttle does seem to deliver a similar performance improvement.
```
        const audioStream = fs.createReadStream(fileName);
        const pushStream = sdk.AudioInputStream.createPushStream();
        const handleData = (buf) => pushStream.write(buf.slice().buffer);

        audioStream
          .on('data', handleData)
          .once('close', () => {
            pushStream.close();
          });
```

**Comment by bivas6** [comment]
Hi, we tried the last version, with @orgads change that disables perMessageDeflate, but CPU is still high.
[processed_no_deflate.txt](https://github.com/microsoft/cognitive-services-speech-sdk-js/files/5372172/processed_no_deflate.txt)

**Comment by glharper** [comment]
@bivas6 The latest version is out now, care to share your thoughts on performance now?

**Comment by bivas6** [comment]
Hi,
We didn't see much improvement. CPU is still very high.
[processed.txt](https://github.com/microsoft/cognitive-services-speech-sdk-js/files/5516288/processed.txt)

**Comment by glharper** [comment]
@bivas6 Are you seeing anything in the profile that stands out? It appears the SDK code accounts for 20% of the processor time. One possible path is switching from the ws node library to websocket, which is what the ms bing speech service package appears to use. What are your thoughts on this approach, or would you suggest something else to look at?

One additional question: May I ask why you're using JavaScript for a task that would appear to benefit greatly from a much more parallelizable stack?

**Comment by orgads** [comment]
One thing that still stands out is message compression which I suggested to remove on https://github.com/microsoft/cognitive-services-speech-sdk-js/pull/258, but it was suspended.

Is it easy to switch from ws to websocket? Can you provide me with a patch?

Node handles media streaming very well, and we didn't notice performance issues so far, except this one. We run 300 concurrent sessions on a single core and it works fine.

**Comment by bivas6** [comment]
Hi @glharper,
We switched ws to websocket, by this:
```
const globalAny: any = global;
globalAny.WebSocket = require('websocket');
```
And CPU seems to be much lower. I'll update once we done our tests.

**Comment by orgads** [comment]
Hi @glharper.

We compared now between `ws` *with perMessageDeflate false* and `websocket`, and `websocket` looks much better.

For 50 requests per sec `websocket` was around 50% CPU, while `ws` was around 80%. We didn't investigate further to explain the difference.

Since we have a workaround, we can proceed with the package. But for the general case, will you consider replacing the default websocket used?

**Comment by glharper** [comment]
Hi @orgads 
I've been looking at the node websocket library as well, and I cannot find a way to easily set perMessageDeflate there. Looking at [https://github.com/websockets/ws/blob/master/lib/permessage-deflate.js](https://github.com/websockets/ws/blob/master/lib/permessage-deflate.js) certainly explains some the performance issues when perMessageDeflate is enabled for ws, but I will engage Ryan Hurey today to understand the reasoning behind websocket message compression.

**Comment by orgads** [comment]
@glharper: I doubt that enabling perMessageDeflate was intentional. It just happened to be the default on `ws`, and it looks like this detail was unnoticed.

Quoting from ws README:

> The extension is disabled by default on the server and enabled by default on the client. It adds a significant overhead in terms of performance and memory consumption so we suggest to enable it only if it is really needed.
> 
> Note that Node.js has a variety of issues with high-performance compression, where increased concurrency, especially on Linux, can lead to catastrophic memory fragmentation and slow performance. If you intend to use permessage-deflate in production, it is worthwhile to set up a test representative of your workload and ensure Node.js/zlib will handle it with acceptable performance and memory usage.
> 

I think it should be safe to just disable it unconditionally, and if anyone complains - add a flag for enabling it. If you do want a flag, at least set the default to false.

**Comment by bivas6** [comment]
Hi @glharper,
We tried again your package with the `ws` package, and with `perMessageDeflate: false`, and it seems to solve the CPU issue.
Probably we didn't disable `perMessageDeflate` properly in our previous tests.  

Thanks

**Comment by glharper** [comment]
@bivas6, @orgads, I've merged code into master that sets perMessageDeflate to false by default. Can you check and make sure current master fixes the CPU load issue?

Thanks,
Glenn

**Comment by orgads** [comment]
@glharper: Looks like it is solved. Thank you very much! When do you plan to release?

**Comment by glharper** [comment]
@orgads This is planned to be part of 1.15, releasing in early January.
