### ISSUE TITLE
How i get higher sampling rate recording from SDK

### ISSUE THREAD

**Issue by xym4869** [microsoft/cognitive-services-speech-sdk-js#245]
Hi,
I'm Yimin from TextToSpeech team, and we are working on build high fidelity TTS. We need sampling rate higher than 24kHz recording from connection message of SDK recorgnizer to build TTS model, but I find current output audio is 16kHz, do you know how to get higher sampling rate recording from SDK?

**Comment by xym4869** [comment]
Let me explain a bit. I use SDK to record the users’ voice and send to service for recognition/pronunciation evaluation, meanwhile, I save the audio sent out, then use the saved audio for custom voice training.
Now i bind the connection.messageSent method to get the audio sent out, which is 16kHz. AFAIK, the SDK was updated to use browser’s default sample rate for recording (usually > 16k). Is there anyway to get the audio before downsampling?

**Comment by glharper** [comment]
@xym4869 The highest rate input stream the SDK can expose before sending on to the endpoint is 16kHz. In order to implement this request, you will have to first capture and process the input stream using another JS library, then pass it on to the SDK.

**Comment by glharper** [comment]
@xym4869 Are you still blocking on this issue, or have you found a different path to get higher sampled audio?

**Comment by xym4869** [comment]
I made the recording by myself, get higher sampled audio from that recorder and put low sampled audio streams into sdk.


| |
肖逸敏
|
|
xym4869@yeah.net
|
签名由网易邮箱大师定制
On 12/10/2020 03:48，Glenn Harper<notifications@github.com> wrote：

@xym4869 Are you still blocking on this issue, or have you found a different path to get higher sampled audio?
