### ISSUE TITLE
fromWavFileInput doesn't work in node.js

### ISSUE THREAD

**Issue by brapifra** [microsoft/cognitive-services-speech-sdk-js#252]
## Steps to reproduce
```javascript
const sdk = require('microsoft-cognitiveservices-speech-sdk');

const speechConfig = sdk.SpeechConfig.fromSubscription(
  'SUBSCRIPTION_KEY',
  'REGION'
);

const audioConfig = sdk.AudioConfig.fromWavFileInput(
  'PATH_TO_WAV'
);

const recognizer = new sdk.SpeechRecognizer(speechConfig, audioConfig);

recognizer.recognizeOnceAsync((result) => {
  switch (result.reason) {
    case ResultReason.RecognizedSpeech:
      console.log(`RECOGNIZED: Text=${result.text}`);
      break;
  }
});
```

## Expected behaviour
It prints the audio transcription

## Current behaviour
It errors with: `ReferenceError: FileReader is not defined`
This is due to the fact that `FileAudioSource` tried to use the browser-only `FileReader` class: https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/common.browser/FileAudioSource.ts#L149

**Comment by glharper** [comment]
@brapifra Please my response and workaround code [https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/813](here)

**Comment by glharper** [comment]
@brapifra JS SDK v1.16 has just been released, and Node support for AudioConfig.fromWavFileInput has been added. Thanks for filing this issue last fall!
