### ISSUE TITLE
Speech is never recognized from PushStream

### ISSUE THREAD

**Issue by nikvitaldusharov** [microsoft/cognitive-services-speech-sdk-js#262]
Hello, 
I am trying to recognize speech from the PushStream, which I populate with the data from the remote stream. 
The problem is - my speech has been never recognized. I always end up with the empty text in a result parameter of the recognized event handler (after some time). I didn't find any example in the docs, so I ask to forgive me if I do something wrong. 
Hope I do something wrong and this is not an issue =). My code is below: 
```
        const mediaStream = audio.captureStream(); //capture remote stream from audiotag
        const pushStream: PushAudioInputStream = PushAudioInputStream.create();
        const waveStreamEncoder = new RiffPcmEncoder(16000, 16000); //I put different values, looks like it doesn't work either
        this.mediaRecorder = new MediaRecorder(mediaStream);
        let extraBytesNumber: number;
        let extraBytes: ArrayBuffer;
        const audioConfig = AudioConfig.fromStreamInput(pushStream);
        const speechConfig = SpeechTranslationConfig.fromSubscription('some-key', 'eastus');
        this.mediaRecorder.ondataavailable = (event) => { // MediaRecorder
            if (event.data.size > 0) {
                event.data.arrayBuffer().then((buffer => {
                    console.log(`byteLength: ${buffer.byteLength}`);
                    let bufferToPush: ArrayBuffer;
                    if (extraBytes && extraBytes.byteLength) {
                        bufferToPush = concatArrayBuffers(extraBytes, buffer);
                    } else {
                        bufferToPush = buffer;
                    }
                    extraBytesNumber = bufferToPush.byteLength % Float32Array.BYTES_PER_ELEMENT;
                    extraBytes = bufferToPush.slice(bufferToPush.byteLength - extraBytesNumber, bufferToPush.byteLength);
                    let floatArray: Float32Array;
                    try {
                        floatArray = new Float32Array(bufferToPush.slice(0, bufferToPush.byteLength - extraBytesNumber));
                    } catch (e) {
                        floatArray = new Float32Array(bufferToPush, 0, bufferToPush.byteLength - extraBytesNumber);
                    }
                    const waveFrame = waveStreamEncoder.encode(floatArray); //RiffPcmEncoder
                    pushStream.write(waveFrame);
                }));
            }
        };
        this.mediaRecorder.start(3000); //force to request data every 3000 millisecs.
        speechConfig.speechRecognitionLanguage = 'en-US';
        this._recognizer = new TranslationRecognizer(speechConfig, audioConfig);

        this._recognizer.recognizing = (s, e) => {
            console.log(`RECOGNIZING: Text=${e.result.text}`); // never here
        };
        this._recognizer.recognized = (s, e) => {
            if (e.result.reason == ResultReason.RecognizedSpeech) { // speech never recognized
                console.log(`RECOGNIZED: Text=${e.result.text}`);
            }
            else if (e.result.reason == ResultReason.NoMatch) { 
                console.log("NOMATCH: Speech could not be recognized.");
            } else {
                console.log("somthinig" + e.result.reason); 
            }
        };

        // start the recognizer
        this._recognizer.startContinuousRecognitionAsync();
```

**Comment by glharper** [comment]
@nikvitaldusharov What is kind of audio is being captured with that first line, audio.captureStream()? Are you redirecting an existing MediaStream from microphone input?

**Comment by nikvitaldusharov** [comment]
@glharper  The audio is from an audio tag, which, in turn, contains an audio stream from a remote source (it is a tag from cisco webex plugin).Just FYI - I've checked that data is valid by playing it back (copy to another audio tag with controls):
    `let chunks = [];
        this.mediaRecorder.ondataavailable = (event) => {
        ... 
        chunks.push(even.data);
    }
     setTimeout(() => {
            const blob = new Blob(chunks, { 'type' : 'audio/ogg; codecs=opus' });
            const audioURL = window.URL.createObjectURL(blob);
            audioTest.src = audioURL;
    }, 35000);`
audioTest is reference to another audio tag

**Comment by glharper** [comment]
@nikvitaldusharov Thanks for your response. This appears to be an issue of creating a wav stream from an ogg stream, correct? Speech SDK can't handle ogg streams, and it doesn't have any functionality for converting them to wav. I'm having trouble finding anything Speech SDK-related that I can help you with here.

**Comment by nikvitaldusharov** [comment]
@glharper, yeah. thank you. As far as I understand I can try to use speech recognition API to work with ogg stream?

**Comment by glharper** [comment]
@nikvitaldusharov Ogg is not supported with the JavaScript Speech SDK. For other languages, however, you can use ogg files. See [this Azure docs page](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-codec-compressed-audio-input-streams) for more details.

**Comment by nikvitaldusharov** [comment]
@glharper I've converted to this format - audio/wav;codecs=MS_PCM, However, it did not help. Not sure if it is not working only because of the format

**Comment by glharper** [comment]
@nikvitaldusharov Can you attach an example file to be recognized using this wav format and MS_PCM codec?

**Comment by nikvitaldusharov** [comment]
@glharper Of course
[test_sample.zip](https://github.com/microsoft/cognitive-services-speech-sdk-js/files/5448746/test_sample.zip)

**Comment by glharper** [comment]
@nikvitaldusharov Yeah, my hex viewer is telling me that file you sent has ogg headers.
