### ISSUE TITLE
Connection class broken in 1.14.0

### ISSUE THREAD

**Issue by alopix** [microsoft/cognitive-services-speech-sdk-js#266]
`src/sdk/Connection.ts` is broken.

The function `setupEvents` does not work anymore, as `connectionEvent.name` will always be undefined. There seems to be an internal change to the events, which now sends out `CustomEvent` classes.
The event's properties are in `connectionEvent.detail.detail.name` now (see screenshot logging the incoming events in `Connection`'s event handler).

![image](https://user-images.githubusercontent.com/124467/97965727-b9970b00-1db2-11eb-8c51-151d473c5fda.png)

This makes it impossible to listen to connections being established or closed again.

That's running in the browser (Edge).

**Comment by glharper** [comment]
@alopix 1.14.1 was released with a fix for this issue. Please update when you can and provide feedback.

Thanks,
Glenn

**Comment by madeInLagny** [comment]
Working on Chrome 86.0.4240.198 on Windows 10.

Le lun. 16 nov. 2020 à 19:29, Glenn Harper <notifications@github.com> a
écrit :
