### ISSUE TITLE
AudioInputStream Error: "ReferenceError: Blob is not defined"

### ISSUE THREAD

**Issue by yoshigev** [microsoft/cognitive-services-speech-sdk-js#268]
Hi,

We are using SDK version 1.14.0.

We are using AudioInputStream for passing audio to Speaker Verification, but I suspect that the issue is relevant also for other usages.

Whenever we call `pushStream.close()`, we face the following error:
```
ReferenceError: Blob is not defined
```

I suspect that the following lines of code in `AudioInputStream.js`:
```js
                            if (typeof (XMLHttpRequest) !== "undefined") {
                                return Promise.resolve(new Blob(data));
                            }
```
Should actually be:
```js
                            if (typeof (Blob) !== "undefined") {
                                return Promise.resolve(new Blob(data));
                            }
```

Note that this problem probably occurs because somewhere else in our code there is the following line (which we need for other purposes):
```ts
globalAny.XMLHttpRequest = require('xhr2');
```

cc: @orgads,@bivas6

Thanks.

**Comment by amitkumarshukla** [comment]
@glharper Could you please take a look at this one.

**Comment by glharper** [comment]
@yoshigev 1.14.1 has been released with a fix for this issue. Please update and provide feedback if you're so inclined. 

Glenn

**Comment by yoshigev** [comment]
The problem is fixed with the new version. Thank you very much.
