### ISSUE TITLE
Connection Class broken on version 1.14.1

### ISSUE THREAD

**Issue by madeInLagny** [microsoft/cognitive-services-speech-sdk-js#274]
Issue still occuring as described in [#266](https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/266)

**Comment by glharper** [comment]
@madeInLagny I would like more information on this. Specifically, are the event callbacks in Connection still not returning correctly for you? I have a test page up with the 1.14.1 lib files that I can share, and I'm seeing the Connection.connected callback. I'm glharper on Teams, could you ping me and walk me through what you're seeing?

**Comment by madeInLagny** [comment]
Sure.
I have implemented the code suggested [here](https://stackoverflow.com/questions/64294986/azure-speech-sdk-createpushstream-from-getusermedia-in-javascript)

`import "../../microsoft.cognitiveservices.speech.sdk.bundle-min.js";`

```
const con = SpeechSDK.Connection.fromRecognizer(this.recognizer);
      con.messageSent = args => {
        // Only record outbound audio mesages that have data in them.
        console.log("args.message.path:",args.message.path)
        if (
          args.message.path === "audio" &&
          args.message.isBinaryMessage &&
          args.message.binaryMessage !== null
        ) {
![Console log 1_11](https://user-images.githubusercontent.com/54598963/99490066-5f2cab80-2969-11eb-89e9-efc1e46f3fae.JPG)

          // this.wavFragments[this.wavFragmentCount++] =args.message.binaryMessage;
          this.wavFragments[this.wavFragmentCount] = args.message.binaryMessage;

          this.wavFragmentCount += 1;
        }
      };
```

When I run this code importing sdk 1.11, I get this in the console:

![image](https://user-images.githubusercontent.com/54598963/99490234-bd598e80-2969-11eb-9146-e68ae2420f9f.png)

When I run the same code importing sdk 1.14.1 (from this [repo](https://aka.ms/csspeech/jsbrowserpackage))

I only see the session start event. No audio entry
![image](https://user-images.githubusercontent.com/54598963/99490480-39ec6d00-296a-11eb-955c-3181a12eec39.png)

Note that in both cases, text is recognized and transcripted correctly.

**Comment by glharper** [comment]
@madeInLagny that zip package link still points to 1.14.0. Please use this [link](https://csspeechstorage.blob.core.windows.net/drop/1.14.1/SpeechSDK-JavaScript-1.14.1.zip)

**Comment by madeInLagny** [comment]
Hi @glharper 
Good catch. 1.14.1 is working for me in both transcript and audio. Thanks
