### ISSUE TITLE
Does not recognize speech from Screen Capture API

### ISSUE THREAD

**Issue by madeInLagny** [microsoft/cognitive-services-speech-sdk-js#279]
This is not strictly a bug but rather a feature missing in the sdk docs.

I want to transcript speech captured from the browser, not the microphone. I tried using getDisplayMedia from the Screen Capture API.

```
mediaStream = await navigator.mediaDevices.getDisplayMedia({
            video: true,
            audio: true
          });
    const audioStreams = mediaStream.getAudioTracks();
    const speechStream = audioStreams[0];

var pushStream = sdk.AudioInputStream.createPushStream();

```
How can I use the pushStream.write() method from there ?

**Comment by glharper** [comment]
@madeInLagny As of 1.14.0, the AudioConfig.fromStreamInput() method now accepts a MediaStream in its constructor
`
  var audioConfig = sdk.AudioConfig.fromStreamInput(mediaStream);
`

This is intended for redirected browser audio, originally from a microphone, but it may work for you as well. Please let us know either way.

**Comment by madeInLagny** [comment]
Tested and working ! Good stuff. Thanks
