### ISSUE TITLE
The result is completely different.

### ISSUE THREAD

**Issue by josephhsieh** [microsoft/cognitive-services-speech-sdk-js#280]
I try the demo on this page
[Speech to Text | Microsoft Azure](https://azure.microsoft.com/en-ca/services/cognitive-services/speech-to-text/#features)

with language Chinese (Taiwanese Mandarin), and the result is great.

But then I signup account, and run the nodeJs sample code with same WAV file, the result turns out completely different.

**Comment by glharper** [comment]
@josephhsieh Thank you for sharing this issue. Would you mind sharing the WAV file you're using to reproduce this?

**Comment by BrianMouncer** [comment]
@josephhsieh can you provide an example audio file?

Thanks,
