### ISSUE TITLE
Can't get the Confidence score of transcription results

### ISSUE THREAD

**Issue by jadch** [Microsoft/cognitive-services-speech-sdk-js#29]
Hello, first of all it's great to see that there's now a Speech Services SDK for node. Thank you!

I'm having trouble getting the confidence score along with the transcription results.

I've tried setting outputFormat in the hopes of getting more detailed output
```
...
const audioConfig = sdk.AudioConfig.fromStreamInput(pushStream);
const speechConfig = sdk.SpeechConfig.fromSubscription(SUBSCRIPTION_KEY, SERVICE_REGION);

speechConfig.speechRecognitionLanguage = language;
speechConfig.outputFormat = 1; 

recognizer = new sdk.SpeechRecognizer(speechConfig, audioConfig);
...
```
but the transcription results still look like this:
```
SpeechRecognitionResult {
    privResultId: 'XXXXXXXXX',
    privReason: 2,
    privText: 'oui',
    privDuration: 1800000,
    privOffset: 100000,
    privErrorDetails: undefined,
    privJson: '{"Text":"oui","Offset":100000,"Duration":1800000}',
    privProperties: undefined },
```

Am I missing anything ?

PS: I tried setting the outputFormat to 1 because I saw it applied in the C++ SDK (https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/12) and because the Node SDK's `SpeechConfig` does have an `OutputFormat` property too.

**Comment by jadch** [comment]
It looks like we're getting the detailed transcription results now, including the confidence. I literally didn't change a thing in my code though (?), but I'll close the request...

**Comment by soumyadipchatterjee** [comment]
I am not getting the confidence score. What is wrong with my code? 

startRecognizeOnceAsyncButton.addEventListener("click", function () {
      startRecognizeOnceAsyncButton.disabled = true;
      phraseDiv.innerHTML = "";

      // if we got an authorization token, use the token. Otherwise use the provided subscription key
      var speechConfig;
      if (authorizationToken) {
        speechConfig = SpeechSDK.SpeechConfig.fromAuthorizationToken(authorizationToken, serviceRegion.value);
      } else {
        if (subscriptionKey.value === "" || subscriptionKey.value === "subscription") {
          alert("Please enter your Microsoft Cognitive Services Speech subscription key!");
          return;
        }
        speechConfig = SpeechSDK.SpeechConfig.fromSubscription(subscriptionKey.value, serviceRegion.value);
       

      }
      speechConfig.OutputFormat = 1;
      speechConfig.speechRecognitionLanguage = "en-US";
      var audioConfig  = SpeechSDK.AudioConfig.fromDefaultMicrophoneInput();
      recognizer = new SpeechSDK.SpeechRecognizer(speechConfig, audioConfig);

      recognizer.recognizeOnceAsync(
        function (result) {
          console.log(result)
          // if (result.Reason == ResultReason.RecognizedSpeech){
            var detailedResults = result.Best();
          // }

          console.log(detailedResults);
          startRecognizeOnceAsyncButton.disabled = false;
          phraseDiv.innerHTML += result.text;
          // window.console.log(result);

          recognizer.close();
          recognizer = undefined;
        },
        function (err) {
          startRecognizeOnceAsyncButton.disabled = false;
          phraseDiv.innerHTML += err;
          window.console.log(err);

          recognizer.close();
          recognizer = undefined;
        });
    });
It would be great if you can resolve this?
