### ISSUE TITLE
ConnectionFailure with Speech Synthesis

### ISSUE THREAD

**Issue by brandom-msft** [microsoft/cognitive-services-speech-sdk-js#291]
hi,
my Speech SDK version  is  1.13.1
I get this error:
SpeechSynthesisResult {
  privResultId: '13F4195BBBC34EB0A4A73670E2F41EAA',
  privReason: 1,
  privAudioData: undefined,
  privErrorDetails: 'Unable to contact server. StatusCode: 1006, undefined Reason:  Failed to obtain OCSP response: 504',
  privProperties: PropertyCollection {
    privKeys: [ 'CancellationErrorCode' ],
    privValues: [ 'ConnectionFailure' ]
  }
}

_Originally posted by @Cincan in https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/157#issuecomment-736201666_

**Comment by brandom-msft** [comment]
@Cincan can you provide more information about your setup/environment?

Is this issue intermittent or does it fail 100%?

**Comment by Cincan** [comment]
many time it works well, and this issue  is  intermittent happens.

**Comment by AdamGustavsson** [comment]
This issue occured for me on the 27 Feb 2021 at 23.00 CET. I used the westeurope region. the issue was present for 5-10 minutes

**Comment by AdamGustavsson** [comment]
The caching of the OCSP response does not work in a serverless context as neither the in memory cache nor the disk cache will share any cached items between calls.  At least not with a cold start.
A feature request would be let the developer provide a cache function to be used.  For AWS Lambda Elasticache, S3 or DynamoDb could be used instead.

**Comment by lowki** [comment]
Hello there.
I've just bumped into the exact same error in a similar context (Lambda in a node 12 runtime)
Our service was running flawlessly for several months now.

**Comment by chschrae** [comment]
Thanks for your continued input!

We have added some connection retry logic to make the connections more robust and mitigate this issue. The changes will be released in 1.17

**Comment by Fradulentus** [comment]
Квинси Кауит, Корпорация Майкрософт

**Comment by Fradulentus** [comment]
> привет,
> моя версия речи SDK является 1.13.1
> Я получаю эту ошибку:
> SpeechSynthesisResult -
> privResultId: '13F4195BBBC34EB0A4A73670E2F41EAA',
> privReason: 1,
> privAudioData: неопределенный,
> privErrorDetails: 'Не удается связаться с сервером. StatusCode: 1006, неопределённые Причины: Не удалось получить ответ
> OCSP: 504',
> privProperties: PropertyCollection -
> privKeys: "CancellationErrorCode", privValues: "ConnectionFailure"
> }
> }
> 
> _Первоначально опубликовано @Cincan в #157 [(комментарий)](https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/157#issuecomment-736201666)_

**Comment by Fradulentus** [comment]
С чего начнем?

**Comment by glharper** [comment]
Closing this as the reconnection logic has been added.
