### ISSUE TITLE
startContinuousRecognitionAsync stopping halfway through the file

### ISSUE THREAD

**Issue by owenallenaz** [microsoft/cognitive-services-speech-sdk-js#292]
I'm using the `startContinuousRecognitionAsync` with a `pushStream` on SDK version `1.14.0`. I have a file which has two sections of speech separated by some garbled radio data. The speech recongition system stops entirely after the first section is processed and never reaches the second.

The file I'm attempting to process is https://storage.googleapis.com/fire-brothers-public/1607963107644-1.wav .

I'm distilled down the code I'm using to the following sample. Using this I get the sole text, "i'm going 271. show person 920. fifty concordia drive engine 271 made at 7." We'll set aside that the recognition is pretty poor, the core problem is that it's missing the entire second half of the file. From the docs my understanding was that `startContinuousRecognitionAsync` should find the whole file. Interestingly, if I use public demo at https://azure.microsoft.com/en-us/services/cognitive-services/speech-to-text/ I get pretty much the same result. Any ideas?

```js
//@ts-check
const sdk = require("microsoft-cognitiveservices-speech-sdk");
const fs = require("fs");
const util = require("util");

const setTimeoutP = util.promisify(setTimeout);

const subscriptionKey = KEY;
const subscriptionRegion = "eastus";
const endpointId = ENDPOINT;

async function run() {
	const fullPath = `/app/data/phoenix/processed/1607963107644-1.wav`;

	const format = sdk.AudioStreamFormat.getWaveFormatPCM(44100, 16, 1);

	// create the push stream we need for the speech sdk.
	var pushStream = sdk.AudioInputStream.createPushStream(format);

	// open the file and push it to the push stream.
	fs.createReadStream(fullPath).on('data', function(arrayBuffer) {
		pushStream.write(arrayBuffer.slice());
	}).on('end', function() {
		pushStream.close();
	});

	// we are done with the setup
	console.log("Now recognizing from: " + fullPath);

	// now create the audio-config pointing to our stream and
	// the speech config specifying the language.
	var audioConfig = sdk.AudioConfig.fromStreamInput(pushStream);
	const speechConfig = sdk.SpeechConfig.fromSubscription(subscriptionKey, subscriptionRegion);
	speechConfig.endpointId = endpointId;

	// setting the recognition language to English.
	speechConfig.speechRecognitionLanguage = "en-US";

	// create the speech recognizer.
	var recognizer = new sdk.SpeechRecognizer(speechConfig, audioConfig);

	const textArr = [];

	await new Promise(function(resolve, reject) {
		recognizer.recognized = function(session, event) {
			console.log("GOT TEXT", event.result.text);
			textArr.push(event.result.text);
		}
	
		recognizer.sessionStopped = function(session, event) {
			console.log("DONE!");
			return resolve();
		}

		recognizer.speechEndDetected = function() {
			console.log("SPEECH END!");
		}

		recognizer.canceled = function() {
			console.log("CANCELLED!");
		}
	
		recognizer.startContinuousRecognitionAsync();
	});

	const allText = textArr.join(" ").toLowerCase();

	console.log("allText", allText);
}

run();
```

**Comment by glharper** [comment]
@owenallenaz Testing this file, I'm finding that recognition does not stop for the second half of the file, but the words get fainter with more noise, and it appears the backend service does not recognize anything in the second half for that reason. To confirm this, change the speechEndDetected callback:
```
		recognizer.speechEndDetected = function(s, event) {
                        console.log(`offset: ${event.offset}`);
			console.log("SPEECH END!");
		}
```
You should get a value of 32.1 seconds, converted, the length of the file. Let me know what you find.

**Comment by trrwilson** [comment]
Thanks, @glharper -- yes, it looks like the low audio quality is just causing the speech-to-text algorithm to not reach a requisite confidence to emit a result. It does appear to be dutifully processing the audio for the full duration, and I see something very similar running a test app using the C# SDK:
```
[13:53.681] Starting...
[13:54.000] Session started: 13c2e938349d425e8c7a6713dc4019b6
[13:54.064] Waiting...
[13:56.632] Speech started: 3.67s
[13:57.849] Recognized (at 4.05s for 0.93s): 371
[14:01.005] Recognized (at 6.52s for 5.93s): 2% nine 2050 concluded drive engine through 71 seven.
[14:12.041] Recognized (at 13.86s for 18.24s): 
[14:12.088] Speech ended: 32.1s
[14:12.209] Canceled (EndOfStream): 
[14:12.255] Session stopped: 13c2e938349d425e8c7a6713dc4019b6
[14:14.114] Done
```
If I use the noise reduction effect built into Audacity (using various snippets of the background as the noise profile source), the postprocessed file will get various recognition results in that second half added in. Still low quality, but my human ability to recognize it is also pretty low quality!

@owenallenaz, this appears to be the expected and by-design behavior when the system just can't derive a meaningful result from the audio. The SpeechStartDetected/SpeechEndDetected events that @glharper mentioned are good ways to know that something is being attempted. Is this quality of audio typical of what you'll be processing? I suspect it's going to be *very* challenging to get good (or even mediocre!) results on input with such a low signal-to-noise ratio without some extensive and intelligent audio processing.

**Comment by owenallenaz** [comment]
@trrwilson and @glharper thanks for looking into it. Sadly this is the quality that some of our radio data comes in on. I have attempted to process so if it by running it through audacity noise reduction filters or amplification but it isn't helping much. Largely get the same result back out. If I noise reduce then it still doesn't catch much, if I amplify it basically just adds the noise right back.

From your comments, this seems like a garbage-in, garbage-out problem, any ideas on how I can pre-process this data to possibly have a better shot?

**Comment by glharper** [comment]
@owenallenaz There is a confidence value that you can retrieve from the result JSON on the recognized event. First you'd need to set the outputFormat of speechConfig to Detailed, like so:
```
speechConfig.outputFormat = SpeechSDK.OutputFormat.Detailed;
```

Below is the JSON I got from the SpeechRecognitionResult on the recognized event using the file you linked:
"{"Id":[...],
"RecognitionStatus":"Success",
"Offset":65200000,
"Duration":59300000,
"DisplayText":"2% Nine 2016 concluded drive thru 71 seven.",
"NBest":[
{"Confidence":0.755552,"Lexical":"two percent nine twenty sixteen concluded drive thru seventy one seven","ITN":"2% nine 2016 concluded drive thru 71 seven","MaskedITN":"2% nine 2016 concluded drive thru 71 seven","Display":"2% Nine 2016 concluded drive thru 71 seven."},
{"Confidence":0.7149952,"Lexical":"two percent nine twenty sixteen concluded drive engine three seventy one seven","ITN":"two percent nine twenty sixteen concluded drive engine three seventy one seven","MaskedITN":"two percent nine twenty sixteen concluded drive engine three seventy one seven","Display":"two percent nine twenty sixteen concluded drive engine three seventy one seven"},
[other ways of interpreting the audio]
]}"

It would appear interpretations below a certain threshold are not returned, however, and I don't know of a way to ask the backend models to lower that threshold, nor do I know if that would even help for this kind of garbled audio.
