### ISSUE TITLE
Error: azure speech recognition stream cancelled with error: 4 Unable to contact server. StatusCode: 1006, undefined Reason: Unexpected server response: 401

### ISSUE THREAD

**Issue by lingumi-remy** [microsoft/cognitive-services-speech-sdk-js#296]
When using the `SpeechRecognizer` in the SDK, occassionally I get the following error:

`Error: azure speech recognition stream cancelled with error: 4 Unable to contact server. StatusCode: 1006, undefined Reason: Unexpected server response: 401`

Can I enquire on what are the possible causes and how can I go about resolving this? Thank you

**Comment by glharper** [comment]
@lingumi-remy The previous fixes for similar issues required generating and using a new subscription key. Could you give that a shot and report back?

Thanks,
Glenn

**Comment by glharper** [comment]
@lingumi-remy, are you still seeing this with a new subscription key?

**Comment by aditya-protonn** [comment]
Facing same issue - SpeechRecognitionResult {
  privResultId: 'F0904DCC71F04A98A446B0F0B13693A9',
  privReason: 1,
  privText: undefined,
  privDuration: undefined,
  privOffset: undefined,
  privLanguage: undefined,
  privLanguageDetectionConfidence: undefined,
  privErrorDetails: 'Unable to contact server. StatusCode: 1006, undefined Reason:  Unexpected server response: 401',
  privJson: undefined,
  privProperties: PropertyCollection {
    privKeys: [ 'CancellationErrorCode' ],
    privValues: [ 'ConnectionFailure' ]
  },
  privSpeakerId: undefined
}
aditya@Adityas-MacBook-Pro video-quickstart-js % node protonn/src/speech.js
Now recognizing from: /Users/aditya/Downloads/RT576b6f341f57a58d5e753fbaa5f9ed01.mka
SpeechRecognitionResult {
  privResultId: '55566521AA274D6796A377D93A16495E',
  privReason: 1,
  privText: undefined,
  privDuration: undefined,
  privOffset: undefined,
  privLanguage: undefined,
  privLanguageDetectionConfidence: undefined,
  privErrorDetails: 'Unable to contact server. StatusCode: 1006, undefined Reason:  Unexpected server response: 401',
  privJson: undefined,
  privProperties: PropertyCollection {
    privKeys: [ 'CancellationErrorCode' ],
    privValues: [ 'ConnectionFailure' ]
  },
  privSpeakerId: undefined
}
aditya@Adityas-MacBook-Pro video-quickstart-js % node protonn/src/speech.js
Now recognizing from: /Users/aditya/Downloads/RT576b6f341f57a58d5e753fbaa5f9ed01.mka
SpeechRecognitionResult {
  privResultId: '5C9F619CF1824E9B8E435BF8664664A0',
  privReason: 1,
  privText: undefined,
  privDuration: undefined,
  privOffset: undefined,
  privLanguage: undefined,
  privLanguageDetectionConfidence: undefined,
  privErrorDetails: 'Unable to contact server. StatusCode: 1006, undefined Reason:  Unexpected server response: 401',
  privJson: undefined,
  privProperties: PropertyCollection {
    privKeys: [ 'CancellationErrorCode' ],
    privValues: [ 'ConnectionFailure' ]
  },
  privSpeakerId: undefined
}

**Comment by dargilco** [comment]
Linking to @aditya-protonn post on the Speech SDK repo:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/292#issuecomment-849409052

**Comment by dargilco** [comment]
@aditya-protonn can you create a new speech key at the same Azure region and let us know if you still get the error? What happens if you use a new key with a different Azure region?

**Comment by glharper** [comment]
@aditya-protonn Adding to the above, if you're not using the latest version, 1.17 (available for Node via npm install [here](https://www.npmjs.com/package/microsoft-cognitiveservices-speech-sdk) and browser via include (https://cdn.jsdelivr.net/npm/microsoft-cognitiveservices-speech-sdk@latest/distrib/browser/microsoft.cognitiveservices.speech.sdk.bundle-min.js)), it does have a reconnect fix that may mitigate this issue.

**Comment by rjstalb** [comment]
I'm experiencing similar (500 https not supported) using v1.19.0 (node v16.10.1)

**Comment by isabirahmed** [comment]
I'm facing the same issue, using v.1.19.0 not sure why does this happen.
The subscription key is fairly new created less than a month ago.

privErrorDetails: 'Unable to contact server. StatusCode: 1006, undefined Reason:  Unexpected server response: 401'

Is there any fix or workaround?

**Comment by gad2103** [comment]
i have a similar error, however it only seems to happen when i use an ssml payload that has the `mstts` schema and tags (i'm trying to get background music to work). 

when i send a payload without those tags everything works just fine. i know this is tts and not stt, but it seems related.
