### ISSUE TITLE
TTS Javascript + Safari iOS = "Format MP3 could not be played by MSE, streaming playback is not enabled"

### ISSUE THREAD

**Issue by leeroy79** [microsoft/cognitive-services-speech-sdk-js#297]
I've written an angular app that works OK on desktop, but when running in iOS Safari I'm seeing "Format MP3 could not be played by MSE, streaming playback is not enabled" and nothing is played. I'm diverting console.log to alert() to get that message.

I've tried all the different sound formats with the same result. I'm guessing it's more about the streaming audio than the format itself. I looked at the options when constructing audio config but I couldn't see a way to not steam. 

I have tried just using the SDK to generate an ArrayBuffer and using Howler.js to process that, but getting a different issue there, in that even without using the default speaker config (i.e. passing undefined as audio config), it's still speaking it out. I.e. the audio gets doubled up when howler then plays it. I'll log a separate issue for that one.

Is there any way to get the JS SDK working on iOS?

Thanks

Lee

`
this.speechConfig = SpeechConfig.fromSubscription(this.SUB_KEY, this.REGION);
this.speechConfig.speechSynthesisLanguage = "de-de";
this.speechConfig.speechSynthesisVoiceName = "de-DE-KatjaNeural";
this.audioConfig = AudioConfig.fromDefaultSpeakerOutput();
this.synthesizer = new SpeechSynthesizer(this.speechConfig, this.audioConfig);
 this.synthesizer.speakTextAsync(
                text,
                result => {
                    if (result) {
                        console.log("TTS OK : " + JSON.stringify(result));
                    }
                    else {
                        console.log("TTS no result");
                    }
                },
                error => {
                    console.log("TTS error : " + error);
                });
`

**Comment by yulin-li** [comment]
Hi @leeroy79, "Format MP3 could not be played by MSE, streaming playback is not enabled" is expected on iOS Safari, as media source extension (MSE) is not available. But the SDK should give this warning and then play the audio in non-steaming mode. What is the SDK version and iOS version you are using?

**Comment by leeroy79** [comment]
Hi @yulin-li, iOS version is 14.2, NPM version 1.14.1. This might point me in the right direction anyway. If the expectation is that it should be working I can focus on double checking the other moving parts to make sure nothing else is wrong.

**Comment by yulin-li** [comment]
Hi @leeroy79 , as a quick check, you can try if the playback in our [demo page](https://azure.microsoft.com/en-us/services/cognitive-services/text-to-speech/#features) could work on your test phone, which also uses this SDK.

![image](https://user-images.githubusercontent.com/12013783/103515859-72a8bd00-4eaa-11eb-88bd-db52548d020b.png)

**Comment by leeroy79** [comment]
@yulin-li hmm you're right, that worked! I guess I must have an issue somewhere else then. If that page is all the same code as this repo then I guess can close this off. Thanks!

**Comment by pompomon** [comment]
@leeroy79 , please did you find the solution?
I'm currently having the same issue with the code I've copied from the demo page shared by @yulin-li 
```html

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
    <title>Text to speech bug</title>
</head>

<body>
    <script
        src="https://azurecomcdn.azureedge.net/cvt-e3ed0d34307a7483a4023cd0e014a57d370e2566f456617b2504a5857f80fcad/scripts/Acom/Components/cognitiveServicesDemos/speechJsSdk/microsoft.cognitiveservices.speech.sdk.bundle.js"></script>


    <script>
    let authToken;
      const getToken = (callback) => {
    const request = new XMLHttpRequest();
    request.open("POST", "/token", true);
    request.onload = (response) => {
      if (request.status >= 200 && request.status < 400) {
        // Success!
        authToken = JSON.parse(request.responseText).token;
        if (typeof callback === "function") {
          callback();
        }
      } else {
        console.error(request);
      }
    };
    request.onerror = function (error) {
      console.error(error);
    };

    request.send();
  };
    
    
        const init = function init() {
            const region = "westeurope";
            var speechConfig = SpeechSDK.SpeechTranslationConfig.fromAuthorizationToken(
                authToken,
                region
            );
            speechConfig.speechSynthesisVoiceName = "Microsoft Server Speech Text to Speech Voice (cs-CZ, VlastaNeural)";

            o = new SpeechSDK.SpeakerAudioDestination();
            o.onAudioEnd = function () {
                console.log("audioEnd")
            };
            i = SpeechSDK.AudioConfig.fromSpeakerOutput(o);
            n = new SpeechSDK.SpeechSynthesizer(speechConfig, i);
            n.synthesisCompleted = function () {
                n.close();
                n = null;
            };
            n.SynthesisCanceled = function (n, i) {
                var r;
                r = e.CancellationDetails.fromResult(i);
                r.reason === e.CancellationReason.Error &&
                    (a.innerText = t.srTryAgain);
            };
            n.speakSsmlAsync(
                '<speak xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="http://www.w3.org/2001/mstts" xmlns:emo="http://www.w3.org/2009/10/emotionml" version="1.0" xml:lang="en-US"><voice name="en-US-JennyNeural"><prosody rate="0%" pitch="0%">You can replace this text with any text you wish. You can either write in this text box or paste your own text here.Try different languages and voices. Change the speed and the pitch of the voice. You can even tweak the SSML (Speech Synthesis Markup Language) to control how the different sections of the text sound. Click on SSML above to give it a try!Enjoy using Text to Speech!</prosody></voice></speak>',
                function () { },
                function (n) {
                    a.innerText = t.srTryAgain + " " + n;
                }
            );
        };

        function onDocumentReady(fn) {
            if (
                document.attachEvent
                    ? document.readyState === "complete"
                    : document.readyState !== "loading"
            ) {
                fn();
            } else {
                document.addEventListener("DOMContentLoaded", fn);
            }
        }
        onDocumentReady(()=>{getToken(init)});
    </script>

</body>

</html>
```

I'm referencing the same bundle as the demo page and literally trying to run the same code I've copied, but for some reason it fails on iOS Safari (just my test page, the original demo page works just fine)

**Comment by himby** [comment]
I experienced the same issue, got it working this way:

    
	const speechConfig = SpeechConfig.fromSubscription(serviceSettings.key, serviceSettings.location);
	const audioConfig = AudioConfig.fromDefaultSpeakerOutput();

	this.speechSynthesizer = new SpeechSynthesizer(speechConfig, audioConfig);

	this.speechSynthesizer?.speakTextAsync('Come again', result => {
	  if (result) {
		return result.audioData;
	  }
	  return undefined;
	},
	error => {
	  console.log(error);
	});




Inspired by samples from: 
[speech-service/get-started-text-to-speech](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-text-to-speech?tabs=script%2Cwindowsinstall&pivots=programming-language-javascript)

**Comment by himby** [comment]
Experiencing the same problem with:

        const speechConfig = SpeechConfig.fromSubscription(key, location);
        const audioConfig = AudioConfig.fromDefaultSpeakerOutput();

        const synthesizer = new SpeechSynthesizer(speechConfig, audioConfig);
        synthesizer.speakTextAsync(text,
          result => {
            if (result) {
              synthesizer.close();
              return result.audioData;
            }
            return undefined;
          },
          error => {
            console.log(error);
            synthesizer.close();
          });

Works nicely on Samsung tablets and in Desktop Chrome, but not on iPad or IPhone.

**Comment by pompomon** [comment]
My issue was that I was trying to start initializing the `synthesizer` before any user interaction, which is not allowed in iOS browsers (see https://stackoverflow.com/questions/13266474/autoplay-audio-on-mobile-safari), so what I did was I created a button and was initializing the `synthesizer` in the 'click' event listener.

Thanks @yulin-li for your help!

**Comment by dhruvjaglan** [comment]
I am facing the same issue, I have initialized the synthesizer on some event click but still audio is not played on IOS but works fine on android and macOS

**Comment by theisof** [comment]
I had this issue because I was asynchronously [fetching the speech token](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/js/browser#token-exchange-process) before playing back the tts. This delayed the playback and hence blocked it on iOS. 
 
Solved it by moving the token refreshing elsewhere and updating it on an interval.

**Comment by snirsnir** [comment]
have the same issue,
tried @theisof and @pompomon methods without luck.
someone can help?

**Comment by prajwalsharma2000** [comment]
@snirsnir did you get any work around or solution as I’m facing the exact same issue!

**Comment by k-daimon** [comment]
I wrote one of solution here.
https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/767
