### ISSUE TITLE
Browser: DialogServiceTurnState default to "audio-24khz-48kbitrate-mono-mp3" when the audio stream is actually RIFF 16khz

### ISSUE THREAD

**Issue by compulim** [microsoft/cognitive-services-speech-sdk-js#313]
In [`DialogServiceTurnState.js:35`](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/common.speech/DialogServiceTurnState.ts#L35), if the developer did not specify audio output format (`SynthOutputFormat`), it use the default value of 48kbps 24khz MP3 in browser, or RIFF 16khz in Node.js. Default value is specified in [`AudioOutputFormat.ts:356`](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/sdk/Audio/AudioOutputFormat.ts#L356)

More details can be found at [`DialogServiceAdapter.ts:597`](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/common.speech/DialogServiceAdapter.ts#L597).

But since this route is for Direct Line Speech, the service actually send RIFF 16khz regardless whether it is in browser or Node.js.

To repro:

- In a browser (or set `global.window` to truthy)
- Initialize `DialogServiceConnector` without specifying `PropertyId.SpeechServiceConnection_SynthOutputFormat`
- Do a single turn and get the synthesized stream

Expected: the `stream.format` should be RIFF with sample rate of 16000 Hz and mono.

Actual: the `stream.format` is `"audio-24khz-48kbitrate-mono-mp3"`.

![image](https://user-images.githubusercontent.com/1622400/106335263-4bdb6d80-6241-11eb-8a82-77f749805841.png)

I tried to workaround by setting the property ID, but it seems impossible. The code handling `SpeechServiceConnection_SynthOutputFormat` is wrong and the cause starts at [`DialogServiceAdapter.ts:599`](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/common.speech/DialogServiceAdapter.ts#L599).

```js
const pullAudioOutputStream: PullAudioOutputStreamImpl = turn.processActivityPayload(
  activityPayload,
  (SpeechSynthesisOutputFormat as any)[this.privDialogServiceConnector.properties.getProperty(PropertyId.SpeechServiceConnection_SynthOutputFormat, undefined)]
);
```

No matter what we set for `SpeechServiceConnection_SynthOutputFormat`, it send a [`SpeechSynthesisOutputFormat` enum](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/sdk/SpeechSynthesisOutputFormat.ts) to [`DialogServiceTurnState.processActivityPayload`](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/common.speech/DialogServiceTurnState.ts#L32), **instead of** [`AudioOutputFormat` object](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/sdk/Audio/AudioOutputFormat.ts#L23). Thus, it is actually sending **a wrong argument**. And [this code here](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/sdk/Audio/AudioOutputStream.ts#L124) detect wrong type of object and fallback to `undefined`.

**Comment by glharper** [comment]
[This commit](https://github.com/microsoft/cognitive-services-speech-sdk-js/commit/99460540dc3619841d660cb8a8de369d2b6e177e) appears to fix this issue. Closing.
