### ISSUE TITLE
Property "SpeechServiceConnection_SynthOutputFormat" is ignored in DialogServiceAdapter

### ISSUE THREAD

**Issue by compulim** [microsoft/cognitive-services-speech-sdk-js#314]
The code handling `SpeechServiceConnection_SynthOutputFormat` is wrong and the cause starts at [`DialogServiceAdapter.ts:599`](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/common.speech/DialogServiceAdapter.ts#L599).

```js
const pullAudioOutputStream: PullAudioOutputStreamImpl = turn.processActivityPayload(
  activityPayload,
  (SpeechSynthesisOutputFormat as any)[this.privDialogServiceConnector.properties.getProperty(PropertyId.SpeechServiceConnection_SynthOutputFormat, undefined)]
);
```

Then, it call the [`DialogServiceTurnState.processActivityPayload` function](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/common.speech/DialogServiceTurnState.ts#L32), it accept `AudioOutputFormatImpl` instead of `SpeechSynthesisOutputFormat`.

```js
public processActivityPayload(payload: ActivityPayloadResponse, audioFormat?: AudioOutputFormatImpl): PullAudioOutputStreamImpl {
    if (payload.messageDataStreamType === MessageDataStreamType.TextToSpeechAudio) {
        this.privAudioStream = AudioOutputStream.createPullStream() as PullAudioOutputStreamImpl;
        this.privAudioStream.format = (audioFormat !== undefined) ? audioFormat : AudioOutputFormatImpl.getDefaultOutputFormat();
        // tslint:disable-next-line:no-console
        // console.info("Audio start debugturn:" + this.privRequestId);
    }
    return this.privAudioStream;
}
```

Then it call the [setter of `PullAudioOutputStream.format`](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/sdk/Audio/AudioOutputStream.ts#L120):

```js
public set format(format: AudioStreamFormat) {
    if (format === undefined || format === null) {
        this.privFormat = AudioOutputFormatImpl.getDefaultOutputFormat();
    }
    this.privFormat = format as AudioOutputFormatImpl;
}
```

No matter what we set for `SpeechServiceConnection_SynthOutputFormat`, it send a [`SpeechSynthesisOutputFormat` enum](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/sdk/SpeechSynthesisOutputFormat.ts) to [`DialogServiceTurnState.processActivityPayload`](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/common.speech/DialogServiceTurnState.ts#L32), **instead of** [`AudioOutputFormat` object](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/sdk/Audio/AudioOutputFormat.ts#L23). Thus, it is actually sending **a wrong argument**. And [this code here](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/sdk/Audio/AudioOutputStream.ts#L124) detect wrong type of object and fallback to `undefined`.

**Comment by tomh05** [comment]
I'm encountering the same problem. 

I set the output format using this:
```
botFrameworkConfig.setProperty(speech_sdk.PropertyId.SpeechServiceConnection_SynthOutputFormat, speech_sdk.SpeechSynthesisOutputFormat.Audio24Khz96KBitRateMonoMp3.toString());
```
When I inspect the websocket, I see this outgoing websocket message which confirms it is requesting mp3 audio as the TTS format:
```
{"botInfo":{"commType":"Default","fromId":"...","ttsAudioFormat":"Audio24Khz96KBitRateMonoMp3"},"version":0.2} 
```
However, the voice sounds muffled, and if I inspect the incoming websocket message containing the binary audio I get: 
```
00000000: 0062 582d 5265 7175 6573 7449 643a 3934  .bX-RequestId:94
00000001: 6530 3131 3437 3262 3335 3433 3362 6138  e011472b35433ba8
00000002: 6561 3539 6439 6437 6662 3138 3063 0d0a  ea59d9d7fb180c..
00000003: 5061 7468 3a61 7564 696f 0d0a 436f 6e74  Path:audio..Cont
00000004: 656e 742d 5479 7065 3a61 7564 696f 2f62  ent-Type:audio/b
00000005: 6173 6963 0d0a 582d 5374 7265 616d 4964  asic..X-StreamId
00000006: 3a31 0d0a 0000 0000 0000 0000 0000 0000  :1..............
00000007: 0000 0000 0000 0000 0000 0000 0000 0000  ................
```
You can see there the `Content-Type:audio/basic`, showing it is uncompressed audio.

I wonder if this is a problem unique to direct line speech, as if I go to https://azure.microsoft.com/en-us/services/cognitive-services/text-to-speech/#features and try to generate some speech, when I inspect the websocket there, I can see that the client is requesting mp3 format, and the speech service returns MP3 audio data:

Outgoing client message:
```
{"synthesis":{"audio":{"metadataOptions":{"sentenceBoundaryEnabled":false,"wordBoundaryEnabled":false},"outputFormat":"audio-24khz-48kbitrate-mono-mp3"},"language":{"autoDetection":false}}}
```

And the incoming binary audio over websocket contains `Content-Type:audio/mpeg`
```
00000000: 0080 582d 5265 7175 6573 7449 643a 3241  ..X-RequestId:2A
00000001: 3431 3538 4432 3434 3044 3444 3446 4243  4158D2440D4D4FBC
00000002: 3832 4433 3946 3144 4141 4642 3231 0d0a  82D39F1DAAFB21..
00000003: 436f 6e74 656e 742d 5479 7065 3a61 7564  Content-Type:aud
00000004: 696f 2f6d 7065 670d 0a58 2d53 7472 6561  io/mpeg..X-Strea
00000005: 6d49 643a 3933 3845 4630 3530 3142 4631  mId:938EF0501BF1
00000006: 3439 3734 4138 3746 4237 4431 3341 4139  4974A87FB7D13AA9
00000007: 3046 3433 0d0a 5061 7468 3a61 7564 696f  0F43..Path:audio
00000008: 0d0a fff3 64c4 0019 0a26 040a 6184 1c10  ....d....&..a...
00000009: 82b7 8e08 4637 dbff dddd effc c200 0000  ....F7..........
```

**Comment by brandom-msft** [comment]
Closing with merge of #329
