### ISSUE TITLE
Use async / await with try catch on demo docs.

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/cognitive-services-speech-sdk-js#316]
Copying over doc feedback from https://github.com/MicrosoftDocs/azure-docs-sdk-node/issues/673 by @allanchua101 

> The document looks quite old and it requires more cognitive effort to read for developers used to async/await in NodeJS.
To solve the issue, implementing the sample on async/await with try catch will reduce callback hell and cognitive workload required to understand sample better.

This feedback is for the page [Cognitive Services Speech SDK for JavaScript](https://docs.microsoft.com/en-us/javascript/api/overview/azure/speech-service?view=azure-node-latest) and the source md file to update is https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/latest/speech-service.md

**Comment by glharper** [comment]
@ramya-rao-a Thank you for writing this and using Speech SDK! As of right now, the vast majority of the JS SDK API is not awaitable, even though the method names end with Async. Our current plan is to change applicable methods to return native Promises with version 2.0, which is at least nine months away. When that happens, the documentation will be updated to match the more modern JS idiom.

Thanks,
Glenn

**Comment by ramya-rao-a** [comment]
Thanks Glenn!

cc @allanchua101
