### ISSUE TITLE
Direct Line Speech: "enableInternalHTTPSupport" flag is not working as service return 400 due to bad URL

### ISSUE THREAD

**Issue by compulim** [microsoft/cognitive-services-speech-sdk-js#317]
In Direct Line Speech adapter, one of our test is to make sure the `enableInternalHTTPSupport` flag is working properly.

After we bumped to Speech SDK 1.15.0, with the flag enabled, we are seeing the Web Socket URL changed and the service always return 400 with the new URL.

Previously, the working URL is (broken into multiple lines for clarity):

```
https://westus2.convai.speech.microsoft.com/directline/api/v1?
  &Authorization=eyJhbGc...
  &format=simple
  &language=en-US
  &X-ConnectionId=3105F06...
  &X-DLS-Secret=ew0KICA...
```

The new URL that does not work is:

```
https://westus2.convai.speech.microsoft.com/directline/api/v1?
  &Authorization=eyJhbGc...
  &enableBotMessageStatus=true
  &format=simple
  &language=en-US
  &connectionid=613A427...
  &botid=ew0KICA...
```

Differences:

```diff
  https://westus2.convai.speech.microsoft.com/directline/api/v1?
    &Authorization=eyJhbGc...
+   &enableBotMessageStatus=true
    &format=simple
    &language=en-US
-   &X-ConnectionId=3105F06...
+   &connectionid=613A427...
-   &botid=ew0KICA...
+   &X-DLS-Secret=ew0KICA...
```

We tried to hack the code by reverting these 2 names and it worked properly:

![image](https://user-images.githubusercontent.com/1622400/106643814-197e8880-653f-11eb-8c56-4fc7432f0c8a.png)

It was caused by a recent PR changed the `QueryParameterNames.ts`, https://github.com/microsoft/cognitive-services-speech-sdk-js/commit/12c0e342f00050769b32c020459633ea6a342c38#diff-30a5c51a0d9988fc248b73ddac085bfdfcff208d0e471a767f2a8ed4d73753b6.

The code that use the `QueryParameterNames` lookup to generate the Web Socket URL can be found in [`DialogConnectorFactory.ts`](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/common.speech/DialogConnectorFactory.ts).

This issue seems not workaround-able and we are blocked on using Speech SDK 1.15.0.

**Comment by trrwilson** [comment]
Thanks for filing this, William; internal discussion underway now on the correct fix. `X-ConnectionId` becoming `connectionId` is clearly wrong, though less clear is how it regressed given the modified code appears to have been setting the latter; `X-DLS-Secret` is a bit of a mystery given it has no results anywhere in the DLS service-side code and nobody could remember where the key came from, but we'll get to the bottom of that shortly.
