### ISSUE TITLE
IE11: When sending plain text message using DirectLineSpeech, it warn with "Payload must be ArrayBuffer"

### ISSUE THREAD

**Issue by compulim** [microsoft/cognitive-services-speech-sdk-js#325]
https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/common/RawWebsocketMessage.ts#L18

In this line of code, it checks if the instance is an `ArrayBuffer` or not:

```js
if (messageType === MessageType.Binary && payload.__proto__.constructor.name !== "ArrayBuffer") {
  throw new InvalidOperationError("Payload must be ArrayBuffer");
}
```

However, this check only works with modern browsers, but not IE11.

![image](https://user-images.githubusercontent.com/1622400/108016153-be30a980-6fc6-11eb-8d2f-b06d0c308def.png)

Thus, in the console of IE11, after sending a plain text messages, we saw many uncaught exceptions appear at the same time.

![image](https://user-images.githubusercontent.com/1622400/108018797-94c74c00-6fcd-11eb-898b-2440631b8d62.png)

> It was introduced in PR #247.

**Comment by glharper** [comment]
@compulim Thanks for writing up this issue and using Speech SDK. Unfortunately, we don't support IE11.
