### ISSUE TITLE
Unable to get started

### ISSUE THREAD

**Issue by PepperAddict** [microsoft/cognitive-services-speech-sdk-js#331]
Hello! 

I just started using azure's speech-to-text and I wasn't able to get it going yet. This may be a duplicate of issue #330 
but I want to show my other attempts and the errors I received. 

I am using react as the front-end and bringing in the sdk with require. 
`const sdk = require('microsoft-cognitiveservices-speech-sdk');`  No issues on this part. 

I think this is my main problem that I can't seem to get right. The tutorial used fromSubscription so I use: 
`const speechConfig = sdk.SpeechConfig.fromSubscription("subscription-key", "eastus")`
But I get the error: 
![image](https://user-images.githubusercontent.com/4171505/108861449-3ac21a00-75bd-11eb-84ea-ea4c5499ad0f.png)

Am I getting the subscriptionKey at the correct place? Why is there two? Which one do I use?

![image](https://user-images.githubusercontent.com/4171505/108861741-8bd20e00-75bd-11eb-8ed1-1b81975284d9.png)

I noticed I could use a different way to initialize it. 
So I tried: `fromEndpoint`
`const speechConfig = sdk.SpeechConfig.fromEndpoint("https://eastus.api.cognitive.microsoft.com/sts/v1.0/issuetoken", "subscriptionKey")`

I get a different error: 
![image](https://user-images.githubusercontent.com/4171505/108862223-04d16580-75be-11eb-8e88-647409862f21.png)

So I tried to initialize it with host: `fromHost`
`const speechConfig = sdk.SpeechConfig.fromHost("https://eastus.api.cognitive.microsoft.com/sts/v1.0/issuetoken", "subscriptionKey")`

I don't get any websocket error anymore, but I get a 500 error `speechRecognizer`
![image](https://user-images.githubusercontent.com/4171505/108862605-6265b200-75be-11eb-87a9-935b2e3db119.png)

I'm not sure what I'm doing wrong and I hope someone can help me with this problem.

**Comment by glharper** [comment]
@PepperAddict There are two subscription keys so the customer has a fallback in case one key expires (or is invalidated) and they quickly need a replacement.
For react, I have a sample repo that pulls in Speech SDK [available here](https://github.com/glharper/cognitive-services-react-js-sdk), if you'd like to see if that app works for your subscription keys.

**Comment by PepperAddict** [comment]
I understand, @glharper and thank you so much for getting back to me about this issue! 
I cloned your app, installed the packages, and started it up! 
But unfortunately I'm getting a `1006` status code error there as well. I tried both of my keys. 

![Screenshot (92)_LI](https://user-images.githubusercontent.com/4171505/108915677-3d436480-75fb-11eb-8232-f82aced86074.jpg)

**Comment by rhurey** [comment]
Your resource is in EastUS, and the drop down for region in the sample app is set to WestUS.

**Comment by PepperAddict** [comment]
Hey @rhurey ! 
I totally missed that! Thanks for pointing that out. 
I put my subscription key and changed it to East US and I still get the same error as the screenshot above.

**Comment by glharper** [comment]
Using this [non-React sample](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/javascript/browser/from-microphone/index.html), does speech recognition work for you using the same key and region?

The react sample seems to work for me, btw: 
![image](https://user-images.githubusercontent.com/64209257/108955836-ab038680-7623-11eb-8cae-c512802252fd.png)

**Comment by PepperAddict** [comment]
I downloaded the sdk and included in the html project and this is what I get. 
![image](https://user-images.githubusercontent.com/4171505/109015824-89d28280-7683-11eb-8742-e42fe27a561d.png)

I regenerated a new key and I'm still getting the same error. 

I want to bring this up just in case it has something to do with it. I'm part of the devpost hackathon Hack for Accessibility so they let us use a login for Azure which is what I'm using. I wonder if it has something to do with that? 
Thanks again for looking into this @glharper

**Comment by rhurey** [comment]
Was the speech resource created in the last week or so? We've tracked down a problem using Subscription Keys for recently created resources and a service fix is rolling out.

**Comment by PepperAddict** [comment]
Hello @rhurey! 
Yes, the speech resource was created very recently. The one I tested for this problem was created just the day before so about two days ago. I deleted that resource and created a new one just today and that subscription key doesn't work either. 
Thank you for keeping me updated! Looking forward to the fix.

**Comment by rhurey** [comment]
As a work around, using an auth token seems to be working.

There's details on how to get an auth token from a subscription key here: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-speech-to-text and the speech sample (more complex than the quickstart) has a token generating php file with it and an will use it automatically if it's present and working. (https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/js/browser)

**Comment by dargilco** [comment]
@PepperAddict any update on this? did you get it to work?

**Comment by PepperAddict** [comment]
Hello @dargilco ! 

I just tested it and it's fixed! Thank you!
