### ISSUE TITLE
Speaker Verification: Missing getProfileAsync method

### ISSUE THREAD

**Issue by yoshigev** [microsoft/cognitive-services-speech-sdk-js#338]
Hi,

This is sort of a feature request.
The class VoiceProfileClient is used to access the speaker verification service, but is is missing some operations.
According to the documentation [here](https://docs.microsoft.com/en-us/rest/api/speakerrecognition/verification/textdependent), the following operations exist, but are not exposed by the SDK:
- Get Profile
- List Profiles
- List Phrases

Can those operations be added?

Thanks,
Yehoshua

**Comment by glharper** [comment]
@yoshigev,
Thanks for using Speech SDK and writing up this issue. I've added this feature request to our backlog, and would expect this to happen within the next few releases, barring higher priority work.

**Comment by glharper** [comment]
@yoshigev,
New VoiceProfileClient methods retrieveEnrollmentResultAsync, getAllProfilesAsync, and getAuthorizationPhrasesAsync have been added to the SDK, and should be available in version 1.17 (next release). Thanks again for submitting this!

**Comment by Fradulentus** [comment]
Когнитивные услуги-речи.
В двух словах,как именно это может выглядеть?
Вся наша  жизнь наглядно показывает что очень часто поставленные задачи лишь выявляют методы,а все установленые результаты возможно существуют лишь для неизбежного открытия иных форм значений и свойств самой структуры знания.

**Comment by Fradulentus** [comment]
Когнитивные услуги-речи.
В двух словах,как именно это может выглядеть?
Вся наша  жизнь наглядно показывает что очень часто поставленные задачи лишь выявляют методы,а вустановленые результаты лишь

**Comment by Fradulentus** [comment]
Вы обращаетесь в компанию Microsoft Corp.

От: Glenn ***@***.***>
Отправлено: 1 апреля 2021 г. в 21:08
Кому: ***@***.***>
Копия: ***@***.***>
Тема: Re: [microsoft/cognitive-services-speech-sdk-js] Speaker Verification: Missing getProfileAsync method (#338)


@yoshigev<https://github.com/yoshigev>,
New VoiceProfileClient methods retrieveEnrollmentResultAsync, getAllProfilesAsync, and getAuthorizationPhrasesAsync have been added to the SDK, and should be available in version 1.17 (next release). Thanks again for submitting this!

**Comment by Fradulentus** [comment]
К сожалению именно сейчас я не способен распознать вас,это вызвано чередой моих проблем технического характер.Чтоб вы понимали лучше меня,я республиканец и мне важен мир,как обитель цивилизации.
Сегодня по сервисному времени моих каталогов,я свяжусь с вами.

Вы обращаетесь в компанию Microsoft Corp.

От: Glenn ***@***.***>
Отправлено: 1 апреля 2021 г. в 21:08
Кому: ***@***.***>
Копия: ***@***.***>

**Comment by glharper** [comment]
@yoshigev v1.17 of SpeechSDK for JavaScript is now live with these new APIs, and is available for Node via npm install ([npm library homepage](https://www.npmjs.com/package/microsoft-cognitiveservices-speech-sdk)) and browser via include (using [this link](https://cdn.jsdelivr.net/npm/microsoft-cognitiveservices-speech-sdk@latest/distrib/browser/microsoft.cognitiveservices.speech.sdk.bundle-min.js)). Thanks again for using Speech SDK!
