### ISSUE TITLE
Speech SDK Angular app WSS security issue

### ISSUE THREAD

**Issue by serhii-lisniakov** [microsoft/cognitive-services-speech-sdk-js#339]
Hi there!
I want to use your speech service in sovereign clouds ( .us domen).
I found your solving here https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/sovereign-clouds#azure-government-united-states with _speechsdk.SpeechConfig.fromHost_ method, but it requires **subscriptionKey**.
using auth token insted of key and other methods throw an error like this:
![image](https://user-images.githubusercontent.com/64072558/110944112-aee21900-8344-11eb-9f6c-7bb16b6cbbee.png)

How can I success in using host method and avoid using the **subscriptionKey** on the Frontend?

**Comment by glharper** [comment]
@serhii-lisniakov fromHost doesn't require a subscription key, it's an optional parameter. Please see the Note [here](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/2e6a802339a151dff3cf87e6bf48b2cabbf64cbd/src/sdk/SpeechConfig.ts#L89)

Give this a shot:
```
let speechConfig = speechsdk.SpeechConfig.fromHost(host);
speechConfig.authorizationToken = authToken;
```

**Comment by serhii-lisniakov** [comment]
@glharper as I say using auth token throw an error above

**Comment by glharper** [comment]
@serhii-lisniakov Could you post the code you're using to reproduce this, minus the auth token?

**Comment by serhii-lisniakov** [comment]
@glharper seems to be OK when I set it as a property insted of parameter.
Great help Glenn, thank a lot!
