### ISSUE TITLE
Improve speakAsText to avoid using speakAsSsml

### ISSUE THREAD

**Issue by ssougnez** [microsoft/cognitive-services-speech-sdk-js#342]
`speakAsText` provides an easy way to use text-to-speech, however, it seems pretty cumbersome to be forced to use `speakAsSsml` as soon as you want to change a small settings.

For example, I want to read the text in French, so I have to build the XML string to do so. 

Wouldn't it be nice to have something like:

`speakAsText(data: string | { text: string, speed?: number, pitch?: number, language?: string }, ...)`

And behind the scene, `speakAsText` would build the SSML.

If you think it's a good idea and are open to PR, I can maybe give it a shot.

Cheers

**Comment by yulin-li** [comment]
Hi @ssougnez , the `speechText()` method support setting locale/voice. For now, we don't support speed or pitch. Do you want to change pitch or just change the locale?

**Comment by yulin-li** [comment]
closing now, feel free to re-open it if needed.

**Comment by Fradulentus** [comment]
Duplicate

**Comment by Mike-Bell** [comment]
For what it's worth, I agree that this would be a nice quality of life improvement for people using this SDK
