### ISSUE TITLE
[Chrome Extension] Getting refused to create worker from blob error 

### ISSUE THREAD

**Issue by SulabhaSudheeran** [microsoft/cognitive-services-speech-sdk-js#343]
I am trying to integrate Microsoft cognitive-services-speech-sdk-js in my chrome extension to recognise the speech in google meet.

After a while of recognition, i am getting following error, resulting in the cancellation of the recognition.

Refused to create a worker from 'blob:https://meet.google.com/4f586067-ea8f-4e7f-9215-51ef426d3c9a' because it violates the following Content Security Policy directive: "worker-src 'self'".

I tried to add the required CSP in the manifest json file, but still facing the issue.

**Comment by glharper** [comment]
@SulabhaSudheeran Thanks for using SpeechSDK, and writing this issue up. [This issue](https://stackoverflow.com/questions/66215765/chrome-extension-refused-to-create-a-worker-from-blob) seems similar to what you're describing, and the submitter is also on github. @bfoysal, would you happen to have any advice here?

**Comment by bfoysal** [comment]
Hi @SulabhaSudheeran  
I guess you are pushing SpeechSDK bundle as content script in the google meet window and then trying to recognize speech. The problem here is google meet already has a service worker running for the meeting and you trying to create another one using SpeechSDK. Thus creating the CSP conflict. The work around I found is running the SpeechSDK worker in an **<iframe>** and attaching it to the meeting window as a child. This way SpeechSDK worker will run in a separate context. You can then use message passing to communicate between your different scripts.
Hope this is helps.

**Comment by SulabhaSudheeran** [comment]
> Hi @SulabhaSudheeran
> I guess you are pushing SpeechSDK bundle as content script in the google meet window and then trying to recognize speech. The problem here is google meet already has a service worker running for the meeting and you trying to create another one using SpeechSDK. Thus creating the CSP conflict. The work around I found is running the SpeechSDK worker in an **<iframe>** and attaching it to the meeting window as a child. This way SpeechSDK worker will run in a separate context. You can then use message passing to communicate between your different scripts.
> Hope this is helps.

**Comment by SulabhaSudheeran** [comment]
> > Hi @SulabhaSudheeran
> > I guess you are pushing SpeechSDK bundle as content script in the google meet window and then trying to recognize speech. The problem here is google meet already has a service worker running for the meeting and you trying to create another one using SpeechSDK. Thus creating the CSP conflict. The work around I found is running the SpeechSDK worker in an **<iframe>** and attaching it to the meeting window as a child. This way SpeechSDK worker will run in a separate context. You can then use message passing to communicate between your different scripts.
> > Hope this is helps.



> @SulabhaSudheeran Thanks for using SpeechSDK, and writing this issue up. [This issue](https://stackoverflow.com/questions/66215765/chrome-extension-refused-to-create-a-worker-from-blob) seems similar to what you're describing, and the submitter is also on github. @bfoysal, would you happen to have any advice here?

Hi @glharper,
I followed the work around (using **iframe**) suggested by @bfoysal and it worked for me.

**Comment by glharper** [comment]
@bfoysal Thank you so much for your help! :-)
