### ISSUE TITLE
The completion callback of "speakAsText" fires when the request end instead of when the sound ends

### ISSUE THREAD

**Issue by ssougnez** [microsoft/cognitive-services-speech-sdk-js#344]
If I call the function `speakAsText` (or `speakAsSsml`), the first callback function fires when the HTTP/WS request is completed. However, when redirecting the sound to the audio speaker, it's generally not we the user wants. Indeed, The user would probably prefer to be notified when the sounds has been played instead that when the request is done.

To workaround this, I had to pass `null` as the stream to get the `ArrayBuffer` of the sound and use howler.js to play the sound and get notified of the completion.

What do you guys think?

**Comment by yulin-li** [comment]
@ssougnez yes, you are right, the `speakText()` completes when we get all data from the service. You can use [`onAudioEnd`](    https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/sdk/Audio/IPlayer.ts#L40) event to get notified when playback is done. See our [sample](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/browser/synthesis.html#L342)
