### ISSUE TITLE
ReferenceError: MediaStream is not defined in sdk/Audio/AudioConfig.js:85:36

### ISSUE THREAD

**Issue by zacswolf** [microsoft/cognitive-services-speech-sdk-js#350]
```
node --version
v14.16.0
npm --version  
6.14.11
```

I get a sdk internal ReferenceError when calling:
```const audioConfig = AudioConfig.fromStreamInput(pushStream)```

This is for a project that uses NodeJS and Express. I'm not sure whose side this issue is on.

Any help is appreciated!

**Comment by glharper** [comment]
@zacswolf, Thanks for using Speech SDK and writing this issue up. This may be an issue with a missing typecheck in AudioConfig.

**Comment by glharper** [comment]
@zacswolf v1.17 of SpeechSDK for JavaScript is now live with this fix, available for Node via npm install ([npm library homepage](https://www.npmjs.com/package/microsoft-cognitiveservices-speech-sdk)) and browser via include (using [this link](https://cdn.jsdelivr.net/npm/microsoft-cognitiveservices-speech-sdk@latest/distrib/browser/microsoft.cognitiveservices.speech.sdk.bundle-min.js)). Thanks again for using Speech SDK!
