### ISSUE TITLE
Question about Azure Speech SDK for Browser (JavaScript)

### ISSUE THREAD

**Issue by inglesuniversal** [microsoft/cognitive-services-speech-sdk-js#357]
Is there another secure way to generate tokens that does NOT make me rely on a PHP server to have a single page which hosts the code to generate these tokens?

I am trying to gradually move from LAMP servers to 100% server-less apps.

Is that possible?

What are my options?

Thanks so much for your HELP and I look forward to start using more services from Azure.

#STAYSAFE

**Comment by inglesuniversal** [comment]
Thanks so much for the detailed response... Can there be a way to run a cloud function on Azure service to generate the same code in a serverless environment?  I have access to 4 of the top major cloud providers... so I just need some pointers on how to make it work. If an idea comes along the way or future releases of products which could unveil the script to could fulfill my need would be just awesome. Please keep me posted on any progress.

Best regards

**Comment by glharper** [comment]
@inglesuniversal Setting up an Azure function may work for you here...for a general overview see [this doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-overview). Basically the function should:
- POST to https://YOUR_REGION_HERE.api.cognitive.microsoft.com/sts/v1.0/issueToken with the headers 'Content-Type: application/json' and 'Ocp-Apim-Subscription-Key: YOUR_KEY_HERE', then
- return the token read from the POST response to the caller of the Azure Function

Hope this helps!
