### ISSUE TITLE
ConversationTranslator Error - this.cancelSpeech is not a function

### ISSUE THREAD

**Issue by harryesslemont** [microsoft/cognitive-services-speech-sdk-js#366]
I'm having issues with the above error getting thrown when my participants leave a conversation. From my limited understanding of 'this' contexts in js, I believe that this was likely introduced in this commit https://github.com/microsoft/cognitive-services-speech-sdk-js/commit/529d62ce5233b8187845c55b7aef8b6e4d887e25 where some arrow functions were replaced. 

src/sdk/Transcription/ConversationTranslator.ts Line 372 - onSpeechDisconnected() is the one that is of interest to me, but it looks like the same issue would occur in multiple other areas too.

**Comment by glharper** [comment]
@harryesslemont Confirmed, the onSpeechConnected and onSpeechDisconnected callbacks fire within a Connection context, and the rest (onSpeechRecognized (line [359](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/346ad5bb4ba63b9565ae233b6abca1ce9fcf64af/src/sdk/Transcription/ConversationTranslator.ts#L359)) through onSpeechSessionStopped) fire within a TranslationRecognizer context. Nice find!

**Comment by harryesslemont** [comment]
Any chance of getting this into a release anytime soon? It's currently holding us back from going live with our speech-to-text feature.

**Comment by glharper** [comment]
@harryesslemont It's checked into the 1.17 release, which should go live in about two weeks.

**Comment by glharper** [comment]
@harryesslemont v1.17 of SpeechSDK for JavaScript is now live with this fix, available for Node via npm install ([npm library homepage](https://www.npmjs.com/package/microsoft-cognitiveservices-speech-sdk)) and browser via include (using [this link](https://cdn.jsdelivr.net/npm/microsoft-cognitiveservices-speech-sdk@latest/distrib/browser/microsoft.cognitiveservices.speech.sdk.bundle-min.js)). Thanks again for using Speech SDK!
