### ISSUE TITLE
Missing Git tag / release for 1.17.0

### ISSUE THREAD

**Issue by nfreear** [microsoft/cognitive-services-speech-sdk-js#378]
Hi,

Thanks for the latest release.

I see you published 11 days ago :~ https://npmjs.com/package/microsoft-cognitiveservices-speech-sdk/v/1.17.0;

However, there's no matching tag on Github :~ https://github.com/microsoft/cognitive-services-speech-sdk-js/tags;

Did someone forget to push tags? (Easily done! ;) )

Thanks,

Nick

**Comment by yulin-li** [comment]
@BrianMouncer could you pls look into this?

**Comment by glharper** [comment]
@nfreear 1.17 tag exists now. Thank you for using Speech SDK, and writing up this issue.
