### ISSUE TITLE
Unable to proceed to speech-to-text conversion

### ISSUE THREAD

**Issue by krisalay** [microsoft/cognitive-services-speech-sdk-js#38]
Hello,
I am referencing to the sample at: [https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/node/speech.js](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/node/speech.js) for speech to text conversion.

But its behaving abruptly. Sometimes the process starts, and sometimes I get the following error.
```
SpeechRecognitionCanceledEventArgs {
  privSessionId: '3309E8B386C94CEEB733BB4ED8DA5895',
  privOffset: undefined,
  privReason: 0,
  privErrorDetails: undefined,
  privErrorCode: 6
}
```
What does this error mean, and how can I resolve it?

Also, according to the documentation at: [https://docs.microsoft.com/en-gb/javascript/api/microsoft-cognitiveservices-speech-sdk/cancellationerrorcode?view=azure-node-latest](https://docs.microsoft.com/en-gb/javascript/api/microsoft-cognitiveservices-speech-sdk/cancellationerrorcode?view=azure-node-latest), the errorCode = 6 Indicates that an error is returned by the service.

**Comment by rhurey** [comment]
Sorry you're having problems.
Couple of questions to help me clarify things:
1) When the process starts, it is successful at recognizing the text?

2) Are you using the free tier for recognition?

**Comment by wolfma61** [comment]
@krisalay  - can you provide the information?

**Comment by rhurey** [comment]
It's been 3 weeks so I'm closing.
