### ISSUE TITLE
Once I call stopContinuousRecognitionAsync, the mediarecorder sharing the same stream will not work properly

### ISSUE THREAD

**Issue by allenmxh** [microsoft/cognitive-services-speech-sdk-js#385]
hello, after I clone the mediarecorder stream and pass it to TranslationRecognizer, once I use stopContinuousRecognitionAsync, the mediarecorder cannot record normally. Can you tell me why?
`function initRecorder() {
    navigator.mediaDevices
      .getUserMedia(mediaOptions)
      .then((stream) => {
        if (type === RecorderType.ALL) {
          videoRef.current.srcObject = stream;
          recorder.current = new MediaRecorder(stream);

          recorder.current.ondataavailable = function (e) {
            if (e.data && e.data.size > 0) {
              console.log("MediaRecorder.ondataavailable");
              chunks.push(e.data);
            }
          };
          recorder.current.onstop = (e) => {
            let blob = new Blob(chunks, { type: "video/mp4" });
            chunks = [];
            if (typeof props.onRecorderFinished === "function") {
              props.onRecorderFinished(blob);
            }
          };

          let audioStream = stream.clone();
          let mediaAudioStream = new MediaStream(audioStream.getAudioTracks());
          initRecognizer(mediaAudioStream);
  }`

**Comment by rhurey** [comment]
Thanks for contacting us about this.

Looking at the implementation when the recognition stops, the SDK is closing the media stream. In the case of a developer-supplied media stream, it should do something different... I'll tag it as a bug and we'll update this when we have a fix in sight.

**Comment by glharper** [comment]
@allenmxh The latest version of SpeechSDK for JavaScript, which includes this fix, is now live, available for Node via npm install ([npm page here](https://www.npmjs.com/package/microsoft-cognitiveservices-speech-sdk)) and browser via include (
https://cdn.jsdelivr.net/npm/microsoft-cognitiveservices-speech-sdk@latest/distrib/browser/microsoft.cognitiveservices.speech.sdk.bundle-min.js
). Thanks again for using Speech SDK!

**Comment by allenmxh** [comment]
@glharper I updated the SpeechSDK to the latest version, and I am glad that this issue has been fixed, thanks！
