### ISSUE TITLE
Multi-device conversation: Leaving participant microphone open results in disconnect after a few minutes

### ISSUE THREAD

**Issue by glharper** [microsoft/cognitive-services-speech-sdk-js#389]
Using the sample [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/javascript/browser/multi-device-conversation/multi-device-conversation.html),
- open sample page in three separate tabs 
- host conversation in first tab, join as participant in other two
- click start speaking in all tabs and allow microphone access

After a few minutes without talking, at least one participant will disconnect. (I'd expect all participants to disconnect about the same time, as well as the host, if there's a set silence timeout.)

More issues
- When all participants disconnect, there's no way to rejoin the conversation using the sample without reloading the page.
- Even after reloading, trying to rejoin results in a 400 error: participant name already exists and is in the conversation.
- The host eventually gets a 404: resource does not exist, and is dropped.

**Comment by harryesslemont** [comment]
I originally reported these issues via azure support. I originally thought the problems were just down to inactivity but I've also had similar issues happen when a user has been actively talking after about 15 minutes or so. A frequent error for me is a set of 5 identical websocket connection errors that I seem to receive simultaneously that then leads to some of the issues detailed above.
