### ISSUE TITLE
 SDK needs to implement ECMAScript 2017

### ISSUE THREAD

**Issue by Joll59** [microsoft/cognitive-services-speech-sdk-js#39]
#### SDK should support modern JS. 
As it stands, complex actions with the SDK is cumbersome, because it utilizes callbacks.

It would be beneficial for the SDK to utilize promises or async/await, lending to a more streamlined coding experience.

**Comment by rhurey** [comment]
Moving to a newer ECMA version is under discussion.

It's not clear which version that move would be to yet, or how much of a breaking change in the API surface will happen as an immediate result.

**Comment by rhurey** [comment]
While this has been longer in coming that I'd hoped the retirement of home grown promises has begun.

Phase 1 will be to plumb native promises to the API surface.
Phase 2 will be to change the API to return Promise objects.

experiment/v2.0.promises is the working branch, I'll try to keep it in more working than not condition.

**Comment by oscholz** [comment]
@Joll59 We have added this to our backlog for our next major version. When we complete this backlog item, we will update this issue with the version information that will contain the functionality.
I will close this issue for the time being.
Thank you for using the JS Speech SDK!

**Comment by glharper** [comment]
@Joll59 We're currently thinking the SDK will wait for our v2.0 to implement ES2018 or higher. Upgrading now would be a breaking change for our customers on earlier versions of Node. Thanks again for using the JS Speech SDK, and we'll ping this issue when v2.0 gets closer (current timeline is TBD).
