### ISSUE TITLE
Error on deploying to azure app service

### ISSUE THREAD

**Issue by ChinnaRajS** [microsoft/cognitive-services-speech-sdk-js#390]
![image](https://user-images.githubusercontent.com/57625472/123396912-7b5b8f80-d5bf-11eb-8a96-14494e038612.png)

Getting this error when to deployed Azure app service but works fine in local what am I doing wrong ?

Note: the error occurs at start of the application

Thanks in advance

**Comment by glharper** [comment]
Hello!

The JS Speech SDK takes a dependency on username-sync but does not invoke this call stack directly. From a quick search, it appears this is typically related to not allocating enough memory on the target machine/instance, and that choosing a [larger amount of memory for your deployment may help](https://stackoverflow.com/questions/26193654/node-js-catch-enomem-error-thrown-after-spawn). 

Could you please give that a shot and investigate along those lines? Given this is a relationship between an NPM dependency and the specific environment that's in use, the Speech SDK team won't have a lot of specific information we can recommend--this is happening outside of the project code.
