### ISSUE TITLE
Replace PCM Recorder script processor with audio worklet

### ISSUE THREAD

**Issue by rssfrncs** [microsoft/cognitive-services-speech-sdk-js#391]
We are getting deprecation warnings in the console due to the use of script processor in pcm recorder. We've also noticed that on lower end devices (or throttling the CPU in chrome devtools) the quality of transcriptions suffers could using an audio worklet help?

**Comment by glharper** [comment]
@rssfrncs We have a work item tracking this feature, and will let you know when it's added.

**Comment by glharper** [comment]
@rssfrncs The latest version of SpeechSDK for JavaScript, which includes this fix, is now live, available for Node via npm install ([npm page here](https://www.npmjs.com/package/microsoft-cognitiveservices-speech-sdk)) and browser via include (
https://cdn.jsdelivr.net/npm/microsoft-cognitiveservices-speech-sdk@latest/distrib/browser/microsoft.cognitiveservices.speech.sdk.bundle-min.js
). Thanks again for using Speech SDK!
