### ISSUE TITLE
How to set sampeRate 8000Hz by using pushStream

### ISSUE THREAD

**Issue by sutekyara** [microsoft/cognitive-services-speech-sdk-js#400]
How to set sampleRate 8000 by using pushStream?

I tried to push wav header with 8000Hz sampleRate to pushStream before pushing pcm audio data.
Azure does not seem to recognize the header, and the result is recognized as 16000Hz sampleRate.

I think there is someway to set 8000Hz sampleRate.

**Comment by glharper** [comment]
@sutekyara Thanks for using Speech SDK. I tested this code, which recognizes different WAV formats correctly.
```
  var filename = "testing_8k.wav"; // 8000 Hz, Mono
  const format = sdk.AudioStreamFormat.getWaveFormatPCM(8000, 16, 1); // bitrate, bits-per-sample, channels
  const pushStream = sdk.AudioInputStream.createPushStream(format);
  
  // open the file and push it to the push stream.
  fs.createReadStream(filename).on('data', function(arrayBuffer) {
    pushStream.write(arrayBuffer.slice());
  }).on('end', function() {
    pushStream.close();
  })
  
  var audioConfig = sdk.AudioConfig.fromStreamInput(pushStream);
  var config = sdk.SpeechConfig.fromSubscription("KEY", "REGION");
  
  config.speechRecognitionLanguage = "en-US";
  var reco = new sdk.SpeechRecognizer(config, audioConfig);
```

What you seem to be asking about is the AudioStreamFormat.getWaveFormatPCM(bitrate, bitsPerSample, channelCount) API.
Does that code and API work for you?

**Comment by sutekyara** [comment]
it works well!!
thank you very much!
