### ISSUE TITLE
SDK depends on Angular even when used in pure Node.js

### ISSUE THREAD

**Issue by compulim** [microsoft/cognitive-services-speech-sdk-js#403]
When installing `microsoft-cognitiveservices-speech-sdk`, it said `@angular/common>=5` is required.

```diff
  compulim@ubuntu:/tmp/speech$ npm i microsoft-cognitiveservices-speech-sdk
  npm WARN saveError ENOENT: no such file or directory, open '/tmp/speech/package.json'
  npm notice created a lockfile as package-lock.json. You should commit this file.
  npm WARN enoent ENOENT: no such file or directory, open '/tmp/speech/package.json'
- npm WARN xmlhttprequest-ts@1.0.1 requires a peer of @angular/common@>= 5.0.0 but none is 
  installed. You must install peer dependencies yourself.
- npm WARN xmlhttprequest-ts@1.0.1 requires a peer of @angular/core@>= 5.0.0 but none is 
  installed. You must install peer dependencies yourself.
  npm WARN speech No description
  npm WARN speech No repository field.
  npm WARN speech No README data
  npm WARN speech No license field.

  + microsoft-cognitiveservices-speech-sdk@1.17.0
  added 45 packages from 42 contributors and audited 45 packages in 2.8s

  7 packages are looking for funding
    run `npm fund` for details

  found 0 vulnerabilities
```

I think should either specify the peer deps in `package.json`, or not requiring Angular.

If the SDK can be targeted to headless environment (a.k.a. on Node.js and not browser), Angular should not be a requirement. But in fact, it is.

The scenario will be worsened as `npm@7` will automatically install all missing peer dependencies. Using this SDK in a pure Node.js environment will need to install/run Angular.

**Comment by glharper** [comment]
@compulim [Version 1.18.1](https://github.com/microsoft/cognitive-services-speech-sdk-js/releases/tag/v1.18.1) of the JS Speech SDK has been released with a fix for this issue. Thanks again for reporting it, and using Speech SDK.
