### ISSUE TITLE
Problems with transcribing audio with music or silent beginning

### ISSUE THREAD

**Issue by KarolScibior** [microsoft/cognitive-services-speech-sdk-js#409]
Hi again, I came across another problem while using this package. This time I have a problem when I try to transcribe songs (like [this](https://www.youtube.com/watch?v=S3ln5ojgYKc)) or audio with silence in the beginning (like [this](https://www.youtube.com/watch?v=Z9fNKV0EULg)).

I'm logging every possible event like this:

`

    recognizer.recognizing = (s, e) => {
      console.log(`RECOGNIZING: Text=${e.result.text}`)
    }

    recognizer.recognized = (s, e) => {
      if (e.result.reason === ResultReason.RecognizedSpeech) {
        console.log(`RECOGNIZED: Text=${e.result.text}`)
        const subs = generateSubtitles(e.result)
        results.push(...subs)
      } else if (e.result.reason === ResultReason.NoMatch) {
        console.log('NOMATCH: Speech could not be recognized.')
      } else {
        console.log('SOMETHING DIFFERENT', e.result)
      }
    }

    recognizer.canceled = (s, e) => {
      console.log(`CANCELED: Reason=${e.reason}`)
      if (e.reason === CancellationReason.Error) {
        console.log(`"CANCELED: ErrorCode=${e.errorCode}`)
        console.log(`"CANCELED: ErrorDetails=${e.errorDetails}`)
        console.log('CANCELED: Did you update the subscription info?')
        reject(
          new AppError('Transcription error', 400, 'APP.ERROR.TRANSCRIPTION')
        )
      }
      recognizer.stopContinuousRecognitionAsync()
    }

    recognizer.sessionStopped = (s, e) => {
      console.log('\n    Session stopped event.')
      recognizer.stopContinuousRecognitionAsync()
      resolve(results)
    }

    recognizer.speechEndDetected = (s, e) => {
      console.log('SPEECH START DETECTED', e)
    }

    recognizer.speechEndDetected = (s, e) => {
      console.log('SPEECH END DETECTED', e)
    }

    recognizer.startContinuousRecognitionAsync(
      () => {
        console.log('Continuous recognition begin')
      },
      err => {
        console.log('ERROR: ', err)
      }
    )
`

And all I'm getting is:

`
Continuous recognition begin
SPEECH END DETECTED RecognitionEventArgs {
  privSessionId: '5BACB9B068AF4C7F947D7021E021F8D5',
  privOffset: 151200000
}
`

Then nothing happens, no cancel or stopped event is triggered. Is there anything I might be missing? Some timeout that I'm not aware of? I couldn't find anything in the docs.

Thanks.

**Comment by glharper** [comment]
@KarolScibior You seem to be running into the initial silence timeout. This can be adjusted on the SpeechConfig object like so:
`speechConfig.setProperty(sdk.PropertyId[sdk.PropertyId.SpeechServiceConnection_InitialSilenceTimeoutMs], "TIMEOUT_IN_MS");`

Thanks for using SpeechSDK, and writing this question up!

**Comment by KarolScibior** [comment]
Thanks again for quick answer, that was exactly what I was looking for!
