### ISSUE TITLE
[1.18.0] Missing console.error in AudioConfig

### ISSUE THREAD

**Issue by dev-loic** [microsoft/cognitive-services-speech-sdk-js#411]
[Description]
When starting a transcription or translation with an `AudioConfig`, we got console errors which looks like debugging logs.
![image](https://user-images.githubusercontent.com/43581675/128134832-7ee38ef3-c677-4353-9875-0f2c34458a4d.png)

[Excepted behavior]
We should not have these logs as this is not an error

[Fix]
I already have the fix locally, how can I suggest it to you ?

**Comment by glharper** [comment]
@dev-loic Thanks for using SpeechSDK, and writing this up. Open a pull request with your fix, and I'll take a look.

**Comment by dev-loic** [comment]
Ok thanks, it's opened 👌🏻 https://github.com/microsoft/cognitive-services-speech-sdk-js/pull/413

**Comment by glharper** [comment]
Closing as fix is merged in. 1.18.1 should be released this week.

**Comment by glharper** [comment]
@dev-loic [Version 1.18.1](https://github.com/microsoft/cognitive-services-speech-sdk-js/releases/tag/v1.18.1) of the JS Speech SDK has been released, and includes your fix for this issue. Thanks again for reporting it, fixing it, and using Speech SDK.

**Comment by dev-loic** [comment]
Thanks a lot for the release and the follow up !
