### ISSUE TITLE
Cannot stop audio output from the default speaker

### ISSUE THREAD

**Issue by qhnu** [microsoft/cognitive-services-speech-sdk-js#415]
## version

Used in a browser

"microsoft-cognitiveservices-speech-sdk": "^1.18.0"

## code

- Specification as documented
(Unfortunately, there is sound)
```ts
const synthesizer = new Sdk.SpeechSynthesizer(this.speechConfig, undefined)
```

- Irregular Specifications
(No sound, desired behavior, but a type error occurs)
```ts
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
const synthesizer = new Sdk.SpeechSynthesizer(this.speechConfig, null)
```

Is it possible to disable output with `undefined`?
thanks!

**Comment by yulin-li** [comment]
Thanks for you suggestion. We will consider to change the behavior but this might a breaking change for others. We will track this work item internally. Closing this issue now.
