### ISSUE TITLE
Get telemetry data and input quality

### ISSUE THREAD

**Issue by robinmanuelthiel** [Microsoft/cognitive-services-speech-sdk-js#42]
In the Readme, you writing:

> We strongly recommend you keep telemetry enabled. With telemetry enabled you transmit information about your platform (operating system and possibly, Speech Service relevant information like **microphone characteristics**, etc.), and information about the performance of the Speech Service (the time when you did send data and when you received data). It can be used to tune the service, monitor service performance and stability, and might help us to analyze reported problems. Without telemetry enabled, it is not possible for us to do any form of detailed analysis in case of a support request.

Is there any chance, to receive that telemetry (especially the microphone characteristics) as a developer.

Throughout our development, we realized that there the Speech-To-Text output quality is obviously highly dependent on the microphone input quality. So we are planning to warn the user, once their microphone volume is too low or it starts clipping.

Is this something, the SDK could theoretically detect by itself?

**Comment by rhurey** [comment]
Currently we don't expose the information that's captured.

For a  microphone it will be the label provided by the MediaDeviceInfo (PR is out to capture it), and the bitstream information that was we requested.

Theoretically the SDK could detect clipping where the amount of audio that's actually be transmitted to the service is less than the bytes / second that should be flowing through. We don't do any analysis of the audio on the client.
