### ISSUE TITLE
OutputFormat.Detailed doesn't work when using ConversationTranscriber

### ISSUE THREAD

**Issue by matej-svejda** [microsoft/cognitive-services-speech-sdk-js#425]
I'm trying to transcribe conversations (mostly recordings of online meetings) with multiple participants and word level timestamps.

One of the issues I'm facing is that when I enable `speechConfig.requestWordLevelTimestamps()` and set `speechConfig.outputFormat = sdk.OutputFormat.Detailed` the transcription just hangs and I don't get any result. If I leave the `outputFormat` as is, then the transcription seems to work (but I don't get the word level timestamps).

Here is the code https://gist.github.com/matej-svejda/8238e370da2bed6c247aafcab88bf0d1 and here is the input audio as a zip file [sample_8.wav.zip](https://github.com/microsoft/cognitive-services-speech-sdk-js/files/7048074/sample_8.wav.zip).

Would be great if someone could look into this.

**Comment by glharper** [comment]
@matej-svejda [Speech SDK version 1.19.0 is available now](https://github.com/microsoft/cognitive-services-speech-sdk-js/releases/tag/v1.19.0), with a fix for this issue. Thanks again for reporting this!
