### ISSUE TITLE
NodeJS speechSynthesizer "window is not defined"

### ISSUE THREAD

**Issue by xoration** [microsoft/cognitive-services-speech-sdk-js#431]
I am trying to use the synthesize to speaker output with NodeJS via the example from the documentation.
(https://docs.microsoft.com/en-gb/azure/cognitive-services/speech-service/get-started-text-to-speech?tabs=import%2Cwindowsinstall&pivots=programming-language-javascript#synthesize-to-speaker-output)

Example code:

    import * as sdk from "microsoft-cognitiveservices-speech-sdk";

    const speechConfig = sdk.SpeechConfig.fromSubscription("xxxx", "xxxx");
    const audioConfig = sdk.AudioConfig.fromDefaultSpeakerOutput();

    const synthesizer = new sdk.SpeechSynthesizer(speechConfig, audioConfig);
    synthesizer.speakTextAsync(
        "Synthesizing directly to speaker output.",
        result => {
            if (result) {
                synthesizer.close();
                return result.audioData;
            }
        },
        error => {
            console.log(error);
            synthesizer.close();
        });

I would expect to get the speaker output but instead I am getting ReferenceError: window is not defined

    node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\sdk\Audio\SpeakerAudioDestination.js:149
    if (typeof (AudioContext) !== "undefined" || typeof (window.webkitAudioContext) !== "undefined") {
                                                                 ^
    ReferenceError: window is not defined

Version: 
"microsoft-cognitiveservices-speech-sdk": "^1.18.1"
node v16.8.0

**Comment by glharper** [comment]
@xoration Thanks for using Speech SDK, and writing this issue up. AudioConfig.fromDefaultSpeakerOutput is not supported for Node. Please use fromAudioFileOutput or fromStreamOutput. I will update the quickstart to note that fromDefaultSpeakerOutput is browser only.
