### ISSUE TITLE
STT correction seems to remove spaces between words sometimes

### ISSUE THREAD

**Issue by dev-loic** [microsoft/cognitive-services-speech-sdk-js#433]
### package.json
`"microsoft-cognitiveservices-speech-sdk": "^1.18.1",`

### package used
`microsoft/cognitive-services-speech-sdk-js`

### description
when getting result from the STT it happens that correction remove all the spaces between words 

https://user-images.githubusercontent.com/43581675/132484181-2a94378a-c519-47cd-88c7-f131c94c9ebd.mov

### issue
the word `brancheouiouinonouijesaisouaisjaijetaisafondsurletempsjouernonilfautquejelefinissetreizeetenfaitouaismemejustedun.de` does not exist in French, it missed all the spaces between words

### to reproduce
you can use this audio file 
[audio_file.zip](https://github.com/microsoft/cognitive-services-speech-sdk-js/files/7127677/audio_file.zip)

**Comment by glharper** [comment]
@dev-loic I was unaware JS SDK has opus support. When attempting to use that file for STT, I get "ERROR: Error: Error occurred while processing '2c167875-1086-11ec-a1ac-77ad607d2dca.opus'. 2c167875-1086-11ec-a1ac-77ad607d2dca.opus is not supported. Only WAVE files are allowed at the moment."

**Comment by dev-loic** [comment]
my bad. we use opus as an output format but never gives it directly to the stt. Here is the same file but in WAV 
[audio_file.zip](https://github.com/microsoft/cognitive-services-speech-sdk-js/files/7130891/audio_file.zip)

**Comment by glharper** [comment]
@dev-loic It looks like this is a service issue where "un point de" is incorrectly converting what comes before to a German domain name (like the English "something something dot com"), but "un point de" is a common figure of speech in French. The service team is now aware of this behavior, and is looking into a fix. I'll update when this has been corrected. Thanks for using Speech SDK, and writing this issue up.

**Comment by dev-loic** [comment]
Thanks a lot for your action and your quick answers, always a pleasure. Have a nice day 👋🏻

**Comment by glharper** [comment]
@dev-loic Retesting this, the issue appears to have been corrected. Thanks again for writing this up, and using Speech SDK.
