### ISSUE TITLE
Text-to-Speech not heard on IOS when triggered from setTimeOut

### ISSUE THREAD

**Issue by martinberit** [microsoft/cognitive-services-speech-sdk-js#436]
Having a test-button fire this TS test-function below only the first text "Velkommen til" is heard on iPad/iPhone. On Android and in a PC browser the last text ("NaviPuma") is indeed heard after 3 seconds.  Using 1.18.1

Any ideas why?

BR Martin Hagerup, Copenhagen

 
 test() {
    this.speakAzure("Velkommen til")
    let t = setTimeout(() => {
      this.speakAzure("NaviPuma");

    }, 3000);
  }

 speakAzure(text: string) {
    const audioConfig = sdk.AudioConfig.fromDefaultSpeakerOutput();
    const speechConfig = sdk.SpeechConfig.fromSubscription("*****", "westeurope");
    speechConfig.speechSynthesisVoiceName = "Microsoft Server Speech Text to Speech Voice (da-DK, ChristelNeural)";
    speechConfig.speechSynthesisLanguage = "da-DK";
    let synthesizer = new sdk.SpeechSynthesizer(speechConfig, audioConfig);
    synthesizer.speakTextAsync(
      text,
      result => {
        if (result) {
          synthesizer.close();
          synthesizer = undefined

          return result.audioData;
        }
      },
      error => {
        console.log(error);
        synthesizer.close();
        synthesizer = undefined
      });
  }

**Comment by glharper** [comment]
@martinberit This is a specific Chrome iOS/iPad issue with autoplay, from my testing. All other mobile/desktop browsers should work. When playing the second time, the play() call in JS SDK throws "NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission."

The documentation seems to indicate that, because the second play() call is not accompanied by a user action giving permission to play that audio, the audio playback is blocked. In theory, that second playback should be blocked on all browsers if autoplay is turned off, but I'm guessing the reason only iOS Chrome blocks it is because iOS Chrome doesn't have site-specific autoplay settings, and just sets autoplay to "allow if play is tied to a user action" everywhere.

**Comment by martinberit** [comment]
Thanks for your reply. I had a suspicion it was related to IOS user-action requirement and I have tried without success to fake a user action prior to a call to speakAzure.  Any suggestions are welcome.

 The ResponsiveVoice.org ( a Text-To-Speech competitor) has solved it somehow and have no blocked speeches on Chrome/iOS, but I rather stay with Azure.

**Comment by glharper** [comment]
@martinberit This code works for me:
```

    const speakAzure = async (text, secondText, timer) => {
        let key = document.getElementById("subskey").value;
        let region = document.getElementById("region").value;
        
        const speechConfig = SpeechSDK.SpeechConfig.fromSubscription(key, region);
 
        speechConfig.speechSynthesisVoiceName = "Microsoft Server Speech Text to Speech Voice (da-DK, ChristelNeural)";
        speechConfig.speechSynthesisLanguage = "da-DK";
      
        const audioConfig = SpeechSDK.AudioConfig.fromDefaultSpeakerOutput();

        let synthesizer = new SpeechSDK.SpeechSynthesizer(speechConfig, audioConfig);
        synthesizer.speakTextAsync(
          text,
          result => {
          if (result) {
                setTimeout(() => {
                  synthesizer.speakTextAsync(secondText);
                }, timer);
                return result.audioData;
              }
            },
            error => {
              console.log(error);
              synthesizer.close();
              synthesizer = undefined
              return null;
            });
    };
    
    startVel.onclick = async () => {
       await speakAzure("Velkommen til", "NaviPuma", 3000);  
    };
```

**Comment by martinberit** [comment]
Thanks for struggling. I tried your example and it works, but your approach is recursive and that doesnt solve the general problem that I perhaps should have elaborated on before.
Building a passive navigation wepapp we need to have the app running and react to the positions of the car. Coming near a turning position the app should speak. So the speak needs to come *without* any user interaction. The setTimeout was to trigger/simulate an non-user event.

Anyway - we managed to solve it anyhow using AudioContexts. In IOS we still need a "Welcome"-button do initiate the init() function below, but hereafter you can have anything trigger  the test()-function - a button or an async event.  Tested somewhat on Safari and Chrome on iPad and iPhone.

So - we consider the case closed and thanks again for your input.

BR Martin Hagerup, Copenhagen


The TypeScript code is:

import { Component } from '@angular/core';
import * as sdk from 'microsoft-cognitiveservices-speech-sdk'

var context 
var buffer
var source

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})



export class AppComponent {


  init(){
    context = new ((<any>window).AudioContext || (<any>window).webkitAudioContext)();
    buffer = context.createBuffer(1, 1, 22050);
    source = context.createBufferSource();
    source.buffer = buffer;
    source.connect(context.destination);
  }

  test(){
  this.speakAzure("Velkommen til")
  let t = setTimeout(() => {
    this.speakAzure("NaviPuma");
  }, 3000);
  }
   
  speakAzure(text: string) {
    const stream = sdk.AudioOutputStream.createPullStream();
    const audioConfig = sdk.AudioConfig.fromStreamOutput(stream);    // 
    const speechConfig = sdk.SpeechConfig.fromSubscription("*******", "westeurope");
    speechConfig.speechSynthesisVoiceName = "Microsoft Server Speech Text to Speech Voice (da-DK, ChristelNeural)";
    speechConfig.speechSynthesisLanguage = "da-DK";
    let synthesizer = new sdk.SpeechSynthesizer(speechConfig, audioConfig);
    synthesizer.speakTextAsync(
      text,
      result => {
        if (result) {
          synthesizer.close();
          context.decodeAudioData(result.audioData, function (buffer) {
            var buf = buffer;
            var source = context.createBufferSource();
            source.buffer = buf
            source.connect(context.destination);
            source.start(0)
          })
          context.resume()
        }
      },
      error => {
        console.log(error);
        synthesizer.close();
        synthesizer = undefined
      });
  }
 }
