### ISSUE TITLE
Continuous recognition suddenly stops without throwing any errors

### ISSUE THREAD

**Issue by KarolScibior** [microsoft/cognitive-services-speech-sdk-js#442]
Hello again, I've been using this sdk for some time and it works really well, but recently I came across weird case, when during continuous recognition it suddenly stops without throwing any errors or firing any particular event. My code:

`recognizer.recognizing = (s, e) => {
      console.log(`RECOGNIZING: Text=${e.result.text}`)
    }

    recognizer.recognized = (s, e) => {
      if (e.result.reason === ResultReason.RecognizedSpeech) {
        console.log(`RECOGNIZED: Text=${e.result.text}`)
        const subs = generateSubtitles(e.result, settings)
        results.push(...subs)
      } else if (e.result.reason === ResultReason.NoMatch) {
        console.log('NOMATCH: Speech could not be recognized.')
      } else {
        console.log('SOMETHING DIFFERENT', e.result)
      }
    }

    recognizer.canceled = (s, e) => {
      console.log(`CANCELED: Reason=${e.reason}`)
      if (e.reason === CancellationReason.Error) {
        console.log(`"CANCELED: ErrorCode=${e.errorCode}`)
        console.log(`"CANCELED: ErrorDetails=${e.errorDetails}`)
        console.log('CANCELED: Did you update the subscription info?')
        reject(
          new AppError('Transcription error', 400, 'APP.ERROR.TRANSCRIPTION')
        )
      }
    }

    recognizer.sessionStopped = (s, e) => {
      console.log('\n    Session stopped event.')
      recognizer.stopContinuousRecognitionAsync()
      resolve(results)
    }

    recognizer.speechStartDetected = (s, e) => {
      console.log('SPEECH START DETECTED', e)
    }

    recognizer.speechEndDetected = (s, e) => {
      console.log('SPEECH END DETECTED', e)
    }

    recognizer.startContinuousRecognitionAsync(
      () => {
        console.log('Continuous recognition begin')
      },
      err => {
        console.log('ERROR: ', err)
      }
    )`
    
Last thing I see is ordinary `RECOGNIZING: Text=może` and it stops recognizing. 
    
For reference, audio I'm trying to recognize is this: https://api.tipscribe.akanza.dev/audio/c72bd26bb6361bfd31f83e4d1078dad0.wav

**Comment by glharper** [comment]
@KarolScibior Thanks for using Speech SDK and writing this issue up. How are you setting up the SpeechRecognizer? I'm guessing the recognition language isn't "en-us"?

**Comment by KarolScibior** [comment]
@glharper This is my speechConfig and speechRecognizer setup:

`const speechConfig = sdk.SpeechConfig.fromSubscription(sttKey, sttRegion)
  speechConfig.requestWordLevelTimestamps()
  speechConfig.enableDictation()
  speechConfig.speechRecognitionLanguage = lang || 'pl-PL'
  speechConfig.outputFormat = 1
  speechConfig.setProperty(
    sdk.PropertyId[
      sdk.PropertyId.SpeechServiceConnection_InitialSilenceTimeoutMs
    ],
    '600000'
  )
  speechConfig.setProperty(
    sdk.PropertyId[sdk.PropertyId.SpeechServiceConnection_EndSilenceTimeoutMs],
    '600000'
  )

  const audioConfig = sdk.AudioConfig.fromWavFileInput(file)

  const recognizer = new sdk.SpeechRecognizer(speechConfig, audioConfig)`
  
  And yeah, recognition language is pl-PL in this case.

**Comment by KarolScibior** [comment]
When can we expect new release? 😅

**Comment by glharper** [comment]
@KarolScibior Oct. 22nd at the earliest, Nov. 2nd at the latest.

**Comment by glharper** [comment]
@KarolScibior [Speech SDK version 1.19.0](https://github.com/microsoft/cognitive-services-speech-sdk-js/releases/tag/v1.19.0) is available now, with a fix for this issue. Thanks again for reporting it!
