### ISSUE TITLE
DifferentiateGuestSpeakers is not working.

### ISSUE THREAD

**Issue by yoshinorihisakawa** [microsoft/cognitive-services-speech-sdk-js#448]
We implemented real-time Japanese transcription using javascript sdk in East Asia region.

Even if I set DifferentiateGuestSpeakers to true, the speakerId in the response is always undefine.

![スクリーンショット 2021-10-25 15 48 52](https://user-images.githubusercontent.com/39504693/138647886-92304b9e-c173-421f-abb8-3cc1ae373295.png)

**Comment by yoshinorihisakawa** [comment]
It still does not work correctly.

The code I'm writing is in javascript.
It is also written in https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/javascript/browser/translate-speech-to- text/index.html for reference.

I tried DifferenciateGuestSpeakers but it didn't work because it was still being used incorrectly spelled here: https://aka.ms/csspeech/jsbrowserpackageraw.

I created a speechConfig in ↓.

```
      function getSpeechConfig(sdkConfigType) {
        var speechConfig = sdkConfigType.fromSubscription(
          azureSubscriptionId,
          "eastasia")
        );
        speechConfig.outputFormat = SpeechSDK.OutputFormat.Detailed;
        speechConfig.speechRecognitionLanguage = "ja-JP";
        speechConfig.requestWordLevelTimestamps();
        speechConfig.setProperty("DifferenciateGuestSpeakers", "true")
        return speechConfig;
      }
```


Translated with www.DeepL.com/Translator (free version)

**Comment by glharper** [comment]
@yoshinorihisakawa That field is meant to be set for Conversation-related scenarios, with [this class](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/sdk/Transcription/Conversation.ts) What documentation are you seeing where DifferentiateGuestSpeakers is used in conjunction with speech translation?

**Comment by josephsctan** [comment]
Is there a field that can be set for normal speech recognition (recognizer.startContinuousRecognitionAsync()) which will return speakerId ?

**Comment by glharper** [comment]
@josephsctan There is not. speakerId is meant to be used with conversation transcription.

**Comment by josephsctan** [comment]
would be handy, since during real time speech to text, more than one person can be talking

**Comment by glharper** [comment]
@josephsctan For that scenario, please use conversation transcription, detailed (here)[https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-conversation-transcription?pivots=programming-language-javascript]

**Comment by josephsctan** [comment]
That requires a 7-mic circular multi-microphone array??  Infeasible. 

What I'm having to do now is recognize speech for real time analysis, record it to storage and send it for batch transcription afterwards, just to get the speaker id.  This is transcribing stuff twice, which is twice the cost.  

If the technology to do real time speaker diarization is already there, why not make it available  in the real time API?

**Comment by glharper** [comment]
@josephsctan If you wouldn't mind dropping me an e-mail at <my_github_username>(at)microsoft(dot)com, I can follow up with you about this privately.

**Comment by jashpal2003** [comment]
I noticed that Speaker Recognition is scheduled for retirement in September. Are there any alternative services or recommended workarounds for identifying speakers in an audio file? I couldn't find any mention of a replacement in the documentation.

Additionally, the documentation states:
'This change doesn't affect other Azure AI Speech capabilities such as [Speech to Text], and [Speech Translation].

I'm currently using Speech to Text—will this feature continue to work as expected, or will it be impacted by the retirement of Speaker Recognition?
