### ISSUE TITLE
Support different coders for input audio stream

### ISSUE THREAD

**Issue by orgads** [microsoft/cognitive-services-speech-sdk-js#452]
`sdk.AudioInputStream.createPushStream()` has an optional argument `format?: AudioStreamFormat`.

But `AudioStreamFormat` (in its public form) only supports PCM, with `getWaveFormatPCM`.

If we want to use other coders, we have to import `AudioStreamFormatImpl` and `AudioFormatTag`, which are not exported in `sdk`, and instantiate it.

Please create a public API for using different coders.

Thanks.

**Comment by orgads** [comment]
See https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/351#issuecomment-955708526 for an example by @yoshigev how he worked around it.

**Comment by glharper** [comment]
@orgads @yoshigev One note on this new API (slated for v1.20, mid-to-late January), this is specifically targeted to unblock Mulaw and Alaw file recognition. All non-WAV transmission is untested currently using getWaveFormat.

**Comment by dargilco** [comment]
From the [1.20 release notes](https://docs.microsoft.com/azure/cognitive-services/speech-service/releasenotes?tabs=speech-sdk):
JavaScript: Added getWaveFormat() API to AudioStreamFormat to support non-PCM wave formats (GitHub issue 452)

**Comment by orgads** [comment]
Thank you.
