### ISSUE TITLE
SpeechRecognizer @ Safari <v14.1 - Error: Unable to start audio worklet node for PCMRecorder

### ISSUE THREAD

**Issue by amer8** [microsoft/cognitive-services-speech-sdk-js#455]
The PCM recorder doesn't create a ScriptProcessor on Safari versions lower than v14.1. Those versions have missing support for AudioWorklet.

Related to:
- https://caniuse.com/?search=audioworklet
- https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/437
- https://github.com/microsoft/cognitive-services-speech-sdk-js/pull/397
- https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/24d787db5b771cbc20ad33c2949cba24ae394102/src/common.browser/PCMRecorder.ts#L46

Either the if/else needs to be rewritten or AudioWorklet needs to be ponyfilled (to run into .catch()) in case it evaluates to undefined.

**Comment by novelja** [comment]
We're also stuck on this. Got it working for all iOS > 14.1 devices, but no luck with making it work with lower versions. Also had no luck finding a good workaround.

**Comment by glharper** [comment]
@novelja The current workaround would be to use version [1.17](https://github.com/microsoft/cognitive-services-speech-sdk-js/releases/tag/v1.17.0) if legacy Safari support is required.

**Comment by SMaurischat** [comment]
@glharper works fine, would be cool to release this in a version in a timely manner, we are also experiencing issues in the product until this is tagged on npm

**Comment by dargilco** [comment]
From the [1.20 release notes](https://docs.microsoft.com/azure/cognitive-services/speech-service/releasenotes?tabs=speech-sdk):
JavaScript: Use script processor fallback for microphone input if no audio worklet is found (GitHub issue 455)
