### ISSUE TITLE
setting OutputFormat.Detailed and requestWordLevelTimestamps in SpeechTranslationConfig is ignored

### ISSUE THREAD

**Issue by armandogmendoza** [microsoft/cognitive-services-speech-sdk-js#459]
I was trying to use TranslationRecognizer as a replacement for SpeechRecognizer as I wanted to obtain the same captions in multiple languages, the captions are delivered correctly,
but I wanted to retrieve the detailed json with word level timestamps per language, is this possible?
According to the current interfaces this seems possible but it does not seem to work.
Thanks.

**Comment by dargilco** [comment]
Hi @armandogmendoza, this is Darren from the Speech SDK team. Can you share snippet of your code showing what you tried to do? Were you able to get word-level timing for the recognition result of the spoken language? I understand you are asking about word-level timing for both the recognition results and its translations to other languages. Only the recognized text from the spoken language has word-level timing. The other languages are a result of text translation, so there is no timing information into the original audio.

**Comment by armandogmendoza** [comment]
Hello @dargilco, 
makes sense now that you say it that the translations won't have word level timings, it is just that the way the API is defined seems to imply that I could configure a TranslationRecognizer like:

     ```
 const speechConfig = sdk.SpeechTranslationConfig.fromSubscription(...)
      speechConfig.speechRecognitionLanguage = language
      outputLanguages.forEach(lang => {
        speechConfig.addTargetLanguage(lang);
      });
      speechConfig.setProfanity(sdk.ProfanityOption.Masked)
      speechConfig.requestWordLevelTimestamps()
      speechConfig.outputFormat = OutputFormat.Detailed
      const recognizer = new sdk.TranslationRecognizer(speechConfig, audioConfig);

```

perhaps it should be made more explicit that those settings won't make any difference in the output,
now looking at this code snipped I wonder if profanity settings will pass into the translations as well.

Thanks!
