### ISSUE TITLE
handle websocket connection errors

### ISSUE THREAD

**Issue by calinalexandru** [microsoft/cognitive-services-speech-sdk-js#462]
Every 10-15 working requests are accompanied by a Websocket connection error. 
<img width="1074" alt="Screenshot 2021-12-21 at 11 36 49" src="https://user-images.githubusercontent.com/14873239/146908484-4485a95f-d92d-434f-9da0-388c670b7c35.png">

When this is happening, `SpeechSynthesizer.speakSsmlAsync` does not invoke the callback error and I'm unable to resume activity in my app.

This is the code I'm using:

```
const synth = new sdk.SpeakerAudioDestination();
const speechConfig = sdk.SpeechConfig.fromSubscription(
	KEY,
	SERVICE_REGION
);
speechConfig.speechSynthesisVoiceName = 'en-US-AriaNeural'
const audioConfig = sdk.AudioConfig.fromSpeakerOutput(synth);
const msg = new sdk.SpeechSynthesizer(speechConfig, audioConfig);

const ssmlText = "<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xml:lang="en-US"><voice name="en-US-AriaNeural"><prosody rate="+60.00%" volume="10" pitch="+0.00st">Hello</prosody></voice></speak>"
msg.speakSsmlAsync(
	ssmlText,
	(result) => {
		if (result) {
			console.log('yey', result);
			msg.close();
			return result.audioData;
		}
		return false;
	},
	(error) => {
		console.error('nope', error);
		msg.close();
	}
);
```

----
After posting this I found [https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/node/synthesis.js](url) which shows the definition for error handling as canceled events
using `SpeechSynthesizer.SynthesisCanceled `

Adapting my code now I get the following two errors:
`(cancel) Reason: Error: Unable to contact server. StatusCode: 1006, undefined Reason:  undefined`
and very rarely:
`(cancel) Reason: Error: Throttled due to too many requests websocket error code: 1007`

I'm requesting one word every second, is that considered too many requests? (FREE tier plan)

**Comment by glharper** [comment]
@calinalexandru Thanks for using Speech SDK, and writing this issue up. Testing this locally, I can reproduce this with a free (F0) key, but not with a standard (S0) key. You're hitting the rate limit. Try slowing to one word every 2 or 3 seconds, or switching to a standard key.

**Comment by unverdi** [comment]
speechConfig.speechSynthesisVoiceName = "en-US-JennyNeural";
