### ISSUE TITLE
JS Azure Speech SDK Text to Speech (control volume for AudioConfig)

### ISSUE THREAD

**Issue by vinothkumar1097** [microsoft/cognitive-services-speech-sdk-js#463]
Hi Team,

I'm working with azure text to speech service for enabling voice based outputs. Using [Speech SDK Javascript](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-text-to-speech?tabs=script%2Cwindowsinstall&pivots=programming-language-browserjs).

For outputing the sound, im creating **fromSpeakerOutput** instance with custom iPlayer (as in [docs](https://docs.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/audioconfig?view=azure-node-latest#fromSpeakerOutput_IPlayer_)).

```
const browserSound = new speechsdk.SpeakerAudioDestination();
const audioConfig = speechsdk.AudioConfig.fromSpeakerOutput(browserSound);
var synthesizer = new speechsdk.SpeechSynthesizer(speechConfig, audioConfig);
```

Issue is, i need some iPlayer customizations like **volume control, stop current sound**. I could see only pause and resume. Is there any way I could achieve this ?

Thanks.

**Comment by glharper** [comment]
@vinothkumar1097 Thanks for using Speech SDK, and writing this issue up. Currently, the SpeakerAudioDestination does not expose the volume setting for the underlying HTMLAudioElement, but that can be added in the next version relatively easily. 

What exactly do you mean by "stop current sound"? Can you not pause() and just not resume?

**Comment by glharper** [comment]
@vinothkumar1097 I've checked in code that allows volume control and mute/unmute for SpeakerAudioDestination. These new APIs will be in the next release, due at the end of the month. Thanks again for using Speech SDK. :-)

**Comment by dargilco** [comment]
From the [1.20 release notes](https://docs.microsoft.com/azure/cognitive-services/speech-service/releasenotes?tabs=speech-sdk):
JavaScript: Added volume getter/setter and mute()/unmute() APIs to SpeakerAudioDestination (GitHub issue 463)
