### ISSUE TITLE
Significant delay when activating language recognition

### ISSUE THREAD

**Issue by orgads** [microsoft/cognitive-services-speech-sdk-js#469]
Hi,

When we activate language detection we notice a 3.5s delay between `sessionStarted` and `speechStartDetected`.

Without language detection, the delay is roughly 1s.

The delay origin seems to be in the backend. The SDK sends the media packets immediately.

See [Test project](https://github.com/microsoft/cognitive-services-speech-sdk-js/files/7862223/detect-lang-reaction-time.zip) and logs [with](https://github.com/microsoft/cognitive-services-speech-sdk-js/files/7862225/detect.log) and [without](https://github.com/microsoft/cognitive-services-speech-sdk-js/files/7862226/no-detect.log) detect.

I'm not sure if it should be reported here or somewhere else.

cc @yoshigev @ArielMannes

**Comment by glharper** [comment]
@orgads I've contacted the service team and will follow up here when I hear back.

**Comment by orgads** [comment]
We tried both Once and Continuous. Both worked, but we experienced the same delay for both (that's the second boolean in the function attached).

**Comment by glharper** [comment]
@orgads 
When you write "Once and Continuous", you're referring to the speech recognition mode, correct? 

Language ID, a feature of recognition, has multiple modes, two of which are "Single-shot" and "Continuous" (not connected to the speech recognition mode). JS SDK only supports Single-shot, and Single-shot always has a 2.5-3s delay (for both speech recognition modes).

JS SDK does not support Continuous mode for Language ID (but C#/C++/Python SDKs do support Continuous mode for LID). Continuous mode for LID does not have as long of a delay when recognition starts.

Does that make sense?

**Comment by orgads** [comment]
Ok, thank you.
