### ISSUE TITLE
Recently added voice `ar-SY-AmanyNeural` returns `Unsupported voice` error

### ISSUE THREAD

**Issue by HazemAM** [microsoft/cognitive-services-speech-sdk-js#470]
Requests using the recently added voice `ar-SY-AmanyNeural` always return an error with the following value for `privErrorDetails`:

```
Unsupported voice ar-SY-AmanyNeural. websocket error code: 1007
```

That happens when using this SDK, but I was also able to reproduce it on Microsoft’s official demo page:

- **URL:** https://azure.microsoft.com/en-us/services/cognitive-services/text-to-speech
- **Language:** Arabic (Syria)
- **Voice:** Amany (Neural)

**Comment by glharper** [comment]
@HazemAM Thank you for using Speech SDK, and writing this issue up. I will pass this on to the service team and follow up here.

**Comment by glharper** [comment]
@HazemAM This should be fixed by next Sunday. Thanks again for letting us know.

**Comment by wgwangang** [comment]
@HazemAM could you try again, please? The issue was fixed.

**Comment by glharper** [comment]
Closing this, as the voice is now available on the test page.

**Comment by HazemAM** [comment]
@wgwangang @glharper I can confirm the voice now works through the SDK. Thanks!
