### ISSUE TITLE
Unable to contact server. StatusCode: 1006, undefined Reason:  Unexpected server response: 401

### ISSUE THREAD

**Issue by isabirahmed** [microsoft/cognitive-services-speech-sdk-js#471]
Trying to use SpeechSynthesizer

`synthesizer.speakSsmlAsync`

Sometimes if there are a lot of requests one after the other some fail with a 401 response.

```
{
  privResultId: '37A4E15CF82F4D438ACB97BBC801B6B8',
  privReason: 1,
  privAudioData: undefined,
  privErrorDetails: 'Unable to contact server. StatusCode: 1006, undefined Reason:  Unexpected server response: 401',
  privProperties: PropertyCollection {
    privKeys: [ 'CancellationErrorCode' ],
    privValues: [ 'ConnectionFailure' ]
  }
}

```

Also getting the below error a few times.

```
{
  privResultId: '24D1AF99807548B2B4012D48093D1400',
  privReason: 1,
  privAudioData: undefined,
  privErrorDetails: 'Throttled due to too many requests websocket error code: 1007',
  privProperties: PropertyCollection {
    privKeys: [ 'CancellationErrorCode' ],
    privValues: [ 'BadRequestParameters' ]
  }
}
```

I'm just sending 20-30 requests at a given instance. Not sure why the API is not able to handle such a small number.

Also, note the region is eastus and the subscription key has been changed recently.
Version: 1.19.0

Is there a solution or workaround for this?

**Comment by glharper** [comment]
@isabirahmed Please see my response to [this issue](https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/462). For free keys there's a rate limit that even 20-30 requests can hit, if done quickly enough.

**Comment by isabirahmed** [comment]
@glharper : 
Thanks so much for the reply, yeah I came across the quota documentation, changed the tier from free to paid and helped instantly. But even here if the requests are more than 50 per second it throws errors.
Wish Azure throttles it from their end with some leaky bucket logic instead of throwing error messages and making it complicated for devs to handle.
Cause Google and AWS does this from their end.

Will batch the requests, but again it gets tricky to handle if there are more than x users simultaneously trying to use the API. So need to add a lot of logic to handle this. Thinking of having 3-4 resources so I can add a round-robin logic with multiple keys. 

Hopefully Azure adds this feature to throttle it from their end.
Users won't mind their requests taking longer time rather than them being rejected.
