### ISSUE TITLE
synthesizer.speakTextAsync passing and not synthesis the text

### ISSUE THREAD

**Issue by XDavidT** [microsoft/cognitive-services-speech-sdk-js#474]
I've created a small sandbox, and after everything was worked, I merged it into my code. In debug I get all the way to the line of `synthesizer.speakTextAsync(` and then it's pass out the function.
Here is the function that creates the voice to 'wav' file:
variables I get into the function:

> textToSpeech="זוהי בדיקה"
> fileName="132214f039745a42405b158ba2231648d915867e.wav"
> langCode="he-IL"
> voiceCode="he-IL-AvriNeural"
> azureConf.speechRegion="francecentral"
> azureConf.speechKey=<valid-key>

```
async function synthesizeSpeech(textToSpeech,fileName,langCode,voiceCode) {
    const speechConfig = sdkSpeech.SpeechConfig.fromSubscription(azureConf.speechKey, azureConf.speechRegion)
    const audioConfig = sdkSpeech.AudioConfig.fromAudioFileOutput(fileName)
    speechConfig.speechSynthesisLanguage = langCode
    speechConfig.speechSynthesisVoiceName = voiceCode

    const synthesizer = new sdkSpeech.SpeechSynthesizer(speechConfig, audioConfig)
    synthesizer.speakTextAsync(
        textToSpeech,
        result => {
            synthesizer.close()
            if (result) {
                return fileName
            }
            else if(result.errorDetails){
                console.error(result.errorDetails)
            }
        },
        error => {
            console.error(error)
            synthesizer.close()
        });
}
```
and I'm calling this function  using await:
`        await synthesizeSpeech(textToSpeech,fileName,text.languageCode,text.voiceCode)`

What can possibly go wrong? and if so, why it's not throwing an error?
Is there any file name limitation? text limitation?

**Comment by glharper** [comment]
@XDavidT Thank you for using Speech SDK, and writing this issue up. In your code, the "result" var in the callback for speakTextAsync will never be null or undefined, even if an error has occurred. Please use this callback code:
```
   result => {
      if (result.reason === sdkSpeech.ResultReason.SynthesizingAudioCompleted) {
        console.log("synthesis finished.");
        return filename;
      } else {
        console.error("Speech synthesis canceled, " + result.errorDetails);
      }
      synthesizer.close();
   }
```

**Comment by XDavidT** [comment]
Thx for the quick answer, but seem your answer is important to stable usage, but it's not solving the issue, my synthesizer isn't starting. I get 'wav' file with zero bytes.
The `synthesizer.speakTextAsync` just skips and breaks out the function.
I got a [short video](shorturl.at/eoqE2), not sure how helpful it can be

**Comment by glharper** [comment]
@XDavidT Got a working wav file by removing the "return filename" line. Does removing that line work for you as well?

**Comment by XDavidT** [comment]
Nope, it's still break in the same line. Here is my current code:
```
    synthesizer.speakTextAsync(
        textToSpeech,
        result => {
            if (result.reason === sdkSpeech.ResultReason.SynthesizingAudioCompleted) {
                console.log("synthesis finished.");
            } else {
                console.error("Speech synthesis canceled, " + result.errorDetails);
            }
            synthesizer.close();
        },
        error => {
            console.error(error)
            synthesizer.close()
        });
```

**Comment by glharper** [comment]
@XDavidT Are you running on node? I'm attaching the JS file I got working. Let me know your results with this after adding your own key/region. (Mine worked on westus and francecentral.)
[node_tts_speak_to_file_474.zip](https://github.com/microsoft/cognitive-services-speech-sdk-js/files/7936529/node_tts_speak_to_file_474.zip)

**Comment by XDavidT** [comment]
> @XDavidT Are you running on node? I'm attaching the JS file I got working. Let me know your results with this after adding your own key/region. (Mine worked on westus and francecentral.) [node_tts_speak_to_file_474.zip](https://github.com/microsoft/cognitive-services-speech-sdk-js/files/7936529/node_tts_speak_to_file_474.zip)

As mention before, copy the same demo is working for me in separate project, but when using this code as part of my project and call the function, gives empty file (0 bytes). That's why I didn't marked it as question

**Comment by glharper** [comment]
@XDavidT Did you figure out the issue here? If the demo was working, but the integration with your app was not, then something in the integration is interfering with the file output from our library. One possibility is that some other part of the code is accessing the file (and locking it), preventing our library from writing to it.

**Comment by XDavidT** [comment]
@glharper yes - by covering it with Promise.
