### ISSUE TITLE
not receiving speechEndDetected

### ISSUE THREAD

**Issue by davehorton** [microsoft/cognitive-services-speech-sdk-js#475]
I am creating a SpeechRecognizer and attaching handlers for speechStartDetected and speechEndDetected, then calling startContinuousRecognitionAsync.  My speechStartDetected handler is called, but the speechEndDetected is never called.

Additionally, I am getting final transcripts in my "recognized" handler, but my "recognizing" handler that should receive interim transcriptions is never called.  I am using version 1.19.0.

I am creating my recognizer like this
```
   const sdk = require('microsoft-cognitiveservices-speech-sdk');

    this.speechConfig = sdk.SpeechConfig.fromSubscription(
      process.env.MICROSOFT_SUBSCRIPTION_KEY,
      process.env.MICROSOFT_REGION
    );
    this.speechConfig.outputFormat = sdk.OutputFormat.Detailed;
    const format = sdk.AudioStreamFormat.getWaveFormatPCM(8000, 16, 1);
    this.pushStream = sdk.AudioInputStream.createPushStream(format);
    const audioConfig = sdk.AudioConfig.fromStreamInput(this.pushStream);
    this.recognizer = new sdk.SpeechRecognizer(this.speechConfig, audioConfig);
```

I am attaching the start and end of speech handlers like this
```
    this.recognizer.speechStartDetected = (s, args) => {
      this.logger.info({args}, 'Recognizer: start of speech detected');
      this.emit('startUtterance');
    }
    this.recognizer.speechEndDetected = (s, args) => {
      this.logger.info({args}, 'Recognizer: end of speech detected');
      this.emit('endUtterance');
    }
```
And I am starting recognition like this:
```
    this.speechConfig.speechRecognitionLanguage = 'en-US';
    this.recognizer.startContinuousRecognitionAsync(() => { ... });
```

Any thoughts on why I would not be receiving end of speech events (or interim transcripts)?

**Comment by dargilco** [comment]
Hi @davehorton, this is Darren from the Speech SDK team. To make sure I understand, you are saying the recognition results you get from "recognized" event are accurate? Also, can you confirm your audio is 8khz sample rate per the settings I see in your code? How long is your sentence? (can you give me an example, or attach an audio WAV file). Note that version 1.20 is out, so please update if possible.
Darren

**Comment by davehorton** [comment]
yes, the recognized results are accurate.  And the sample rate is 8khz.  I am just speaking a long-ish single sentence, so I will try with some thing longer perhaps, and will update to 1.20 and test there.  Will post results here

**Comment by glharper** [comment]
@davehorton Was this issue mitigated on your end? If so, could you share what fixed it?
