### ISSUE TITLE
help: package broken with vite

### ISSUE THREAD

**Issue by souzaramon** [microsoft/cognitive-services-speech-sdk-js#477]
Hello,

when running a react app with vite this package just explodes itself with the follow error

```
index.js:22 Uncaught TypeError: heimdall.hasMonitor is not a function
    at ../../node_modules/async-disk-cache/index.js (index.js:22:15)
    at __require2 (chunk-YKO6EBPH.js?v=f67a1cef:45:44)
    at CertChecks.ts:32:19
```

Ehhh, I'll be very happy with any help

**Comment by glharper** [comment]
@souzaramon Thanks for using Speech SDK, and writing this issue up. Which version of our library are pulling, that repros this? I found [this issue](https://github.com/stefanpenner/async-disk-cache/issues/58) in async-disk-cache, but I believe the v0.2.6 of heimdalljs that is pulled in our build (looking at the package-lock.json) is the latest version, and exposes hasMonitor as a function (based on [this code](https://github.com/heimdalljs/heimdalljs/blob/62b9eb2d1e14ce0d5da1fd9dd3ba7fb1509f022c/packages/heimdalljs/src/heimdall.js#L94)).

Could you look through your package-lock.json and see which version of heimdalljs got pulled for you?

**Comment by souzaramon** [comment]
Sure,

I found this in the lock file.

async-disk-cache@^2.1.0:
  version "2.1.0"
  resolved "https://registry.yarnpkg.com/async-disk-cache/-/async-disk-cache-2.1.0.tgz#e0f37b187ed8c41a5991518a9556d206ae2843a2"
  integrity sha512-iH+boep2xivfD9wMaZWkywYIURSmsL96d6MoqrC94BnGSvXE4Quf8hnJiHGFYhw/nLeIa1XyRaf4vvcvkwAefg==
  dependencies:
    debug "^4.1.1"
    heimdalljs "^0.2.3"
    istextorbinary "^2.5.1"
    mkdirp "^0.5.0"
    rimraf "^3.0.0"
    rsvp "^4.8.5"
    username-sync "^1.0.2"

**Comment by souzaramon** [comment]
And for anyone looking for a temp solution:

add this on top of the component, and use the global window.SpeechSDK instance.

```ts
import "microsoft-cognitiveservices-speech-sdk/distrib/browser/microsoft.cognitiveservices.speech.sdk.bundle";

declare global {
  interface Window {
    SpeechSDK: any; // you could do better
  }
}
```

**Comment by glharper** [comment]
@souzamon [This entry](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/447962b53af349e9d12709c0166cc41ed6345ad0/package-lock.json#L5242) in our package-lock.json should force heimdalljs to be 0.2.6. Could you share all the heimdalljs entries (not the entries for other libs) with exact version info in your package-lock.json when you repro this?

**Comment by souzaramon** [comment]
Sure, no problem.

This is all the matchies for 'heimdalljs" in my package.lock
```
async-disk-cache@^2.1.0:
  version "2.1.0"
  resolved "https://registry.yarnpkg.com/async-disk-cache/-/async-disk-cache-2.1.0.tgz#e0f37b187ed8c41a5991518a9556d206ae2843a2"
  integrity sha512-iH+boep2xivfD9wMaZWkywYIURSmsL96d6MoqrC94BnGSvXE4Quf8hnJiHGFYhw/nLeIa1XyRaf4vvcvkwAefg==
  dependencies:
    debug "^4.1.1"
    heimdalljs "^0.2.3"
    istextorbinary "^2.5.1"
    mkdirp "^0.5.0"
    rimraf "^3.0.0"
    rsvp "^4.8.5"
    username-sync "^1.0.2"

heimdalljs@^0.2.3:
  version "0.2.6"
  resolved "https://registry.yarnpkg.com/heimdalljs/-/heimdalljs-0.2.6.tgz#b0eebabc412813aeb9542f9cc622cb58dbdcd9fe"
  integrity sha512-o9bd30+5vLBvBtzCPwwGqpry2+n0Hi6H1+qwt6y+0kwRHGGF8TFIhJPmnuM0xO97zaKrDZMwO/V56fAnn8m/tA==
  dependencies:
    rsvp "~3.2.1"
    
    
```

**Comment by souzaramon** [comment]
If needed I could create a repository to better show this problem, my current project is a really big monorepo and also propertary one

**Comment by glharper** [comment]
@souzaramon An example repo would demonstrate this better, much appreciated.

**Comment by souzaramon** [comment]
Well, the problem is gone, at least at this small repo, it just works (and also make me look crazy haha)
https://github.com/souzaramon/demo-microsoft-cognitiveservices-speech-sdk-issue-477

Soooo, the problem is propabably related to my monorepo setup and not vite itself(or the sdk). I think we should just close this, and if it still happen I will open another issue, with way more information and pointing the real problem.

**Comment by benbucksch** [comment]
I am running into the same problem. Also with a project using vite and Svelte.

* microsoft-cognitiveservices-speech-sdk 1.24.1
* heimdalljs 0.2.6
* async-disk-cache 2.1.0
* vite 2.9.9

**Comment by glharper** [comment]
@benbucksch Sorry for the super late reply, we are currently exploring removing the async-disk-cache dependency. If you'd like to try this out again, take a look at the "remove-ocsp" branch [here](https://github.com/microsoft/cognitive-services-speech-sdk-js/tree/remove-ocsp).
