### ISSUE TITLE
local build node 17+

### ISSUE THREAD

**Issue by calinalexandru** [microsoft/cognitive-services-speech-sdk-js#488]
continuing #476 

I did a fresh clone of the repo, tried several node 17+ versions, it's the same error as shown in #476
It does work with node version v16.9.1 but I need it to work for 17+

**Comment by glharper** [comment]
@calinalexandru We can only support stable node versions, the latest of which is 16.14.0. To unblock you, I've created the branch glharper/node-17-mac which should work from a git clone into a new directory on mac with node 17. This newly created branch currently does not work on windows with node 17. Let me know if this works for you.
