### ISSUE TITLE
Pronunciation Assessment EnableMiscue Never Returns Error

### ISSUE THREAD

**Issue by nhterry** [microsoft/cognitive-services-speech-sdk-js#495]
I'm trying to get the pronunciation assessment to return omissions, mispronunciations, and insertions but I am unable to. It always returns an ErrorType of 'None'. I have changed my reference text to try different inputs, but nothing seems to work. I have also switched the PronunciationAssessmentGranularity between Word and Phoneme.

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-pronunciation-assessment?pivots=programming-language-javascript

```
  let speechConfig = SpeechConfig.fromAuthorizationToken(azureToken, azureRegion);
  let audioConfig = SpeechSDK.AudioConfig.fromDefaultMicrophoneInput(microphoneSources.value);

  speechConfig.speechRecognitionLanguage = 'en-US';
  speechConfig.outputFormat = SpeechSDK.OutputFormat.Detailed;
  
  let speechRecognizer = new SpeechSDK.SpeechRecognizer(speechConfig, audioConfig);

  setRecognizerCallbacks(speechRecognizer);

  let pronunciationAssessmentConfig = new SpeechSDK.PronunciationAssessmentConfig("sat mat rat bat cat fat cap sap map tap lap rap am ram Sam ham dam jam rag bag tag wag hag lag can man ran tan fan pan",
    SpeechSDK.PronunciationAssessmentGradingSystem.HundredMark,
    SpeechSDK.PronunciationAssessmentGranularity.Phoneme, 
    true);
  pronunciationAssessmentConfig.applyTo(speechRecognizer);

  speechRecognizer.startContinuousRecognitionAsync();
```

```
const setRecognizerCallbacks = (reco) => {
  reco.recognized = (s, e) => {
      let pronunciationAssessmentResult = SpeechSDK.PronunciationAssessmentResult.fromResult(e.result);
      console.log(pronunciationAssessmentResult);
  }
}
```

I'm also curious if there is a max length for the ReferenceText parameter.

**Comment by nhterry** [comment]
It looks like `EnableMiscue` works with `recognizeOnceAsync()`. I was trying to avoid using `recognizeOnceAsync()` since the documentation says there is a limit of 30 seconds. Testing the API, it looks like the limit might actually be 60 seconds. I am unsure if this limit is consistent, I will have to test it out more.

It might help others to list in the documentation that `EnableMiscue` does not work with `startContinuousRecognitionAsync()`.

Are there any best practices for using the pronunciation assessment with longer audio input? I figure it might just be best to immediately call `recognizeOnceAsync` immediately after the `sessionStopped` and/or `speechEndDetected` events and to stop the detection within other application logic.

**Comment by yulin-li** [comment]
The continuous pronunciation assessment cannot report `Omission` or `Insertion` for now. We recommend you to get the the difference after getting all result. 

See [this](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/browser/index.html#L749) for reference

cc @yinhew
