### ISSUE TITLE
How to use mic with speech recognition

### ISSUE THREAD

**Issue by Scarner56** [microsoft/cognitive-services-speech-sdk-js#497]
Hello

I wanna make a real-time recognition from mic with azure speech recognition.
I can make it from wav files but i want to get sound from mic.

Thanks

**Comment by ralph-msft** [comment]
Thanks for using the Cognitive Services Speech SDK.

You can follow our [speech recognition quickstart](https://docs.microsoft.com/azure/cognitive-services/speech-service/get-started-speech-to-text) to walk you through recognizing speech from the default microphone on your device.

We also have instructions on how to choose a [specific microphone (or other audio input device)](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-select-audio-input-devices).
