### ISSUE TITLE
What are the actually supported formats for input audio?

### ISSUE THREAD

**Issue by has-n** [microsoft/cognitive-services-speech-sdk-js#501]
This is probably the wrong place to ask this question but since I'm working with the JS SDK, might as well. 

I'm creating a PushStream to write raw audio samples into for continuous recognition. The documentation indicates support for  `WAV (16 kHz or 8 kHz, 16-bit, and mono PCM)` ([source](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-codec-compressed-audio-input-streams?tabs=android%2Cdebian&pivots=programming-language-csharp)).

But I'm able to pipe in samples at 44.1kHz and it works with only a minor drop in accuracy. Are there other secret configurations the back end supports?

**Comment by chschrae** [comment]
Hi there,

There are no secret configurations that are supported. Keep in mind that if you put 44.1kHz audio into a system reading it at 16kHz it would just become low pitch and really slow. The SR system might still be able to determine a result, but accuracy is not guaranteed and thus "unsupported".
