### ISSUE TITLE
Translation Recognizer

### ISSUE THREAD

**Issue by filipe-campos** [microsoft/cognitive-services-speech-sdk-js#511]
Apparently the Translation Reconizer is not working anymore, the Azure example itself is not working and also the demo site is not working either.

Azure example:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/node/translation.js

Site demo:
https://azure.microsoft.com/en-us/services/cognitive-services/speech-translation/#features

Anyone else having problems?

And it doesn't return any error or information, it just doesn't perform the translation.

**Comment by eluchsinger** [comment]
Can confirm this is broken as of yesterday. Looking at the network tab, it looks like there is a loop when trying to switch the websockets protocol.

There must have been a server-side change of behavior, because several projects stopped working simultaneously without any changes / updates.

**Comment by filipe-campos** [comment]
Yes @eluchsinger, today I analyzed the network tab and saw that it is really in a loop doing a protocol switch on the websocket.

Is microsoft aware of this?

Is there any way we can open a ticket directly there to know the status?

**Comment by glharper** [comment]
We are aware of this issue, and merged in a [fix last week.](https://github.com/microsoft/cognitive-services-speech-sdk-js/pull/507)

**Comment by eluchsinger** [comment]
@glharper I understand. Thanks for the update. Shouldn't this be a hotfix though (v1.20.1)? Because a lot of projects are broken now...

**Comment by filipe-campos** [comment]
@glharper Thanks for the info.

@eluchsinger I agree with you, I believe it should be a hotfix too.
For me the downgrade worked too.
