### ISSUE TITLE
SpeechRecognizer - utterance recognized reports wrong Offset sometimes

### ISSUE THREAD

**Issue by mraxus** [microsoft/cognitive-services-speech-sdk-js#518]
## Background

I am using `sdk.SpeechRecognizer` to transcribe text. In this case Swedish. I am extracting timestamps for each word and that works as well.

## Problem

Sometimes the `recognizer.recognized` gives a wrong reporting of the utterance Offset.
By looking at the raw information from the event (`e.result.json`), I get this.

(This is the proper output coming from the Azure service, should you want to check this particular event)

```
{
    "Id": "b32587d8f5224b91b1f816a52c93e096",
    "RecognitionStatus": 0,
    "Offset": 36900000,
    "Duration": 53700000,
    "DisplayText": "Sonja gick dit för att få sin katt tillbaka, men direktören lyssnade inte.",
    "NBest":
    [
        {
            ...
            "Words":
            [
                {
                    "Word": "sonja",
                    "Offset": 11936100000,
                    "Duration": 5300000
                },
                {
                    "Word": "gick",
                    "Offset": 11941500000,
                    "Duration": 2600000
                },
...
```

As can be seen, the utterance Offset is different from the word Offset. In all cases I have looked at, the word offset is correct. Possibly a bug decoding the utterance Offset?

**Comment by glharper** [comment]
@mraxus Thanks for using Speech SDK, and writing this issue up. The word level offsets in the json have been corrected to account for the length of the stream (see #394 for the discussion around that change), but the JSON Offset value has not. How does e.result.offset compare for this result? The value of e.result.offset should be more accurate than the JSON offset.
