### ISSUE TITLE
How to Recover from Websocket connection failures

### ISSUE THREAD

**Issue by josephsctan** [microsoft/cognitive-services-speech-sdk-js#521]
Hi There,

I am using conversation transcription via a browser with microsoft-cognitiveservices-speech-sdk.js  v1.20.

In the main,  it works really well. 

Occasionally, I will get websocket errors, mid way during the call,  such as this : 

microsoft.cognitiveservices.speech.sdk.bundle-min.js:10 WebSocket connection to 'wss://transcribe.southeastasia.cts.speech.microsoft.com/speech/recognition/multiaudio?language=en-AU&Authorization=bearer%(...snipped...)&X-ConnectionId=4E6A0491AE0A4C419FF02730ACA62B81' failed: 
open @ microsoft.cognitiveservices.speech.sdk.bundle-min.js:10

For example, it just happened at around the 30 minute mark today.

Can you advise where we can trap the error in order to initiate a connection retry? 

Thanks

**Comment by glharper** [comment]
@josephsctan Thanks for using Speech SDK, and writing this issue up. The SDK should be handling the reconnection for you (see [this code](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/da95559ddcab0a4c2d8303f059e0dad42ef90f90/src/common.speech/ServiceRecognizerBase.ts#L122), so this disconnect seems strange. What error code/message are you getting back when the connection fails?

**Comment by josephsctan** [comment]
Hi there,

I'm not  seeing any error messages apart from that one which I sent, above. There are 5 of them in quick succession, which is probably the internal retry logic running.

Where would be the best place to try/catches to trap this error? 

Also is there an easy way to force this error mid-stream, in order to test my retry code.
I tried to zero out the authentication credentials while the transcription is going on, but that didn't do it.

**Comment by paschaldev** [comment]
@glharper I doubt if this solves the issue... From what I read, the token lasts for 10mins + extra 9miniutes.... If you run a long transcription (20min+), it cuts off around the 20minutes mark with the websocket disconnect error. How do we recover and continue transcribing with little to no loss?

I am able to fetch a new token every 8minutes from the backend, how do I silently update the token without disruptin the transcription?

**Comment by paschaldev** [comment]
@rhurey I setup the transcriber by doing this (React App)

```
const speechConfig = sdk.SpeechConfig.fromAuthorizationToken(
    azureToken,
    azureRegion,
  );
```

Is it recommended to call the setter function at intervals when I get a new token?
