### ISSUE TITLE
(Error 1007) Socket not responding with audio data on prod/built app

### ISSUE THREAD

**Issue by nzambello** [microsoft/cognitive-services-speech-sdk-js#524]
Hello, I have a problem which is happening only on the built app but not in dev mode.
I get no audio data from the socket. 

## Context
NextJS: v12.1.0
React: v17.0.2
Node: 16
OS: MacOS (dev) - MacOS, Linux (build)
Brower: any

## The problem
In dev mode running my NextJS app locally I get answers from the socket correcly so TTS is working as expected.
When run from the build in prod mode, I get no audio data in response.
This error is happening on any browser.

As the result from the api call, I get no data in the built version, and I get the following error:
```
privErrorDetails: "Invalid message format. Text message contains no header separator websocket error code: 1007"
privProperties: e
  privKeys: ['CancellationErrorCode']
  privValues: ['BadRequestParameters']
```

## Debug steps I took
I'm initializing the SpeechConfig correctly with my project subscription key on client side.

Both dev and build apps are calling on ```wss://eastus.tts.speech.microsoft.com/cognitiveservices/websocket/v1?Ocp-Apim-Subscription-Key=xxx&X-ConnectionId=xxx```.

In both cases, I see the socket sending 3 messages: config, context and ssml and they are equal.

### Config
Dev:
```
Path: speech.config
X-RequestId: 7C8B09E2A70D416D98BA2533A526C544
X-Timestamp: 2022-04-22T14:44:09.182Z
Content-Type: application/json

{"context":{"system":{"name":"SpeechSDK","version":"1.20.0","build":"JavaScript","lang":"JavaScript"},"os":{"platform":"Browser/MacIntel","name":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36","version":"5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"}}}
```

Build:
```	
Path: speech.config
X-RequestId: 5E5609F3AC78466684E9B6F80CDF07B1
X-Timestamp: 2022-04-22T14:35:55.841Z
Content-Type: application/json

{"context":{"system":{"name":"SpeechSDK","version":"1.20.0","build":"JavaScript","lang":"JavaScript"},"os":{"platform":"Browser/MacIntel","name":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36","version":"5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"}}}
```

### context
dev:
```
Path: synthesis.context
X-RequestId: 7C8B09E2A70D416D98BA2533A526C544
X-Timestamp: 2022-04-22T14:44:09.183Z
Content-Type: application/json

{"synthesis":{"audio":{"metadataOptions":{"bookmarkEnabled":false,"sentenceBoundaryEnabled":false,"visemeEnabled":false,"wordBoundaryEnabled":false},"outputFormat":"audio-24khz-48kbitrate-mono-mp3"},"language":{"autoDetection":false}}}
```

build:
```
Path: synthesis.context
X-RequestId: 5E5609F3AC78466684E9B6F80CDF07B1
X-Timestamp: 2022-04-22T14:35:55.842Z
Content-Type: application/json

{"synthesis":{"audio":{"metadataOptions":{"bookmarkEnabled":false,"sentenceBoundaryEnabled":false,"visemeEnabled":false,"wordBoundaryEnabled":false},"outputFormat":"audio-24khz-48kbitrate-mono-mp3"},"language":{"autoDetection":false}}}
```

### ssml
dev:
```
Path: ssml
X-RequestId: 7C8B09E2A70D416D98BA2533A526C544
X-Timestamp: 2022-04-22T14:44:09.183Z
Content-Type: application/ssml+xml

<speak version='1.0' xmlns='http://www.w3.org/2001/10/synthesis' xmlns:mstts='http://www.w3.org/2001/mstts' xmlns:emo='http://www.w3.org/2009/10/emotionml' xml:lang='it-IT'><voice name='it-IT-ElsaNeural'>Text here</voice></speak>
```

build:
```
Path: ssml
X-RequestId: 5E5609F3AC78466684E9B6F80CDF07B1
X-Timestamp: 2022-04-22T14:35:55.842Z
Content-Type: application/ssml+xml

<speak version='1.0' xmlns='http://www.w3.org/2001/10/synthesis' xmlns:mstts='http://www.w3.org/2001/mstts' xmlns:emo='http://www.w3.org/2009/10/emotionml' xml:lang='it-IT'><voice name='it-IT-DiegoNeural'>Text here</voice></speak>
```

The three messages are sent successfully but then, while in dev mode I get several messages in response with the audio buffers, in build/prod mode I'm not.

## The code
```ts
speechConfig.speechSynthesisLanguage = getCultureCodeByLanguage(userLang);
speechConfig.speechSynthesisVoiceName = getTTSVoice(userLang); // https://docs.microsoft.com/it-it/azure/cognitive-services/speech-service/language-support#text-to-speech

let audioConfig = speechSdk.AudioConfig.fromSpeakerOutput(
  speechSynthesizerDefaultPlayer,
);
speechSynthesizer = new speechSdk.SpeechSynthesizer(
  speechConfig,
  audioConfig,
);

speechSynthesizer.speakTextAsync(
  text,
  (result) => {
    if (speechSynthesizerDefaultPlayer)
      speechSynthesizerDefaultPlayer.pause();
    if (result) {
      try {
        console.log('speak result', result);
        playAudioAsync(result.audioData);
      } catch (e) {
        console.error('speak error: ', e);
        window.speechSynthesis.speak(new SpeechSynthesisUtterance(text));
      }
    }
  },
  (error) => {
    console.error('speak:', error);
    window.speechSynthesis.speak(new SpeechSynthesisUtterance(text));
  },
);
```

`playAudioAsync` is a function that handles audiocontext and players and their state.

Here, when logging ```console.log('speak result', result);```, that is the object I pasted before with the error 1007, and then `result.audioData` is `undefined`.

What should I look? I don't know how to debug this further, no clue about any difference that could be between the two versions.

**Comment by glharper** [comment]
@nzambello Thank you for using Speech SDK, and writing this issue up. From [this issue](https://github.com/Azure-Samples/SpeechToText-WebSockets-Javascript/issues/87), it would appear that one or all of the above websocket messages is being written in your prod environment with a "\n" newline between the headers and the text payload, instead of the "\r\n" newline that the service expects. 
@yulin-li Can you think of anything in JS SDK that would cause this behavior on Linux?

**Comment by nzambello** [comment]
Thank you @glharper for answering me in such a short time.
It happens on macOS for sure, too. No clue on Windows.

As further details, I can add that I'm using TypeScript and Next's [swc](https://github.com/swc-project/swc) compiler.

**Comment by nzambello** [comment]
Oupsie, I found it!
The issue is from swc: I enabled the `swcMinify` experimental feature, see [docs](https://nextjs.org/docs/advanced-features/compiler#minification).

Once I disabled it with `{ swcMinify: false }`, it's now working.

Sorry for the non-related issue and thank you again.
