### ISSUE TITLE
[REG 1.20 -> 1.21] Cannot use on node/ts without esModulesInterop

### ISSUE THREAD

**Issue by orgads** [microsoft/cognitive-services-speech-sdk-js#525]
Hi,

Starting from version 1.21.0, we cannot use this package with typescript because it requires `esModulesInterop`, which we don't use (and it breaks our build).

```
node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.browser/RestMessageAdapter.d.ts:2:8 - error TS1259: Module '"node_modules/@types/bent/index"' can only be default-imported using the 'esModuleInterop' flag

2 import bent from "bent";
         ~~~~

  node_modules/@types/bent/index.d.ts:77:1
    77 export = bent;
       ~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
```

**Comment by glharper** [comment]
@orgads Thanks for writing this up, and using Speech SDK. This breakage going from 1.20->1.21 is interesting, as the switch to the bent dependency happened in 1.18.1, and our "esModuleInterop" flag has been set to true in tsconfig.json for much longer than that. Any idea why 1.20 is working for you despite that?

**Comment by orgads** [comment]
I suppose it's because of 6c070c429f44a9213d562a794886da768590ada4 which changed `any` to `bent` types, causing typescript *not* to drop the import on the declaration file.

**Comment by glharper** [comment]
@orgads Could you check out the branch in the above PR and see if that addresses this issue?

**Comment by orgads** [comment]
Looks better with this, thank you!
