### ISSUE TITLE
Can't new SpeechRecognizer twice on Safari

### ISSUE THREAD

**Issue by ashramwen** [microsoft/cognitive-services-speech-sdk-js#526]
Hi, I am using React with `microsoft-cognitiveservices-speech-sdk` from npm.
**Version:** 1.20.0 and 1.21.0
**Browser:** Safari 15.2 (Macbook and iPhone)
**React:** 17 (CRA 5.0)

For the first time, when I call `new SpeechRecognizer`, the whole thing works well.
Then I want to refresh the token, so I call `new SpeechRecognizer` again with the new token.
Safari no longer captures the sound from the microphone and `sessionStarted` won't trigger as well.
It works well on Chrome, but not on Safari or any browsers on iPhone.

```js
const speechConfig = SpeechConfig.fromAuthorizationToken(token, region);
speechConfig.speechRecognitionLanguage = lang;
const audioConfig = AudioConfig.fromDefaultMicrophoneInput();
const recognizer = new SpeechRecognizer(speechConfig, audioConfig);

recognizer.sessionStarted = onSessionStarted;
recognizer.recognizing = recognizing;
recognizer.recognized = recognized

recognizer.startContinuousRecognitionAsync();
```
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/3334950/164973160-ad302810-50ad-4644-ad54-532e6953c4c9.png">

The first connection has upload info, but the second one doesn't.
First connection
<img width="1327" alt="Screen Shot 2022-04-24 at 18 59 03" src="https://user-images.githubusercontent.com/3334950/164973255-76af7e8c-901e-481d-94d5-c30e0e46a0e7.png">

Second connection
<img width="1459" alt="Screen Shot 2022-04-24 at 18 59 19" src="https://user-images.githubusercontent.com/3334950/164973266-29b82ad5-e378-444a-8df9-cd31173db417.png">

**Comment by ashramwen** [comment]
No, it's not working with v1.18.1 as well unfortunately.

**Comment by glharper** [comment]
@ashramwen Thanks for checking. Apple typically implements cumbersome permissions for accessing the microphone multiple times, so my initial thought is that this is a iOS/Safari problem, but I will take a look later this week to confirm or deny that hypothesis.

**Comment by glharper** [comment]
@ashramwen Are you seeing this issue when you use a key/region (and not a token), where the new SpeechRecognizer() isn't capturing properly after the second instantiation?
