### ISSUE TITLE
What does word boundary duration refer to?

### ISSUE THREAD

**Issue by taktran** [microsoft/cognitive-services-speech-sdk-js#534]
Hi, I was quite excited by this PR (https://github.com/microsoft/cognitive-services-speech-sdk-js/pull/494) to add `duration` to [word boundary events](https://docs.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/speechsynthesiswordboundaryeventargs?view=azure-node-latest), as I was calculating the `duration` manually by using the offset of the next word. However, I found the `duration` returned overlaps with the next word, so I'm wondering what do you use the returned `duration` for? What does it actually represent?

This is a code sandbox of what I'm seeing: https://codesandbox.io/s/donkey-chinese-words-017t1y

The word boundaries using the event duration ([audioOffset, eventDuration]):

```
我: [50, 187.5]
有: [175, 225]
一: [325, 243.75]
只: [487.5, 225]
小: [637.5, 300]
毛驴: [837.5, 750]
```

and the word boundaries using the next word offset ([audioOffset, nextWordOffsetDuration]):

```
我: [50, 125]
有: [175, 150]
一: [325, 162.5]
只: [487.5, 150]
小: [637.5, 200]
毛驴: [837.5, 750]
```

**Comment by yulin-li** [comment]
Hi @takran, the `duration` is the duration of current word, it should less or equal to `nextWordOffsetDuration` in your code.

Looks that we have a bug, let me check with our engineers.

**Comment by yulin-li** [comment]
Hi, @takran, I confirmed this bug and service team is fixing it. The bug is only with 16kHz output format. You can use a 24kHz one as a work around (actually we recommend customers use 24kHz format for better quality)

The `duration` is shorter than or equal to `next offset - current offset`. If we have a pause before next word, then the duration excludes the pause to make it more accurate.

**Comment by taktran** [comment]
Oh great! Thanks for looking into it @yulin-li ! I'll try out 24kHz later 😃

**Comment by yulin-li** [comment]
thx, and it's a very nice app you built

**Comment by taktran** [comment]
Heya @yulin-li , it works with the `24kHz` output format 🎉  https://codesandbox.io/s/donkey-chinese-words-24khz-8btfjl - Thanks! 😄 

As you said, it factors in the pause from punctuation too, so:

```
// with `duration`
毛驴: [800, 487.5]
，: [1400, 175]

// with next word offset
毛驴: [800, 600]
，: [1400, 175]
```

I had to make the following change when initialising `SpeechSynthesizer`

```
speechConfig.speechSynthesisOutputFormat = SpeechSynthesisOutputFormat.Audio24Khz160KBitRateMonoMp3;
return new SpeechSynthesizer(speechConfig, audioConfig);
```

I'll leave it to you whether you want to keep this issue open, or sort it out elsewhere.

**Comment by yulin-li** [comment]
Thanks for confirmation. I'd like to keep this issue open until we fix this issue, so other developers could refer to this one.

**Comment by yulin-li** [comment]
Closing this issue as this bug is fixed.
