### ISSUE TITLE
NodeJS v18 compatibility

### ISSUE THREAD

**Issue by Supergiovane** [microsoft/cognitive-services-speech-sdk-js#535]
Hi
thank you for this package. I'm using it in my TTS-Ultimate node for Node-Red. I noticed many users are upgrading to NodeJS v18.x.x.
This either broke the working environment or my node simply won't install from fresh.
I know you're running only on LTS versions of NodeJS, but i wish to inform you about that, because we devs will run in more and more issues, as more and more "non expert" users update NodeJS to v18.
Thanks.

**Comment by glharper** [comment]
@Supergiovanne Thanks for using Speech SDK, and making us aware of this issue. Which OS are you seeing this with, and is this all scenarios (or just Translation, Speech to Text, Text to Speech, etc.)? I installed node 18.2 on windows using nvm for windows, then ran "npm install microsoft-cognitiveservices-speech-sdk", getting back:
```
added 44 packages, and audited 45 packages in 2m

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
Using this installed library on node 18.2, startContinuousRecognitionAsync seems to recognize my test wav file correctly.

**Comment by Supergiovane** [comment]
PS: doint an "npm rebuild" into the **microsoft-cognitiveservices-speech-sdk** with node 18.2, results in:

npm rebuild
npm ERR! code 1
npm ERR! path /root/node_modules/microsoft-cognitiveservices-speech-sdk
npm ERR! command failed
npm ERR! command sh -c npm install --package-lock-only --ignore-scripts --no-audit && npx npm-force-resolutions
npm ERR! npm ERR! Invalid Version: ^1.2.6
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR! /root/.npm/_logs/2022-05-30T19_16_36_256Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2022-05-30T19_16_29_472Z-debug-0.log
`

**Comment by Supergiovane** [comment]
Ok no problem. Just to inform you.

**Comment by Nickersoft** [comment]
Hey 👋🏻  Just wanted to say that I just stumbled upon this issue, and am facing the same `Invalid Version: ^1.2.6` after upgrading my Node version from 16.3 to 16.15.
