### ISSUE TITLE
Use prebuilt neural voices in preview

### ISSUE THREAD

**Issue by crllnsmnn** [microsoft/cognitive-services-speech-sdk-js#541]
Hi,

are the [Prebuilt neural voices in preview](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support?tabs=speechtotext#prebuilt-neural-voices-in-preview) supported by this SDK?
I am not able to use any of the newly added voices, even though I am using one of the specified regions.

I also noticed that these new voices are not mentioned in this path: src/sdk/SpeechSynthesizer.ts
This might be related?

Thank you!

**Comment by yulin-li** [comment]
The SDK doesn't limit the voices, and the voices checked-in are only the default voices for each locale.

I noted that the doc says `voices and styles in public preview are only available in three service [regions](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/regions#prebuilt-neural-voices): East US, West Europe, and Southeast Asia.`

Could you double check the region you are using?

**Comment by crllnsmnn** [comment]
> Could you double check the region you are using?

Thanks for the quick response!
I figured that not only the TTS service itself, but also the Azure Resource Group has to be in one of the three regions.
After moving my TTS service to another resource group everything works as expected. Thanks!
