### ISSUE TITLE
The readme quick tutorial browser link is broken

### ISSUE THREAD

**Issue by fungiboletus** [microsoft/cognitive-services-speech-sdk-js#544]
Hi,

It looks like the `[Quick tutorial - Browser](https://docs.microsoft.com/azure/cognitive-services/speech-service/quickstart-js-browser)` link is broken as it redirects to the NodeJS quick start.

**Comment by dargilco** [comment]
Thanks @fungiboletus for bringing this to our attention!  We've recently made changes to the QuickStart documentation which may have resulted in this link being broken. Let me follow up internally with our team and technical writer on this.
