### ISSUE TITLE
How to pass audio stream to SpeechRecognizer

### ISSUE THREAD

**Issue by dhruvjaglan** [microsoft/cognitive-services-speech-sdk-js#546]
I am using a custom pcm worker to record the audio stream, I would like to pass the same stream to SpeechRecognizer. But I am not able to get any response from SpeechRecognizer (which works fine with audioConfig.fromDefaultMicrophoneInput()).

Here is the code for pcm worker,
```const quantumSize = 128;

/*
transcoding of the stream
combining frames into 100 ms audio chunks
*/
class TranscodeAndChunkProcessor extends AudioWorkletProcessor {
  constructor(options) {
    super();
    this.quantaPerFrame = 12; /// 8*32 = 256ms is the time of a frame
    this.quantaCount = 0;
    this.frame = new Int16Array(quantumSize * this.quantaPerFrame);
  }

  process(inputs, outputs, parameters) {
    const offset = quantumSize * this.quantaCount;
    inputs[0][0].forEach((sample, idx) => (this.frame[offset + idx] = Math.floor(sample * 0x7fff)));
    this.quantaCount = this.quantaCount + 1;
    if (this.quantaCount === this.quantaPerFrame) {
      this.port.postMessage(this.frame);
      this.quantaCount = 0;
    }
    return true;
  }
}

registerProcessor('pcm-worker', TranscodeAndChunkProcessor);
```

This is the setting I am using with the SpeechRecognizer:

```
pushStream = speechsdk.AudioInputStream.createPushStream(
      speechsdk.AudioStreamFormat.getWaveFormatPCM(16000, 16, 1)
    );

    const audioConfig = speechsdk.AudioConfig.fromStreamInput(pushStream);
    this.speechRecognizer = new speechsdk.SpeechRecognizer(speechConfig, audioConfig);
```

I am writing pcm data to the pushStream but not getting any response or error. Am I doing anything wrong or does the SDK provide an option to record too.

**Comment by jhakulin** [comment]
@dhruvjaglan Thanks for the report. Could you please share recording of PCM data (e.g. few seconds) which you are writing using push stream ? The format of the PCM data could be unexpected. If you plug into Canceled event, do you get that ? If yes, what is the cancellation information ?

SDK do not provide API currently for capturing mic data.

**Comment by dhruvjaglan** [comment]
Yes, the audio format 16kHz (Sample rate), 16bit (as you can see above in the audio sample), mono (channel count =1)

```navigator.mediaDevices.getUserMedia({
    audio: {
      deviceId: 'default',
      sampleRate: 16000,
      sampleSize: 16,
      channelCount: 1
    },
    video: false
  });```

**Comment by dhruvjaglan** [comment]
@jhakulin any updates?

**Comment by jhakulin** [comment]
@dhruvjaglan Have you confirmed the audio format you have requested is really what browser is capable of doing ?
Could you please provide information about audio capabilities of the browser?
````
let stream = await navigator.mediaDevices.getUserMedia({audio: true});
let track = stream.getAudioTracks()[0];
console.log(track.getCapabilities());
````
Also would it be possible to share few seconds of audio data dumped into .pcm file so that we could analyze it better ?

**Comment by brandom-msft** [comment]
@dhruvjaglan, In addition to @jhakulin's latest reply, you can reference some example usage of the PushStream in the tests. Depending on your scenario, you can populate the stream before or during recognition.

https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/ba8be3e8827bd4c238cb2a449371510e159f7099/tests/SpeechRecognizerTests.ts#L1016

https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/ba8be3e8827bd4c238cb2a449371510e159f7099/tests/SpeechRecognizerTests.ts#L1204

**Comment by dhruvjaglan** [comment]
@jhakulin I am attaching a screenshot with the browser details, we are using chrome Version 103.0.5060.114 on mac book.  Here is a link to a file containing 5 sec of chunks: https://drive.google.com/file/d/1IS0U7tjvrEa5QwcDpo5cFCMkcl9RpOZX/view?usp=sharing

@brandom-msft I looked at the examples you shared. I am trying to do ContinuousRecognitionAsync on user mic using PCM worker but the example you shared is recognizeOnceAsync and on a prebuild file, not sure if I can replicate these examples to my use case.

<img width="726" alt="Screenshot 2022-07-12 at 10 06 57 AM" src="https://user-images.githubusercontent.com/26343492/178421134-5196c511-9696-4e83-8d03-66d381269e89.png">

**Comment by dhruvjaglan** [comment]
@jhakulin  I tried the setting mentioned above but it didn't work.

**Comment by dhruvjaglan** [comment]
Is there a way I access the chunks sent for STT when we directly catch the microphone.

`audioConfig = speechsdk.AudioConfig.fromDefaultMicrophoneInput();`

or if you can share, how speechsdk is catching the audio stream fromDefaultMicrophoneInput. I can do the same and pass it to the pushStream.

**Comment by dhruvjaglan** [comment]
I tried using the pcm-worker mentioned here but didn't work for me. https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/audioworklet/speech-processor.js

**Comment by glharper** [comment]
@dhruvjaglan Were you able to get this working? There's a similar issue, with some sample code [here](https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/564#issuecomment-1242438471), that may help you out.

A couple of notes:
- make sure the reassembled pcm is actual audio and not noise or garbage. The sdk's BaseAudioPlayer class has a playAudioSample method (taking an ArrayBuffer) that can help you ensure this when debugging.
- the audio written to the pushStream must be an ArrayBuffer, not a typed int array.

Let me know if any of this helps.

**Comment by dhruvjaglan** [comment]
@glharper, It's working for me now. I used something similar to your [RiffPCMEncoder](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/common/RiffPcmEncoder.ts) to encode the stream in the required format. 
Thank you for your constant support.
