### ISSUE TITLE
[Feature request] Improvements on the SDK import when using Vite

### ISSUE THREAD

**Issue by fungiboletus** [microsoft/cognitive-services-speech-sdk-js#548]
As seen in #477, it is possible to use the SDK when using Vite but it is not ideal. The SDK is imported globally on the `window` global variable and with everything. Moreover, the typescript types are a bit lost in the way and you need to rebuild them.

This is how it looks for me:

```typescript
import 'microsoft-cognitiveservices-speech-sdk/distrib/browser/microsoft.cognitiveservices.speech.sdk.bundle';
import type * as SpeechSDKType from 'microsoft-cognitiveservices-speech-sdk/distrib/lib/microsoft.cognitiveservices.speech.sdk';

declare global {
  interface Window {
    SpeechSDK: {
      AudioConfig: typeof SpeechSDKType.AudioConfig;
      OutputFormat: typeof SpeechSDKType.OutputFormat;
      Recognizer: typeof SpeechSDKType.Recognizer;
      SpeechConfig: typeof SpeechSDKType.SpeechConfig;
      SpeechRecognizer: typeof SpeechSDKType.SpeechRecognizer;
    };
  }
}
const { AudioConfig, OutputFormat, Recognizer, SpeechConfig, SpeechRecognizer } = window.SpeechSDK;
```

I would prefer the following:
```typescript
import { AudioConfig, OutputFormat, Recognizer, SpeechConfig, SpeechRecognizer } from 'microsoft-cognitiveservices-speech-sdk';
```

**Comment by benbucksch** [comment]
@jhakulin I ran confirm the same problem #477 . The workaround here works for me, but it's obviously very suboptimal. I cannot use TypeScript types. Most importantly, it took me a while to figure this out and find this bug report here.

> The SDK is imported globally on the window global variable and with everything

Please don't do that.

**Comment by waeltken** [comment]
> @jhakulin I can confirm the same problem as descibed in #477 . The workaround here works for me, but it's obviously very suboptimal and a HACK. I cannot use TypeScript types. Most importantly, it took me a while to figure this out and find this bug report here.
> 
> > The SDK is imported globally on the window global variable and with everything
> 
> I see. Please don't do that.

This workaround works with vite in dev mode for me. Not for the build of the static webapp that I'm working on.
Is there a way to import the SDK that works for both modes?

@jhakulin, can we please prioritize the work item you've created?

**Comment by SahilTara** [comment]
@jhakulin pinging.

**Comment by glharper** [comment]
@SahilTara @fungiboletus @waeltken @benbucksch JS Speech SDK v1.28.0 has been released (npm link [here](https://www.npmjs.com/package/microsoft-cognitiveservices-speech-sdk)), which may mitigate this issue. Could you update your dependency to 1.28.0 and see if that helps?

**Comment by apavel3458** [comment]
This update has not resolved the issue.
