### ISSUE TITLE
SDK hanging up on audio files after first sentence / 15 seconds

### ISSUE THREAD

**Issue by noopkat** [microsoft/cognitive-services-speech-sdk-js#55]
Hi there 😄 

When I use this SDK with long, multi-sentence audio files, the SDK appears to hang up the socket connection after the first sentence is recognised, and abandons the rest of the audio. The process then exits.

[On the following documentation page](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-to-text), it infers that the SDK can process long audio files:

> Continuous transcription of long utterances and streaming audio (>15 seconds). Supports interim and final transcription results.

**To reproduce:**

I tried running the following code sample from the official [NodeJS Quickstart](https://docs.microsoft.com/en-us/javascript/api/overview/azure/speech-service?view=azure-node-latest). I made no modifications aside from the audio file name in both tests I did.

[Here are two audio samples](https://github.com/noopkat/ms-bing-speech-service/tree/master/examples/node/samples) I tested with. They are both mono and 16kHz. 

It is important to note that **both of these audio files have worked perfectly with the previous versions of the Translator and Bing Speech websocket endpoints**, as I have used them for benchmarking in the past when writing software to interface with the endpoints.

It's because of this previous point that I don't believe the gaps between sentences are long enough to trigger an end of speech event, so I'm not exactly sure what is going on. Do I need to change the recognition mode? I had trouble finding detailed documentation about this use case.

I would love to be able to stop using my own code and switch to the official SDK but this is a bit of a showstopper for me. Any help or pointers would be wonderful; thank you so much for your time 🙏 🙇‍♀️

**Comment by wolfma61** [comment]
Hi @noopkat
the sample you reference uses recognizeOnceAsync.

 RecognizeOnceAsync() returns when the first utterance has been recognized, so it is suitable only for single shot recognition like command or query. For long-running recognition, use StartContinuousRecognitionAsync() instead.

thx
Wolfgang

**Comment by noopkat** [comment]
Hi @wolfma61

thanks so much for a fast response! I tried using this + subscribing to events and it worked exactly as I needed it to 😸 

I didn't know about this continuous recognition method as it's buried in the SDK API docs and it's hard to know what to look for when you don't know what knowledge you're missing. The samples required quite an amount of digging into as well in order to find the event subscriptions that were needed. Is there a page of examples beyond the Quickstarts in the docs that I can reference in future? There are no examples I can find of using the continuous recognition with the events (just the once async is all I could find).

I am happy to contribute an example in the appropriate place if that would be helpful 🙇‍♀️

**Comment by rhurey** [comment]
Glad you were able to get things working.

Our GitHub samples repo (NodeJS samples: https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/js/node) has more in depth usage examples than the quick starts do. There isn't a doc that references them directly, but rather a table of contents link to the root of the samples repo.

**Comment by rhurey** [comment]
And I'm going to open this back up, as none of our Node samples use continuous recognition, its just the browser based ones that do. So adding one for node needs to be done.

**Comment by noopkat** [comment]
thank you @rhurey this was totally what I meant 😄I was using it within a NodeJS scenario, so I was only looking at those specific JavaScript examples. Thanks for looking into this!

**Comment by dlcrista** [comment]
Just wondering on what the progress is for posting a Node sample that uses continous recognition?

**Comment by oscholz** [comment]
@noopkat @dlcrista 
We have put work for this on our backlog, and we will create an updated sample set. But we are going to use this opportunity to go broader with unified samples across programming languages. I can't give you a timeline for this, but when we fix this, we will update this ticket to let you know what release will contain the updated samples. 
Until then I will close this issue. 
Thank you for using the JS Speech SDK.
