### ISSUE TITLE
SpeechSynthesizer.getVoicesAsync does not work with authorization token auth

### ISSUE THREAD

**Issue by Mike-Bell** [microsoft/cognitive-services-speech-sdk-js#551]
This class does not respect `SpeechServiceAuthorization_Token` like some other classes do https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/common.speech/SynthesisRestAdapter.ts

As a result, this will always 401.

```
const speechConfig = SpeechConfig.fromAuthorizationToken('some_valid_token', 'some_valid_region');
const synthesizer = new SpeechSynthesizer(speechConfig, null);
const voices = (await synthesizer.getVoicesAsync()).voices;
```

I confirmed that the endpoint itself does support token auth by manually firing a CURL against it with a valid Bearer token and seeing the voice list return

**Comment by BrianMouncer** [comment]
@yulin-li 

Yulin, can you please take a look at this.  
I've used the getVoicesAsync before, but only with a subscription key.

Thanks,

**Comment by yulin-li** [comment]
Hi Mike-Bell, I will update the codes to support token auth.
