### ISSUE TITLE
Uncaught ReferenceError: can't access lexical declaration 'Recognizer' before initialization

### ISSUE THREAD

**Issue by nzambello** [microsoft/cognitive-services-speech-sdk-js#552]
I'm using this library as a dependency of a NextJS app and had no problem.
I'm now importing it as a dependency in another library and tests run fine, but when I use that in other apps I run into this error:
```
Uncaught ReferenceError: can't access lexical declaration 'Recognizer' before initialization
```

The only use of `Recognizer` in my code is for:
```ts
sdk.Recognizer.enableTelemetry(false);
```

Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_access_lexical_declaration_before_init

Any hint on this?

**Comment by nzambello** [comment]
Removing the line
```ts
speechSdk.Recognizer.enableTelemetry(false);
```

make the whole thing being compiled and works correctly.

Still, I'd like to disable telemetry for privacy reasons, so I don't consider this as resolved.

**Comment by glharper** [comment]
@nzambello Would it be possible to called speechSdk.Recognizer.enableTelemetry() as a point in your code where you're sure the speechSdk library has been loaded properly? The error you're getting doesn't seem to be something any code change to our library can address, as it relates to code execution order in JS.
