### ISSUE TITLE
Unable to contact server. StatusCode: 1006, undefined Reason:  Unexpected server response: 500

### ISSUE THREAD

**Issue by stephenLxz** [microsoft/cognitive-services-speech-sdk-js#554]
my code is here,it returns: **Unable to contact server. StatusCode: 1006, undefined Reason:  Unexpected server response: 500** ，anyone can help me？

> function geneOptions(lang: Language) {
  let config = sdk.SpeechConfig.fromSubscription((global as any)[symbol_azure].key, (global as any)[symbol_azure].location)
  config.speechSynthesisVoiceName = convertTTSLanguage(lang)

  return config
}

async function getTTSResult(param: {
  text: string
  lang: Language,
}) {

  let config = geneOptions(param.lang)
  const synthesizer = new sdk.SpeechSynthesizer(config)

  return new Promise((resolve, reject) => {
    try {
      synthesizer.speakTextAsync(param.text, (result: any) => {
        if (result) {
          synthesizer.close()
          resolve(result.privAudioData)
        } else {
          synthesizer.close()
          reject()
        }
      }, (err: any) => {
        synthesizer.close()
        reject(err)
      })
    } catch (e) {
      reject(e)
    }
  })
}

**Comment by yulin-li** [comment]
There was a service issue hours ago and it should be fixed now.
