### ISSUE TITLE
speakTextAsync callback runs before the audio save to to the file is finished;

### ISSUE THREAD

**Issue by el** [microsoft/cognitive-services-speech-sdk-js#559]
```
        const audioConfig = AudioConfig.fromAudioFileOutput(audioFilePath);
        const synthesizer = new SpeechSynthesizer(speechConfig, audioConfig);
        return new Promise((resolve, reject) => synthesizer.speakTextAsync(
            translatedText, (result: SpeechSynthesisResult) =>
            {
                synthesizer.close();
                if (result.errorDetails)
                {
                    return reject(result.errorDetails);
                }
                resolve(audioFilePath);
            },
            error =>
            {
                reject(error);
                synthesizer.close();
            })
        );

```

For the above code, the callback runs before the file is complete. I can fix this by adding the resolve to the synthesizer.close() callback like this:

```
        return new Promise((resolve, reject) => synthesizer.speakTextAsync(
            translatedText, (result: SpeechSynthesisResult) =>
            {
                synthesizer.close(() => resolve(audioFilePath), reject);
                if (result.errorDetails)
                {
                    return reject(result.errorDetails);
                }
            },
            error =>
            {
                reject(error);
                synthesizer.close();
            })
        );
```

But I was expecting it to run only after the file write is complete.

**Comment by rhurey** [comment]
Thanks for bringing this issue up.

Looking through the code and the tests, I can confirm this is how things work today.

I'm going to follow up with some team members to see if there are plans to make the completion more predictable.

**Comment by yulin-li** [comment]
Hi @el I think this is by design as the audio file is "session" level, which means that you can synthesize more than one text using the same synthesizer and the SDK will concatenate these outputs to a single audio file. So you need a `synthesizer.close()` here to close the output file.

To achieve your goal, I think you can use "turn" level output. Refer to this unit test ["testSpeechSynthesizer: synthesis to file in turn."](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/fa4c748ad699eecb05fd6d77c8337a97b9f625aa/tests/SpeechSynthesisTests.ts#L370)

```js
s.speakTextAsync("input", complete_cb, errro_cb, "output.wav")
```

**Comment by yulin-li** [comment]
> Thanks for bringing this issue up.
> 
> Looking through the code and the tests, I can confirm this is how things work today.
> 
> I'm going to follow up with some team members to see if there are plans to make the completion more predictable.

I will open a work item internally to update the samples/docs for this.
