### ISSUE TITLE
Support overriding recognition mode for continuous speech recognition

### ISSUE THREAD

**Issue by orgads** [microsoft/cognitive-services-speech-sdk-js#56]
Originally reported in https://github.com/MicrosoftDocs/azure-docs/issues/28399.

It looks like continuous async recognition has Conversation mode hardcoded. Can you please provide a way to override it by configuration? We need to use Dictation.

Thanks.

**Comment by orgads** [comment]
ping?

**Comment by wolfma61** [comment]
this will be possible in the next SDK update. It will be available early May.

Wolfgang

**Comment by wolfma61** [comment]
currently not possible by setting a property. We are going to try to address this in an upcoming release.

as a work-around you can create the recognizer fromEndpoint
https://docs.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/speechconfig?view=azure-node-latest#fromendpoint-url--string-

the URL should look similar to this:

wss://<region>.stt.speech.microsoft.com/speech/recognition/dictation/cognitiveservices/v1

**Comment by orgads** [comment]
Thank you. I'll try it.

**Comment by geooot** [comment]
Hello!
I am trying to use dictation mode as well and this is how I setup the speechConfig using the workaround. It worked using `fromSubscription`, but doesn't work using `fromEndpoint`.  I am kind of guessing on how the url should be formatted as I have not found a reference to a websocket url in the azure portal. 
If you could see what I am doing wrong, help would be much appreciated
```javascript
// now create the audio-config pointing to our stream and
// the speech config specifying the language.
let audioConfig = sdk.AudioConfig.fromStreamInput(pushStream);
// let speechConfig = sdk.SpeechConfig.fromSubscription(SUBSCRIPTION_KEY, SERVICE_REGION);
let speechConfig = sdk.SpeechConfig.fromEndpoint(`wss://${SERVICE_REGION}.stt.speech.microsoft.com/speech/recognition/dictation/cognitiveservices/v1`, SUBSCRIPTION_KEY);

// setting the recognition language to English.
speechConfig.speechRecognitionLanguage = LANG;

// create the speech recognizer.
let recognizer = new sdk.SpeechRecognizer(speechConfig, audioConfig);
```

**Comment by rhurey** [comment]
The data type for the endpoint isn't of the expected type.

fromEndPoint is defined as:
public static fromEndpoint(endpoint: URL, subscriptionKey: string): SpeechConfig

So in this case, you'd want something like: (node)
var URL = require('url').URL;
let speechConfig = sdk.SpeechConfig.fromEndpoint(new URL (`wss://${SERVICE_REGION}.stt.speech.microsoft.com/speech/recognition/dictation/cognitiveservices/v1`), SUBSCRIPTION_KEY);

The SDK's parameter check at that point was only for null on the passed in parameter, it didn't type check the parameter or the .href property it used. I'll put a bug in our backlog to tighten the parameter check and get a better error message out.

Hope that helps.

**Comment by orgads** [comment]
I've noticed that fromEndpoint uses subscription key. Is there an alternative that accepts token (and still enabled dictation mode)? I want to avoid issueToken for each client.

**Comment by rhurey** [comment]
You should be able to pass in any value you want for the subscription key passed to fromEnedPoint and then call recognizer.authorizationToken = <token>  and the token will be used instead of the subscription key.

**Comment by rhurey** [comment]
enableDictation was added to the SpeechConfig object in the 1.7.0 release.
