### ISSUE TITLE
502 - BAD GATEWAY

### ISSUE THREAD

**Issue by Brenerss** [microsoft/cognitive-services-speech-sdk-js#560]
I'm using the aws transcription lib and I downloaded 2 packages to use as a polyfill of the `react-speech-recognition` library

The libs are `microsoft-cognitiveservices-speech-sdk` and `web-speech-cognitive-services`

on the local machine it is working without problems, but when we go up to production, it returned 502 (Bad Gatway), is there any configuration that we should do in `azure`?

**Comment by rhurey** [comment]
There shouldn't be an additional configuration, unless you're using an Azure Speech Resource that's been configured to use a Private Link.

Is the gateway error happening from connect, or does it say anything about an OCSP error?

**Comment by Brenerss** [comment]
We solved it. Was a internal problem about lambda limit of AWS. Our bundle size of reactjs was too large.
