### ISSUE TITLE
Word boundary event for multi-subword token only specifies duration of first subword

### ISSUE THREAD

**Issue by rotemdan** [microsoft/cognitive-services-speech-sdk-js#562]
Synthesizing an utterance like:
```
H.G. Wells (21 September 1866 – 13 August 1946) was an English writer.
```

The entire substring `21 September 1866 – 13 August 1946` is treated as a single token and receives a single word boundary event.

However, the duration specified in the event does not correspond to the duration of the whole token. It corresponds to the duration of the word "the", as the token seems to be normalized to:

```
the twenty first of September eighteen sixty six to the thirteenth of August nineteen forty six
```
(the voice used here is `BellaNeural`, other voices may have different normalizations, but they also seem to suffer from this problem)

**Expected behavior**
The duration property should correspond to the duration of the entire token (`21 September 1866 – 13 August 1946`).

**Version of the Cognitive Services Speech SDK**
`1.22.0`

**Platform, Operating System, and Programming Language**
Windows 10 x64
JavaScript
Node.js v16.17.0

**Remarks**
This issue doesn't seem specific to the JavaScript SDK implementation. The incorrect duration value seems to directly originate from the server (so it should also appear in Go, C#, C++ SDKs as well). However, I couldn't find a better place to report it, since Azure Cognitive Services doesn't seem to have a dedicated bug-report mechanism.

Please forward this as needed!

**Comment by yulin-li** [comment]
Thanks for using azure TTS service and report this bug with detailed information. I can repro this bug and we will fix it. As a (maybe ugly) workaround, you can use the audio offset of next word (`was`) as the end audio offset of `21 September 1866 – 13 August 1946`.

**Comment by yulin-li** [comment]
@newhillchan could you help to check?

**Comment by Kerry-LinZhang** [comment]
We have fixed the issue, this can be closed now

**Comment by rotemdan** [comment]
Thanks. Since I don't have an active subscription anymore (trial period expired many months ago), I can't really test it. I'll close the issue.
