### ISSUE TITLE
Token based authentication is broken in Safari

### ISSUE THREAD

**Issue by Domratchev** [microsoft/cognitive-services-speech-sdk-js#57]
There appears to be a feature (bug?) in the latest Safari (v12.1) where an attempt to resume AudioContext upon completion of an async operation fails, even it was initiated by a user action.
This makes it impossible to effectively use AuthorizationToken, as it only makes sense to fetch one upon a user action (e.g. button click) and the fetch has to be asynchronous. Plus there is no way to wait till AudioContext is resumed before supplying the token.

Proposed solution: CognitiveSubscriptionKeyAuthentication class already supports fetch (and fetchOnExpiry) function as a parameter. If it could be passed in via SpeechConfig, the issue would be solved. One obvious obstacle - fetch function returns proprietary Promise. Hence the part of the solution has to be the migration to es6 Promise.

**Comment by rhurey** [comment]
From the behavior I'm seeing in 12.2 on phone, I'd hope bug. (It asks for the microphone permission when the next UI element is pushed, regardless of what)

**Comment by Domratchev** [comment]
HTTPS is a big factor too, BTW

**Comment by rhurey** [comment]
Yes, https is important.

I should mention the workaround of keeping an auth token before the user starts recognition. Yes, that means a call every 9 minutes or so that's not needed, but its unblocking.

We're discussing what the calling pattern for refreshing the auth token should be across all the languages.

**Comment by oscholz** [comment]
@Domratchev Sorry for the long radio silence on this.
We've discussed this, and realistically, we won't get to this anytime in the near future. So we will close this issue. With the above workaround, we hope you can accomplish your end to end use case. In case you cannot, please reopen this issue, and describe your use case so we can see what we might be able to do. In an ideal world, we'd love to fix all issues, but unfortunately we are resource constrained.
