### ISSUE TITLE
Suggestions: create audio worklet blob URL only if `audioContext.audioWorklet` is supported

### ISSUE THREAD

**Issue by compulim** [microsoft/cognitive-services-speech-sdk-js#572]
In [`PCMRecorder.ts`](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/v1.23.0/src/common.browser/PCMRecorder.ts#L86), no matter if `audioContext.audioWorklet` is supported by the browser/environment, it will create audio worklet as blob URL.

I think the better logic should be:

```ts
if (!!context.audioWorklet) {
  if (!this.privSpeechProcessorScript) {
    ...
   this.privSpeechProcessorScript = URL.createObjectURL(blob);
  }

  context.audioWorklet
    .addModule(this.privSpeechProcessorScript)

  ...
}
```

This will help when the SDK is run under JSDOM, such as Jest. This is because [JSDOM does not support `URL.createObjectURL`](https://github.com/jsdom/jsdom/issues/1721).

**Comment by glharper** [comment]
@compulim Thanks for writing this up, and using JS Speech SDK. If you create a PR, I'll test the change.
