### ISSUE TITLE
"Object already disposed" after updating authorizationToken in SpeechRecognizer

### ISSUE THREAD

**Issue by bpampuch** [microsoft/cognitive-services-speech-sdk-js#591]
Version: microsoft-cognitiveservices-speech-sdk@1.24.0

I use ephemeral tokens with Speech Recognizer, with the following initial config:
```ts
  const speechConfig = SpeechSDK.SpeechConfig.fromAuthorizationToken(speechToken, speechApiRegion);
  speechConfig.outputFormat = OutputFormat.Detailed;
  speechConfig.enableDictation();
  speechConfig.speechRecognitionLanguage = speechRecognitionLanguage;
  speechConfig.setProperty(PropertyId.SpeechServiceConnection_InitialSilenceTimeoutMs, "5000");
  speechConfig.setProperty(PropertyId.SpeechServiceConnection_EndSilenceTimeoutMs, "5000");

  const recognizer = new SpeechRecognizer(speechConfig, AudioConfig.fromDefaultMicrophoneInput());

  SpeechRecognizer.enableTelemetry(false);
```

and use `startContinuousRecognitionAsync` to start the recognition

After updating the ephemeral token:
```js
recognizer.authorizationToken = newToken;
```
the recognizer stops working. 

The next  `startContinuousRecognitionAsync` fails silently and under the hood an "Error: the object is already disposed" is being thrown.

My current workaround is to create a new SpeechRecognizer everytime I change the token, but shouldn't setting the `authorizationToken` work for existing recognizers?

**Comment by glharper** [comment]
@bpampuch Thanks for using Speech SDK, and writing this issue up. One quick question, why are you using a different SpeechConfig instance to create the SpeechRecognizer above? Shouldn't the code be:
```
  const recognizer = new SpeechRecognizer(
    speechConfig,
    AudioConfig.fromDefaultMicrophoneInput()
  );
```

**Comment by bpampuch** [comment]
Absolutely ;-) I was pasting two parts of the code and made a mistake while copying ;-) I've updated the original post.

What makes me wonder though is that I can't reproduce this bug at the moment (although I haven't changed the code). It seems to be working properly. I wonder what kind of edge case this might be, but I'd assume it's something on my side. 

I'll close this issue now and if it happens again, I'll try to narrow the repro and I'll get back to you
Thx
