### ISSUE TITLE
[Bug] Continuous recognition not re-starting after stopping programatically

### ISSUE THREAD

**Issue by dhavalsoni2001** [microsoft/cognitive-services-speech-sdk-js#599]
**Describe the bug**

When first time using startContinuousRecognitionAsync Safari prompts correctly for microphone access, I have a 'microphone active' display next to the url, and speech gets recognized. 

As I am integrated GPT3 I am using stopContinuousRecognitionAsync to stop it until GPT 3 respond and after that I start again using startContinuousRecognitionAsync to listen the user but at that time I do not get a microphone access prompt, and there is no 'microphone active' display next to the URL.

We are using SpeechSDK.TranslationRecognizer's recognized method for the capturing the user input but it's never go into that function second time as microphone is not active.

**Expected behavior**
Once I stop using stopContinuousRecognitionAsync and then I again start it using  startContinuousRecognitionAsync it should show the microphone active again and go to recognized method again.

**Version of the Cognitive Services Speech SDK**
I am  using https://aka.ms/csspeech/jsbrowserpackageraw to load the latest SDK.

**Platform, Operating System, and Programming Language**
 - OS: iOS 16.1
 - Hardware - iPhone 13
 - Programming language: Javascript
 - Browser Chrome, Safari

**Comment by glharper** [comment]
@dhavalsoni2001 Thanks for using JS Speech SDK and writing this issue up. Some browsers only allow microphone access after a user interaction, all iOS browsers included. There's no code I can suggest here to work around browser security restrictions like this one.

**Comment by dhavalsoni2001** [comment]
@glharper Just want to confirm it's working on some of the Android Devices e.g. Redmi, Vivo etc. but it's not working on Samsung so is it again related to same issue where each and every time to access microphone we require user interaction?

**Comment by glharper** [comment]
@dhavalsoni2001 Yes. By the way, I seem to recall that a "click" event may count as a user interaction.

**Comment by dhavalsoni2001** [comment]
@glharper I had tried with "click" event as well but it's not working.

**Comment by nygrilla** [comment]
Guys why is it closed?
This bug still exist

**Comment by nygrilla** [comment]
If the coders from Microsoft weren't too lazy to think one step ahead, they would have thought of not turning off the microphone when processing a user response
This forces us to do monkeypatching, here is the solution I found

` 
          const instance = new sdk.SpeechRecognizer(speechConfig, audioConfig);
          const originalTurnOff = instance.audioConfig.privSource.turnOff 
          instance.audioConfig.privSource.turnOff = () => {}
`
