### ISSUE TITLE
Job requests

### ISSUE THREAD

**Issue by YonatanHanan** [microsoft/cognitive-services-speech-sdk-js#602]
Hi,

Is there a way to submit a job to the API?

I want to use the service in a pull method and check after one minute if the transcription is done.

something like:
```
id = createJob(buffer)
if(checkJob(id) === done){
   result = getResult(id)
}
```

**Comment by glharper** [comment]
@YonatanHanan Thanks for writing this up. JS Speech SDK does not support any of the REST batch transcription functionality at this time.
