### ISSUE TITLE
ResourceExhausted issue with some payloads

### ISSUE THREAD

**Issue by lowki** [microsoft/cognitive-services-speech-sdk-js#605]
When I call speech synthetizer via js sdk (latest version), with some payloads, it fails with the following error:

`Status(StatusCode="ResourceExhausted", Detail="the duration of the data sent in mts.v1.InputChannel websocket error code: 101`

But if I send this exact same payload via the REST API, it works just fine.

The error message seems like truncated and doesn't give much informations.

Any help please?

**Comment by yulin-li** [comment]
Thanks for reporting this. `ResourceExhausted` indicates a service error. The service had some outage at that time and it already recoverd.
