### ISSUE TITLE
why there is no stop function.

### ISSUE THREAD

**Issue by FocusThen** [microsoft/cognitive-services-speech-sdk-js#608]
StopSpeakingAsync ?

**Comment by yulin-li** [comment]
For now we don't have `StopSpeakingAsync` api but we have [samples](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/browser/synthesis.html#L337) to show how to stop (pause) the playback.

**Comment by FocusThen** [comment]
Cheers.
