### ISSUE TITLE
SpeechConfig.fromHost vs SpeechConfig.fromEndpoint the differences between them

### ISSUE THREAD

**Issue by ninode97** [microsoft/cognitive-services-speech-sdk-js#609]
Hello everyone. 

I am working on a project that requires an user to provide custom endpoint (on-premises) solution. 
It targets text-to-speech api.

When developing solution on my environment I could generate audio from SSML when creating **SpeechConfig** when using:

- **SpeechConfig.fromHost**
- **SpeechConfig.fromSubscription**

But I wasn't able to successfully  use **SpeechConfig.fromEndpoint**, I would get not found error or, the request would time out. 

When using azure cloud, how to use **fromEndpoint** ? Which endpoint would be correct for **uksouth** region?

**Comment by brandom-msft** [comment]
Hi @ninode97 

Please have a look at [this section of the docs on constructing the endpoint](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-services-private-link?tabs=portal#speech-resource-with-a-custom-domain-name-and-a-private-endpoint-usage-with-the-speech-sdk) URL you'll need. (There you'll also see where you provide the `uksouth` region you mentioned)

Hope this helps and please do reach out with further questions!
