### ISSUE TITLE
[bug] - safari recognition missing phrases between speech

### ISSUE THREAD

**Issue by ygorlf** [microsoft/cognitive-services-speech-sdk-js#622]
**bug Description:**

I have a simple instance of SpeechRecognizer and my goal is to describe patients allergic symptoms using phrases like:

**My name is Mike I am 40 years old and I am allergic to peanut**

Everything works pretty well using chrome but the recognition on IOS is missing phrases between my speech. The results on Safari are inconsistent and give results like:

**My name is Mike I and I'm allergic to peanut.**
**My name is Michael and I'm allergic to.**

**Expected behavior**

The recognition result must be consistent across browsers.

**Version of the Cognitive Services Speech SDK**
I have this same behavior on all versions I tried: 1.24.1, 1.22.0, 1.22.1, 1.20.0

**Code:**
```
class AzureRecognizer {
  mediaSource: any;
  audioConfig: any;
  speechConfig: any;
  recognizer: any;

  constructor(options: Options) {
    this.mediaSource = null;

    this.audioConfig = AudioConfig.fromStreamInput(options.stream);
    this.speechConfig = SpeechConfig.fromSubscription(options.azureKey, 'westus');

    this.speechConfig.speechRecognitionLanguage = "en-US";
    this.speechConfig.endpointId = options.endpointId;

    this.speechConfig.enableDictation();
    this.speechConfig.enableAudioLogging();

    this.recognizer = new SpeechRecognizer(this.speechConfig, this.audioConfig);

    this.recognizer.recognizing = (s: any, e: any) => {
      options.onTranslation(e.result.text);
    };
  
    this.recognizer.recognized = (s: any, e: any) => {
      options.translationEnd(e.result.text);
    };

    return this.recognizer;
  }
}
```

**Platform, Operating System, and Programming Language**
MacOS - Monterey 12.5.1
JavaScript
Node.js v14.18.1

Looking forward to any advice!

**Comment by SMaurischat** [comment]
+1 this is quite critical for us, it seems that the problem lies before sending, since the `con.messageSent ` hook is already missing wav fragments. A quick fix is greatly appreciated!

**Comment by glharper** [comment]
@ygorlf @SMaurischat Thank you for using Speech SDK and for writing this issue up. Can you provide details on the input stream you're sending to AudioConfig.fromStreamInput()? Is it a mediaStream, a resampled file, a microphone input, and what format is the audio?

**Comment by SMaurischat** [comment]
Glad your picking this up so quickly!

!e are directly using the provided fromDefaultMicrophoneInput() like so
`      const tokenObj = await getTokenOrRefresh();
      const audioConfig = AudioConfig.fromDefaultMicrophoneInput();
      const speechConfig = SpeechConfig.fromAuthorizationToken(
        tokenObj.authToken,
        tokenObj.region
      );
      speechConfig.outputFormat = OutputFormat.Detailed;
      speechConfig.setServiceProperty(
        "wordLevelConfidence",
        "true",
        ServicePropertyChannel.UriQueryParameter
      );
      speechConfig.requestWordLevelTimestamps();` 
      
and instanciate the recognizer like so:
      `     const recognizer = SpeechRecognizer.FromConfig(
        speechConfig,
        autoDetectConfig,
        audioConfig
      );`

we then get the connection instance to save the produced wav file into a memory blob for processing to our backend
`      const con = Connection.fromRecognizer(recognizer);
      con.messageSent = (args) => {..`
      
Happy to provide more info if needed!

**Comment by glharper** [comment]
Does the issue still occur when you comment out the lines below?
```
speechConfig.outputFormat = OutputFormat.Detailed; 
speechConfig.setServiceProperty( "wordLevelConfidence", "true", ServicePropertyChannel.UriQueryParameter );
speechConfig.requestWordLevelTimestamps();
```

**Comment by SMaurischat** [comment]
Still occurs.

like so:
`      const autoDetectConfig = AutoDetectSourceLanguageConfig.fromLanguages([
        "en-US",
        "de-DE",
      ]);`

**Comment by glharper** [comment]
@ygorlf @SMaurischat I've repro-ed the dropping of speech phrases after recognized events in the latest version. Today I will test with pre-1.20 versions and figure out if this ever behaved correctly on iOS.

**Comment by SMaurischat** [comment]
I can assure you this worked fine before, not sure when it stopped working though. There was also a recent bug with Webkit, so it somehow could have overlapped and i assumed it was an edge case coupled with this one and then dropped out of my radar: https://github.com/WebKit/WebKit/pull/5855

**Comment by glharper** [comment]
@SMaurischat I've just tested back to v1.15.1, and I'm still seeing missed words after the recognized event on iOS. JS SDK did not test for microphone input on iOS before maybe 1.17, as mic input on iOS browsers wasn't allowed until December 2021, if memory serves. My current guess is this has always been broken on iOS.

**Comment by glharper** [comment]
@ygorlf @SMaurischat Using the same speech cadence in Edge on Windows testing with both the latest and v1.15.1, I'm still seeing dropped words after a recognized event. What appears to be happening is the service returns "No Match: NotRecognized" response immediately after a recognized event. The audio sent that produces that "no match" response may be the "dropped" audio.

Would either of you be able to attach an audio file that demonstrates the exacerbated dropped behavior on iOS, but not on other platforms?

**Comment by ygorlf** [comment]
@glharper thanks for the feedback!

I'm sending a web stream using this method:

```
this.audioConfig = AudioConfig.fromStreamInput(stream);
```

If helps I can record some videos and attach a mp3 file with some phrases I've been trying to transcript in the past days. I can send this later today

**Comment by SMaurischat** [comment]
@glharper check this out, this is a shared audio file in german, you can directly get it from the public s3 bucket url we call for the audio player ;) https://voiceline.me/vl/xSnIoCaQ

**Comment by ygorlf** [comment]
Hi @glharper,

I recorded a successfull transcription attempt using chrome from a mp3 file. I am attaching both the record and the mp3 here. I had never tried to transcript from a sound file before (only from my voice on the browser) and Safari was not able to recognize a single word from the audio. I don't know if anything on my setup is causing this but I think the mp3 and the chrome record will help to understand in what context I am using the library.

[microsoft-recognition-sdk-evidence.zip](https://github.com/microsoft/cognitive-services-speech-sdk-js/files/10702514/microsoft-recognition-sdk-evidence.zip)

**Comment by glharper** [comment]
> Hi @glharper,
> 
> I recorded a successfull transcription attempt using chrome from a mp3 file. I am attaching both the record and the mp3 here. I had never tried to transcript from a sound file before (only from my voice on the browser) and Safari was not able to recognize a single word from the audio. I don't know if anything on my setup is causing this but I think the mp3 and the chrome record will help to understand in what context I am using the library.
> 
> [microsoft-recognition-sdk-evidence.zip](https://github.com/microsoft/cognitive-services-speech-sdk-js/files/10702514/microsoft-recognition-sdk-evidence.zip)

@ygorlf Speech SDK does not support mp3 file input, only wav (PCM/MuLAW/ALAW) currently. I will test using your mp3 over a speaker through the mic on both iOS and Windows browsers, though, and make sure no words are lost.

**Comment by ygorlf** [comment]
@glharper

Sorry, when I said I never tested a mp3 file I mean play an audio to capture from the computer microphone. It will be interesting to convert to WAV and see how it behaves

**Comment by glharper** [comment]
> @glharper check this out, this is a shared audio file in german, you can directly get it from the public s3 bucket url we call for the audio player ;) [voiceline.me/vl/xSnIoCaQ](https://voiceline.me/vl/xSnIoCaQ)

@SMaurischat This audio seems to clip some words. I'm getting a couple of dropped words both on Windows Edge and on iOS Safari, so I can't really see anything conclusively different about usage on those two browser/platform combinations.

**Comment by glharper** [comment]
> @glharper
> 
> Sorry, when I said I never tested a mp3 file I mean play an audio to capture from the computer microphone. It will be interesting to convert to WAV and see how it behaves (although is not my use case)

@ygorlf I played this file (record.mp3) aloud and used fromMicrophoneInput() with JS SDK v1.25.1 on both Windows Edge and iOS Safari, and both captured the full statement without dropping any words.

**Comment by SMaurischat** [comment]
Irrespective of browsers, are you still investigating for a fix here? For us, the whole js package is really unusable with inconsistent transcription. 
On another note, for me as said before, working perfectly on chrome and edge (chromium), not working on safari.

**Comment by glharper** [comment]
@SMaurischat Currently I'm not investigating for a fix, but, on MacOS Safari, I can confirm whether each audio packet read into our audio stream also gets sent out, if that helps.

The audio stream you shared will probably be inconsistently transcribed from a microphone, btw, as words and sentences seem to be jammed together when listening to it.

One more question, the input stream for your use case is 16K 16-bit mono-channel, correct? If it isn't, you may have to set the audioStreamFormat for the AudioStream during setup, as showed [here](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/855f0940284532e369cb6e3ee64cf5c398dad864/tests/SpeechRecognizerTests.ts#L1171).

**Comment by SMaurischat** [comment]
But you could repro lost words after a recognized event and thats not a bug? Or how could you fix this issue then to not lose the words on your side?

To your points:
1. Exactly the investigation we need, yes!
2. Yes totally agree, buts its not the microphone it seems to still be browser related.
3. We are using the fromDefaultMicrophoneInput() method which should do that already, correct?

**Comment by SMaurischat** [comment]
@glharper ?

**Comment by ygorlf** [comment]
@glharper Unfortunately I was not able to succesfully transcribe the audio on my desktop safari (15.16.1), testing on my iphone that runs ios 16.3.1 everything works well. Maybe something broke on Safari 15.X :(

I will update my system and see if there is any difference on Safari 16.

Luckily my project is built to run mostly on mobile devices so I think this issue will not have great impact.

**Comment by ysheep-js** [comment]
I have stuck on this long time. Chrome is good, safari is not. I am willing to help like investigation and others.

**Comment by ysheep-js** [comment]
> 
I have set mic sample rate as 16k
`navigator.mediaDevices.getUserMedia({ audio: { sampleRate: 16000 } }).then(async (micStream) => {...}`
But seems not work in Safari. Establishing the websocket connection still takes time so the first sentence can be lost
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/65909463/231931151-ce7e4f1a-d68f-40a2-a16a-8836687d1a55.png">

**Comment by SMaurischat** [comment]
@glharper is this fixed in a release?
