### ISSUE TITLE
Cannot access 'ConversationServiceRecognizer' before initialization

### ISSUE THREAD

**Issue by maik-parloa** [microsoft/cognitive-services-speech-sdk-js#623]
With the most recent update (1.25.0) to the Speech SDK, we are experiencing an issue when embedding in a React application. Unfortunately, I couldn't check the changes from the most recent version as it does not seem to be published on GitHub (yet). The following exception breaks the application:

```
Uncaught ReferenceError: Cannot access 'ConversationServiceRecognizer' before initialization
    at Module.ConversationServiceRecognizer (ConnectionFactoryBase.ts:73:1)
    at ./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/es2015/src/common.speech/TranslationServiceRecognizer.js (TranslationServiceRecognizer.ts:41:1)
```

- microsoft-cognitiveservices-speech-sdk: `1.25.0`

As the minor version automatically upgrades from e.g. `^1.24.1`, this could be a blocking issue for some integrations.

**Comment by glharper** [comment]
@maik-parloa @ricveal Thank you for using JS Speech SDK, and for writing this issue up. This seems like an import ordering issue with an added class in 1.25.0. If either of you would be willing to test a fix for this issue with a private binary, please email me at <my username>(at)microsoft(dot)com. Thanks.

**Comment by glharper** [comment]
Here is a test binary for this issue: 
[microsoft-cognitiveservices-speech-sdk-1.25.1-alpha.0.1.tgz](https://github.com/microsoft/cognitive-services-speech-sdk-js/files/10548784/microsoft-cognitiveservices-speech-sdk-1.25.1-alpha.0.1.tgz)

**Comment by pthalamy** [comment]
I can confirm that I'm also reproducing this issue after upgrading my React app to `1.25.0`.

**Comment by glharper** [comment]
Test binary for this issue: 
[microsoft-cognitiveservices-speech-sdk-1.25.1-alpha.0.1.tgz.zip](https://github.com/microsoft/cognitive-services-speech-sdk-js/files/10678089/microsoft-cognitiveservices-speech-sdk-1.25.1-alpha.0.1.tgz.zip)

**Comment by pthalamy** [comment]
@glharper I've just tried out running my React app with the supplied binary and did not encounter any issue - the problem seems fixed.

**Comment by glharper** [comment]
@pthalamy Thanks for the feedback. Expect a new release with this bugfix very soon.

**Comment by birla** [comment]
I am also facing this issue. Waiting for the bug fix release.

**Comment by glharper** [comment]
@birla @pthalamy @maik-parloa The bugfix release, v1.25.1, is up in npm [here]:( https://www.npmjs.com/package/microsoft-cognitiveservices-speech-sdk). Our releases page should update with this release soon, but the fix is available. Thanks again for reporting this!
