### ISSUE TITLE
EnableMiscue parameter not working when using javascript Speech SDK

### ISSUE THREAD

**Issue by mikeShout** [microsoft/cognitive-services-speech-sdk-js#631]
The javascript below uses the SpeechSDK.SpeechRecognizer class to return pronunciation assessment results. The code works and I can change pronunciation configuration parameters and see those changes in the results. For example, I can switch GradingSystem between FivePoint and HundredMark. However, when I set enableMiscue to true (it defaults to false), the results do NOT change. The results do not include error types for omission or insertion. It appears the enableMiscue parameter is not working

```
// Set up recognizer
var speechConfig = SpeechSDK.SpeechConfig.fromSubscription("###", "australiaeast");
    speechConfig.speechRecognitionLanguage = "en-US";

    var audioConfig = SpeechSDK.AudioConfig.fromDefaultMicrophoneInput();

    recognizer = new SpeechSDK.SpeechRecognizer(speechConfig, audioConfig);

// Add pronunciation parameters
    var pronunciationConfig = SpeechSDK.PronunciationAssessmentConfig.fromJSON('{"referenceText":"' + referenceText + '","gradingSystem":"HundredMark","granularity":"Word"}');
    pronunciationConfig.enableMiscue = true; // I have also tried including this in the JSON in the line above
    pronunciationConfig.applyTo(recognizer);

// Get results
    recognizer.recognized = function (s, e) {

    let paResult = SpeechSDK.PronunciationAssessmentResult.fromResult(e.result);
}

// starting and stopping using: recognizer.startContinuousRecognitionAsync() and recognizer.stopContinuousRecognitionAsync()
```

**Comment by glharper** [comment]
@mikeShout Thanks for using JS Speech SDK, and writing this issue up. Where are you seeing that enableMiscue is a settable property of the PronunciationAssessmentConfig class in JavaScript? I'm looking [here](https://learn.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/pronunciationassessmentconfig?view=azure-node-latest#properties), but not seeing it.

Could you try setting it in the PronunciationAssessmentConfig constructor, or using this code before calling applyTo():
```
pronunciationConfig.properties.setProperty(SpeechSDK.PropertyId.PronunciationAssessment_EnableMiscue, String(enableMiscue));
```

**Comment by mikeShout** [comment]
@glharper Thank you for looking into this issue. Regarding your point about the line, ```pronunciationConfig.enableMiscue = true; ``` - in retracing my steps, I do not know how I came upon using this! You are right, it is not part of the documentation, so sorry for the extra confusion. 

However, before trying that (and I tried again just now), I used the PronunciationAssessmentConfig constructor like so,
`var pronunciationConfig = SpeechSDK.PronunciationAssessmentConfig.fromJSON('{"referenceText":"' + referenceText + '","gradingSystem":"HundredMark","granularity":"Word","EnableMiscue":"True"}');`
`window.console.log('test: ' + pronunciationConfig.properties.getProperty(SpeechSDK.PropertyId.PronunciationAssessment_EnableMiscue)); `
`pronunciationConfig.applyTo(recognizer);`
This does not work and I see the EnableMiscue property is undefined

I tried your line, however, I do not understand why you have enableMiscue in the String() constructor? I can set the property to true using the code below, but that also does not work.

`var pronunciationConfig = SpeechSDK.PronunciationAssessmentConfig.fromJSON('{"referenceText":"' + referenceText + '","gradingSystem":"HundredMark","granularity":"Word"}');`
`pronunciationConfig.properties.setProperty(SpeechSDK.PropertyId.PronunciationAssessment_EnableMiscue, String(true));`
`window.console.log('test: ' + pronunciationConfig.properties.getProperty(SpeechSDK.PropertyId.PronunciationAssessment_EnableMiscue));`
`pronunciationConfig.applyTo(recognizer);`

**Comment by glharper** [comment]
@mikeShout By constructor, I mean like:
```
    const pronConfig = new SpeechSDK.PronunciationAssessmentConfig("reference",
        PronunciationAssessmentGradingSystem.HundredMark,
        PronunciationAssessmentGranularity.Word, true);
    const j = JSON.parse(pronConfig.toJSON());
    expect(j.enableMiscue).toBeTruthy();
```
I added lines testing the properties to the PronunciationAssessmentTests in the repo, and they seem to pass. Not sure what's happening for your code, perhaps my previous suggestion to use String(true) should be ignored, and you should just use "true", as in:
```
    pronConfig.properties.setProperty(SpeechSDK.PropertyId.PronunciationAssessment_EnableMiscue, "true");
    const j = JSON.parse(pronConfig.toJSON());
    expect(j.enableMiscue).toBeTruthy();
```

**Comment by mikeShout** [comment]
I have tried several variations, but no luck. Should the enableMiscue parameter behave just like the others? Why shouldn't this work?  ```SpeechSDK.PronunciationAssessmentConfig.fromJSON('{"referenceText":"' + referenceText + '","gradingSystem":"HundredMark","granularity":"Word","EnableMiscue":"True"}');```

I tried your above example too, but I am not sure how to use the constant j when applying the configuration to the recognizer, e.g. ```pronConfig.applyTo(recognizer);```

I am going to change my code to use javascript to post an audio variable to PHP and within the PHP use the REST API to get the pronunciation assessment results (avoiding the javascript SpeechRecognizer class). I hope that will work better.

**Comment by mikeShout** [comment]
I have tried several variations, but no luck. Should the enableMiscue parameter behave just like the others, Idont understand why this does not work, ```SpeechSDK.PronunciationAssessmentConfig.fromJSON('{"referenceText":"' + referenceText + '","gradingSystem":"HundredMark","granularity":"Word","EnableMiscue":"True"}');```

I tried your above example too, but I am not sure how to use the constant j when applying the configuration to the recognizer, e.g. ```pronConfig.applyTo(recognizer);```

I am now going to change my code to use javascript to post an audio variable to PHP and then use the REST API to get the pronunciation assessment results (avoiding the j and I am hoping that will work better.

**Comment by glharper** [comment]
@mikeShout In your JSON, "EnableMiscue" should "enableMiscue", and there should not be quotes around "true". So try: `SpeechSDK.PronunciationAssessmentConfig.fromJSON('{"referenceText":"' + referenceText + '","gradingSystem":"HundredMark","granularity":"Word","enableMiscue":true}');`
