### ISSUE TITLE
Speech to Speech translation with one API

### ISSUE THREAD

**Issue by ILG2021** [microsoft/cognitive-services-speech-sdk-js#634]
Hello, I have see the docs says that the sdk can generate speech-to-speech and speech-to-text translations with a single API call, but I could not find it in the sdk really. I still need a recognizer and a TranslationRecognizer and SpeechSynthesizer and connect them to realize a speech to speech translation.

**Comment by glharper** [comment]
@ILG2021 Thanks for using JS SDK, and for writing this issue up. We have a sample demonstrating speech to speech translation using just the TranslationRecognizer [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/js/browser).
