### ISSUE TITLE
Cannot get js sdk functional in Blazor

### ISSUE THREAD

**Issue by Benjamin1973** [microsoft/cognitive-services-speech-sdk-js#651]
**Short version:** after reading through all the online docs, and going through the sample "synthesis" project for js/browser for several days, I cannot find any way to get the package loaded and ready to use in Blazor using JS Interop.  I've tried very hard to understand the docs and samples, but cannot find my way without further assistance.

**Long version:**
Installation instructions for the "browser" flavor just says to download the bundle and include it in the head of an html file:

`<script src="microsoft.cognitiveservices.speech.sdk.bundle.js"></script>`

Okay, in Blazor, I add that to `_Host.cshtml` with my other .js declarations. I was happy, because I'm done a fair bit of JS Interop of my own, and this was feeling pretty simple so far.  But now what?

The next section, Use the Speech SDK, tells me to:
`import * as sdk from "microsoft-cognitiveservices-speech-sdk";`
This throws an error in the browser: complaining that the response is text, not a module and telling me if it's relative, I need to prefix sith "/, ./, ../". I read on the internet this means I'm most likely trying to use the module from a subfolder (which I am), but since I'm not trying to use Node.js, but instead the js/browser flavor, I reckon I'm lost and try to load directly from the file:

`import * as sdk from "/code/js/microsoft.cognitiveservices.speech.sdk.bundle.js"` in the .js file where I wanted to use the sdk, as it at least didn't through an error, but nope, every method like `sdk.SpeechConfig.fromSubscription(subscriptionKey.value, regionOptions.value);` was undefined.

I also tried running the browser-based samples, which worked out of the box, putting
`<script src="https://aka.ms/csspeech/jsbrowserpackageraw"></script>` and
`<script src="https://unpkg.com/axios/dist/axios.min.js"></script>`
in _Hosts.cshtml, and moving the rest of the scripts to a separate .js file, but the SDK never resolved, and I have no idea where even to start fixing that.

Is anyone able to give simple and concise directions on how to use the sdk in Blazor?

**Comment by glharper** [comment]
@Benjamin1973 Thank you for using JS Speech SDK, and writing this issue up. It would appear an example blazor integration repo using our library would be useful to our dev community.

For this issue, I'd try importing specific classes one by one and seeing if that helps. For example:
`
import { SpeechConfig } from "microsoft-cognitiveservices-speech-sdk";
`
Failing that, [this comment ](https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/477#issuecomment-1050115266) may help as well. Once I have allocation, I'll get a blazor sample repo up and see what's causing this issue.

**Comment by Benjamin1973** [comment]
ty for your quick response.  The sample project blew me away, and I'll be happy when I can get the sdk working.

**Comment by Benjamin1973** [comment]
I should mention that I'm using the Blazor server flavor, and my reason for using the js SDK isn't that the .net client doesnt work-- (I haven't got it to work yet, but I no longer care)-- it's that I don't want 1000 users burning a hole through my VM's CPU / storage.

**Comment by glharper** [comment]
@Benjamin1973 Didn't parse that your code is browser based. As you've realized and stated, the lib code needs to be resolved before being referred to.

FYI, I'll be using [this project/code](https://github.com/conficient/BlazorDynamicScriptLoad/blob/master/BlazorDynamicScriptLoad/Pages/Index.razor) as a starting point for JS integration. Would that approach mesh with "letting the client browser do the heavy lifting"? 

Once I start that integration, I'll probably have a better idea of what's needed for your approach. 

Also, regarding using the C# Speech SDK, Blazor integration requires WASM WebAssembly support for .NET dependencies, correct? There are no plans to add such support to the C# Speech SDK at the moment.

**Comment by glharper** [comment]
@Benjamin1973 Got it working via static import, kinda dirty, but should do what you need. If you have tips for best practices using webpack to allow module imports, I'm all ears.

repo [here](https://github.com/glharper/BlazorApp).

**Comment by Benjamin1973** [comment]
Thanks for the demo-- it couldn't be simpler.

This line in the packager made me cry a little bit:
`window.SpeechSDK = __webpack_require__(1);`

I've probably had a working SDK on my system several times in the last few days and not known it.  I'm starting to think that it's worth actually buckling down and properly learning JavaScript.

As you say, it would be nice to load it dynamically, but 1.4MB in Korea is probably about 0.01s of downloading for most customers.
