### ISSUE TITLE
Streaming audio data from a browser to a node server and then to Azure speech-to-text

### ISSUE THREAD

**Issue by tritos-design** [microsoft/cognitive-services-speech-sdk-js#655]
Is there a cross-browser way to record audio data in a browser, stream it to a Node server and from there forward it to Azure STT?

I am aware of the SDK for JavaScript and I checked the examples for sending data from the browser directly to Azure or from Node directly to Azure. However, what I would like to do is to record an audio stream in the browser, stream it to the Node server (in best case while the recording is still running; using MediaRecorder's `ondataavailable` method?) and then send a request from the Node server to Azure STT.

The building blocks must be in the SDK code, but can such a setup be achieved with native SDK functions?

The whole setup should work cross-browser as does the Azure JavaScript SDK.

Thanks in advance for any help!

Best regards,
Steffen

**Comment by M-Hietala** [comment]
As you mentioned, you could use the SDK to send the data from Node server to Azure, but relaying the data from browser to 3rd party service and then to Azure is not directly supported in the SDK. You can find some additional info around similar topic here: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1895

**Comment by codylittle** [comment]
@tritos-design did you ever get this working? We're trying to do something similar
