### ISSUE TITLE
[question]  An error occurred while use recognizeOnceAsync   

### ISSUE THREAD

**Issue by liou666** [microsoft/cognitive-services-speech-sdk-js#665]
When I use recognizeOnceAsync for speech recognition, an error occurs, the error message is as follows,

`WebSocket connection to 'wss://eastasia.stt.speech.microsoft.com/speech/recognition/interactive/cognitiveservices/v1?language=en-US&format=simple&Ocp-Apim-Subscription-Key=<KEY>&XConnectionId=9BAEDD0494844CFAB6C982B74551DAA3' failed: Error in connection establishment: net::ERR_PROXY_CONNECTION_FAILED`

```js
// my code
 recognizer.value.recognizeOnceAsync((result) => {
        if (result.text) {
          isRecognizing.value = false
          resolve(result.text)
        }
        else {
          console.log(result)
          isRecognizing.value = false
          reject(new Error(`未识别到任何内容-${language.value}`),
          )
        }
      }
```

I am using windows10 system，microsoft-cognitiveservices-speech-sdk@1.26.0

can you give me some help thank you

**Comment by glharper** [comment]
@liou666 Thanks for using JS Speech SDK and writing this issue up. First, I updated your comment to remove your subscription key information, posting that in public is not a good idea. For your issue, it would appear your network's topology is not allowing a connection to the eastasia Azure endpoint. If you're running this code via Node.js, the SDK provides a SpeechConfig.setProxy API, with example usage [here](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/628d560d5a96f05ebd39424613604ea68ae9337f/tests/ConnectionTests.ts#L81).

Try using that API with your proxy info and see if that helps.

**Comment by liou666** [comment]
Thank you for your reply, I have no problem after trying to use proxy, thank you
