### ISSUE TITLE
Issue with Rollup, StencilJS, and Node Pollyfills

### ISSUE THREAD

**Issue by Checkroth** [microsoft/cognitive-services-speech-sdk-js#668]
Referencing a similar issue in `azure-sdk-for-js` : https://github.com/Azure/azure-sdk-for-js/issues/23051

Packaging cognitive-services-speech-sdk-js for web does not seem to play nicely with pollyfills.

I have tried to set up a repository that reproduces the issue to no avail. I suspect this could be an issue with stencil, webpack, rollup, azure sdk itself. THe post in the azure-sdk-for-js appears to have been fruitful, I'm sorry if this is the wrong place to ask this.

I have tried tried the solution listed in the linked issue, but it has the exact same result.
Removing the cognitive services sdk from our stencil components resolves the issue.

## The Error

```
Compiled with problems:
×
ERROR
Cannot read properties of undefined (reading 'env')
TypeError: Cannot read properties of undefined (reading 'env')
    at eval (webpack-internal:///./node_modules/tt-components/dist/esm/sttQueueEngine-b2274a9b.js:12364:15)
    at createCommonjsModule (webpack-internal:///./node_modules/tt-components/dist/esm/punycode-3971ef08.js:17:5)
    at eval (webpack-internal:///./node_modules/tt-components/dist/esm/sttQueueEngine-b2274a9b.js:12255:68)
    at ./node_modules/tt-components/dist/esm/sttQueueEngine-b2274a9b.js (http://localhost:8080/js/chunk-vendors.js:73:1)
    at __webpack_require__ (http://localhost:8080/js/app.js:9646:33)
    at fn (http://localhost:8080/js/app.js:9943:21)
    at eval (webpack-internal:///./node_modules/tt-components/dist/esm/index.js:17:85)
    at ./node_modules/@joyzartifact/tt-components/dist/esm/index.js (http://localhost:8080/js/chunk-vendors.js:29:1)
    at __webpack_require__ (http://localhost:8080/js/app.js:9646:33)
    at fn (http://localhost:8080/js/app.js:9943:21)
```

The references to `sttQueueEngine` are our stencil component utility that uses the cognitive services speech sdk. Simply including it causes this error.

## Stencil Project

`package.json` dependencies:

```
  "dependencies": {
    "@picovoice/web-voice-processor": "4.0.6",
    "@stencil/core": "3.1.0",
    "markdown-it": "13.0.1",
    "microsoft-cognitiveservices-speech-sdk": "1.25.1",
    "wavefile": "11.0.0"
  },
```

`stencil.config.js`:

```
import { Config } from '@stencil/core'
import dotenv from 'rollup-plugin-dotenv'
import nodePolyfills from 'rollup-plugin-node-polyfills'

export const config: Config = {
  globalStyle: 'src/css-variables/ttui-css-variables.css',
  namespace: 'tt-components',
  rollupPlugins: {
    before: [dotenv()],
    after: [nodePolyfills()],
  },
  testing: {
    browserArgs: ['--no-sandbox', '--disable-setuid-sandbox'],
    verbose: true,
  },
  outputTargets: [
    {
      type: 'dist',
      esmLoaderPath: '../loader',
    },
    {
      type: 'dist-custom-elements',
    },
    {
      type: 'docs-readme',
    },
    {
      type: 'www',
      serviceWorker: null, // disable service workers
    },
  ],
}
```

## Vue Project

The vue project is a little outdated -- it is vue2 + webpack.

Package.json dependencies (there are some duplicates as we are migrating things out of the vue project to the stencil components).

The `tt-components` (our component library from above) dependency is a local tarball in an attempt to reproduce the issue, but it is also published in a private npm repository.

```
  "dependencies": {
    "tt-components": "../tt-ui/tt-components/tt-components-0.0.3-beta.2.tgz",
    "@kangc/v-md-editor": "1.7.11",
    "aws-sdk": "2.1139.0",
    "axios": "0.27.2",
    "chart.js": "3.7.1",
    "chartjs-adapter-date-fns": "2.0.0",
    "date-fns": "2.28.0",
    "furigana-markdown-it": "1.0.3",
    "markdown-it": "13.0.1",
    "microsoft-cognitiveservices-speech-sdk": "1.21.1",
    "mpg123-decoder": "0.3.8",
    "onesignal-vue": "1.0.2",
    "raw-loader": "4.0.2",
    "string.prototype.replaceall": "1.0.6",
    "util": "0.12.4",
    "uuid": "8.3.2",
    "v-calendar": "2.4.1",
    "vue": "2.7.7",
    "vue-chartjs": "4.1.0",
    "vue-router": "3.5.4",
    "vuex": "3.6.2"
  },
```

**Comment by glharper** [comment]
@Checkroth Thank you for using JS Speech SDK, and writing this issue up. I've actually checked in code recently to make the library easier to integrate. Would you mind updating your dependencies to 1.28.0-beta.1 to see if my recent changes help with this issue?

**Comment by Checkroth** [comment]
@glharper

Thank you so much! `1.28.0-beta.1` unilaterally fixed our issues.

For reference, the issues outlined here: https://github.com/Azure/azure-sdk-for-js/issues/23051 were also not necessary with 1.28.0-beta.1.

Our rollup plugins with dotenv and node pollyfills now work perfectly

```
  rollupPlugins: {
    before: [dotenv()],
    after: [nodePolyfills()],
  },
```

Is there a target date for a non-beta release of 1.28.0?

**Comment by glharper** [comment]
@Checkroth The current timeframe for the 1.28.0 release is end of next week or beginning of May.

**Comment by glharper** [comment]
Release is pending, closing this issue.
