### ISSUE TITLE
speckTextAsync not working properly

### ISSUE THREAD

**Issue by kinjal-mori** [microsoft/cognitive-services-speech-sdk-js#669]
```ts
  const handleSpeak = (text:string) => {
    // use the SpeechSynthesizer object to synthesize the text and play it
    const result = synthesizer.speakTextAsync(text);
    console.log({result})
    if (result) {
      result.onSuccess = () => {
        console.log('Speech synthesized and played');
      };
      result.onError = (error) => {
        console.error(error);
      };
      result.onAudioEnd = () => {
        console.log('Speech synthesis complete');
      };
      result.onCanceled = (reason) => {
          console.log(reason);
      };
    }
  };
```

Always getting result as undefined, Once voice audio is complete i want trigger but its not working, 

I have tried another way also 

```ts
const handleSpeak = (text:string) => {
  return new Promise((resolve, reject) => {
    synthesizer.speakTextAsync(text, (result) => {
      if (result.reason === ResultReason.SynthesizingAudioCompleted) {
        // onEnd();
        console.log("synthesis finished.");
        result.onAudioEnd = () => {
          console.log('Speech synthesis complete');
        };
      resolve();
    } else {
      reject(new Error(`Speech synthesis failed with reason: ${result.reason}`));
    }
  });
});
```

Above code is getting "synthesis finished" console before audio has complete.

"microsoft-cognitiveservices-speech-sdk": "^1.27.0",

**Comment by kinjal-mori** [comment]
any update on this?

**Comment by ralph-msft** [comment]
Unfortunately, you are not using the SpeechSynthesizer API correctly. In your first code snippet, ```speakTextAsync``` doesn't have a return value. In your second code snippet ```result``` doesn't have an ```onAudioEnd()``` event.

For your reference:
- [Speech Synthesizer Quick Start](https://learn.microsoft.com/azure/cognitive-services/speech-service/get-started-text-to-speech?tabs=windows%2Cterminal&pivots=programming-language-javascript)
- [Example of using speech synthesis in a web browser](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/browser/synthesis.html)
- [Example of using speech synthesis in Node.js](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/node/synthesis.js)
- JS SDK API reference
  - [SpeechSynthesizer](https://learn.microsoft.com/javascript/api/microsoft-cognitiveservices-speech-sdk/speechsynthesizer?view=azure-node-latest#microsoft-cognitiveservices-speech-sdk-speechsynthesizer-speaktextasync)
  - [SpeechSynthesisResult](https://learn.microsoft.com/javascript/api/microsoft-cognitiveservices-speech-sdk/speechsynthesisresult?view=azure-node-latest)

**Comment by kinjal-mori** [comment]
@ralph-msft  Thanks for your respone.

In first code we have no return value then how do i know that audio speaking is finished? I want that trigger that audio speaking is getting finished.

**Comment by ralph-msft** [comment]
In the success callback function you pass to the ```speakTextAsync```, you can check to see if the ```reason``` property of the ```result``` argument is equal to ```ResultReason.SynthesizingAudioCompleted```.

For example:
```js
const speechConfig = SpeechConfig.fromSubscription(subscriptionKey, serviceRegion);
const audioConfig = AudioConfig.fromAudioFileOutput("c:\\temp\\synthesis.wav");

const synth = new SpeechSynthesizer(speechConfig, audioConfig);
synth.speakTextAsync(
    "This is a short test message.",
    (result) => {
        if (result.reason == ResultReason.SynthesizingAudioCompleted) {
            console.log("Speech synthesis completed");
        } else {
            console.log("Speech synthesis was cancelled. Error: " + result.errorDetails);
        }
        synth.close();
    },
    (error) => {
        console.log("Failed to start synthesizing. Error: " + error);
        synth.close();
    }
);
```

**Comment by jackiealex** [comment]
> ResultReason

that means synthesis complete,  rather than the audio playback ending

**Comment by jackiealex** [comment]
> In the success callback function you pass to the `speakTextAsync`, you can check to see if the `reason` property of the `result` argument is equal to `ResultReason.SynthesizingAudioCompleted`.
> 
> For example:
> 
> ```js
> const speechConfig = SpeechConfig.fromSubscription(subscriptionKey, serviceRegion);
> const audioConfig = AudioConfig.fromAudioFileOutput("c:\\temp\\synthesis.wav");
> 
> const synth = new SpeechSynthesizer(speechConfig, audioConfig);
> synth.speakTextAsync(
>     "This is a short test message.",
>     (result) => {
>         if (result.reason == ResultReason.SynthesizingAudioCompleted) {
>             console.log("Speech synthesis completed");
>         } else {
>             console.log("Speech synthesis was cancelled. Error: " + result.errorDetails);
>         }
>         synth.close();
>     },
>     (error) => {
>         console.log("Failed to start synthesizing. Error: " + error);
>         synth.close();
>     }
> );
> ```

that issue should not have ended, but...
