### ISSUE TITLE
Disabling Disfluency / enabling TrueText

### ISSUE THREAD

**Issue by daniel112** [microsoft/cognitive-services-speech-sdk-js#670]
I want to be able to recognize and transcribe filler words through a live feed. According to the code documentation, it seems like I should be able to disable `Disfluency` by setting this property below, but it doesn't seem to work.

![image](https://user-images.githubusercontent.com/3317835/233571678-ffc3ad2f-14ce-4128-a974-21d59fa1c622.png)

```js
const speechConfig = speechsdk.SpeechConfig.fromAuthorizationToken(
      tokenObj.authToken,
      tokenObj.region
    );
    speechConfig.outputFormat = speechsdk.OutputFormat.Detailed;
    speechConfig.setProperty(
      speechsdk.PropertyId.SpeechServiceResponse_PostProcessingOption,
      "TrueText"
    ); // <-- this property

    var convLanguage = document.getElementById("formSelectConvLanguage").value;

    speechConfig.speechRecognitionLanguage = convLanguage;
    const audioConfig = speechsdk.AudioConfig.fromDefaultMicrophoneInput();
    recognizer = new speechsdk.SpeechRecognizer(speechConfig, audioConfig);
```

Adding 
```js
 speechConfig.setProperty(
      speechsdk.PropertyId.SpeechServiceResponse_PostProcessingOption,
      "TrueText"
    ); 
```

still is skipping my filler words through the Mike. Am I missing something?

**Comment by glharper** [comment]
@daniel112 Thank you for using the Speech SDK, and writing this issue up. Apparently for the SpeechServiceResponse_PostProcessingOption property, "default" is suppose to leave in the Disfluency words, while "TrueText" would filter them out.

If the "default" option filters out filler words from recognized text, or you want to use TrueText to get proper punctuation, but still want to see Disfluencies, you might set the speech Output format to "detailed" and then parse the output json for the DLP output and look at the "Pronunciation" and "Lexical" forms to see if all three are filtered.  (Thanks @BrianMouncer for this advice.)

**Comment by daniel112** [comment]
> @daniel112 Thank you for using the Speech SDK, and writing this issue up. Apparently for the SpeechServiceResponse_PostProcessingOption property, "default" is suppose to leave in the Disfluency words, while "TrueText" would filter them out.
> 
> If the "default" option filters out filler words from recognized text, or you want to use TrueText to get proper punctuation, but still want to see Disfluencies, you might set the speech Output format to "detailed" and then parse the output json for the DLP output and look at the "Pronunciation" and "Lexical" forms to see if all three are filtered.  (Thanks @BrianMouncer for this advice.)

Thanks @glharper,
setting it to `default` works for me on the default `speechConfig`. Could we update the documentations to reflect that?

could you give me a quick walkthrough on how I can set `SpeechServiceResponse_PostProcessingOption` for a `speechTranslation` config? I'm able to set it for the default speechConfig, but not translation speech config

```ts
 const tokenObj = await getAzSpeechToken();
      const audioConfig = speechSDK.AudioConfig.fromDefaultMicrophoneInput();

      const speechConfig =
        speechSDK.SpeechTranslationConfig.fromAuthorizationToken(
          tokenObj.authToken!,
          tokenObj.region!
        );
      speechConfig.outputFormat = speechSDK.OutputFormat.Detailed;
      speechConfig.setProperty(
        speechSDK.PropertyId.SpeechServiceResponse_PostProcessingOption,
        "default"
      );

      speechConfig.addTargetLanguage(languageToRef.current.iso);
      speechConfig.speechRecognitionLanguage = "en-US";
      var translationRecognizer = new speechSDK.TranslationRecognizer(
        speechConfig,
        audioConfig
      );
```


![image](https://user-images.githubusercontent.com/3317835/234346104-ecbca428-ba59-4187-b5c9-ab94117ed265.png)

**Comment by daniel112** [comment]
> If the "default" option filters out filler words from recognized text, or you want to use TrueText to get proper punctuation, but still want to see Disfluencies, you might set the speech Output format to "detailed" and then parse the output json for the DLP output and look at the "Pronunciation" and "Lexical" forms to see if all three are filtered.

@glharper 
I am attempting to test this out by adding this line `speechConfig.outputFormat = speechSDK.OutputFormat.Detailed;`
and then logging out the entire event object onRecognized (screenshot below)

![image](https://user-images.githubusercontent.com/3317835/234352391-94e1b23e-3477-40b7-a96c-9fe4bb8a3dbf.png)

Am I looking in the right place?

The JSON I see does not seem to have the properties you mentioned.

![image](https://user-images.githubusercontent.com/3317835/234358457-809d5706-52c3-4a09-8093-7e87d81b9f03.png)

**Comment by daniel112** [comment]
> @daniel112 I had assumed this issue solely concerned speech recognition scenarios. Where are you finding documentation that disfluency is available with translation scenarios?

I didn't find exact documentation but saw these posts
- https://learn.microsoft.com/en-us/answers/questions/1122802/speech-to-text-how-to-config-disfluency-removal
- https://learn.microsoft.com/en-us/answers/questions/1131875/speech-to-text-disfluency-removal-configuration

it looks like it does work though, because I tried below, by hardcoding the string value instead of using the id:
```ts
const tokenObj = await getAzSpeechToken();
      const audioConfig = speechSDK.AudioConfig.fromDefaultMicrophoneInput();

      const speechConfig =
        speechSDK.SpeechTranslationConfig.fromAuthorizationToken(
          tokenObj.authToken!,
          tokenObj.region!
        );
      speechConfig.outputFormat = speechSDK.OutputFormat.Detailed;
      speechConfig.setProperty(
        "SpeechServiceResponse_PostProcessingOption", //speechSDK.PropertyId.SpeechServiceResponse_PostProcessingOption,
        "default"
      );
      console.log(speechConfig);
      speechConfig.addTargetLanguage(languageToRef.current.iso);
      speechConfig.speechRecognitionLanguage = "en-US";
      var translationRecognizer = new speechSDK.TranslationRecognizer(
        speechConfig,
        audioConfig
      );

```

the resulting translation is not accurate at all on the filler words, but it is capturing them pre-translation
![image](https://user-images.githubusercontent.com/3317835/234411935-8a00d44d-cb1d-404d-8d3d-ad78ac1c62cd.png)

**Comment by glharper** [comment]
> We should maybe also update the setProperty method of SpeechTranslationConfig to also accept ids, similar to the non translationConfig. Otherwise, it's very difficult to know what properties we can set

Agreed, I'll put in a PR for this now.

**Comment by daniel112** [comment]
@glharper 
do you have any insight regarding my question on Detailed output format?
https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/670#issuecomment-1522173453

**Comment by glharper** [comment]
@daniel112 I don't believe the intermediate translation results have "Lexical" or "Pronunciation" fields currently, my previous answer was in the context of Speech Recognition, not Translation. It would appear the text and translation properties in the intermediate results are the only way currently to see filler words.

**Comment by daniel112** [comment]
> @daniel112 I don't believe the intermediate translation results have "Lexical" or "Pronunciation" fields currently, my previous answer was in the context of Speech Recognition, not Translation. It would appear the text and translation properties in the intermediate Translation results are the only way currently to see filler words for translation scenarios.

Thank you. I appreciate the prompt responses :)

**Comment by maivanchuong95** [comment]
Hi @daniel112, how do I know if Disfluency Removal is working or not?
Thanks.

**Comment by daniel112** [comment]
> Hi @glharper, how do I know if Disfluency Removal is working or not?
> 
> Thanks.

Start recording or audio transcription with audio containing filler words like "umm", "uhh" etc.
If it doesn't filter it out then disfluency removal is off

**Comment by maivanchuong95** [comment]
> > Hi @glharper, how do I know if Disfluency Removal is working or not?
> > Thanks.
> 
> Start recording or audio transcription with audio containing filler words like "umm", "uhh" etc. If it doesn't filter it out then disfluency removal is off

Hi @daniel112, I have configured: speechConfig.SetProperty(PropertyId.SpeechServiceResponse_PostProcessingOption, "TrueText"); in the .NET SDK. But it feels like it's still not working very well. Sometimes remove, sometimes not remove. Is there any config to increase its performance?

**Comment by maivanchuong95** [comment]
> > Hi @glharper, how do I know if Disfluency Removal is working or not?
> > Thanks.
> 
> Start recording or audio transcription with audio containing filler words like "umm", "uhh" etc. If it doesn't filter it out then disfluency removal is off

I use SpeechRecognizer real-time from microphone, will this function support? What functions does it currently support?
Thank.

**Comment by daniel112** [comment]
> > > Hi @glharper, how do I know if Disfluency Removal is working or not?
> 
> > > Thanks.
> 
> > 
> 
> > Start recording or audio transcription with audio containing filler words like "umm", "uhh" etc. If it doesn't filter it out then disfluency removal is off
> 
> 
> 
> Hi @daniel112, I have configured: speechConfig.SetProperty(PropertyId.SpeechServiceResponse_PostProcessingOption, "TrueText"); in the .NET SDK. But it feels like it's still not working very well. Sometimes remove, sometimes not remove. Is there any config to increase its performance?


When I was testing. I think after the "recognized" callback, what gets returned is still somewhat a formatted version.  Like when I extend my "ummmmmms" it still result in "umm".

Maybe you can show some of the code and or video testing showing the output?

**Comment by daniel112** [comment]
> > > Hi @glharper, how do I know if Disfluency Removal is working or not?
> 
> > > Thanks.
> 
> > 
> 
> > Start recording or audio transcription with audio containing filler words like "umm", "uhh" etc. If it doesn't filter it out then disfluency removal is off
> 
> 
> 
> I use SpeechRecognizer real-time from microphone, will this function support? What functions does it currently support?
> 
> Thank.

Are you doing English voice or another language? Disfluency removal in other languages aren't as precise

**Comment by maivanchuong95** [comment]
> > > > Hi @glharper, how do I know if Disfluency Removal is working or not?
> > 
> > 
> > > > Thanks.
> > 
> > 
> > > 
> > 
> > 
> > > Start recording or audio transcription with audio containing filler words like "umm", "uhh" etc. If it doesn't filter it out then disfluency removal is off
> > 
> > 
> > I use SpeechRecognizer real-time from microphone, will this function support? What functions does it currently support?
> > Thank.
> 
> Are you doing English voice or another language? Disfluency removal in other languages aren't as precise

With English Australia.

**Comment by maivanchuong95** [comment]
> > > > Hi @glharper, how do I know if Disfluency Removal is working or not?
> > 
> > 
> > > > Thanks.
> > 
> > 
> > > 
> > 
> > 
> > > Start recording or audio transcription with audio containing filler words like "umm", "uhh" etc. If it doesn't filter it out then disfluency removal is off
> > 
> > 
> > Hi @daniel112, I have configured: speechConfig.SetProperty(PropertyId.SpeechServiceResponse_PostProcessingOption, "TrueText"); in the .NET SDK. But it feels like it's still not working very well. Sometimes remove, sometimes not remove. Is there any config to increase its performance?
> 
> When I was testing. I think after the "recognized" callback, what gets returned is still somewhat a formatted version. Like when I extend my "ummmmmms" it still result in "umm".
> 
> Maybe you can show some of the code and or video testing showing the output?
Can I see its result after removing noise in Detail Results json?

**Comment by maivanchuong95** [comment]
> > > > Hi @glharper, how do I know if Disfluency Removal is working or not?
> > 
> > 
> > > > Thanks.
> > 
> > 
> > > 
> > 
> > 
> > > Start recording or audio transcription with audio containing filler words like "umm", "uhh" etc. If it doesn't filter it out then disfluency removal is off
> > 
> > 
> > I use SpeechRecognizer real-time from microphone, will this function support? What functions does it currently support?
> > Thank.
> 
> Are you doing English voice or another language? Disfluency removal in other languages aren't as precise

Can I see its result after removing noise in Detail Results json?

**Comment by daniel112** [comment]
> > > > > Hi @glharper, how do I know if Disfluency Removal is working or not?
> 
> > > 
> 
> > > 
> 
> > > > > Thanks.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Start recording or audio transcription with audio containing filler words like "umm", "uhh" etc. If it doesn't filter it out then disfluency removal is off
> 
> > > 
> 
> > > 
> 
> > > I use SpeechRecognizer real-time from microphone, will this function support? What functions does it currently support?
> 
> > > Thank.
> 
> > 
> 
> > Are you doing English voice or another language? Disfluency removal in other languages aren't as precise
> 
> 
> 
> Can I see its result after removing disfluency in Detail Results json?

Check the onRecognizing callback and print out the text result
