### ISSUE TITLE
How to solve this Error ? 'TypeError: Class extends value undefined is not a constructor or null'

### ISSUE THREAD

**Issue by chengfengfengwang** [microsoft/cognitive-services-speech-sdk-js#673]
I am developing a web app using webpack, but i encounter an error in browser log: 'TypeError: Class extends value undefined is not a constructor or null at microsoft-cognitiveservices-speech-sdk.js:559:37'.

repro steps：
1. git clone https://github.com/chengfengfengwang/bug-report.git
2. npx webpack
3. run a web server in dist folder and see browser log
Am I using it improperly？

**Comment by glharper** [comment]
@chengfengfengwang Thank you for using Speech SDK, and reporting this issue. Would you mind using our latest beta version, 1.28.0-beta.1, and seeing if this still happens?

I tried reproing using the steps listed above, but got "Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported" when running "node dist/main.js" on MacOS.
