### ISSUE TITLE
[Question] - PT-BR Blendshapes

### ISSUE THREAD

**Issue by ygorlf** [microsoft/cognitive-services-speech-sdk-js#676]
There is plan to support blendshapes for other languages? Specially Brazilian Portuguese.

I am developing a digital assistant and the 3d blendshapes in english work pretty well, but I need to support the assistant in my native language as well.

**Comment by brandom-msft** [comment]
We don't have any published timelines for additional language support, but customer feedback like you've provided is a great signal for us to capture. 

As you've mentioned, currently there is blendshape support for `en-us` and `zh-cn`.  ([More info](https://learn.microsoft.com/azure/cognitive-services/speech-service/how-to-speech-synthesis-viseme?pivots=programming-language-javascript&tabs=visemeid))

You can also check back on [this page on language support](https://learn.microsoft.com/azure/cognitive-services/speech-service/language-support?tabs=tts) for future updates.

Tagging @yulin-li as an FYI

**Comment by yulin-li** [comment]
Thanks for using blendshapes feature and we will add `pt-br` support, I will update this issue.

**Comment by ygorlf** [comment]
Hi @yulin-li, this is great, I'll be checking this issue to be up to date!

Have a nice week :)

**Comment by yulin-li** [comment]
The support was added to our service and deployed.
