### ISSUE TITLE
SpeechConfig.EnableDictation method cannot recognize the punctuation word in the speech

### ISSUE THREAD

**Issue by KwFung7** [microsoft/cognitive-services-speech-sdk-js#686]
**Describe the bug**
I have implemented the speech-to-text feature into existing React application with Microsoft Speech JS SDK.
My Product Owner reported that the SDK cannot recognize punctuation in the speech. For example, we expected that saying "question mark" will add a question mark to the sentence when dictation is enabled, instead of printing the actual word.

**To Reproduce**
1. Import the Speech JS SDK
2. Enable the EnableDictation in SpeechConfig
https://learn.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/speechconfig?view=azure-node-latest#microsoft-cognitiveservices-speech-sdk-speechconfig-enabledictation
4. Enable the speech recording and say "question mark" in the speech

**Expected behavior**
When I set the EnableDictation in SpeechConfig to true, the Speech SDK should be able to recognize the punctuation in the speech and return the punctuation after recognization process, instead of printing out the word.

**Version of the Cognitive Services Speech SDK**
[Speech SDK 1.28.0](https://github.com/microsoft/cognitive-services-speech-sdk-js/releases/tag/v1.28.0)

**Platform, Operating System, and Programming Language**
React application, Chrome browser v114, Window 10

**Comment by glharper** [comment]
@KwFung7 Thank you for using the JS Speech SDK and writing this issue up. Which method are you using to start speech recognition?

**Comment by KwFung7** [comment]
@glharper Kindly refer to below coding snippet

```
const audioConfig = SpeechSDK.AudioConfig.fromDefaultMicrophoneInput();
const speechConfig = SpeechSDK.SpeechConfig.fromEndpoint(endpoint, apiKey);
const recognizer = new SpeechSDK.SpeechRecognizer(speechConfig, audioConfig);
recognizer.startContinuousRecognitionAsync();
```

**Comment by glharper** [comment]
> @glharper Kindly refer to below coding snippet
> 
> ```
> const audioConfig = SpeechSDK.AudioConfig.fromDefaultMicrophoneInput();
> const speechConfig = SpeechSDK.SpeechConfig.fromEndpoint(endpoint, apiKey);
> const recognizer = new SpeechSDK.SpeechRecognizer(speechConfig, audioConfig);
> recognizer.startContinuousRecognitionAsync();
> ```

@KwFung7 Thank you for the reply. To enable dictation, you are using the code `speechConfig.enableDictation();`, correct, and not setting the non-existant enableDictation property?

**Comment by KwFung7** [comment]
@glharper Thanks for the quick follow up,
As I'm working in banking industy, I cannot directly copy the original code and paste here as its confidential.
so I just briefly typed the above snippet to explain how I start the speech recognition.
I have added `speechConfig.enableDictation();` in my original code but the issue still happened.

**Comment by glharper** [comment]
@KwFung7 Testing this on v1.30.1, I'm seeing that intermediate results do not convert words like "question mark" to punctuation, but final results do. Which callback are you using to capture results, recognizer.recognizing or recognizer.recognized? 
Also, which websocket URL are you connecting to? In your network requests tab in developer tools, you should see a URL like "wss://<region>.stt.speech.microsoft.com/speech/recognition/dictation/cognitiveservices..."

If you're seeing "speech/recognition/conversation" instead, that enableDictation() call is not working correctly.

**Comment by KwFung7** [comment]
@glharper I'm using recognizer.recognized to capture the results.
For the websocket URL, I'm using below format

`wss://xxxxxxx.cognitiveservices.azure.com/stt/speech/recognition/conversation/cognitiveservices/v1?format=detailed`

**Comment by glharper** [comment]
> @glharper I'm using recognizer.recognized to capture the results. For the websocket URL, I'm using below format
> 
> `wss://xxxxxxx.cognitiveservices.azure.com/stt/speech/recognition/conversation/cognitiveservices/v1?format=detailed`

So enableDictation() is not setting the websocket URL properly. Could you upgrade to v1.30.1 and try again? I'll attach a sample page that's working for me later today.

**Comment by glharper** [comment]
@KwFung7 Were you able to get dictation working?

**Comment by KwFung7** [comment]
seems working fine in v1.30.1, thanks for the follow up
