### ISSUE TITLE
[uniapp with vue3 + vite]StatusCode: 500, undefined Reason: Error: Module "" has been externalized for browser compatibility. Cannot access ".Agent" in client code.

### ISSUE THREAD

**Issue by jaycaoln** [microsoft/cognitive-services-speech-sdk-js#690]
1.  below Error
![image](https://github.com/microsoft/cognitive-services-speech-sdk-js/assets/22727660/3cfaad41-607f-4a3c-ac09-a185799cf9e3)
StatusCode: 500, undefined Reason: Error: Module "" has been externalized for browser compatibility. Cannot access ".Agent" in client 
2. vue note that is polyfills Error. 
![image](https://github.com/microsoft/cognitive-services-speech-sdk-js/assets/22727660/c67caa40-a00d-42c6-bd1a-19863ebad30d)
4. uniapp h5 works fine, but app runs error.  i found source code,   uniapp app run the else func.
![image](https://github.com/microsoft/cognitive-services-speech-sdk-js/assets/22727660/67f1a0bf-c960-43e6-a621-3a7b9adba44a)
5. i tried change my vite.config.ts，but it doesn't work
https://stackoverflow.com/questions/69286329/polyfill-node-os-module-with-vite-rollup-js/70666018#70666018

how can i fix it? thx!

**Comment by glharper** [comment]
@jaycaoln Thank you for using JS Speech SDK, and writing this issue up. Looking at https://github.com/remorses/esbuild-plugins/blob/master/node-modules-polyfill/src/polyfills.ts, the polyfill for fs is EMPTY_PATH, but the file has browserify-fs commented out as a polyfill.

We don't officially support vue or vite integrations (and this is the first I've heard of "uniapp"), but with enough customer signal, I can write an integration example along the lines of our [react](https://github.com/Azure-Samples/AzureSpeechReactSample) and [react native](https://github.com/microsoft/cognitive-services-sdk-react-native-example) example repos.

**Comment by jaycaoln** [comment]
i solved by using https://github.com/davidmyersdev/vite-plugin-node-polyfills 
<img width="513" alt="image" src="https://github.com/microsoft/cognitive-services-speech-sdk-js/assets/22727660/501351cf-7227-4fd6-a4e1-7062f45d7cc6">

**Comment by jaycaoln** [comment]
but this error， i don't konw how to fix.
StatusCode: 500, undefined Reason: Error: Module "" has been externalized for browser compatibility. Cannot access ".Agent" in client

**Comment by jaycaoln** [comment]
it seems just uniapp don't support Websocket。https://uniapp.dcloud.net.cn/api/request/websocket.html#connectsocket。
and the source code run 'else' func。
![image](https://github.com/microsoft/cognitive-services-speech-sdk-js/assets/22727660/d614f134-dd34-4a7c-887e-52ec2eba3964)

**Comment by jaycaoln** [comment]
when i set 'WebSocket = undefined' in chrome，throw this error。 
<img width="945" alt="image" src="https://github.com/microsoft/cognitive-services-speech-sdk-js/assets/22727660/65ed4c9a-a949-49ce-922d-4f908bf1c2b8">
may be the same problem with 'WebSocket in undefined in uniapp'

**Comment by jaycaoln** [comment]
uniapp run webview in app environment。but not support WebSocket。
![image](https://github.com/microsoft/cognitive-services-speech-sdk-js/assets/22727660/9df6ce75-8ac6-423b-8c7c-a82a1b8dbb00)
![Xnip2023-07-18_02-23-06](https://github.com/microsoft/cognitive-services-speech-sdk-js/assets/22727660/3d0efef6-54b2-4881-b09f-2cee905be901)
i found agent-base was desperate from browser

**Comment by glharper** [comment]
@jaycaoln Websocket is a hard dependency for this library, as the sdk connects to websocket backend service endpoints. Websocket and Agent definitions are pre-included in all browser JS implementations, which is why ws and agent-base are not compiled into our web binaries (same story for "tls" and "net" node libs, and "fs" is not included bc of File API support in browsers).

**Comment by jaycaoln** [comment]
> @jaycaoln Websocket is a hard dependency for this library, as the sdk connects to websocket backend service endpoints. Websocket and Agent definitions are pre-included in all browser JS implementations, which is why ws and agent-base are not compiled into our web binaries (same story for "tls" and "net" node libs, and "fs" is not included bc of File API support in browsers).

 ok i got it thx. maybe i will try in nodejs
