### ISSUE TITLE
Speech Service is forceably ending turns at 10 minute intervals

### ISSUE THREAD

**Issue by maik-parloa** [microsoft/cognitive-services-speech-sdk-js#694]
Using the recognizer we experienced the behavior of forcibly ending recognitions after **10 minutes**. I found the following hint in the cognitive services speech SDK:
> If withing 100ms of an even 10 min, ignore text issues. The Speech Service is forceably ending turns at 10 minute intervals.

https://github.com/maik-parloa/cognitive-services-speech-sdk-js/blob/master/tests/LongRunning/SpeechRecoReconnectTests.ts#L156

1. In some cases, we'd like to keep the transcription running for more than 10 minutes. Is there a way to increase that timeout?
2. How can the 10-minute timeout be handled gracefully? Can we trigger a restart of the recognition right away without loosing the last transcriptions?

**Comment by glharper** [comment]
@maik-parloa Thanks for using the JS Speech SDK and writing this issue up. Is this 10 minutes of silence that causes the timeout? If not, are there specific circumstances that repro this, and can you add a wav file for me to test? Regarding long recognition scenarios, I've tested with hour-long files and not seen recognition end using startContinuousRecognitionAsync().

**Comment by maik-parloa** [comment]
Thank you for the fast response. The timeout, in this case, is not happening after silence.

- We are using `ConversationTranslator` and trigger the recognition with `startTranscribingAsync` (which also triggers `startContinuousRecognitionAsync` internally).
- I am using a Lex Fridman podcast (https://content.blubrry.com/takeituneasy/lex_ai_marc_andreessen.mp3), which I stream in using WebSocket through our telephony integration
- There is no exception triggered. The transcription just stops reproducible after exactly 10 minutes. The connection is not broken, we just don't receive any transcribing / transcribed events anymore.
 
Could this be related to using the `ConversationTranslator` instead of the SpeechRecognizer directly?

Can more detailed logs be enabled for the Cognitive Services SDK? Happy to provide any debug logs that are necessary.

**Comment by glharper** [comment]
@maik-parloa I can repro this with ConversationTranslator on a long audio file, but not with SpeechRecognizer. If you are able to use continuous speech recognition (or continuous translation via Translator) for this use case, do so.

I will start a thread with the service team and see what's going on here, as the SDK does not seem to be receiving any notice that the session has been terminated, the transcription results just stop appearing.

**Comment by iamcoreyg** [comment]
I am also experiencing this issue.

**Comment by maik-parloa** [comment]
@glharper We are using `startTranscribingAsync`, which already triggers `startContinuousRecognitionAsync` internally with the recognition mode set to `RecognitionMode.Conversation`. Is there any other function/recognition mode available to trigger the continuous translation in the ConversationTranslator?

**Comment by glharper** [comment]
@maik-parloa There is not, each Recognizer/Translator in the SDK has only one continuous API. 

The current operating hypothesis is that, on the 10 minute translation service timeout, the SDK is not properly renewing the conversation (Capito) token on reconnect. Sometime this week I will create a branch updating that token properly on service timeout to test that hypothesis.

**Comment by maik-parloa** [comment]
@glharper Thank you for dealing with this topic. Is there any workaround for this issue? Can I support with validation / testing somehow?

**Comment by glharper** [comment]
@maik-parloa I'm still testing this vs normal translation behavior, and this seems to be a gap in the service implementation for Conversation Translation. Normally, for users authenticating with a subscription key and region, they don't have to care about updating an auth token every 10 minutes. The service handles that behind the scenes.

For this scenario, however, the service does not handle updating the auth token every 10 minutes when the user authenticates with a key and region.

The current workaround I'd suggest is setting a timeout and updating the auth token on the conversationTranslator every 9.9 minutes once you start translating. To that end, I'm adding a setter in the associated PR.

**Comment by glharper** [comment]
@maik-parloa The latest version of JS Speech SDK, v.1.32, has been released and should fix this issue. Thank you for letting us know about this, and for using Speech SDK.
