### ISSUE TITLE
How to stop speaking?

### ISSUE THREAD

**Issue by jackiealex** [microsoft/cognitive-services-speech-sdk-js#700]
**Background**
I want the speaker to shut up, when i want. but how, i can't find any ways

**Comment by ralph-msft** [comment]
Sample code to demonstrate how to pause/resume/stop TTS playback
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/633b8fd841a98deeb8b22319271487dffd518755/samples/js/browser/public/synthesis.html#L341
