### ISSUE TITLE
How to know TTS current spoken  word or voice stream

### ISSUE THREAD

**Issue by jackiealex** [microsoft/cognitive-services-speech-sdk-js#703]
I want to know current word or voice stream for lipSync work

**Comment by glharper** [comment]
@jackiealex Thank you for using JS Speech SDK, and writing this up. Our documentation for viseme events is [here](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-speech-synthesis-viseme?tabs=visemeid&pivots=programming-language-javascript). Could you be a little more specific about what you'd like to know?

**Comment by glharper** [comment]
Closing pending submitter response
