### ISSUE TITLE
[Bug]: speechConfig.enableDictation is not functioning.

### ISSUE THREAD

**Issue by faster-than-human** [microsoft/cognitive-services-speech-sdk-js#711]
### What happened?

Hello Support,

I am trying to use the dictation mode for this service and the speech config's enableDictation() function seems to have no effect when called.

For reference here is the initialization of the relevant objects.
`
const speechConfig = SpeechConfig.fromSubscription('some_val', 'some_region')
speechConfig.enableDictation()
//speechConfig.setServiceProperty('punctuation', 'explicit', ServicePropertyChannel.UriQueryParameter)

const recognizer = new SpeechRecognizer(speechConfig, AudioConfig.fromDefaultMicrophoneInput())
recognizer.recognizing = onRecognizing
recognizer.recognized = onRecognized
isInitialized = true

recognizer.startContinuousRecognitionAsync()
`

As results begin to roll in while I dictate the text has punctuation already in it as if I never called enableDictation(). Now interesting enough, if I explicitly set the service property for explicit punctuation (see comment in code) then dictation mode works as I would expect. I have been running it this way for months at this point, but with the recent July v1.31.0 update I figured I would test again today and it still doesn't function as I expect it to so I wanted to post a ticket for it and see what I may be missing.

Please let me know if you have any questions that I can answer or anything that needs cleared up. 

As a quick example if I dictate, "some guy walked into my house" I would expect that back exactly as shown prior (with the capital S in "Some" of course), but the result is, "Some guy walked into my house." with the period at the end. My understanding with dictation mode is that shouldn't happen so I am not sure what I am doing wrong.

Thank you.

### Version

1.31.0 (Edge)

### What browser/platform are you seeing the problem on?

Node, Chrome, React

**Comment by glharper** [comment]
@faster-than-human Thanks for using the JS Speech SDK, and writing this issue up. The [description](https://learn.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechconfig.enabledictation?view=azure-dotnet) for EnableDictation from our .NET SDK reads "With dictation enabled, word descriptions of sentence structures are understood. For example, ending a statement by saying "question mark" adds a question mark to the sentence when dictation is enabled."

So your expectation here is that punctuation is not displayed, even when "question mark" is spoken?

**Comment by chschrae** [comment]
@faster-than-human Hi there,

This is intended as there are really 3 modes of punctuation at play here:

1. Explicit, which is set by the service property you mentioned, where punctuation will not be added unless the user specifically says the punctuation words, such as "period"
2. Explicit and Intelligent, which is the enableDictation() API, where punctuation is inferred based on the speech. This is where the extra punctuation is coming from, and it also tries to translate the explicit phrases. It will attempt to handle explicit phrases as well.
3. Intelligent, which is the default, will not translate explicit phrases, but will add intelligent based punctuation.

Example utterance. "What do we really do question mark"
1. What do we really do?
2. What do we really do?
3.  What do we really do? question mark.

Example utterance. "What do we really do" <- note without the explicit punctuation
1. What do we really do
2. What do we really do?
3.  What do we really do?

Hopefully with this combination of options you can find one that is best for your scenario. If there is something that you feel is missing from the offering please let us know.

I'm closing this issue to try and keep the list of open issues down, but feel free to re-open if you think it is necessary.
