### ISSUE TITLE
[Bug]: When using `fromDefaultMicrophoneInput` and `startContinuousRecognitionAsync` the user hanged up

### ISSUE THREAD

**Issue by GalDayan** [microsoft/cognitive-services-speech-sdk-js#719]
### What happened?

I would expect the auto-detection to finish the recognition (`recognized` method) only when the user actually stopped to talk. When the user thinks and mumbles ("hmm") the recognition is stopped and declared as a finish.

I'm wondering if there is any possibility to add a threshold in seconds (for example add 1second from the moment the recognition detected silence moment and only if after this nothing happened, trigger the `recognized` function)

### Version

1.31.0 (Edge)

### What browser/platform are you seeing the problem on?

Firefox, Chrome, Safari, React

**Comment by rhurey** [comment]
Hey, thanks for using the Speech SDK...

The SegmentationTimeout property can be used to adjust the silence delay before a phrase is recognized.
https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/4ccb5a0915974814f55bb6c83eba00e1c4c95f88/src/sdk/PropertyId.ts#L242

It can be set like:

```
let s: sdk.SpeechConfig);
...
s.setProperty(sdk.PropertyId[sdk.PropertyId.Speech_SegmentationSilenceTimeoutMs], "1000");
```
