### ISSUE TITLE
Continuous Recognition from Microphone

### ISSUE THREAD

**Issue by lucasctd** [microsoft/cognitive-services-speech-sdk-js#72]
I am trying to use the continuous recognition feature when somebody speaks on the microphone.
I am using the [mic ](https://www.npmjs.com/package/mic) package to get the data from the microphone and recognize it, but I am always getting wrong results. Idk what's missing, may you help me?
I will add some parts of my code so you can understand.

Here is how I create an instance of pushStream
```
this.pushStream = AudioInputStream.createPushStream(AudioStreamFormat.getWaveFormatPCM(16, 16000, 1));
```

Here is the method I call to recognize the user voice
```
    recognizeAsync() {
        this.audioConfig = AudioConfig.fromStreamInput(this.pushStream);
        this.recognizer = new SpeechRecognizer(this.speechConfig, this.audioConfig);
        this.subject = new Observable(subs => {
            this.subscription = subs;
            this.recognizer.startContinuousRecognitionAsync();
            this.recognizer.recognizing = (rec, {result}) => {
                subs.next(result);
            };
            this.recognizer.recognized = (rec, {result}) => {
                subs.next(result);
            };
        });
        return this.subject;
    }
```
And here is where I use the mic package to get the user voice data

```
speech = new Speech(language, subscriptionKey, region);
speech.recognizeAsync().subscribe(result => {
        console.log('result', result);
});
var micInstance = mic({
        rate: '16000',
        channels: '1',
        debug: false,
        exitOnSilence: 6,
        fileType: 'wav' //have also tried with raw type
});
const micInputStream = micInstance.getAudioStream();

micInputStream.on('data', function(data) {
    speech.pushStream.write(data);
    //console.log("Recieved Input Stream: ", data);
});
```

**Comment by amitkumarshukla** [comment]
Thanks a lot for your input. We are looking into it and will get back to you asap..

**Comment by amitkumarshukla** [comment]
@lucasctd please look at this https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/244
and let us know if it helps.

**Comment by lucasctd** [comment]
@amitkumarshukla, @rhurey is saying that we could do what I am doing right now actually. 

> Once the MediaStream is captured, you'd need to process audio frames from it, PCM encode them, and send them into a stream type that AudioConfig did understand. (I'd recommend a PushStream)

I just need to know how I can get the data from the microphone in a format that PushStream understand.
I think I could do it If I have access to the function that you use to get the data from microphone on the "recognizeOnceAsync" method.
I just want to know how I can get the data (that`s ready to send to PushStream.write() method)  from the microphone using your SDK.

**Comment by rhurey** [comment]
I experimented a bit with sox / mic on windows, and regardless of bitwidth settings, I"m getting roughly 64K/s of audio data which is double what I'd expect. Sox itself from the command line outputs to a wave file at the expected rate. But if I redirect 

Strangely, when I turned the sample rate down to 8k, the audio that started arriving could be recognized.

I'm not sure what's happening with the node stdout pipe to double the expected data, or how to handle it.

**Comment by lucasctd** [comment]
@rhurey Thank you so much. =D
When I changed the rate to 8k, it worked as I expected xD.
So now my settings are like below:

```
const micInstance = mic({
        rate: '8000', //it's the line that matters
        channels: '1',
        debug: false,
        exitOnSilence: 1
    });
```

**Comment by rhurey** [comment]
I'm concerned that solution is going to be fragile.

Just playing with sox a bit more leads me to concerns that there some platform differences possible that may produce inconsistent results.

sox.exe -c 1 -b 16 -e signed-integer -r 16000 -t waveaudio  default -p > redirect.wav
Ran for 10s.
redirect.wav is 655,408 redirect.wav

Had Sox write the file directly:
sox.exe -c 1 -b 16 -e signed-integer -r 16000 -t waveaudio  default redirect2.wav
Ran for 10s.
327,724 redirect2.wav

That tells me the doubling of the data is happening as a result of the stdio redirect. It's not clear why that's happening, but the possibility that the doubling is platform specific causes fragility concerns. Plus who knows what extra data is winding up in the audio.

Setting the mic frequency to 8K may work, but it may also work differently on different platforms.

Asking the mic maintainers why you're seeing double the expected data would be a worthwhile exercise.

**Comment by lucasctd** [comment]
Yeah, I actually have opened an [issue ](https://github.com/ashishbajaj99/mic/issues/35 )there but they haven't answered.
