### ISSUE TITLE
[Bug]: Unable to contact server. StatusCode: 1006, https://westeurope.api.cognitive.microsoft.com/sts/v1.0/issuetoken Reason:  Unexpected server response: 404

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [microsoft/cognitive-services-speech-sdk-js#723]
### What happened?

I cannot use the endpoint, it works with curl

```bash
curl -X POST --header "Ocp-Apim-Subscription-Key:<FOO>" --data "" "https://westeurope.api.cognitive.microsoft.com/sts/v1.0/issuetoken"
```
returns a big string

### Version

1.31.0 (Edge)

### Relevant log output

```shell
// example.js
const fs = require("fs");
const sdk = require("microsoft-cognitiveservices-speech-sdk");

// This example requires environment variables named "SPEECH_KEY" and "SPEECH_REGION"
let speechConfig = sdk.SpeechConfig.fromEndpoint(new URL(process.env.SPEECH_ENDPOINT), process.env.SPEECH_KEY);
// speechConfig.region = process.env.SPEECH_REGION;
// speechConfig.speechSynthesisLanguage = "en-US"

function fromFile() {
    const filename = "katiesteve.wav";

    let audioConfig = sdk.AudioConfig.fromWavFileInput(fs.readFileSync(filename));
    let conversationTranscriber = new sdk.ConversationTranscriber(speechConfig, audioConfig);

    var pushStream = sdk.AudioInputStream.createPushStream();

    fs.createReadStream(filename).on('data', function(arrayBuffer) {
        pushStream.write(arrayBuffer.slice());
    }).on('end', function() {
        pushStream.close();
        console.log("Push stream closed");
    });

    console.log("Transcribing from: " + filename);

    conversationTranscriber.sessionStarted = function(s, e) {
        console.log("SessionStarted event");
        console.log("SessionId:" + e.sessionId);
    };
    conversationTranscriber.sessionStopped = function(s, e) {
        console.log("SessionStopped event");
        console.log("SessionId:" + e.sessionId);
        conversationTranscriber.stopTranscribingAsync();
    };
    conversationTranscriber.canceled = function(s, e) {
        console.log("Canceled event");
        console.log(e.errorDetails);
        conversationTranscriber.stopTranscribingAsync();
    };
    conversationTranscriber.transcribed = function(s, e) {
        console.log("TRANSCRIBED: Text=" + e.result.text + " Speaker ID=" + e.result.speakerId);
    };

    // Start conversation transcription
    conversationTranscriber.startTranscribingAsync(
        function () {},
        function (err) {
            console.trace("err - starting transcription: " + err);
        }
    );

}
fromFile();
```

if I run it, I got

```bash
node example.js
Transcribing from: katiesteve.wav
Push stream closed
Canceled event
Unable to contact server. StatusCode: 1006, https://westeurope.api.cognitive.microsoft.com/sts/v1.0/issuetoken Reason:  Unexpected server response: 404
```

Thanks a lot
```

**Comment by FrancescoSaverioZuppichini** [comment]
Okay, if I do

```javascript
let speechConfig = sdk.SpeechConfig.fromSubscription(process.env.SPEECH_KEY, "westeurope");
```

it works, I am wondering why

**Comment by glharper** [comment]
@FrancescoSaverioZuppichini  Thank you for using JS Speech SDK, and writing this issue up. In JS SDK, the "Issuetoken" URL is not considered a speech service endpoint. Try using "wss://westeurope.stt.speech.microsoft.com/speech/universal/v2" as the endpoint, and you should be successful.

**Comment by FrancescoSaverioZuppichini** [comment]
> @FrancescoSaverioZuppichini Thank you for using JS Speech SDK, and writing this issue up. In JS SDK, the "Issuetoken" URL is not considered a speech service endpoint. Try using "wss://westeurope.stt.speech.microsoft.com/speech/universal/v2" as the endpoint, and you should be successful.

thanks a lot, so when I create a service on azure I should always use that link?

**Comment by glharper** [comment]
> > @FrancescoSaverioZuppichini Thank you for using JS Speech SDK, and writing this issue up. In JS SDK, the "Issuetoken" URL is not considered a speech service endpoint. Try using "wss://westeurope.stt.speech.microsoft.com/speech/universal/v2" as the endpoint, and you should be successful.
> 
> thanks a lot, so when I create a service on azure I should always use that link?

Well, that's the default service endpoint that the SDK connects to, so using the config API SpeechConfig.fromSubscription(key, region) should produce the same service connection behavior when you start recognition, if you don't need a specific service endpoint.

**Comment by FrancescoSaverioZuppichini** [comment]
> > > @FrancescoSaverioZuppichini Thank you for using JS Speech SDK, and writing this issue up. In JS SDK, the "Issuetoken" URL is not considered a speech service endpoint. Try using "wss://westeurope.stt.speech.microsoft.com/speech/universal/v2" as the endpoint, and you should be successful.
> > 
> > 
> > thanks a lot, so when I create a service on azure I should always use that link?
> 
> Well, that's the default service endpoint that the SDK connects to, so using the config API SpeechConfig.fromSubscription(key, region) should produce the same service connection behavior when you start recognition, if you don't need a specific service endpoint.

Copy that, in my case I will need to create a service under a private network (we have already created that but no idea which URL we should use)
