### ISSUE TITLE
[Question]: Incorrect auto-capitalization in dictation mode.

### ISSUE THREAD

**Issue by ghost** [microsoft/cognitive-services-speech-sdk-js#726]
### What happened?

Hello Support,

I wanted to ask a few questions about the auto-capitalization workflow when using the speech-to-text service. To get started the behavior I see out of the box is that anytime you turn the microphone off and then back on (aka cycle the microphone) the first word in the second utterance will always be capitalized as if it is the start of a sentence. 

This makes sense to me in the default workflow for the service. However in the dictation mode workflow this doesn't make sense to me. My solution is for medical dictation and some providers like to start and stop during their encounter notes which causes lots of unwanted, and from the user's view, random capitalization. 

As a simple example lets consider this workflow...
**_//Provider dictates..._**
The patient presents today
**_//Provider stops recording for a moment and then starts recording again and dictates..._**
complaining of a headache.

What I receive currently is...
The patient presents today **C**omplaining of a headache.

What I expect to receive is...
The patient presents today complaining of a headache.

What I am looking for is a way to either disable that first-char always cap, unless it should actually be uppercase (e.g. proper noun), or to find a way to detect if the first char should actually be uppercase. For the available medical dictation clients out there (e.g. Dragon Medical, CSpeak, MModal, etc) this is the given and expected functionality by medical providers and I am trying to replicate this with this service.

Any advice or thoughts are appreciated.

Thank you.

### Version

1.31.0 (Edge)

### What browser/platform are you seeing the problem on?

Node, React

**Comment by glharper** [comment]
@faster-than-human From our service contact: "The behavior is as expected I would presume as we would get an end of audio signal. Seems to me that the best solution for him here is to manage the audio stream directly such that turning the microphone off just results in either silence sent to the service or just skipping of the audio, but not a closing and reopening of the audio stream."
