### ISSUE TITLE
Sample Code Request: Fetch and Autoupdate PHP Token every 10 minutes

### ISSUE THREAD

**Issue by inglesuniversal** [microsoft/cognitive-services-speech-sdk-js#730]
Target Platform: JS-Browser SDK

Hello,

Your QuickStart examples show how to interact with Speech Recognition, but most of the time, if our Students leave any Chrome browser tab opened for more than 10 minutes, they will start getting an error when pressing on one shot Recognizer trigger button.

Can Azure Team kindly provide some sample code to accomplish this common issue written in vanilla JavaScript?

Kind Regards

**Comment by glharper** [comment]
@inglesuniversal Thank you for using the JS Speech SDK, and writing this issue up. There's a browser-based sample that features token authentication [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/js/browser). If you'll note the description of the RequestAuthorizationToken function towards the end of the Readme, you would just need to add `setTimeout(RequestAuthorizationToken, 600000);` to the frontend code to update the auth token every 10 minutes.

Let me know if that works for you.
