### ISSUE TITLE
[Bug]: STT Continuous recognition transcription lags/doesn't display

### ISSUE THREAD

**Issue by muchai-mercy** [microsoft/cognitive-services-speech-sdk-js#733]
### What happened?

When using the `SpeechRecognizer` Speech to Text continuous recognition, once the session starts, sometimes the transcription does not display or displays with a lag of several seconds per token/word with no errors

Things we have tried:
1. Updating the speech configuration to renew the keys
2. Ending the session and starting a new one (this sometimes changes the behaviour)
3. Language in use: `en-KE`

We are unable to recreate this issue as it happens sometimes.

Things we are yet to try, viewing logs from here: `sdk.Diagnostics.SetLoggingLevel(sdk.LogLevel.Debug)`

### Version

1.31.0 (Edge)

### What browser/platform are you seeing the problem on?

React Native

**Comment by glharper** [comment]
@muchai-mercy Thanks for submitting this issue. Were you able to collect logs?

**Comment by glecaros** [comment]
@muchai-mercy, pinging again to see if you had logs for this issue.
