### ISSUE TITLE
[Question]: I can't pause TTS audio in my React App

### ISSUE THREAD

**Issue by Yousseffakhry20** [microsoft/cognitive-services-speech-sdk-js#738]
### What happened?

I am using TTS service in my React App and it's working fine, but I want to pause/stop the audio playing since the synthesized text could be long.

I tried using SpeakerAudioDestination.pause function but it's not working although when call the handlePause function the console log is working so I am unable to trace why the player.pause() is not working as expected.

Code Sample Below:

  
  const player = new speechsdk.SpeakerAudioDestination();
  const speechConfig = speechsdk.SpeechConfig.fromSubscription(
    speechKey,
    speechRegion
  );

  const audioConfig = speechsdk.AudioConfig.fromSpeakerOutput(player);
  
  const handlePause = () => {
    console.log("Pause audio");

    try {
      player.pause();
    } catch (error) {
      alert(error.message);
    }
  };

**Comment by glharper** [comment]
@Yousseffakhry20 Thank you for submitting this issue and using the JS Speech SDK. This issue gave me an excuse to update our React sample to use more modern react primitives. I've added a mute/resume button to the sample, please check it out (here)[https://github.com/Azure-Samples/AzureSpeechReactSample].

**Comment by Yousseffakhry20** [comment]
I followed the updated React Sample and it worked. Thank you so much.

I have another question related to TTS but this could be in another issue
