### ISSUE TITLE
[Bug]: Invalid translation result returned for Filipino language (en-US > fil-PH)

### ISSUE THREAD

**Issue by maik-parloa** [microsoft/cognitive-services-speech-sdk-js#740]
### What happened?

Using the ConversationTranslator, we see inconsistent translation behavior for the target language **Filipino**. When translating from `en-US`
> sourceText: Understood, one moment, please.

to `fil-PH` (Filipino), we are receiving

> targetText: Understood, one moment, please.

I additionally verified the behavior with the [Microsoft Translator](https://translator.microsoft.com/). Slight modifications of the sourceText leads to the text being translated properly though.

### Version

1.31.0 (Edge)

### What browser/platform are you seeing the problem on?

Chrome

### Relevant log output

```shell
Translator Website Logs for 1696850161096
====================================================
PAGE
	eventName: home_page_loaded
PAGE
	pathname: /
	eventName: home_page_pathname
PAGE
	eventName: conversation_page_loaded
PAGE
	from: /
	to: /Conversation
	eventName: app_route_changed
CONVERSATION
	sourceLanguage: en-US
	targetLanguage: fil-PH
	targetLength: 31
	eventName: text_message_received
	from: d540efda-d16b-4b9c-802c-95a66f1b3be3
	sourceText: Understood, one moment, please.
	targetText: Understood, one moment, please.
	sessionId: 14D5FAB996634C13BF2451A017817C4C
	roomCode: WIDQY
CONVERSATION
	sourceLanguage: en-US
	targetLanguage: fil-PH
	targetLength: 26
	eventName: text_message_received
	from: d540efda-d16b-4b9c-802c-95a66f1b3be3
	sourceText: understood, please wait a moment
	targetText: naintindihan, sandali lang
	sessionId: 14D5FAB996634C13BF2451A017817C4C
	roomCode: WIDQY
CONVERSATION
	sourceLanguage: en-US
	targetLanguage: fil-PH
	targetLength: 38
	eventName: text_message_received
	from: d540efda-d16b-4b9c-802c-95a66f1b3be3
	sourceText: Understood one moment, please.
	targetText: Naunawaan ang isang sandali, pakiusap.
	sessionId: 14D5FAB996634C13BF2451A017817C4C
	roomCode: WIDQY
CONVERSATION
	sourceLanguage: en-US
	targetLanguage: fil-PH
	targetLength: 32
	eventName: text_message_received
	from: d540efda-d16b-4b9c-802c-95a66f1b3be3
	sourceText: Understood, one moment, please.

	targetText: Understood, one moment, please.

	sessionId: 14D5FAB996634C13BF2451A017817C4C
	roomCode: WIDQY
CONVERSATION
	sourceLanguage: en-US
	targetLanguage: fil-PH
	targetLength: 31
	eventName: text_message_received
	from: d540efda-d16b-4b9c-802c-95a66f1b3be3
	sourceText: Understood, one moment, please.
	targetText: Understood, one moment, please.
	sessionId: 14D5FAB996634C13BF2451A017817C4C
	roomCode: WIDQY
CONVERSATION
	sourceLanguage: en-US
	targetLanguage: fil-PH
	targetLength: 36
	eventName: text_message_received
	from: d540efda-d16b-4b9c-802c-95a66f1b3be3
	sourceText: Understood one moment please
	targetText: Naintindihan ng isang sandali please
	sessionId: 14D5FAB996634C13BF2451A017817C4C
	roomCode: WIDQY
```

**Comment by matt-parloa** [comment]
I've noticed a few examples where translation from English to Filipino has returned full or partial translations in the original language. e.g.

**e:** what is the time please?
**f:** ano po ba ang **time please**
_also no ? in translation_.

**e:** Hello, thank you for calling Energy Solutions. How may I assist you?
**f:** **Hello**, salamat sa pagtawag sa Energy Solutions. Paano ko kayo matutulungan?

**e:** This is an automatically translated call, just talk to us in English. Sometimes an answer can take a little longer, so please be patient. I’ll connect you with an agent now!
**f:** Ito ay isang awtomatikong isinalin na tawag, makipag usap lamang sa amin sa Ingles. Minsan ang sagot ay maaaring tumagal ng kaunti, kaya mangyaring maging matiyaga. Ikokonekta kita sa isang **agent** ngayon!

**Comment by glharper** [comment]
@matt-parloa @maik-parloa Greetings to the Parloa team, I've pinged the service team to take a look at this.

**Comment by matt-parloa** [comment]
Not sure that this is an SDK specific bug. I'm getting the same translation failures calling the API directly at https://api.cognitive.microsofttranslator.com/translate

**Comment by glharper** [comment]
No action on this in six months, closing.
