### ISSUE TITLE
[Bug]:  Bug I reported from april still isn't fixed 

### ISSUE THREAD

**Issue by shareefalis** [microsoft/cognitive-services-speech-sdk-js#741]
### What happened?

Hi Microsoft team,

We are endeavoring to eliminate the workaround that had previously been claimed to be resolved. It appears that issue #658 is still unresolved. Currently, we are using version 1.32.0 of the NPM package.

Best regards,
Shareef

### Version

1.32.0

**Comment by shareefalis** [comment]
Thank you for fixing the bug, i look forward to testing the new version of the Speech SDK.

**Comment by glharper** [comment]
@shareefalis This should be in v1.34, which should release sometime in December.

**Comment by shareefalis** [comment]
Ok good, @glharper  What was changed in v1.33?  i'm not seeing the change log for that release, btw

**Comment by glharper** [comment]
JS: AudioWorkletNode module loads [now uses a trusted URL](https://github.com/microsoft/cognitive-services-speech-sdk-js/pull/732), with fallback for CDN browser includes.
JS: Packed lib files now targets ES6 JS, with support for ES5 JS removed.
JS: [intermediate events for translation scenario targeting v2 endpoint are correctly handled](https://github.com/microsoft/cognitive-services-speech-sdk-js/pull/735)
JS: [The language property for TranslationRecognitionEventArgs is now set for translation.hypothesis events.](https://github.com/microsoft/cognitive-services-speech-sdk-js/pull/736/files)

The release notes should be published next week.
