### ISSUE TITLE
[Bug]: Error code 4, StatusCode: 1006

### ISSUE THREAD

**Issue by znwhite** [microsoft/cognitive-services-speech-sdk-js#743]
### What happened?

Did everything right, getting this error:

```
CANCELED: Reason=0
CANCELED: ErrorCode=4
CANCELED: ErrorDetails=Unable to contact server. StatusCode: 1006, undefined Reason:  Unexpected server response: 401
```

Yes I tried regenerating key, didn't work.

Service region = "eastus"

Using version 1.32.0

Here is code:

```
const speechConfig = sdk.SpeechConfig.fromSubscription(speechKey, serviceRegion);
speechConfig.speechRecognitionLanguage = "en-US";

function fromFile() {
    let audioConfig = sdk.AudioConfig.fromWavFileInput(fs.readFileSync("./sr_show.wav"));
    let speechRecognizer = new sdk.SpeechRecognizer(speechConfig, audioConfig);

    speechRecognizer.recognizeOnceAsync(result => {
        switch (result.reason) {
            case sdk.ResultReason.RecognizedSpeech:
                console.log(`RECOGNIZED: Text=${result.text}`);
                break;
            case sdk.ResultReason.NoMatch:
                console.log("NOMATCH: Speech could not be recognized.");
                break;
            case sdk.ResultReason.Canceled:
                const cancellation = sdk.CancellationDetails.fromResult(result);
                console.log(`CANCELED: Reason=${cancellation.reason}`);

                if (cancellation.reason == sdk.CancellationReason.Error) {
                    console.log(`CANCELED: ErrorCode=${cancellation.ErrorCode}`);
                    console.log(`CANCELED: ErrorDetails=${cancellation.errorDetails}`);
                }
                break;
        }
        speechRecognizer.close();
    });
}
fromFile();
```

Pretty frustrating since this is taken directly from your example. Any guidance here would be appreciated.

### Version

1.31.0 (Edge)

### Relevant log output

```shell
CANCELED: Reason=0
CANCELED: ErrorCode=4
CANCELED: ErrorDetails=Unable to contact server. StatusCode: 1006, undefined Reason:  Unexpected server response: 401
```
```

**Comment by glharper** [comment]
@znwhite Thank you for using JS Speech SDK, and writing this issue up. I copied your sample code and was able to get a result with correct credentials. Can you tell me more about the Azure resource you're getting the key/region pair from? Is it a Speech Service, or is it another kind of Azure resource? For the Azure Speech SDK, you have to use keys specifically from a Speech Service.

**Comment by matt-carbon** [comment]
I'm seeing the same issue with some cadence reported in our logging system (but I'm unable to reproduce on my own device). We're using `eastus`. We get the token just fine. Transcription works normally for most users. But every once in awhile we get errors. Here's one of the logs we have: 
```
errorCode | 4
errorDetails | Unable to contact server. StatusCode: 0, undefined Reason:
origError | 0
sessionId | 1B262BF6100A49E09CBA075231C371FD
```

Which comes directly form our code that logs this error:
```
ApptAudioTranscriber.recognizer.canceled = (
        s: Recognizer,
        e: SpeechRecognitionCanceledEventArgs,
      ) => {
        logError(e.reason, "ApptAudioTranscriber canceled", {
          data: {
            errorDetails: e.errorDetails,
            errorCode: e.errorCode,
            sessionId: e.sessionId,
          },
        });
      };
```

Is there any other information we can debug to understand why it go canceled? We are seeing some other errors that get logged at different times but may be correlated. Specifically `Another turn started before current completed.` and `The number of parallel requests exceeded the number of allowed concurrent transcriptions.`.

Happy to open separate issues if needed.

**Comment by glharper** [comment]
@matt-carbon, this is a separate issue that updating to v1.32 may fix. If you still see this after updating, please open a new issue.
