### ISSUE TITLE
[Bug]: Cantonese Speech Generation Not Working (zh-HK) with the new Multilingual Model

### ISSUE THREAD

**Issue by kiostudio** [microsoft/cognitive-services-speech-sdk-js#748]
### What happened?

![Screenshot 2023-10-27 at 12 45 27 PM](https://github.com/microsoft/cognitive-services-speech-sdk-js/assets/63901064/49c9ee73-be30-4102-890f-62d2f727d3b3)
![Screenshot 2023-10-27 at 12 45 33 PM](https://github.com/microsoft/cognitive-services-speech-sdk-js/assets/63901064/5ede73f2-1a8f-4db8-8599-d8fbb923589e)
![Screenshot 2023-10-27 at 12 47 12 PM](https://github.com/microsoft/cognitive-services-speech-sdk-js/assets/63901064/8dd69064-f714-46c5-9e24-a2cdaec23606)

Setting the language code into "zh-HK" will output a Mandarin Chinese audio instead of Cantonese Chinese.

### Version

1.31.0 (Edge)

**Comment by glharper** [comment]
@yulin-li @yinhew FYI

**Comment by yulin-li** [comment]
I cannot repro.

I saw you also set the voice name in the last line of your first screenshot. The voice name has higher priority than language, if you set voice to a zh-cn voice, (e.g., zh-CN-XiaoxiaoNeural), then the language setting takes no effect.
