### ISSUE TITLE
[Bug]: Not working with esbuild (e.g. NG17) 

### ISSUE THREAD

**Issue by Squixx** [microsoft/cognitive-services-speech-sdk-js#765]
### What happened?

In Angular 17,  Esbuild is included as a compilation option (and default for new projects)

However when using the microsoft-cognitiveservices-speech-sdk, you will get the error:

```

✘ [ERROR] Could not resolve "net"

    (disabled):node_modules/.pnpm/https-proxy-agent@4.0.0/node_modules/https-proxy-agent/index.js:5:18:
      5 │ var net = require('net');
        ╵                   ~~~~~

  The package "net" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
  
  ```

as `microsoft-cognitiveservices-speech-sdk` depends on the `https-proxy-agents`  and thus cant compile.  (not this issue also applies when using the latest version of `https-proxy-agents` 

### Version

1.33.0 (Latest)

### What browser/platform are you seeing the problem on?

Angular 17

**Comment by glharper** [comment]
> Is there no work around or additional feedback for this with Angular 17 projects?

https://github.com/dotnet/aspnetcore/issues/52082#issuecomment-1819753030

**Comment by dabasejumper** [comment]
Thank you Glenn, that worked for in my case! Hopefully this issue is still on Microsoft's radar though for server rendering.

**Comment by glharper** [comment]
I'm closing this, as this issue is upstream of JS Speech SDK.
