### ISSUE TITLE
[Help Wanted] Issues Proxying Browser Transcription Stream to Microsoft Transcription Service Title

### ISSUE THREAD

**Issue by LiGo666** [microsoft/cognitive-services-speech-sdk-js#769]
### Background
I am currently working on a web application where an interactive avatar communicates with users using natural language. The key feature of this application is to capture user speech in real time, transcribe it into text using speech-to-text services, and then use this text to generate responses which the avatar conveys back to the users.

### The Problem
I have encountered challenges in implementing the speech-to-text component. My goal is to proxy the user's voice stream from the browser to Microsoft's Transcription Service. I chose this approach, because IMHO streaming the voice data from the browser directly to speech service would not allow to to manage rate limits and cause cross-site scripting, content security, and cookie-related issues that arise with direct browser-to-Microsoft service communication.

### Versions

    Node.js: v18.18.2v
      "ejs": "^3.1.9",
    "express": "^4.18.2",
    "http-errors": "~1.6.3",
    "http-proxy-middleware": "^2.0.6",
    "microsoft-cognitiveservices-speech-sdk": "^1.33.1",
    "morgan": "~1.9.1",
    "request": "^2.88.2",
    "ws": "^8.14.2"
    
    Host: Win11 / Azure Web App

### Expected Behavior

The server should act as a proxy, handling both HTTP and WebSocket traffic from the browser and forwarding it to Microsoft's Transcription Service. This setup is intended to manage rate limiting and handle security concerns more effectively than a direct browser-to-Microsoft service connection.

### Code

_express routing:_
```

// proxy http requests to the speech-to-text service
router.all('/speech/recognition/conversation/cognitiveservices', (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', req.headers.origin || req.headers.host);
  axios({
    url: 'https://westeurope.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?language=de-DE',
    method: req.method, // Use the method of the incoming request
    headers: {
      'Ocp-Apim-Subscription-Key': subscriptionKey,
      'Content-Type': req.headers['content-type'] // Use the content-type of the incoming request
    },
    data: req.body
  })
  .then(response => {
    console.log('Speech-to-text response:', response.data);
    res.send(response.data);
  })
  .catch(error => {
    console.error('Speech-to-text error:', error);
    res.status(500).send(error.message);
  });
});

//proxy websocket requests to the speech-to-text service
const proxyMiddleware = createProxyMiddleware('/speech/recognition/conversation/cognitiveservices', {
  target: 'wss://westeurope.stt.speech.microsoft.com',
  changeOrigin: true,
  ws: true,
  pathRewrite: {
    '^/speech/recognition/conversation/cognitiveservices': '/speech/recognition/conversation/cognitiveservices/v1'
  },
  onProxyReqWs: (proxyReq, req, socket, options, head) => {
    proxyReq.setHeader('Ocp-Apim-Subscription-Key', subscriptionKey);
    // Set any other headers you need here
  }
});

router.use(proxyMiddleware);
```

_frontent call_
following the example: [Use continuous recognition](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-recognize-speech?pivots=programming-language-javascript)

```
const speechConfig = SpeechSDK.SpeechConfig.fromHost(new URL('http://localhost:3000/speech/recognition/conversation/cognitiveservices'));
const audioInConfig = SpeechSDK.AudioConfig.fromDefaultMicrophoneInput();
```

### Current Behavior

When I test the connection to http://localhost:3000/speech/recognition/conversation/cognitiveservices with Postman i get:

```
{
    "RecognitionStatus": "Success",
    "Offset": 0,
    "Duration": 200000,
    "DisplayText": ""
}
```

Testing with a Websocket client I also get something back, that looks like its coming from Microsoft:

```
WebSocket connection established
[HPM] Upgrading to WebSocket
[HPM] WebSocket error: Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
WebSocket connection closed
Continuous detection started
Transcription aborted: undefined
Transcription session ended
```

However, browser logging always shows:

```
Recognition started [transcriptionManager.js:55:13](http://localhost:3000/js/transcriptionManager.js)
CANCELED: Reason=0 [transcriptionManager.js:111:19](http://localhost:3000/js/transcriptionManager.js)
CANCELED: ErrorCode=4 [transcriptionManager.js:113:21](http://localhost:3000/js/transcriptionManager.js)
CANCELED: ErrorDetails=Unable to contact server. StatusCode: 500, undefined Reason: SyntaxError: An invalid or illegal string was specified [transcriptionManager.js:114:21](http://localhost:3000/js/transcriptionManager.js)
Recognition stopped.
```

### Additional Thoughts

I wonder what good practice setup is for my use case. Considering whether an Azure-managed API could be a more scalable and efficient solution for this. The managed API could potentially provide better control over rate limiting and streamline the handling of transcription requests. However I have no experience so far with this and I first want to ensure what is the right way to go.

### Questions

1. Are there best practices or recommended patterns for proxying such real-time data streams (HTTP and WebSocket) to Microsoft's Transcription Service?
2. Is there a need for additional configuration or handling in our current setup to ensure reliable and secure communication between the browser, our server, and Microsoft's service?

Thank you very much for your assistance!

**Comment by LiGo666** [comment]
Rubber duck debugging ...

const speechConfig = SpeechSDK.SpeechConfig.fromHost(new URL('http://localhost:3000/speech/recognition/conversation/cognitiveservices'));

i need to use ws:// here, not http ... however, i would be very happy to get a brief guideline on the good practice architecture.

**Comment by LiGo666** [comment]
Thank you Glenn,

I try to use only the hostname now:

`const speechConfig = SpeechSDK.SpeechConfig.fromHost(new URL('wss://xxx-api.azure-api.net'));`

In the Azure Managed API i configured this as a base-URL:
`wss://teekenner-berater-api.azure-api.net `
 
this websocket URL:
`wss://westeurope.stt.speech.microsoft.com`

I still get a HTTP error 400:

Firefox can’t establish a connection to the server at wss://xxx-api.azure-api.net/speech/recognition/conversation/cognitiveservices/v1?language=de-DE&format=simple&X-ConnectionId=B6648AEAF4F743FE8E1E4XXXXDC62EAB.



Managed API is defined like this:
```
<policies>
    <inbound>
        <base />
        <!-- Add subscription key to the request header -->
        <set-header name="Ocp-Apim-Subscription-Key" exists-action="override">
            <value>XXXXX489881XXXXXXfd901ab42XXXXX</value>
        </set-header>
    </inbound>
    <backend>
        <base />
    </backend>
    <outbound>
        <base />
    </outbound>
    <on-error>
        <base />
    </on-error>
</policies>
```

**Comment by glharper** [comment]
> Thank you Glenn,
> 
> I try to use only the hostname now:
> 
> `const speechConfig = SpeechSDK.SpeechConfig.fromHost(new URL('wss://xxx-api.azure-api.net'));`
> 
> In the Azure Managed API i configured this as a base-URL: `wss://xxx-api.azure-api.net `
> 
> this websocket URL: `wss://westeurope.stt.speech.microsoft.com`
> 
> I still get a HTTP error 400:
> 
> Firefox can’t establish a connection to the server at wss://xxx-api.azure-api.net/speech/recognition/conversation/cognitiveservices/v1?language=de-DE&format=simple&X-ConnectionId=B6648AEAF4F743FE8E1E4XXXXDC62EAB.
> 

This sounds like a configuration issue with Azure Managed API, along the lines of a port not being open (443 for wss). There doesn't seem to be anything specific to JS Speech SDK I can assist with here.

**Comment by jpalvarezl** [comment]
To keep our open issues list up to date, this item will be closed since it's been inactive and needs more information to proceed. Please file a new issue (and feel free to reference this one) if there's new information we can follow up on. Thank you!
