### ISSUE TITLE
How can I hide my key from user when using microsoft-cognitiveservices-speech-sdk with react

### ISSUE THREAD

**Issue by bennaaym** [microsoft/cognitive-services-speech-sdk-js#774]
Hello,

In my app I m using microsoft-cognitiveservices-speech-sdk for speech-to-text conversion. however I can clearly see my key when checking the network request on the browser. is there anyway to hide or secure the key?

**Comment by git-syl** [comment]
文档确实很不详细，参考：

js:
 speechConfig = SpeechSDK.SpeechConfig.fromAuthorizationToken(authorizationCodeFromServer, regionOptions.value);

server:
_how-to-get-an-access-token_
https://learn.microsoft.com/en-us/azure/ai-services/speech-service/rest-text-to-speech?tabs=streaming#how-to-get-an-access-token
