### ISSUE TITLE
Objects are not cleaned up

### ISSUE THREAD

**Issue by orgads** [microsoft/cognitive-services-speech-sdk-js#78]
When running a load test, I notice that sockets and most objects remain and never get cleaned up.

I'm using a mock server that accepts websocket connections, and simulates cognitive services responses.

I start the sessions with `recognizer.startContinuousRecognitionAsync()`, and stop them after a while by calling `recognizer.close()`.

Memory consumption increases constantly at a high rate (about 8-10MB/s when the session rate is 20/s).

Using Google Chrome inspector, I see that sockets and many other objects remain alive long after sessions are terminated.

**Comment by rhurey** [comment]
That's unexpected. I'll put an item into our work queue to dig in deeper.

What if you call stopContinuousRecognitionAsync() instead of close()?

**Comment by orgads** [comment]
Hi,

Sorry for the (very) late response.

We checked it now, and it doesn't seem to improve.

**Comment by orgads** [comment]
@rhurey?

**Comment by oscholz** [comment]
@orgads, thank you for your follow up. We've added this to our backlog, and will update this issue when we know more. For the time being, we will close this issue, but we'll continue to track this on our backlog. If there is any urgency to this, please reactivate, and tell us what this is blocking.
Once we resolve the backlog item, we will update this ticket to let you know what the resolution was.

**Comment by orgads** [comment]
Because of this issue we just can't use the official package, and we stick with an old implementation of ms-bing-speech-service with [several patches](https://www.npmjs.com/package/ac-ms-bing-speech-service).

We do want to use this package, but until this is solved, it will crash every few minutes on load runs, so obviously this blocks us.

**Comment by glharper** [comment]
@orgads Would you happen to still have the mock server with fake cog. service responses available to pass on so that I could take a look at this?

**Comment by orgads** [comment]
https://github.com/orgads/mock-server

**Comment by orgads** [comment]
@oscholz @glharper ^

**Comment by glharper** [comment]
@orgads Thank you for taking the time to write this up and help us out. We found and fixed a rather large memory leak, and the fix will be in our next release, 1.13. Much appreciated! :-)
