### ISSUE TITLE
[Bug]: WebSocketConnection failed after updating authorizationToken in SpeechRecognizer

### ISSUE THREAD

**Issue by GrantAnt** [microsoft/cognitive-services-speech-sdk-js#781]
### What happened?

I am initializing

    let speechTokenResult = await SpeechServiceService.getSpeechTokenSpeechServiceTokenGet();
    const speechConfig = sdk.SpeechConfig.fromAuthorizationToken(speechTokenResult.token, speechTokenResult.region);
    speechConfig.speechRecognitionLanguage = this.speechRecognitionLanguage;
    speechConfig.setProperty("Speech_SegmentationSilenceTimeoutMs", "5000");
    const audioConfig = sdk.AudioConfig.fromMicrophoneInput();
    this.speechRecognizer = new sdk.SpeechRecognizer(speechConfig, audioConfig);

and starting the recording

    this.speechRecognizer.startContinuousRecognitionAsync();
    this.intervalId = setInterval(() => {
        this.updateToken();
      }, 9 * 60 * 1000);

my update updateToken() runs succesfully.

    let speechTokenResult = await SpeechServiceService.getSpeechTokenSpeechServiceTokenGet();
    this.speechRecognizer.authorizationToken = speechTokenResult.token
    
 But after a certain time, I receive an " WebSocket connection failed" error. Message see below.

### Version

1.33.0 (Latest)

### What browser/platform are you seeing the problem on?

Chrome, Microsoft Edge

### Relevant log output

```shell
WebsocketMessageAdapter.ts:118  WebSocket connection to 'wss://westeurope.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?language=de-DE&format=simple&segmentationSilenceTimeoutMs=5000&Authorization=Bearer%20XXX' failed:
```

**Comment by glharper** [comment]
@GrantAnt Thank you for using JS Speech SDK and writing this issue up. I reproduced your issue, but was able to mitigate it by changing the interval for token fetching from 9 minutes to 5 minutes. Could you give that a shot and see if your recognition sessions are still being disrupted?

**Comment by GrantAnt** [comment]
I even set every 2 Minutes a new token. After arround 11 minutes in total, I have the same error. 
Currently I am investigating to stop recroding and restarting it.

I realized that loadScript('
[https://aka.ms/csspeech/jsbrowserpackageraw'](https://aka.ms/csspeech/jsbrowserpackageraw%27)
) uses version 1.34.0. Might this be the problem?

**Comment by glharper** [comment]
@GrantAnt Is this still affecting you? Version 1.36 is the latest now, could you update to that version?

**Comment by tranquanghuy0801** [comment]
@GrantAnt Hi, did you resolve this issue? I am having the same issue

**Comment by iamAravindks** [comment]
I am experiencing the same issue. Currently, I am using version 1.36.0. Normally, I can maintain a session for 20 minutes even though the token expires in 10 minutes (I don't know the exact reason ). I refresh the token every 15 minutes, yet the connection still breaks exactly at the 20-minute mark. I'm using the authorizationToken setter, so why does the connection drop every 20 minutes? Isn't the purpose of the authorizationToken setter to allow the session to continue without interruptions? @glharper  @GrantAnt , could you please verify this issue again? It is a critical issue for our business.
