### ISSUE TITLE
Text to speech Avatar resizing video

### ISSUE THREAD

**Issue by shilpaCM** [microsoft/cognitive-services-speech-sdk-js#783]
Hi,

How to resize Text to speech Avatar video which we receive via avatarSynthesizer by making WebRTC connection.
Any references around this will be useful.

Regards,
shilpa

**Comment by yulin-li** [comment]
Hi @shilpaCM, thanks for using Azure Avatar Service.

If you want to change the resolution, then it's not supported, and the resolution is fixed as `1920x1080` for now.

If you want to crop the video, then you can refer to 

https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/sdk/AvatarVideoFormat.ts#L50C1-L57C11``
