### ISSUE TITLE
[Question] Using not default speaker for TTS

### ISSUE THREAD

**Issue by bojanen** [microsoft/cognitive-services-speech-sdk-js#788]
Hello!

Is there a way to select the device on which you want to play TTS?
I can see that I can pass deviceId to AudioConfig.fromMicrophoneInput(deviceId?: string) for microphone, but I don't see the option for speaker.

**Comment by glharper** [comment]
@bojanen Thank you for using JS Speech SDK and writing this issue up. Speech SDK exposes the [AudioConfig.fromSpeakerOutput API](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/f87fe1f72914987af8ca8951f7228029222f40e5/src/sdk/Audio/AudioConfig.ts#L129), which takes a SpeakerAudioDestination. The [SpeakerAudioDestination constructor](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/f87fe1f72914987af8ca8951f7228029222f40e5/src/sdk/Audio/SpeakerAudioDestination.ts#L50) takes an optional AudioDestinationId parameter, have you tried setting that parameter to your deviceId?

**Comment by bojanen** [comment]
@glharper Thanks for answer. I've tried that way:
```
this.synthesizer = new sdk.SpeechSynthesizer(
  this.speechConfig,
  sdk.AudioConfig.fromSpeakerOutput(new SpeakerAudioDestination(speakerId)),
);
```
but it always plays on default device.

**Comment by glharper** [comment]
@bojanen Looking at [this guide](https://developer.chrome.com/blog/audiocontext-setsinkid), it seems AudioContext did not have the ability to change the default audio output until recently. I will add an item to our backlog to call setSinkId if there's a id parameter for SpeakerAudioDestination, but as a temporary workaround you could adjust the shared audio context in your own code using the above guide.

**Comment by vergun** [comment]
@glharper can the audio source now be changed from the microphone to the speaker out on FF and Safari?

**Comment by vergun** [comment]
@glharper the issue we are trying to solve is using the speaker (instead of the microphone) as the input source for audio transcription.

**Comment by glharper** [comment]
> @glharper can the audio source now be changed from the microphone to the speaker out on FF and Safari?

This is possible, but the difficulty seems to be in accessing the speaker out, not in actual JS Speech SDK code.
If you can somehow wrangle the speaker out into a [MediaStream](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream), you can then use the code `AudioConfig.fromStreamInput(myMediaStream);` to set up input for audio transcription.

I found [this SO question discussing speaker out to MediaStream](https://stackoverflow.com/questions/58644808/how-to-get-a-media-stream-of-the-speakers-output-to-transfer-it-over-the-networ), if that helps. Best of luck.

**Comment by abubakarAMBONE** [comment]
@glharper I was able to stream the speaker out and use it in AudioConfig.fromStreamInput(myMediaStream); but the transcription is returning undefined. its only captures mic's stream.

`      const getAudioStream = useCallback(async () => {
        const stream = await navigator.mediaDevices.getDisplayMedia({
            video: true,
            audio: true,
            displaySurface: "screen",
            systemAudio: "include",
            preferCurrentTab: true
          });
        // Access both audio and video tracks from the stream
        const speaker = new MediaStream;
        const [audioTrack] = stream.getAudioTracks();
          speaker.addTrack(audioTrack);
        stream.getVideoTracks()[0].stop();
        return speaker;
        }, []);
`
How i use the function .....
`       useEffect(() => {
             const startStreaming = async () => {
            const speaker = await getAudioStream();
            console.log('speaker', speaker);
            const speechConfig = SpeechConfig.fromSubscription(""xxxx, "yyy");
            const speechrecognizer = new SpeechRecognizer(speechConfig);
            const audioConfig = AudioConfig.fromStreamInput(speaker);
            speechrecognizer.audioConfig = audioConfig;
            speechrecognizer.startContinuousRecognitionAsync(() => {
                console.log('Recognition started');
            }, (error) => {
                console.error(`Error starting recognition: ${error}`);
            });
            speechrecognizer.recognizing = (s, e) => {
                console.log(`RECOGNIZING: Text=${e?.result?.text}`);
            }
            speechrecognizer.recognized = (s, e) => {
                console.log(e?.result?.text);
            }
        }
        startStreaming();
    }, [getAudioStream]);
`

**Comment by glharper** [comment]
> @glharper I was able to stream the speaker out and use it in AudioConfig.fromStreamInput(myMediaStream); but the transcription is returning undefined. its only captures mic's stream.

Any idea what the sample rate and bit rate are for the speaker out stream?

**Comment by abubakarAMBONE** [comment]
Sample Rate: 44100
Bit Depth: 2

**Comment by abubakarAMBONE** [comment]
@glharper below is my implementation, I also compared the stream with that of the mic and its the same.
   // Get the screen share stream with audio
            const screenShareStream = await navigator.mediaDevices.getDisplayMedia({
                        video: true,
                        audio: true,
                        displaySurface: "screen",
                        systemAudio: "include",
                        preferCurrentTab: true
            });
          
            const pushStream = AudioInputStream.createPushStream();
          
            const audioContext = new AudioContext();
            const blob = new Blob([audioProcessorWorklet], { type: 'text/javascript' });
            const url = URL.createObjectURL(blob);
            await audioContext.audioWorklet.addModule(url);
            const source = audioContext.createMediaStreamSource(screenShareStream);
            const processor = new AudioWorkletNode(audioContext, 'audio-processor');
            source.connect(processor);
            processor.connect(audioContext.destination);
            processor.port.onmessage = (event) => {
              pushStream.write(event.data);
            };          
          
            // Create an audio config from the stream
            const audioConfig = AudioConfig.fromStreamInput(pushStream);
          
            // Set up the speech recognizer
            const speechConfig = SpeechConfig.fromSubscription("Api Key", "region");
            const recognizer = new SpeechRecognizer(speechConfig, audioConfig);
          
            // Start recognizing
            recognizer.startContinuousRecognitionAsync(() => {
              console.log("Recognition started");
            }, (error) => {
              console.error(`Error starting recognition: ${error}`);
            });
          
            // Recognizing event
            recognizer.recognizing = (s, e) => {
              console.log(`RECOGNIZING: Text=${e.result.text}`);
            };
          
            // Recognized event
            recognizer.recognized = (s, e) => {
              console.log(`RECOGNIZED: Text=${e.result.text}`);
            };
          
            // Canceled event
            recognizer.canceled = (s, e) => {
              console.log(`CANCELED: Reason=${e.reason}`);
            };
          }

        handleRecognition();

**Comment by glharper** [comment]
@abubakarAMBONE PushStream actually is an acceptable way to accomplish this, but you'll need to add stream format info, as in:
```
            const format = sdk.AudioStreamFormat.getWaveFormatPCM(sampleRate, bitRate, numChannels);
            const pushStream = AudioInputStream.createPushStream(format);
```
where sampleRate = 44100, bitRate = 16 (maybe, try 8 if that doesn't work), and channels is either 1 or 2 (hopefully 1).

For the mediaStream approach, I'm a little surprised that's not working. If I have time, I'll take a look and see what's going on there.

**Comment by abubakarAMBONE** [comment]
I will try the updates to pushStream and revert. Thank you

**Comment by glharper** [comment]
Closing for lack of updates.
