### ISSUE TITLE
Microphone keep recording if subscription key is wrong

### ISSUE THREAD

**Issue by compulim** [microsoft/cognitive-services-speech-sdk-js#79]
Using SDK 1.6.0 on Chrome 75.

If the subscription key is wrong, the microphone will not turn itself off and not able to turn off.

Repro:
1. Put a wrong subscription key
1. Call `startContinuousRecognitionAsync()`
1. Got `audioSourceReady` event
1. Got `canceled` event, saying "Unable to contact server. StatusCode: 1006, undefined Reason: "

Expected:
- Microphone should turn off, or
- Calling `stopContinuousRecognitionAsync` could turn off the microphone

Actual:
- Microphone is not turned off, and
- Calling `stopContinuousRecognitionAsync` did not turn off the microphone
- The red dot on Chrome tab bar show microphone is continue recording

**Comment by rhurey** [comment]
Thanks for the report. This isn't expected behavior and you're right the audio stack should be cleaned up better.

I've put an item into our backlog to address this.

**Comment by oscholz** [comment]
@compulim We've added this to our backlog. We will update this issue when we resolve the backlog item. I will close this issue for now.
