### ISSUE TITLE
What is ServiceTimeout value and how to modify that?

### ISSUE THREAD

**Issue by czarekowyxjs** [microsoft/cognitive-services-speech-sdk-js#796]
Hello,

In my system I would like to know when SpeechRecognition request to azure api takes too much time, so I can handle it and user doesn't have to wait for nothing.

https://learn.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/cancellationerrorcode?view=azure-node-latest
In above docs I see that information about that ServiceTimeout should be passed to "canceled" function.

The questions are:
1. Does ServiceTimeout means azure api timeout?
2. What is the value of azure api timeout? 10 seconds, 1 minute, 5 minutes? 
3. Is it possible to modify that timeout? If yes, then how?

Thank you

**Comment by glharper** [comment]
@czarekowyxjs Thank you for using Speech SDK, and writing this issue up. In practice, you shouldn't see a ServiceTimeout, as recognition should begin in the span of a few seconds. I believe that service timeout value is internal to the speech recognition service, and is variable depending on the endpoint. For normal speech recognition without a custom endpoint, that timeout is not modifiable.

If you do see a ServiceTimeout, [get a log](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-use-logging), and we'll engage to service team to find out what happened.

**Comment by SalAlba** [comment]
@glharper  we are using Azure Speech SDK in node JS for converting sound to text, bellow part of our code.

**_The main question is there a way to catch the timeout on the connection  when we are sending request to Azure via the SDK ??_**

``` js


function createMicrosoftRecognizer(logger, socket, obj, sendError) {
  const { language } = obj;
  const speechConfig = SpeechConfig.fromSubscription(
    process.env.AZURE_API_KEY,
    process.env.AZURE_REGION
  );
  speechConfig.speechRecognitionLanguage = language;

  const pusher = AudioInputStream.createPushStream(AudioStreamFormat.getWaveFormatPCM(8000, 16, 1));
  const recognizer = new SpeechRecognizer(speechConfig, AudioConfig.fromStreamInput(pusher));

  recognizer.recognizing = (s, e) => {
    const obj = {
      type: 'transcription',
      transcription: transcription
      ...
    };

    logger.debug({ obj, transcription }, 'createMicrosoftRecognizer: recognizing');
    socket.send(JSON.stringify(obj));
  };

  recognizer.recognized = (s, e) => {
    const transcription = e?.result?.text;
    logger.debug({ transcription }, "recognized");
    if (e.result.reason === ResultReason.RecognizedSpeech) {
      const obj = {
        type: 'transcription',
        transcription: transcription
        ...
      };
      logger.debug({ obj }, "createMicrosoftRecognizer: recognized");
      socket.send(JSON.stringify(obj));
    }
  };

  recognizer.canceled = function (s, e) {
    const errorCode = e.errorCode;
    const errorDetails = e.errorDetails;
    const reason = e.reason;
    const message = `Details: ${errorDetails}. Reason: ${reason}. Error code: ${errorCode}`;

    logger.debug(
      { errorCode, errorDetails, reason },
      'createMicrosoftRecognizer: canceled'
    );

    sendError({ language, logger, message })
  };

  return { recognizer };
};


// ...
const {recognizer} =  createMicrosoftRecognizer(...);
recognizer.startContinuousRecognitionAsync();
```

**Comment by glharper** [comment]
@SalAlba From the sample code you provided, that recognizer.canceled callback should catch any cancellation errors, such as ServiceTimeout (although I've yet to see a "ServiceTimeout" cancellation in practice). Is there a specific issue with cancellation you're seeing with this code?

There are non-fatal timeouts you may see as status messages during recognition, such as InitialSilenceTimeout, which just means the service hasn't detected any speech, but will continue listening.

**Comment by SalAlba** [comment]
No I don't see any issue at the moment. I think we can close this topic for now. Thanks for the help 😄
