### ISSUE TITLE
[Bug]:Interim Failed WebSocket connection in Continuous translation

### ISSUE THREAD

**Issue by mirzaAshir** [microsoft/cognitive-services-speech-sdk-js#800]
### What happened?

When doing Continuous translation the WebSocket connection failed shown following error on browser console

![image (4)](https://github.com/microsoft/cognitive-services-speech-sdk-js/assets/45087476/9008eaa4-c7bf-42f2-a46a-60cc0a817a8d)

![Screenshot 2024-03-20 091648](https://github.com/microsoft/cognitive-services-speech-sdk-js/assets/45087476/c5665df0-1766-4e04-b838-53a3e90fcd59)

### Version

1.34.0 (Latest)

### What browser/platform are you seeing the problem on?

chrome , Microsoft Edge

### Relevant log output

```shell
WebsocketMessageAdapter.ts:118 WebSocket connection to 'wss://eastus.s2s.speech.microsoft.com/speech/translation/cognitiveservices/…P_yG1L38sHapdINgbVtP6VGQOA&X-ConnectionId=B6B17E73D60A44A3829B4B7189D156CB' failed:
open	@ WebsocketMessageAdapter.ts:118
open	@ WebsocketConnection.ts:116
retryableConnect@ ServiceRecognizerBase.ts:928
```

**Comment by glharper** [comment]
@mirzaAshir Thank you for using JS Speech SDK, and for writing this issue up. The connection id you listed, B6B17E73D60A44A3829B4B7189D156CB, ended after 10 minutes of translation, which is the time limit before the service switches to a new connection id. One cause of this kind of connection switch failure is a stale auth token. Can you describe how you're obtaining and renewing your auth token in your use case?

**Comment by mirzaAshir** [comment]
@glharper Thank for your quick response. So when Cancellation event is trigger we generate the new auth token and recreate the Speech SDK object

**Comment by glharper** [comment]
No response, closing.

**Comment by kaleemku9991** [comment]
@glharper I am encountering an issue with the Azure Speech Service WebSocket connection. Despite implementing a token refresh logic (<10 minutes), the application occasionally fails to maintain a stable connection. The error typically occurs when the application is idle for more than 5 minutes(not confirm exact time).
