### ISSUE TITLE
[Bug]: TTS doesn't strip out markdown for English(India) voices - both Prabhat and Neerja.

### ISSUE THREAD

**Issue by RajatAkaike** [microsoft/cognitive-services-speech-sdk-js#802]
### What happened?

TTS shouldn't pronounce markdown syntax variables like ###, ** . It works fine for Hindi, Kannada and Tamil. I see the issue with English (India)

### Version

1.34.0 (Latest)

### What browser/platform are you seeing the problem on?

Chrome

**Comment by yulin-li** [comment]
@RajatAkaike thanks for reporting this issue.

@Kerry-LinZhang could you help to find the right engineer to follow up?

**Comment by Kerry-LinZhang** [comment]
Hi @RajatAkaike Thanks and well received for the feedback, for the readout issue with such marks like '###, **' on en-IN locale, would you please share with us more details, such as the sentences you tried and on which voices the issue were found, which could really help us to repro the case and quick fix it.

**Comment by RajatAkaike** [comment]
> Hi @RajatAkaike Thanks and well received for the feedback, for the readout issue with such marks like '###, **' on en-IN locale, would you please share with us more details, such as the sentences you tried and on which voices the issue were found, which could really help us to repro the case and quick fix it.

Example sentence : 
### Scholarship Schemes for Pursuing Higher Education Abroad #### Prabuddha Overseas Scholarship (Karnataka Government) - **Aim:** Provides financial assistance for pursuing Graduation, Masters, and Ph.D. abroad in various fields of study. - **Eligibility:** Permanent resident of Karnataka, age limits, academic qualifications, standardized test scores, admission into full-time degree program at overseas university/college. - **Documents Required:** Aadhaar card, caste certificate, income certificate, IT returns, convocation certificate, semester marks card, offer letter from university, passport copy, tuition fee and maintenance fee details. - **Application Process:** Check eligibility, select universities, prepare necessary documents, take standardized tests, apply online at https://swdservices.karnataka.gov.in/foreignstudies/. #### Scholarship Scheme for Disabled Students to Study Abroad (Central Government) - **Features:** Provides scholarships to disabled students for postgraduate level courses abroad. - **Eligibility:** Natives of Madhya Pradesh, 40% or more disability, age limit, academic qualifications, income criteria. - **Documents Required:** Disability certificate, domicile certificate, Aadhaar card, medical certificate, income certificate. - **How to Apply:** Fill the online form at https://socialjustice.mp.gov.in/ with relevant documents. For further details, you can also visit the State Scholarship Portal for Karnataka and the National Scholarships Portal for Central Government schemes.

I observed the issue with both voices - Prabhat and Neerja

**Comment by RajatAkaike** [comment]
> Hi @RajatAkaike Thanks and well received for the feedback, for the readout issue with such marks like '###, **' on en-IN locale, would you please share with us more details, such as the sentences you tried and on which voices the issue were found, which could really help us to repro the case and quick fix it.

Example sentence : 
`### Scholarship Schemes for Pursuing Higher Education Abroad #### Prabuddha Overseas Scholarship (Karnataka Government) - **Aim:** Provides financial assistance for pursuing Graduation, Masters, and Ph.D. abroad in various fields of study. - **Eligibility:** Permanent resident of Karnataka, age limits, academic qualifications, standardized test scores, admission into full-time degree program at overseas university/college. - **Documents Required:** Aadhaar card, caste certificate, income certificate, IT returns, convocation certificate, semester marks card, offer letter from university, passport copy, tuition fee and maintenance fee details. - **Application Process:** Check eligibility, select universities, prepare necessary documents, take standardized tests, apply online at https://swdservices.karnataka.gov.in/foreignstudies/. #### Scholarship Scheme for Disabled Students to Study Abroad (Central Government) - **Features:** Provides scholarships to disabled students for postgraduate level courses abroad. - **Eligibility:** Natives of Madhya Pradesh, 40% or more disability, age limit, academic qualifications, income criteria. - **Documents Required:** Disability certificate, domicile certificate, Aadhaar card, medical certificate, income certificate. - **How to Apply:** Fill the online form at https://socialjustice.mp.gov.in/ with relevant documents. For further details, you can also visit the State Scholarship Portal for Karnataka and the National Scholarships Portal for Central Government schemes.`

I faced the issue with both the voices - Prabhat and Neerja

**Comment by Kerry-LinZhang** [comment]
Hi @RajatAkaike Thanks for the input and voices information, we will take further look into it.

**Comment by Kerry-LinZhang** [comment]
Hi @RajatAkaike After investigation on it, TTS currently does not support stripping out markdown, it still requires formal input to synthesize accurate speech.

If there is any further concern, please feel free to let us know.

**Comment by yulin-li** [comment]
close as won't fix
