### ISSUE TITLE
Timeout errors: modifying the default timeout

### ISSUE THREAD

**Issue by jadch** [microsoft/cognitive-services-speech-sdk-js#81]
Hello ! I've been having trouble with timeout errors lately that seem to happen when I'm starting a session. The errors don't happen systematically, but seem to affect a small percentage of the sessions started.

This is the code I use to initialize and start my sessions:
```
      return new Promise((resolve) => {
          /* Event listener that signals that a new session has started with the
          speech service */
          recognizer.sessionStarted = (speechRecognizer, event) => {
            logger.verbose(`[recognizerPromise] | (sessionStarted) SessionId: ${event.sessionId}`);
            startStreamingAudioToMicrosoft();
            resolve(recognizer);
          };

          /* Starting the speech recognition, we use the continous recognition async mode
          given that we're working with streams (and not reading from a file) */
          recognizer.startContinuousRecognitionAsync(
            () => {
              logger.verbose('[recognizerPromise] | starting session...');
            },
            (error) => {
              logger.error('[recognizerPromise] | error during async recognition ', error);
              /* We don't really know when this callback is triggered, the Speech Services
              doc is quite vague, only saying ("Callback invoked in case of an error.")
              https://docs.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/speechrecognizer?view=azure-node-latest#startcontinuousrecognitionasync-------void---e--string-----void- */
              return stopStream();
            },
          );
        });
```

The time-out error happens like that:

- After the function in the code snippet above is called, we start by seeing a `[recognizerPromise] | starting session...` log as expected

- However, we don't see the `[recognizerPromise] | (sessionStarted) SessionId` log line next as expected.

- After about two minutes, we receive the following error:
```
{
    "privSessionId": "XXXX",
    "privReason": 0,
    "privErrorDetails": "Unable to contact server. StatusCode: 1006, undefined Reason: ",
    "privErrorCode": 4
}
```

As i mentioned above, this error only happens sometimes. **I would like to modify the timeout value because two minutes is too long of a timeout for my use case** - is there any way of doing that with the SDK ?

I tried looking around in the code but couldn't find it. I'd be happy to help with a PR if someone could just point me in the right direction. Also, any additional info about the "Unable to contact server" error happening two minutes after the start of a sessions is appreciated :slightly_smiling_face:

**Comment by rhurey** [comment]
I'm going to assume you're browser based with this advice, if you're using node.js, I'll come up with different guidance.

Sadly, the W3 spec for browser based web sockets explicitly forbids useful connection error information from being returned to the caller for security reasons.

The individual browser's debugger may provide richer information in it's output. Chrome for instance will display the real reason a connection fails (auth, connection refused, etc) in the debuggers networking tab.

**Comment by jadch** [comment]
Thank you for your answer ! I'm actually using node.js, running on Node 10 (v10.16.0) and using the latest version of the SDK (1.6.0)

**Comment by Mehdi40** [comment]
Hello @rhurey,

I'm working with @jadch !

Is there a way of specifying the SDK that we do not want to wait 120sec for an effective timeout ?
For example, our others external services have a connect timeout of about 2sec.

MS Speech is the only SDK on which we do not have the ability to force a connect timeout parameter, and this creates issues on ours systems.

Thank you !

**Comment by oscholz** [comment]
@Jadch and @Mehdi40 We've added better logging in a later version of the SDK. Please try version 1.12.1 (the current version) or later, and let us know if this problem still repros. If it does, please attach logs to this issue, and reopen the issue, and we'll have a look at the details.
Thank you for using the JS Speech SDK.
