### ISSUE TITLE
[Bug]: No way to determine when the produced audio has completed

### ISSUE THREAD

**Issue by OldManMeta** [microsoft/cognitive-services-speech-sdk-js#813]
### What happened?

I've not found any way to determine when the audio has completed.
Am I missing something? All of the ResultReason options do not appear to support it or event out on audio playback complete.

Many thanks for any pointers in resolving this

EDIT:
related to #656 which is not resolved I see. This is a pretty important feature guys.

```
synthesizer.speakSsmlAsync(this.ssml, (result) => {
          if (result.reason === ResultReason.SynthesizingAudioCompleted) {

            //Testing
            console.log('Speech not finished - just the actual Synthesis has finished.');

            this.synchronizeVisemesWithAudio(result.audioData, audioContext);
            
          } else {
            console.error('Speech synthesis canceled:', result.errorDetails);
          }
```

### Version

1.29.0

### What browser/platform are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, React

**Comment by yulin-li** [comment]
As I replied in that issue, you can refer to [onAudioEnd](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/f37a6d245e1b750dc2571226048e60ec40db520c/src/sdk/Audio/IPlayer.ts#L40)

A more detailed sample

https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/browser/synthesis.html#L370C9-L388C1

**Comment by jpalvarezl** [comment]
I have added the `pending close` label, as @yulin-li has provided a path forward for this issue.
