### ISSUE TITLE
[Bug]:  Refused to create a worker from 'data:text/javascript;base64,

### ISSUE THREAD

**Issue by hubingkang** [microsoft/cognitive-services-speech-sdk-js#830]
### What happened?

```
【chrome extension】

microsoft.cognitiveservices.speech.sdk.bundle.js:2862 Refused to create a worker from 'data:text/javascript;base64,IWZ1bmN0aW9uKGUpe3ZhciB0PXt9O2Z1bmN0aW9uIG4ocil7aWYodFtyXSlyZXR1cm4gdFtyXS5leHBvcnRzO3ZhciBvPXRbcl09e2k6cixsOiExLGV4cG9ydHM6e319O3JldHVybiBlW3JdLmNhbGwoby5leHBvcnRzLG8sby5leHBvcnRzLG4pLG8ubD0hMCxvLmV4cG9ydHN9bi5tPWUsbi5jPXQsbi5kPWZ1bmN0aW9uKGUsdCxyKXtuLm8oZSx0KXx8T2JqZWN0LmRlZmluZVByb3BlcnR5KGUsdCx7ZW51bWVyYWJsZTohMCxnZXQ6cn0pfSxuLnI9ZnVuY3Rpb24oZSl7InVuZGVmaW5lZCIhPXR5cGVvZiBTeW1ib2wmJlN5bWJvbC50b1N0cmluZ1RhZyYmT2JqZWN0LmRlZmluZVByb3BlcnR5KGUsU3ltYm9sLnRvU3RyaW5nVGFnLHt2YWx1ZTo...50TGlzdGVuZXIoIm1lc3NhZ2UiLCh7ZGF0YTplfSk9Pnt0cnl7aWYoImNsZWFyIj09PWUubWV0aG9kKXtjb25zdHtpZDp0LHBhcmFtczp7dGltZXJJZDpufX09ZTtPYmplY3Qoci5iKShuKSxwb3N0TWVzc2FnZSh7ZXJyb3I6bnVsbCxpZDp0fSl9ZWxzZXtpZigic2V0IiE9PWUubWV0aG9kKXRocm93IG5ldyBFcnJvcignVGhlIGdpdmVuIG1ldGhvZCAiJy5jb25jYXQoZS5tZXRob2QsJyIgaXMgbm90IHN1cHBvcnRlZCcpKTt7Y29uc3R7cGFyYW1zOntkZWxheTp0LG5vdzpuLHRpbWVySWQ6b319PWU7T2JqZWN0KHIuZCkodCxvLG4pfX19Y2F0Y2godCl7cG9zdE1lc3NhZ2Uoe2Vycm9yOnttZXNzYWdlOnQubWVzc2FnZX0saWQ6ZS5pZCxyZXN1bHQ6bnVsbH0pfX0pfV0pOw==' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' http://localhost:3000/". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.
  ```
### Version

1.36.0 (Latest)

**Comment by hubingkang** [comment]
How do I use setProperty

**Comment by hubingkang** [comment]
【chrome extension】

microsoft.cognitiveservices.speech.sdk.bundle.js:2862 Refused to create a worker from 'data:text/javascript;base64,IWZ1bmN0aW9uKGUpe3ZhciB0PXt9O2Z1bmN0aW9uIG4ocil7aWYodFtyXSlyZXR1cm4gdFtyXS5leHBvcnRzO3ZhciBvPXRbcl09e2k6cixsOiExLGV4cG9ydHM6e319O3JldHVybiBlW3JdLmNhbGwoby5leHBvcnRzLG8sby5leHBvcnRzLG4pLG8ubD0hMCxvLmV4cG9ydHN9bi5tPWUsbi5jPXQsbi5kPWZ1bmN0aW9uKGUsdCxyKXtuLm8oZSx0KXx8T2JqZWN0LmRlZmluZVByb3BlcnR5KGUsdCx7ZW51bWVyYWJsZTohMCxnZXQ6cn0pfSxuLnI9ZnVuY3Rpb24oZSl7InVuZGVmaW5lZCIhPXR5cGVvZiBTeW1ib2wmJlN5bWJvbC50b1N0cmluZ1RhZyYmT2JqZWN0LmRlZmluZVByb3BlcnR5KGUsU3ltYm9sLnRvU3RyaW5nVGFnLHt2YWx1ZTo...50TGlzdGVuZXIoIm1lc3NhZ2UiLCh7ZGF0YTplfSk9Pnt0cnl7aWYoImNsZWFyIj09PWUubWV0aG9kKXtjb25zdHtpZDp0LHBhcmFtczp7dGltZXJJZDpufX09ZTtPYmplY3Qoci5iKShuKSxwb3N0TWVzc2FnZSh7ZXJyb3I6bnVsbCxpZDp0fSl9ZWxzZXtpZigic2V0IiE9PWUubWV0aG9kKXRocm93IG5ldyBFcnJvcignVGhlIGdpdmVuIG1ldGhvZCAiJy5jb25jYXQoZS5tZXRob2QsJyIgaXMgbm90IHN1cHBvcnRlZCcpKTt7Y29uc3R7cGFyYW1zOntkZWxheTp0LG5vdzpuLHRpbWVySWQ6b319PWU7T2JqZWN0KHIuZCkodCxvLG4pfX19Y2F0Y2godCl7cG9zdE1lc3NhZ2Uoe2Vycm9yOnttZXNzYWdlOnQubWVzc2FnZX0saWQ6ZS5pZCxyZXN1bHQ6bnVsbH0pfX0pfV0pOw==' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' http://localhost:3000". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.

**Comment by dinesh22TL5** [comment]
any solution?

**Comment by hubingkang** [comment]
> any solution?

Combine sandbox and iframe

**Comment by amritpattanayak** [comment]
> > any solution?
> 
> Combine sandbox and iframe

Please share little more detail. How to use the sandbox and iframe?
