### ISSUE TITLE
[Bug]:  Audio48Khz192KBitRateMonoMp3 always return 16Khz

### ISSUE THREAD

**Issue by MedinaGitHub** [microsoft/cognitive-services-speech-sdk-js#875]
### What happened?

no matter what I set I always got a 16Khz file.
NextJS14 code.
S0 category AZURE

Code:
`const generateSsml = (text: string, voice: string): string => {
  return `
    <speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="http://www.w3.org/2001/mstts" xml:lang="en-US">
      <voice name="${voice}">
        <mstts:express-as style="cheerful">
          ${text}
        </mstts:express-as>
      </voice>
    </speak>
  `;
};

const textToSpeech = async (
  text: string,
  config: TextToSpeechConfig
): Promise<ArrayBuffer> => {
  const speechConfig = sdk.SpeechConfig.fromSubscription(
    config.key,
    config.region
  );

  speechConfig.setProperty(
    sdk.PropertyId.SpeechServiceConnection_SynthOutputFormat,
    sdk.SpeechSynthesisOutputFormat.Audio48Khz192KBitRateMonoMp3.toString()
  );

  const synthesizer = new sdk.SpeechSynthesizer(
    speechConfig,
    sdk.AudioConfig.fromDefaultSpeakerOutput()
  );
  const ssml = generateSsml(
    text,
    config?.voice || "en-US-AvaMultilingualNeural"
  );

  return new Promise((resolve, reject) => {
    synthesizer.speakSsmlAsync(
      ssml,
      (result) => {
        if (result.errorDetails) {
          reject(new Error(result.errorDetails));
        }
        const { audioData } = result;
        synthesizer.close();
        resolve(audioData);
      },
      (error) => {
        synthesizer.close();
        reject(error);
      }
    );
  });
};`

then with JS I donwload the audio, I also tried with WAV file but it is the same.

### Version

1.36.0 (Latest)

### Relevant log output

```shell

```

**Comment by yulin-li** [comment]
Format cannot be set via property, you can call `speechConfig.speechSynthesisOutputFormat = sdk.SpeechSynthesisOutputFormat.Audio48Khz192KBitRateMonoMp3;`

**Comment by MedinaGitHub** [comment]
@yulin-li  Thank you very much!!!
