### ISSUE TITLE
Does the NodeJS version support fromDefaultMicrophone?

### ISSUE THREAD

**Issue by dlcrista** [microsoft/cognitive-services-speech-sdk-js#91]
It looks like this isn't possible to do, I get an error saying window is not defined. There also doesn't seem be any examples of the nodejs sdk using `AudioConfig.fromDefaultMicrophoneInput` so I'm guessing it isn't supported? It works perfectly fine if I use `AudioConfig.fromStreamInput`

If it is possible, can someone tell me what I'm doing wrong here?

    var speechsdk = require("microsoft-cognitiveservices-speech-sdk");
    var subscriptionKey = ";)";
    var serviceRegion = "eastus"; // e.g., "westus"

    const speech_Config = speechsdk.SpeechConfig.fromSubscription(subscriptionKey, serviceRegion, "en-US");
    const audioConfig = speechsdk.AudioConfig.fromDefaultMicrophoneInput();
    let speech_recognizer= new speechsdk.SpeechRecognizer(speech_Config, audioConfig);

    speech_recognizer.recognizeOnceAsync(
        function (result) {
	    console.log(result);
    	    speech_recognizer.close();
    	    speech_recognizer = undefined;
        },
       function (err) {
           console.trace("err - " + err);
    	   speech_recognizer.close();
    	   speech_recognizer = undefined;
    });

**Comment by rhurey** [comment]
You need something to hold node around long enough for recognition to have started. 

Here's something I threw together real quick:
`"use strict";

// pull in the required packages.
var sdk = require("microsoft-cognitiveservices-speech-sdk");
var fs = require("fs");

var subscriptionKey = "KEY";
var serviceRegion = "REGION"; // e.g., "westus"
var filename = "AUDIOFILE.wav"; // 16000 Hz, Mono

function analyze(pushStream) {
    return new Promise(function (resolve, reject) {
        // we are done with the setup
        console.log("Now recognizing from: " + filename);

        // create the push stream we need for the speech sdk.
        var pushStream = undefined;

        pushStream = sdk.AudioInputStream.createPushStream();
        // open the file and push it to the push stream.
        fs.createReadStream(filename).on('data', function (arrayBuffer) {
            pushStream.write(arrayBuffer.buffer);
        }).on('end', function () {
            pushStream.close();
        });

        // now create the audio-config pointing to our stream and
        // the speech config specifying the language.

        var audioConfig = sdk.AudioConfig.fromStreamInput(pushStream);
        var speechConfig = sdk.SpeechConfig.fromSubscription(subscriptionKey, serviceRegion);
        speechConfig.outputFormat = sdk.OutputFormat.Detailed;

        let recognizer = new sdk.SpeechRecognizer(speechConfig, audioConfig);
        speechConfig.speechRecognitionLanguage = "en-us";

        recognizer.sessionStarted = (r, e) => {
            console.log(new Date(Date.now()).toLocaleString() + " " + e.sessionId);
        }

        recognizer.canceled = (r, e) => {
            console.warn(e);
            console.info("resolving");
            r.close();
            resolve();
        };

        // The event recognized signals that a final recognition result is received.
        // This is the final event that a phrase has been recognized.
        // For continuous recognition, you will get one recognized event for each phrase recognized.
        recognizer.recognized = function (s, e) {
            // Indicates that recognizable speech was not detected, and that recognition is done.
            if (e.result.reason === sdk.ResultReason.NoMatch) {
                var noMatchDetail = sdk.NoMatchDetails.fromResult(e.result);
                console.log("\r\n" + new Date(Date.now()).toLocaleString() + " " + "(recognized)  Reason: " + sdk.ResultReason[e.result.reason] + " NoMatchReason: " + sdk.NoMatchReason[noMatchDetail.reason]);
            } else {
                console.log("\r\n" + new Date(Date.now()).toLocaleString() + " " + "(recognized)  Reason: " + sdk.ResultReason[e.result.reason] + " Text: " + e.result.text);
                console.log("\r\n" + new Date(Date.now()).toLocaleString() + " " + "(recognized)  Reason: " + sdk.ResultReason[e.result.reason] + " Text: " + e.result.json);
            }
        };

        recognizer.recognizing = function (s, e) {
            // Indicates that recognizable speech was not detected, and that recognition is done.
            console.info("Recognizing " + e.result.text);
        };

        console.info("Starting");
        recognizer.startContinuousRecognitionAsync();
    });
};

async function main() {
    await analyze();
    console.info("Main done");
}

main();
`

**Comment by dlcrista** [comment]
As I mentioned, I am looking to capture audio streams **from the microphone**. 

Also, the only methods in my SpeechRecognizer object are:
[ 'audioConfig',
  'authorizationToken',
  'close',
  'constructor',
  'createRecognizerConfig',
  'createServiceRecognizer',
  'dispose',
  'endpointId',
  'implCommonRecognizerSetup',
  'implRecognizerStart',
  'implRecognizerStop',
  'internalData',
  'outputFormat',
  'privConnectionFactory',
  'privDisposed',
  'privDisposedSpeechRecognizer',
  'privProperties',
  'privReco',
  'properties',
  'recognizeOnceAsync',
  'speechRecognitionLanguage',
  'startContinuousRecognitionAsync',
  'startKeywordRecognitionAsync',
  'stopContinuousRecognitionAsync',
  'stopKeywordRecognitionAsync' ]

I don't see `recognized` or `recognizing`

**Comment by rhurey** [comment]
Ah, I'd missed that, sorry.

fromDefaultMicrophone() is targeted at browser based development.

There is no intrinsic microphone support in NodeJs, @lucasctd had some success with the mic package via streams.

https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/72

Its still not clear why mic package produced 2x the audio data it was asked to, though.

**Comment by rhurey** [comment]
I'm going to close this as there isn't more to do here.
