### ISSUE TITLE
Unable to contact server. StatusCode: 1006, undefined Reason. Error Code: 7

### ISSUE THREAD

**Issue by robinmanuelthiel** [microsoft/cognitive-services-speech-sdk-js#94]
During long-running recordings, I quite randomly get the following error after approximately 15 - 20 minutes:

![image](https://user-images.githubusercontent.com/5874465/66705015-1b0cb780-ed22-11e9-8370-3837e4b44e7d.png)

The recording crashes and can't be started again.

I use the following code:

```javascript
const token = // fetch token from server...
const config = // ...
const region = // ...

this.speechConfig = SpeechSDK.SpeechConfig.fromAuthorizationToken(token, config.region);
this.speechConfig.speechRecognitionLanguage = 'de-DE';
this.audioConfig = SpeechSDK.AudioConfig.fromDefaultMicrophoneInput();

this.speechRecognizer = new SpeechSDK.SpeechRecognizer(this.speechConfig, this.audioConfig);
this.speechRecognizer.recognizing = (s, e) => this.recognizing(s, e);
this.speechRecognizer.recognized = (s, e) => this.recognized(s, e);
this.speechRecognizer.canceled = (s, e) => this.recordingCanceled(s, e);

this.speechRecognizer.startContinuousRecognitionAsync();

// Renew token every 9 minutes
setInterval(async () => {
  const token = // fetch token from server...
  this.speechRecognizer.authorizationToken = token;
}, 540000);
```

Is there something wrong on your end or my end?

According to [the documentation](https://docs.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/cancellationerrorcode?view=azure-node-latest) it is an unexpected error.

**Comment by vadkasevas** [comment]
looks like websocket cannot connect to server (westeurope.stt.speech.microsoft.com) in my case

**Comment by robinmanuelthiel** [comment]
That's all we got, does it help? 
![image](https://user-images.githubusercontent.com/5874465/67618483-82ca0480-f7f0-11e9-8c76-d7946a7ac1e4.png)

**Comment by rhurey** [comment]
Yes, it's helpful.

The service is unhappy about the token when the Speech SDK is reconnecting. (As opposed to any other network issues) Not sure why yet, that'll take some investigation.

**Comment by oscholz** [comment]
@robinmanuelthiel We have added an item in our backlog to investigate this further. We will update this issue when we resolve the backlog item. I will close this issue for now.

**Comment by mrgrain** [comment]
We encounter the same issue with versions `1.15.1` and `1.16.0`. It seems like the `authorizationToken` doesn't populate all the way down to the Websocket connection.

@oscholz  Did you get anywhere with this item in your backlog?

**Comment by ssinghi** [comment]
Facing a similar problem with `1.18.1`.

**Comment by durdenx** [comment]
Same with `^1.26.0`... Is there a solution?
