### ISSUE TITLE
speech sdk js for cordova / phonegap (ios / android)

### ISSUE THREAD

**Issue by inglesuniversal** [microsoft/cognitive-services-speech-sdk-js#95]
Hello, I'm an Azure customer, and I currently use your speech sdk-js on the browser (it works great)... I want to port this project to mobile phones under an environment like cordova or phonegap ... Is there a way to easily do that or do I need additional plugins?

Regards

Hugo Barbosa

Congrats to your whole team!!!

**Comment by inglesuniversal** [comment]
Hello again... I was able to record audio wav format on ios and play it back immediately using the cordova media plugin... do you have an example web folder of this kind of implementation in order to be able to record and process speech recognition under cordova / phonegap ?

**Comment by chrisbasoglu** [comment]
For js, our samples are the node and browser folders.  We do not currently have a sample that records audio and then does recognition on the recorded audio.
