### ISSUE TITLE
AudioInputId is not passed into MicAudioSource when making a new audio configuration

### ISSUE THREAD

**Issue by corinagum** [microsoft/cognitive-services-speech-sdk-js#96]
https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/sdk/Audio/AudioConfig.ts#L40

Hi, I'm reporting from the Bot Framework Web Chat team. 

When passing in the `deviceId` to the `AudioConfig.fromMicrophoneInput`, it looks like `deviceId` is being passed as the `audioSourceId` into the `MicAudioSource`.

This is causing bugs for Web Chat when attempting to manually set the audio source. We pass the `deviceId` in, but it continues to use the default device.

**Comment by compulim** [comment]
@rhurey Could you take a look at this? It is affecting one of our customers, preventing them to use AirPods on iPhone for Cognitive Services because iPhone did not set AirPods as their default microphone.

**Comment by rhurey** [comment]
I took a quick look this morning, and when I have my Surface Headphones (Sorry, don't have AirPods) connected to my iphone the `navigator.mediaDevices.enumerateDevices()` device enumeration only returns a single device, an iPhone Microphone, but it does take audio from the headphones.

Where did you get the device id for the AirPods?

**Comment by rhurey** [comment]
I managed to get a set of AirPods to try with also, and the device enumeration still only returns a single device.

So I'm still looking for where you got a device ID from?

**Comment by cwhitten** [comment]
@rhurey that's odd. you should see at least the built-in audio id and the airpods id.

**Comment by corinagum** [comment]
I have a sample that shows the manual fix: https://github.com/corinagum/WebChat-Samples

Run `npx serve` from the root and go to http://localhost:5000/audioconfig/ to test the sample

The line I modified in the Speech SDK bundle was `3036` (added the `null` for third parameter)

In my screencap below, the `deviceId` starting '225'.. represents my Airpods. There is a list of 11 devices, and from there I filtered out the non-audioinput items. The dropdown on the sample let's you choose the device.

![image](https://user-images.githubusercontent.com/14900841/72233555-e60c3d00-357c-11ea-809b-13c548f0dfaf.png)

**Comment by rhurey** [comment]
Odd indeed. I changed the media label seeking code in the SDK's microphone to dump the audio devices and got far less.
https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/e619be29f065f67de777a984a676480c76e58e1f/src/common.browser/MicAudioSource.ts#L257

```
Array (3)
0 MediaDeviceInfo {deviceId: "D0096C92FAAE60D3FFC0D2896FC1925E79ECEA21", kind: "audioinput", label: "iPhone Microphone", groupId: "", toJSON: function}
1 MediaDeviceInfo {deviceId: "4A1DEAA6119FBCEFAE2C5C1CC053742A6CEE4915", kind: "videoinput", label: "Front Camera", groupId: "", toJSON: function}
2 MediaDeviceInfo {deviceId: "D8EC54A72CFAE4FBACD9A59ADE27C45005CA0D65", kind: "videoinput", label: "Back Camera", groupId: "", toJSON: function}
```

**Comment by compulim** [comment]
1. Do you see AirPod when you go to this page? https://webrtc.github.io/samples/src/content/devices/input-output/
1. Are you playing music with Bluetooth while you are enumerating? Playing audio thru A2DP could temporarily disable HFP/HSP.

**Comment by rhurey** [comment]
1) No. But they're what the page is using. I can set the phone down and walk away while still hearing myself.

2) Not intentionally.

**Comment by rhurey** [comment]
Fix will be in our next release. Closing.
